'use strict';

// scripts/hook-runtime/materialize/_helpers.cjs
// Shared marker constant + private helpers for project materialization:
// fs/text utilities, generated-file detection & cleanup, plugin-authoring
// detection, and AGENTS.md rendering. The exported functions each live in
// their own sibling file and import what they need from here.

const fs = require('fs');
const path = require('path');

const { pluginRoot } = require('../config.cjs');
const { templatePath } = require('../stacks/stacks.cjs');
const { isLeanMaterialization } = require('./isLeanMaterialization.cjs');

const GENERATED_MARKER = '<!-- GENERATED BY traffic-one: project-local active rules -->';

function toPosix(filePath) {
  return filePath.split(path.sep).join('/');
}

function readText(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
}

function writeTextIfChanged(filePath, content) {
  if (fs.existsSync(filePath) && readText(filePath) === content) {
    return false;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function isGenerated(filePath) {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(GENERATED_MARKER);
}

function removeGeneratedFile(filePath) {
  if (fs.existsSync(filePath) && isGenerated(filePath)) {
    fs.rmSync(filePath, { force: true });
    return true;
  }
  return false;
}

function isGeneratedManifest(filePath) {
  try {
    const json = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    return json && json.generatedBy === 'traffic-one';
  } catch {
    return false;
  }
}

function removeGeneratedManifest(filePath) {
  if (fs.existsSync(filePath) && isGeneratedManifest(filePath)) {
    fs.rmSync(filePath, { force: true });
    return true;
  }
  return false;
}

function isGeneratedTree(dirPath) {
  if (!fs.existsSync(dirPath)) return false;
  const stat = fs.lstatSync(dirPath);
  if (stat.isFile()) return isGenerated(dirPath);
  if (!stat.isDirectory()) return false;

  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  return entries.every((entry) => isGeneratedTree(path.join(dirPath, entry.name)));
}

function removeGeneratedTree(dirPath) {
  if (fs.existsSync(dirPath) && isGeneratedTree(dirPath)) {
    fs.rmSync(dirPath, { recursive: true, force: true });
    return true;
  }
  return false;
}

function removeGeneratedSkillDir(dirPath) {
  const skillPath = path.join(dirPath, 'SKILL.md');
  if (fs.existsSync(skillPath) && isGenerated(skillPath)) {
    fs.rmSync(dirPath, { recursive: true, force: true });
    return true;
  }
  return false;
}

function migrateLegacyMemoryFile(cwd, fileName) {
  const legacyPath = path.join(cwd, '.traffic-one', 'rules', fileName);
  const targetPath = path.join(cwd, '.traffic-one', fileName);
  if (!fs.existsSync(legacyPath) || fs.lstatSync(legacyPath).isDirectory()) {
    return false;
  }

  if (!fs.existsSync(targetPath)) {
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.renameSync(legacyPath, targetPath);
    return true;
  }

  if (readText(legacyPath) === readText(targetPath)) {
    fs.rmSync(legacyPath, { force: true });
    return true;
  }

  return false;
}

function copySkillDir(srcDir, dstDir) {
  if (!fs.existsSync(srcDir)) return false;
  fs.mkdirSync(dstDir, { recursive: true });
  const entries = fs.readdirSync(srcDir, { withFileTypes: true });
  for (const entry of entries) {
    const src = path.join(srcDir, entry.name);
    const dst = path.join(dstDir, entry.name);
    if (entry.isDirectory()) {
      copySkillDir(src, dst);
    } else if (entry.isFile()) {
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      let content = fs.readFileSync(src, 'utf8');
      if (entry.name === 'SKILL.md' && !content.includes(GENERATED_MARKER)) {
        content = `${content.trimEnd()}\n\n${GENERATED_MARKER}\n`;
      }
      fs.writeFileSync(dst, content, 'utf8');
    }
  }
  return true;
}

function loadPreviousManifest(cwd) {
  const candidates = [
    path.join(cwd, '.traffic-one', 'manifest.json'),
    path.join(cwd, '.traffic-one', 'rules', 'manifest.json'),
  ];
  for (const manifestPath of candidates) {
    try {
      return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    } catch {
      // Try the legacy/new location pair before falling back to an empty state.
    }
  }
  return {};
}

function cleanupPrevious(cwd, previous, nextRulePaths, nextSkillNames) {
  let removed = 0;
  const projectMemoryRoot = path.join(cwd, '.traffic-one');
  const legacyActiveRoot = path.join(cwd, '.traffic-one', 'rules', 'active');
  const skillsRoot = path.join(cwd, '.traffic-one', 'skills');

  for (const relPath of Array.isArray(previous.rules) ? previous.rules : []) {
    const currentRulePath = path.join(projectMemoryRoot, relPath);
    const legacyRulePath = path.join(legacyActiveRoot, relPath);
    if (removeGeneratedFile(legacyRulePath)) removed += 1;
    if (nextRulePaths.has(relPath)) continue;
    if (removeGeneratedFile(currentRulePath)) removed += 1;
  }

  if (removeGeneratedTree(legacyActiveRoot)) removed += 1;
  if (removeGeneratedFile(path.join(cwd, '.traffic-one', 'rules', 'AGENTS.md'))) removed += 1;
  if (removeGeneratedManifest(path.join(cwd, '.traffic-one', 'rules', 'manifest.json'))) {
    removed += 1;
  }
  if (migrateLegacyMemoryFile(cwd, 'coding.md')) removed += 1;
  if (migrateLegacyMemoryFile(cwd, 'security.md')) removed += 1;

  for (const name of Array.isArray(previous.skills) ? previous.skills : []) {
    if (nextSkillNames.has(name)) continue;
    if (removeGeneratedSkillDir(path.join(skillsRoot, name))) removed += 1;
  }

  return removed;
}

function hasPluginAuthoringMarkers(root) {
  try {
    const pluginJsonPath = path.join(root, 'plugin.json');
    const codexPluginJsonPath = path.join(root, '.codex-plugin', 'plugin.json');
    const hookRuntimePath = path.join(root, 'scripts', 'hook-runtime', 'handlers', 'handlers.cjs');
    const authScriptPath = path.join(root, 'scripts', 'traffic-one-auth.cjs');
    if (!fs.existsSync(hookRuntimePath) || !fs.existsSync(authScriptPath)) {
      return false;
    }
    const manifestPath = fs.existsSync(pluginJsonPath) ? pluginJsonPath : codexPluginJsonPath;
    if (!fs.existsSync(manifestPath)) return false;
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    return manifest && manifest.name === 'traffic-one';
  } catch {
    return false;
  }
}

function compactRuleKernel() {
  return [
    '## Active Rule Kernel',
    '',
    'This compact kernel is always-on. Full rule bodies are materialized under `.traffic-one/rules/**`; read the matching rule before work whose behavior, security, data shape, architecture, or UX depends on it.',
    '',
    '- Read project memory first for non-trivial work: `.traffic-one/.agentignore`, product/stack/coding/security notes, known issues, schema, and recent agent log when present.',
    '- Keep changes surgical: preserve existing structure, avoid unrelated refactors, never revert user edits, and match local style even when a different style would be tempting.',
    '- Prefer the selected Traffic One stack and local helpers. Do not add libraries, abstractions, alternate modes, or extension points without a real current caller.',
    '- Security stays active: no secrets in source or memory, validate input at boundaries, enforce auth and authorization server-side, avoid credentialed wildcard CORS, use parameterized SQL, and keep production errors sanitized.',
    '- New-project onboarding gates are blocking: mobile, code graph, and team choices must be persisted before scaffolding; when `team.mode="subagents"`, the parent coordinates and role agents own feature-source writes.',
    '- UI work must satisfy i18n, SEO for public routes, accessibility, responsive layout, real visual polish, stable dimensions, and verification screenshots when the change is visual.',
    '- Backend/data work must keep API contracts explicit, schema changes reviewed, migrations reversible where practical, RLS/storage policies safe, and generated clients or schema snapshots refreshed when applicable.',
    '- Verification should match risk: reproduce bugs when practical, run focused tests/build/lint for touched surfaces, and report any skipped check with the exact reason.',
    '- External or destructive actions still need explicit current confirmation: deploy, publish, push protected environments, run shared/prod migrations, send messages, delete data/files, or call side-effecting external APIs.',
    '',
  ];
}

function compactReadRouting() {
  return [
    '## Read Rules When',
    '',
    '- Starting/scaffolding/onboarding: `rules/modes/new-project.md`, `rules/common/senior-engineer-team.md`, `rules/common/stack-recommendations.md`, `rules/common/project-memory.md`, `rules/common/documentation.md`.',
    '- Editing existing code: `rules/modes/existing-codebase.md`, `rules/common/execution-discipline.md`, `rules/common/clean-code.md`, plus the stack rule for touched files.',
    '- Building UI/pages/components/styles: `rules/frontend/ui-quality.md`, `rules/frontend/typography.md`, `rules/frontend/i18n.md`, `rules/frontend/accessibility.md`, and the framework-specific frontend rules.',
    '- Working on React/Vite state, services, realtime, testing, performance, or security: read the matching `rules/frontend/react/*.md` file before editing.',
    '- Touching Supabase, auth, storage, RLS, SQL, migrations, or schema snapshots: `rules/common/security.md`, `rules/frontend/react/supabase-client.md`, and `rules/backend/postgres.md`.',
    '- Adding APIs, connectors, libraries, observability, docs, SEO, tests, release, or deployment work: read the matching common rule and trigger the matching skill from `.traffic-one/skills/**`.',
    '- Running subagents or fix cycles: `rules/common/agent-handoff-digests.md`, `rules/common/codebase-graph.md`, and the role-scoped rules named in the task prompt.',
    '',
  ];
}

function renderRuleIndexSection(title, relPaths) {
  if (!Array.isArray(relPaths) || relPaths.length === 0) return [];
  return [
    `### ${title}`,
    '',
    ...relPaths.map((relPath) => `- .traffic-one/${relPath}`),
    '',
  ];
}

function ruleGroupsForOptions(rules, options) {
  const mandatory = unique(options.mandatoryRules || []);
  const reference = unique(options.referenceRules || [])
    .filter((relPath) => !mandatory.includes(relPath));
  if (mandatory.length > 0 || reference.length > 0) {
    return { mandatory, reference };
  }
  return { mandatory: unique(rules), reference: [] };
}

function renderAgents(state, rules, skills, options = {}) {
  const leanMode = options.leanMode === true;
  const lines = [
    '# Traffic One Local Agent Context',
    '',
    GENERATED_MARKER,
    '',
    leanMode
      ? 'Use the compact project-local rule kernel and index below before falling back to plugin-root rules.'
      : 'Use the project-local active rule bundle below before falling back to plugin-root rules.',
    leanMode
      ? 'Compact context mode keeps critical guidance always-on and reads full `.traffic-one` rules on demand.'
      : 'Host runtimes may read AGENTS.md directly, so active rule contents are inlined instead of relying on host-specific import syntax.',
    '',
    '## Active State',
    '',
    `- Stack: ${state.stack || 'minimal'}`,
    `- Frontend: ${state.frontend || 'none'}`,
    `- Backend: ${state.backend || 'none'}`,
    `- Mobile: ${(state.mobile && state.mobile.framework) || 'none'}`,
    '',
    '## Active Rules',
    '',
    ...rules.map((relPath) => `- .traffic-one/${relPath}`),
    '',
    '## Active Skills',
    '',
    ...skills.map((name) => `- .traffic-one/skills/${name}/SKILL.md`),
    '',
  ];
  if (leanMode) {
    const { mandatory, reference } = ruleGroupsForOptions(rules, options);
    lines.push(
      ...compactRuleKernel(),
      ...compactReadRouting(),
      '## Active Rule Index',
      '',
      'Full rule content is materialized under `.traffic-one/<path>`.',
      'Read only the specific rules needed for the current file or task; the kernel above is the always-on baseline.',
      '',
      ...renderRuleIndexSection('Mandatory Baseline', mandatory),
      ...renderRuleIndexSection('Reference On Demand', reference),
    );
    return `${lines.join('\n')}\n`;
  }

  const root = pluginRoot();
  lines.push('## Active Rule Contents', '');
  for (const relPath of rules) {
    const source = readText(path.join(root, templatePath(relPath)));
    lines.push(`### ${relPath}`, '');
    if (typeof source === 'string' && source.trim()) {
      lines.push(source.trimEnd(), '');
    } else {
      lines.push(`Rule source missing in plugin root: ${templatePath(relPath)}`, '');
    }
  }
  return `${lines.join('\n')}\n`;
}

function localContextName(fileName) {
  return fileName === 'CLAUDE.md' ? 'CLAUDE.local.md' : 'AGENTS.local.md';
}

function preserveManualRootContext(cwd, fileName, state) {
  const rootPath = path.join(cwd, fileName);
  if (!fs.existsSync(rootPath)) return false;
  const stat = fs.lstatSync(rootPath);
  if (stat.isSymbolicLink() || isGenerated(rootPath)) return false;
  if (!state || state.mode !== 'new-project') return false;

  const localName = localContextName(fileName);
  const localPath = path.join(cwd, '.traffic-one', localName);
  const existing = readText(rootPath) || '';
  const preserved = [
    `# Preserved ${fileName}`,
    '',
    `This content existed before Traffic One generated root ${fileName}.`,
    '',
    '---',
    '',
    existing.trimEnd(),
    '',
  ].join('\n');

  if (!fs.existsSync(localPath)) {
    writeTextIfChanged(localPath, preserved);
  }
  fs.rmSync(rootPath, { force: true });
  return true;
}

function localContextBlocks(cwd) {
  const blocks = [];
  for (const fileName of ['AGENTS.local.md', 'CLAUDE.local.md']) {
    const filePath = path.join(cwd, '.traffic-one', fileName);
    const content = readText(filePath);
    if (typeof content === 'string' && content.trim()) {
      blocks.push(`### .traffic-one/${fileName}\n\n${content.trimEnd()}`);
    }
  }
  return blocks;
}

function renderAgentsWithLocalContext(cwd, state, rules, skills, options = {}) {
  const base = renderAgents(state, rules, skills, {
    leanMode: isLeanMaterialization(cwd, state),
    ...options,
  }).trimEnd();
  const localBlocks = localContextBlocks(cwd);
  if (localBlocks.length === 0) {
    return `${base}\n`;
  }
  return [
    base,
    '',
    '## Preserved Project Notes',
    '',
    ...localBlocks,
    '',
  ].join('\n');
}

function renderClaudeFallback() {
  const lines = [
    '# Traffic One Claude Context',
    '',
    GENERATED_MARKER,
    '',
    'Read the canonical root agent context:',
    '',
    '@AGENTS.md',
    '',
  ];
  return `${lines.join('\n')}\n`;
}

function writeRootAgents(cwd, content) {
  const rootAgents = path.join(cwd, 'AGENTS.md');
  if (fs.existsSync(rootAgents) && !fs.lstatSync(rootAgents).isSymbolicLink() && !isGenerated(rootAgents)) {
    return false;
  }
  if (fs.existsSync(rootAgents)) {
    fs.rmSync(rootAgents, { force: true });
  }
  return writeTextIfChanged(rootAgents, content);
}

function writeRootClaude(cwd) {
  const rootClaude = path.join(cwd, 'CLAUDE.md');
  if (fs.existsSync(rootClaude) && !fs.lstatSync(rootClaude).isSymbolicLink() && !isGenerated(rootClaude)) {
    return false;
  }
  if (fs.existsSync(rootClaude)) {
    fs.rmSync(rootClaude, { force: true });
  }
  try {
    fs.symlinkSync('AGENTS.md', rootClaude);
    return true;
  } catch {
    return writeTextIfChanged(rootClaude, renderClaudeFallback());
  }
}

function unique(values) {
  const seen = new Set();
  const out = [];
  for (const value of values) {
    if (!value || seen.has(value)) continue;
    seen.add(value);
    out.push(value);
  }
  return out;
}

function modeRulesForState(root, state) {
  const mode = state && typeof state.mode === 'string' ? state.mode : '';
  if (!mode) return [];

  const relPath = `rules/modes/${mode}.md`;
  if (!fs.existsSync(path.join(root, templatePath(relPath)))) return [];

  return [relPath];
}

module.exports = {
  GENERATED_MARKER,
  toPosix,
  readText,
  writeTextIfChanged,
  isGenerated,
  removeGeneratedFile,
  isGeneratedManifest,
  removeGeneratedManifest,
  isGeneratedTree,
  removeGeneratedTree,
  removeGeneratedSkillDir,
  migrateLegacyMemoryFile,
  copySkillDir,
  loadPreviousManifest,
  cleanupPrevious,
  hasPluginAuthoringMarkers,
  compactRuleKernel,
  compactReadRouting,
  renderRuleIndexSection,
  ruleGroupsForOptions,
  renderAgents,
  localContextName,
  preserveManualRootContext,
  localContextBlocks,
  renderAgentsWithLocalContext,
  renderClaudeFallback,
  writeRootAgents,
  writeRootClaude,
  unique,
  modeRulesForState,
};
