import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { materializeFromProjectMemoryWrite, materializeFromToolInputHints } from '../converge-from-write';

function withProject(state: Record<string, unknown> | null, fn: (cwd: string) => void): void {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 't1-cfw-')));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  fs.mkdirSync(path.join(dir, '.traffic-one'), { recursive: true });
  if (state) fs.writeFileSync(path.join(dir, '.traffic-one', '.one.json'), JSON.stringify(state), 'utf8');
  try { fn(dir); } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

test('materializeFromProjectMemoryWrite: null for non-memory paths', () => {
  withProject({ stack: 'default', onboardingComplete: true }, (cwd) => {
    assert.equal(materializeFromProjectMemoryWrite(cwd, path.join(cwd, 'src', 'app.ts')), null);
    // a generated subtree write is not project memory
    assert.equal(materializeFromProjectMemoryWrite(cwd, path.join(cwd, '.traffic-one', 'rules', 'core.md')), null);
  });
});

test('materializeFromProjectMemoryWrite: null when stack/onboarding incomplete', () => {
  withProject({ mode: 'new-project' }, (cwd) => {
    // a project-memory write but no valid stack / not onboarded → no materialization
    assert.equal(materializeFromProjectMemoryWrite(cwd, path.join(cwd, '.traffic-one', 'product.md')), null);
  });
});

test('materializeFromToolInputHints: null when no tool-input hints resolve to a project', () => {
  withProject({ stack: 'default', onboardingComplete: true }, (cwd) => {
    assert.equal(materializeFromToolInputHints(cwd, { command: 'ls -la' }), null);
    assert.equal(materializeFromToolInputHints(cwd, {}), null);
  });
});

test('materializeFromToolInputHints: reporter is invoked for a resolved already-materialized root (returns null)', () => {
  // a fully-materialized project so materializeProjectIfNeeded early-returns null (no heavy writer)
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 't1-cfw2-')));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  try {
    const t1 = path.join(dir, '.traffic-one');
    fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
    fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
    fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
    fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
    fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({ generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'] }), 'utf8');
    fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
    fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
    fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({ mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' }, onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none' }), 'utf8');
    let reported = 0;
    const out = materializeFromToolInputHints(dir, { file_path: path.join(dir, 'apps', 'web', 'x.ts') }, { reportOneMcp: () => { reported += 1; } });
    assert.equal(out, null); // already materialized → nothing to converge
    assert.ok(reported >= 1); // reporter still fired for the resolved root
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
