import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { runPostStackSetup } from '../post-stack-setup';
import type { Ctx, HookInput } from '../../../core/types';
import { endpointFromEnv } from '../../../shared/auth';

function ctx(cwd: string, toolInput: Record<string, unknown>): Ctx {
  const input: HookInput = { event: 'PostToolUse', host: 'claude', cwd, raw: { tool_name: 'Write', tool_input: toolInput } };
  return { input, host: 'claude', cwd, now: () => 'x' } as unknown as Ctx;
}

function withAuthedProject(materialized: boolean, fn: (cwd: string) => void): void {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 't1-pss-')));
  const env = process.env;
  const prevAuth = env.TRAFFIC_ONE_AUTH_STATE_PATH;
  const prevPrefs = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_AUTH_STATE_PATH = path.join(dir, 'auth.json');
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  fs.writeFileSync(env.TRAFFIC_ONE_AUTH_STATE_PATH, JSON.stringify({
    version: 1, endpoint: endpointFromEnv(), sessionToken: 'tok_x.sig',
    expiresAt: '2099-01-01T00:00:00Z', lastRemoteCheckedAt: new Date().toISOString(),
  }), 'utf8');
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(t1, { recursive: true });
  if (materialized) {
    fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
    fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
    fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
    fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
    fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({ generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'] }), 'utf8');
    fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
    fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
    fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({ mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' }, onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none' }), 'utf8');
  }
  try { fn(dir); } finally {
    if (prevAuth === undefined) delete env.TRAFFIC_ONE_AUTH_STATE_PATH; else env.TRAFFIC_ONE_AUTH_STATE_PATH = prevAuth;
    if (prevPrefs === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prevPrefs;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

test('noop when not authenticated (no auth state)', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-pss-noauth-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_AUTH_STATE_PATH;
  env.TRAFFIC_ONE_AUTH_STATE_PATH = path.join(dir, 'nope.json');
  try {
    assert.equal(runPostStackSetup(ctx(dir, { file_path: 'src/x.ts' })).kind, 'noop');
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_AUTH_STATE_PATH; else env.TRAFFIC_ONE_AUTH_STATE_PATH = prev;
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('noop in the plugin authoring root for a write inside cwd', () => {
  // process.cwd() is the authoring root; a file_path inside it → noop (auth not reached for authoring).
  const env = process.env;
  const prev = env.TRAFFIC_ONE_AUTH_STATE_PATH;
  env.TRAFFIC_ONE_AUTH_STATE_PATH = path.join(os.tmpdir(), 'pss-authoring-auth.json');
  fs.writeFileSync(env.TRAFFIC_ONE_AUTH_STATE_PATH, JSON.stringify({ version: 1, endpoint: endpointFromEnv(), sessionToken: 'tok_x.sig', expiresAt: '2099-01-01T00:00:00Z', lastRemoteCheckedAt: new Date().toISOString() }), 'utf8');
  try {
    assert.equal(runPostStackSetup(ctx(process.cwd(), { file_path: 'src/x.ts' })).kind, 'noop');
  } finally {
    fs.rmSync(env.TRAFFIC_ONE_AUTH_STATE_PATH, { force: true });
    if (prev === undefined) delete env.TRAFFIC_ONE_AUTH_STATE_PATH; else env.TRAFFIC_ONE_AUTH_STATE_PATH = prev;
  }
});

test('oversized handoff digest → trim warning', () => {
  withAuthedProject(false, (cwd) => {
    const digestDir = path.join(cwd, '.traffic-one', 'digests', 'run1');
    fs.mkdirSync(digestDir, { recursive: true });
    const digestFile = path.join(digestDir, 'architect.md');
    fs.writeFileSync(digestFile, 'x'.repeat(4 * 1024), 'utf8'); // > 3 KB
    const r = runPostStackSetup(ctx(cwd, { file_path: digestFile }));
    assert.equal(r.kind, 'context');
    if (r.kind === 'context') {
      assert.ok(r.systemMessage?.includes('digest architect.md'));
      assert.ok(r.context.includes('[digest-size]'));
    }
  });
});

test('function-edit with no deploy hook → noop', () => {
  withAuthedProject(false, (cwd) => {
    const r = runPostStackSetup(ctx(cwd, { file_path: path.join(cwd, 'supabase', 'functions', 'foo', 'index.ts') }));
    assert.equal(r.kind, 'noop');
  });
});

test('generic write in an already-materialized project → noop (nothing to converge)', () => {
  withAuthedProject(true, (cwd) => {
    const r = runPostStackSetup(ctx(cwd, { file_path: path.join(cwd, 'apps', 'web', 'feature.ts') }));
    assert.equal(r.kind, 'noop');
  });
});
