import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { materializeProjectFromState, materializeProjectIfNeeded } from '../converge';

// Isolate local-prefs so readEffectiveState never reads the developer's machine.
function withTempProject(fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-converge-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeState(dir: string, state: Record<string, unknown>): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(t1, { recursive: true });
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify(state), 'utf8');
}

// A fully-materialized fixture: manifest + rule + skill on disk, AGENTS.md with
// the generated marker, and a .one.json whose materializedStack matches the
// fingerprint so isMaterialized() + hasMaterializedProjectAssets() are true.
function writeMaterialized(dir: string): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'rule', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 'skill', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'ctx\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
  writeState(dir, {
    mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
    onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none',
  });
}

test('materializeProjectFromState: incomplete state reports an "incomplete" outcome (no writer run)', () => {
  withTempProject((dir) => {
    writeState(dir, { mode: 'new-project', stack: 'default' });
    const out = materializeProjectFromState(dir, { trigger: 'unit' });
    assert.equal(out.status, 'incomplete');
    assert.ok(out.systemMessage.includes('incomplete'));
    assert.ok(out.context.includes('State validation issues'));
    assert.equal(out.result, null);
  });
});

test('materializeProjectFromState: moves local-only fields out of shared .one.json', () => {
  withTempProject((dir) => {
    writeState(dir, {
      mode: 'new-project',
      stack: 'default',
      frontend: 'react-vite',
      backend: 'supabase',
      mobile: { enabled: false, framework: 'none', source: 'prompted' },
      technologies: { frontend: ['react'], backend: ['supabase'], mobile: [] },
      projectContext: { source: 'prompted', originalPrompt: 'x', summary: 's', answers: { a: 1 }, collectedAt: '2026-01-01T00:00:00Z' },
      openCode: { enabled: false, source: 'prompted', decidedAt: '2026-01-01T00:00:00Z' },
      codeGraphProvider: 'graphify',
      performance: { level: 'low', source: 'prompted' },
      team: { mode: 'main-agent', source: 'prompted' },
      confirmed: true,
      onboardingComplete: true,
      confirmedAt: '2026-01-01T00:00:00Z',
    });

    const out = materializeProjectFromState(dir, { trigger: 'unit' });
    assert.notEqual(out.status, 'incomplete');
    const onDisk = JSON.parse(fs.readFileSync(path.join(dir, '.traffic-one', '.one.json'), 'utf8'));
    assert.equal('openCode' in onDisk, false);
    assert.equal('codeGraphProvider' in onDisk, false);
    assert.equal('performance' in onDisk, false);
    assert.equal('team' in onDisk, false);
    const prefsPath = process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
    assert.ok(prefsPath);
    const prefs = JSON.parse(fs.readFileSync(prefsPath, 'utf8'));
    assert.equal(prefs.codeGraphProvider, 'graphify');
  });
});

test('materializeProjectIfNeeded: already-materialized → fires the reporter, returns null', () => {
  withTempProject((dir) => {
    writeMaterialized(dir);
    let reported = 0;
    const out = materializeProjectIfNeeded(dir, { trigger: 'unit', reportOneMcp: () => { reported += 1; } });
    assert.equal(out, null);
    assert.equal(reported, 1);
  });
});

test('materializeProjectIfNeeded: unknown stack + not new-project + not onboarded → null', () => {
  withTempProject((dir) => {
    writeState(dir, { mode: 'existing-codebase', stack: 'not-a-stack' });
    const out = materializeProjectIfNeeded(dir, {});
    assert.equal(out, null);
  });
});
