import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { materializeProjectFromState, materializeProjectIfNeeded } from '../converge';
import { stackFingerprint, stateVersion, writeGlobalCodeGraphProvider } from '../../state';
import { declaredProjectContent, writeMaterializedContent, type ProjectContent } from './fixtures/materialized-content';

// Isolate local-prefs AND one.json (the machine-wide store) so readEffectiveState
// never reads the developer's machine.
function withTempProject(fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-converge-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  const prevState = env.TRAFFIC_ONE_STATE_PATH;
  const prevHost = env.TRAFFIC_ONE_HOST;
  const prevPlan = env.TRAFFIC_ONE_USER_PLAN;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  env.TRAFFIC_ONE_STATE_PATH = path.join(dir, 'one.json');
  env.TRAFFIC_ONE_HOST = 'codex';
  env.TRAFFIC_ONE_USER_PLAN = 'pro';
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    if (prevState === undefined) delete env.TRAFFIC_ONE_STATE_PATH; else env.TRAFFIC_ONE_STATE_PATH = prevState;
    if (prevHost === undefined) delete env.TRAFFIC_ONE_HOST; else env.TRAFFIC_ONE_HOST = prevHost;
    if (prevPlan === undefined) delete env.TRAFFIC_ONE_USER_PLAN; else env.TRAFFIC_ONE_USER_PLAN = prevPlan;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeState(dir: string, state: Record<string, unknown>): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(t1, { recursive: true });
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify(state), 'utf8');
}

function writePkg(dir: string, json: Record<string, unknown>): void {
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify(json), 'utf8');
}

const MATERIALIZED_STATE = {
  mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
  onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none',
} as const;

const declaredContent = (dir: string): ProjectContent => declaredProjectContent(dir, { ...MATERIALIZED_STATE });

// manifest + every declared rule/skill on disk, AGENTS.md with the generated
// marker, and a .one.json whose materializedStack matches the fingerprint so
// isMaterialized() + hasMaterializedProjectAssets() are true.
function writeMaterialized(dir: string): void {
  writeMaterializedContent(dir, { state: { ...MATERIALIZED_STATE } });
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'ctx\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
  // The ACTIVE HOST'S ROLE CONTRACTS, which "materialized" now includes: a
  // project whose host contract directory is empty is one convergence short, and
  // `materializeProjectIfNeeded` says so (`roleContractsNeedConvergence`). The
  // host is pinned to codex above, so this is `.traffic-one/agents/**`.
  //
  // Deliberately WITHOUT the generated marker: an unmarked file is user-authored
  // as far as every writer is concerned, so it is never swept and never rewritten,
  // and the `written`/`removed` counts other tests in this file assert are
  // untouched by its presence.
  const agents = path.join(dir, '.traffic-one', 'agents');
  fs.mkdirSync(agents, { recursive: true });
  fs.writeFileSync(path.join(agents, 'senior-architect.md'), '# senior-architect\ncontract\n', 'utf8');
  writeState(dir, { ...MATERIALIZED_STATE });
}

test('materializeProjectFromState: incomplete state reports an "incomplete" outcome (no writer run)', () => {
  withTempProject((dir) => {
    writeState(dir, { mode: 'new-project', stack: 'default' });
    const out = materializeProjectFromState(dir, { trigger: 'unit' });
    assert.equal(out.status, 'incomplete');
    assert.ok(out.systemMessage.includes('incomplete'));
    assert.ok(out.context.includes('State validation issues'));
    assert.equal(out.result, null);
  });
});

test('materializeProjectFromState: moves local-only fields out of shared .one.json', () => {
  withTempProject((dir) => {
    const performanceTarget = { plan: 'pro', appliedFingerprint: 'a'.repeat(64), configVersion: 0 };
    fs.writeFileSync(process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH as string, JSON.stringify({
      hosts: {
        codex: {
          performance: { level: 'low', source: 'prompted', target: performanceTarget },
          team: { mode: 'main-agent', source: 'prompted' },
        },
      },
    }), 'utf8');
    writeState(dir, {
      mode: 'new-project',
      stack: 'default',
      frontend: 'react-vite',
      backend: 'supabase',
      mobile: { enabled: false, framework: 'none', source: 'prompted' },
      technologies: { frontend: ['react'], backend: ['supabase'], mobile: [] },
      projectContext: { source: 'prompted', originalPrompt: 'x', summary: 's', answers: { a: 1 }, collectedAt: '2026-01-01T00:00:00Z' },
      openCode: { enabled: false, source: 'prompted', decidedAt: '2026-01-01T00:00:00Z' },
      codeGraphProvider: 'graphify',
      performance: { level: 'low', source: 'prompted' },
      team: { mode: 'main-agent', source: 'prompted' },
      confirmed: true,
      onboardingComplete: true,
      confirmedAt: '2026-01-01T00:00:00Z',
    });
    // codeGraphProvider is machine-wide now — completeness needs it set globally.
    writeGlobalCodeGraphProvider('graphify');

    const out = materializeProjectFromState(dir, { trigger: 'unit' });
    assert.notEqual(out.status, 'incomplete');
    const onDisk = JSON.parse(fs.readFileSync(path.join(dir, '.traffic-one', '.one.json'), 'utf8'));
    assert.equal('openCode' in onDisk, false);
    // codeGraphProvider is machine-wide now — stripped from shared state and NOT
    // promoted into per-project prefs.
    assert.equal('codeGraphProvider' in onDisk, false);
    assert.equal('performance' in onDisk, false);
    assert.equal('team' in onDisk, false);
    const prefsPath = process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
    assert.ok(prefsPath);
    const prefs = JSON.parse(fs.readFileSync(prefsPath, 'utf8'));
    assert.deepEqual(prefs.hosts.codex.performance, {
      level: 'low', source: 'prompted', target: performanceTarget,
    });
    assert.equal('performance' in prefs, false, 'legacy top-level host prefs are not migrated silently');
    assert.equal('codeGraphProvider' in prefs, false);
  });
});

test('materializeProjectIfNeeded: already-materialized → fires the reporter, returns null', () => {
  withTempProject((dir) => {
    writeMaterialized(dir);
    let reported = 0;
    const out = materializeProjectIfNeeded(dir, { trigger: 'unit', reportOneMcp: () => { reported += 1; } });
    assert.equal(out, null);
    assert.equal(reported, 1);
  });
});

// An 'installed'-classified plugin root: the compiled runtime entry plus real
// content at the SHIPPED paths (`rules/**`, `skills-catalog/**`, `agents/**`).
// Any test that expects materialization to actually happen needs one, because
// materializeProjectAssets refuses every other layout — including this repo,
// which is a 'source' checkout under tsx and keeps its rules under
// `src/modules/rules/rules/**`, where no `<root>/rules/**` join can reach them.
function withInstalledPluginRoot(fn: () => void): void {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 't1-converge-plugin-'));
  const modules = path.resolve(__dirname, '..', '..', '..', 'modules');
  fs.mkdirSync(path.join(root, 'scripts'), { recursive: true });
  fs.writeFileSync(path.join(root, 'scripts', 'hook-runtime.cjs'), '// test fixture stub\n', 'utf8');
  // stateVersion() reads THIS root's package.json (pluginVersion, default
  // '0.0.0'), and it is what isMaterialized() compares materializedVersion
  // against — so a fixture root without one makes every version look stale-free.
  fs.writeFileSync(path.join(root, 'package.json'), JSON.stringify({ name: 'traffic-one', version: '9.9.9' }), 'utf8');
  // Symlinks to the real trees, not a two-rule/two-skill stub: the writer now
  // refuses a root that resolves only PART of what the project's own runtime
  // declares (materialize.ts tornRootRefusal), and a stub is that shape.
  fs.symlinkSync(path.join(modules, 'rules', 'rules'), path.join(root, 'rules'), 'dir');
  fs.symlinkSync(path.join(modules, 'skills', 'skills-catalog'), path.join(root, 'skills-catalog'), 'dir');
  fs.mkdirSync(path.join(root, 'agents'), { recursive: true });
  for (const role of ['senior-frontend', 'senior-backend']) {
    fs.copyFileSync(path.join(modules, role, 'agent.md'), path.join(root, 'agents', `${role}.md`));
  }
  const previous = process.env.TRAFFIC_ONE_PLUGIN_ROOT;
  process.env.TRAFFIC_ONE_PLUGIN_ROOT = root;
  try {
    fn();
  } finally {
    if (previous === undefined) delete process.env.TRAFFIC_ONE_PLUGIN_ROOT; else process.env.TRAFFIC_ONE_PLUGIN_ROOT = previous;
    fs.rmSync(root, { recursive: true, force: true });
  }
}

test('materializeProjectIfNeeded: a stale materializedVersion refreshes generated context', () => {
  withTempProject((dir) => withInstalledPluginRoot(() => {
    const performanceTarget = { plan: 'pro', appliedFingerprint: 'a'.repeat(64), configVersion: 0 };
    writeMaterialized(dir);
    const statePath = path.join(dir, '.traffic-one', '.one.json');
    const stale = JSON.parse(fs.readFileSync(statePath, 'utf8')) as Record<string, unknown>;
    Object.assign(stale, {
      materializedVersion: '0.0.0',
      mobile: { enabled: false, framework: 'none', source: 'prompted' },
      technologies: { frontend: ['react'], backend: ['supabase'], mobile: [] },
      projectContext: { source: 'prompted', originalPrompt: 'x', summary: 'x', answers: {}, collectedAt: '2026-01-01T00:00:00Z' },
      confirmed: true,
      confirmedAt: '2026-01-01T00:00:00Z',
      realtime: 'none',
      supabaseFunctionsAutoDeploy: 'ask',
    });
    writeState(dir, stale);
    fs.writeFileSync(process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH as string, JSON.stringify({
      openCode: { enabled: false, source: 'prompted', decidedAt: '2026-01-01T00:00:00Z' },
      hosts: {
        codex: {
          performance: { level: 'balanced', source: 'prompted', target: performanceTarget },
          team: { mode: 'subagents', source: 'prompted', approved: true },
        },
      },
    }), 'utf8');
    writeGlobalCodeGraphProvider('graphify');

    const out = materializeProjectIfNeeded(dir, { trigger: 'version-refresh' });
    assert.ok(out, 'a version mismatch must invoke the materializer');
    assert.ok(out?.status === 'materialized' || out?.status === 'current');
    const persisted = JSON.parse(fs.readFileSync(statePath, 'utf8'));
    assert.equal(persisted.materializedVersion, stateVersion());
    assert.ok(fs.readFileSync(path.join(dir, 'AGENTS.md'), 'utf8').includes('run maintenance triage before that greenfield team flow'));
  }));
});

// materializeProjectFromState validates the FULL state (unlike
// materializeProjectIfNeeded's isMaterialized short-circuit), so a refusal test
// needs the same complete fixture as the "stale materializedVersion" test above.
function writeCompleteMaterializedFixture(dir: string): string {
  const performanceTarget = { plan: 'pro', appliedFingerprint: 'a'.repeat(64), configVersion: 0 };
  writeMaterialized(dir);
  const statePath = path.join(dir, '.traffic-one', '.one.json');
  const state = JSON.parse(fs.readFileSync(statePath, 'utf8')) as Record<string, unknown>;
  Object.assign(state, {
    mobile: { enabled: false, framework: 'none', source: 'prompted' },
    technologies: { frontend: ['react'], backend: ['supabase'], mobile: [] },
    projectContext: { source: 'prompted', originalPrompt: 'x', summary: 'x', answers: {}, collectedAt: '2026-01-01T00:00:00Z' },
    confirmed: true,
    confirmedAt: '2026-01-01T00:00:00Z',
    realtime: 'none',
    supabaseFunctionsAutoDeploy: 'ask',
  });
  writeState(dir, state);
  fs.writeFileSync(process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH as string, JSON.stringify({
    openCode: { enabled: false, source: 'prompted', decidedAt: '2026-01-01T00:00:00Z' },
    hosts: {
      codex: {
        performance: { level: 'low', source: 'prompted', target: performanceTarget },
        team: { mode: 'main-agent', source: 'prompted' },
      },
    },
  }), 'utf8');
  writeGlobalCodeGraphProvider('graphify');
  return statePath;
}

// Every way materializeProjectAssets can refuse, surfaced end-to-end. The stamp
// assertions are the point: materializedStack/materializedAt/materializedVersion
// are what isMaterialized() reads to short-circuit later convergence, so
// stamping them after a run that materialized nothing is what turned a transient
// condition (a plugin root mid-write, misconfigured, or a checkout) into a
// project that never tried again and silently had zero skills forever.
const REFUSALS = [
  {
    name: "'unverified' root: an unrelated directory",
    skipped: 'plugin-root-unverified',
    expect: ['carries neither a compiled runtime', 'scripts/hook-runtime.cjs'],
    build: (dir: string) => { fs.writeFileSync(path.join(dir, 'README.txt'), 'not a plugin\n', 'utf8'); },
  },
  {
    name: "'source' root: the Traffic One authoring checkout (the reported incident)",
    skipped: 'plugin-root-source-checkout',
    expect: ['SOURCE checkout', 'npm run gen', 'src/modules/skills/skills-catalog/**'],
    build: (dir: string) => {
      fs.mkdirSync(path.join(dir, 'src', 'gen', 'static'), { recursive: true });
      fs.writeFileSync(path.join(dir, 'src', 'gen', 'static', 'plugin-instructions.md'), '# stub\n', 'utf8');
      fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ name: 'traffic-one' }), 'utf8');
    },
  },
  {
    name: "'installed' root that resolves no rule and no skill (a partial install)",
    skipped: 'resolved-content-empty',
    // The wording is the assertion: this id also covers "45 rules resolved, no
    // skills", so the sentence has to be read off the counts rather than hedged
    // into "0 rule file(s) and 0 skill(s)" — which described none of the three
    // shapes it was serving.
    expect: ['resolved nothing at all — not one rule file, not one skill', 'rsync'],
    build: (dir: string) => {
      fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
      fs.writeFileSync(path.join(dir, 'scripts', 'hook-runtime.cjs'), '// stub\n', 'utf8');
      fs.mkdirSync(path.join(dir, 'rules'), { recursive: true });
      fs.writeFileSync(path.join(dir, 'rules', 'unrelated.md'), '# not a Traffic One rule\n', 'utf8');
    },
  },
  {
    // The torn root: a complete `rules/` beside a `skills-catalog/` that lost the
    // race with an rsync. Nothing is empty, so no count-based clause fires — and
    // before the completeness refusal this run swept every manifest-tracked skill
    // and stamped the project materialized over one skill.
    name: "'installed' root with a complete rules/ and a torn skills-catalog/",
    skipped: 'plugin-root-content-incomplete',
    expect: ['content trees are incomplete', 'resolved SOME of this project', 'did not come from one build', 'rsync'],
    build: (dir: string) => {
      const modules = path.resolve(__dirname, '..', '..', '..', 'modules');
      fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
      fs.writeFileSync(path.join(dir, 'scripts', 'hook-runtime.cjs'), '// stub\n', 'utf8');
      fs.symlinkSync(path.join(modules, 'rules', 'rules'), path.join(dir, 'rules'), 'dir');
      const kept = path.join(dir, 'skills-catalog', 'project-memory');
      fs.mkdirSync(kept, { recursive: true });
      fs.copyFileSync(
        path.join(modules, 'skills', 'skills-catalog', 'project-memory', 'SKILL.md'),
        path.join(kept, 'SKILL.md'),
      );
    },
  },
] as const;

test("materializeProjectFromState: every plugin-root refusal reports 'skipped', preserves disk byte-for-byte, and never stamps the state", () => {
  for (const refusal of REFUSALS) {
    withTempProject((dir) => {
      const statePath = writeCompleteMaterializedFixture(dir);
      const rulePath = path.join(dir, '.traffic-one', 'rules', 'common', 'auth-gate.md');
      const skillPath = path.join(dir, '.traffic-one', 'skills', 'project-memory', 'SKILL.md');
      const manifestPath = path.join(dir, '.traffic-one', 'manifest.json');
      const before = {
        rule: fs.readFileSync(rulePath, 'utf8'),
        skill: fs.readFileSync(skillPath, 'utf8'),
        manifest: fs.readFileSync(manifestPath, 'utf8'),
        agents: fs.readFileSync(path.join(dir, 'AGENTS.md'), 'utf8'),
        state: JSON.parse(fs.readFileSync(statePath, 'utf8')) as Record<string, unknown>,
      };
      assert.equal(before.state.materializedAt, undefined, 'the fixture has never been stamped');

      const brokenRoot = fs.mkdtempSync(path.join(os.tmpdir(), 't1-converge-refusal-'));
      refusal.build(brokenRoot);
      const prevPlugin = process.env.TRAFFIC_ONE_PLUGIN_ROOT;
      process.env.TRAFFIC_ONE_PLUGIN_ROOT = brokenRoot;
      let out;
      try {
        out = materializeProjectFromState(dir, { trigger: 'unit' });
      } finally {
        if (prevPlugin === undefined) delete process.env.TRAFFIC_ONE_PLUGIN_ROOT; else process.env.TRAFFIC_ONE_PLUGIN_ROOT = prevPlugin;
        fs.rmSync(brokenRoot, { recursive: true, force: true });
      }

      assert.equal(out.status, 'skipped', refusal.name);
      assert.equal(out.result?.skipped, refusal.skipped, refusal.name);
      assert.equal(out.result?.removed, 0, `${refusal.name}: nothing deleted`);
      assert.equal(out.result?.written, 0, `${refusal.name}: nothing written`);
      // The diagnostic has to name the root, who supplied it, what is wrong, and
      // how to fix it — a bare "skipped" leaves the user with zero skills and no
      // idea why.
      assert.ok(out.context.includes(brokenRoot), `${refusal.name}: names the resolved root`);
      assert.ok(out.context.includes('TRAFFIC_ONE_PLUGIN_ROOT'), `${refusal.name}: names which env var supplied it`);
      assert.ok(out.context.includes('doctor'), `${refusal.name}: points at the doctor command`);
      assert.ok(out.context.includes('Nothing was deleted'), `${refusal.name}: states that disk is intact`);
      for (const needle of refusal.expect) {
        assert.ok(out.context.includes(needle), `${refusal.name}: explains the cause (${needle})`);
      }

      assert.equal(fs.readFileSync(rulePath, 'utf8'), before.rule, `${refusal.name}: rule is byte-identical`);
      assert.equal(fs.readFileSync(skillPath, 'utf8'), before.skill, `${refusal.name}: skill is byte-identical`);
      assert.equal(fs.readFileSync(manifestPath, 'utf8'), before.manifest, `${refusal.name}: manifest is byte-identical`);
      assert.equal(fs.readFileSync(path.join(dir, 'AGENTS.md'), 'utf8'), before.agents, `${refusal.name}: AGENTS.md is byte-identical`);

      const after = JSON.parse(fs.readFileSync(statePath, 'utf8')) as Record<string, unknown>;
      assert.equal(after.materializedAt, undefined, `${refusal.name}: materializedAt is NOT stamped for a run that materialized nothing`);
      assert.equal(after.materializedVersion, before.state.materializedVersion, `${refusal.name}: materializedVersion is untouched`);
      assert.equal(after.materializedStack, before.state.materializedStack, `${refusal.name}: materializedStack is untouched`);
    });
  }
});

// THE SELF-HEAL. The refusal above protects a project that still has its content;
// this covers the projects that already lost it, before the refusal existed. Their
// manifest lists 1 skill, that 1 skill is on disk, the stamp is current, and
// isMaterialized() + hasMaterializedProjectAssets() therefore short-circuit every
// later convergence — so nothing looks wrong and the other 46 never come back.
test('materializeProjectIfNeeded: a project truncated by an earlier torn root re-converges and gets its content back', () => {
  withTempProject((dir) => withInstalledPluginRoot(() => {
    const statePath = writeCompleteMaterializedFixture(dir);
    const declared = declaredContent(dir);
    const t1 = path.join(dir, '.traffic-one');

    // Truncate exactly the way the bug did: one surviving skill, one surviving
    // rule, a manifest that agrees with disk, and a `materializedAt` stamp
    // claiming the run succeeded.
    const survivingRule = declared.rules[0];
    for (const relPath of declared.rules.slice(1)) fs.rmSync(path.join(t1, relPath), { force: true });
    for (const name of declared.skills.filter((s) => s !== 'project-memory')) {
      fs.rmSync(path.join(t1, 'skills', name), { recursive: true, force: true });
    }
    fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
      generatedBy: 'traffic-one', stack: 'default', rules: [survivingRule], skills: ['project-memory'],
    }), 'utf8');
    const stamped = JSON.parse(fs.readFileSync(statePath, 'utf8')) as Record<string, unknown>;
    stamped.materializedAt = '2026-01-01T00:00:00Z';
    writeState(dir, stamped);

    const out = materializeProjectIfNeeded(dir, { trigger: 'unit' });

    assert.ok(out, 'a truncated manifest must invoke the materializer instead of short-circuiting');
    assert.equal(out?.result?.skipped, undefined, `the healthy root must materialize, got ${out?.result?.skipped}`);
    const healed = JSON.parse(fs.readFileSync(path.join(t1, 'manifest.json'), 'utf8')) as Record<string, unknown>;
    assert.deepEqual([...(healed.skills as string[])].sort(), declared.skills, 'every declared skill is tracked again');
    for (const name of declared.skills) {
      assert.ok(fs.existsSync(path.join(t1, 'skills', name, 'SKILL.md')), `${name} is back on disk`);
    }
    for (const relPath of declared.rules) {
      assert.ok(fs.existsSync(path.join(t1, relPath)), `${relPath} is back on disk`);
    }

    // Self-limiting: the successful run rewrote the manifest, so the next hook
    // short-circuits again. A heal that re-fired every time would re-materialize
    // on every mutating tool call forever.
    assert.equal(materializeProjectIfNeeded(dir, { trigger: 'unit' }), null, 'the heal goes quiet once the project is whole');
  }));
});

// ── the refused STAMP ───────────────────────────────────────────────────────
// The refusals above are about the WRITER declining. These two are about the
// state write at the end, whose boolean was dropped: `materializedStack` /
// `materializedAt` / `materializedVersion` are the entire record that
// materialization happened, and `isMaterialized()` reads them to decide whether
// to converge again. Without them every later hook re-converges and keeps
// returning a NON-NULL outcome — which onboarding-gate/handler.ts reads on a
// mutating PreToolUse as allow+context after a successful heal, or
// `deny('materialization-not-converged')` when the stamp was refused. A refused
// stamp reported as `materialized` would now allow writes against an unstamped
// tree on every later hook. So the refused stamp must not report `materialized`.
//
// MOVE-ASIDE rather than a dangling link: writeState re-reads `.one.json` (for
// preserveCurrentRunId) and readEffectiveState reads it first, so a dangling link
// makes the read fail and the run bails before the write — a vacuous pass the
// writable baseline cannot catch, since the baseline is a different directory.
function fenceStateMoveAside(statePath: string): void {
  const aside = `${statePath}.aside`;
  const before = fs.readFileSync(statePath, 'utf8');
  fs.renameSync(statePath, aside);
  fs.symlinkSync(aside, statePath);
  assert.equal(fs.readFileSync(statePath, 'utf8'), before,
    'fixture guard: reads still resolve through the link, so the run reaches its write');
}

test('materializeProjectFromState: a refused materialization stamp is reported as failed, not materialized', () => {
  withTempProject((dir) => withInstalledPluginRoot(() => {
    const statePath = writeCompleteMaterializedFixture(dir);
    const baseline = materializeProjectFromState(dir, { trigger: 'unit' });
    assert.ok(baseline.status === 'materialized' || baseline.status === 'current',
      `writable baseline: an unfenced run materializes, got ${baseline.status}`);
    assert.equal(typeof JSON.parse(fs.readFileSync(statePath, 'utf8')).materializedAt, 'string',
      'writable baseline: and the stamp — the whole record that it happened — is on disk');
  }));

  withTempProject((dir) => withInstalledPluginRoot(() => {
    const statePath = writeCompleteMaterializedFixture(dir);
    fenceStateMoveAside(statePath);

    const out = materializeProjectFromState(dir, { trigger: 'unit' });
    assert.equal(out.status, 'failed',
      'a run whose stamp the fence refused must not report the project as materialized or current');
    assert.match(out.context, /\.one\.json/, 'and the diagnostic names the exact refused path');
    assert.match(out.context, /materializedStack/, 'and the fields that are missing because of it');
    assert.ok((out.result?.written ?? 0) > 0,
      'fixture guard: the assets really were written — this is the RECORD that is missing, not the content');
    assert.equal(JSON.parse(fs.readFileSync(statePath, 'utf8')).materializedAt, undefined,
      'fixture guard: the stamp really was refused');
  }));
});

test('materializeProjectIfNeeded: a refused canonicalization is not answered with "nothing needed"', () => {
  // The sharp shape: this state is materialized, its assets are complete, and the
  // three `return null` branches below the canonicalization would all say "nothing
  // needed" — about a project whose state file cannot be written at all.
  const seed = (dir: string): string => {
    const statePath = writeCompleteMaterializedFixture(dir);
    const state = JSON.parse(fs.readFileSync(statePath, 'utf8')) as Record<string, unknown>;
    state.materializedAt = '2026-01-01T00:00:00Z';
    state.materializedVersion = stateVersion();
    state.materializedStack = stackFingerprint(state);
    // Left noncanonical on purpose, so normalizeState reports a change and the
    // canonicalization write is actually attempted.
    delete state.confirmed;
    writeState(dir, state);
    return statePath;
  };

  withTempProject((dir) => withInstalledPluginRoot(() => {
    seed(dir);
    assert.equal(materializeProjectIfNeeded(dir, { trigger: 'unit' }), null,
      'writable baseline: an unfenced convergence on a whole, materialized project needs nothing');
  }));

  withTempProject((dir) => withInstalledPluginRoot(() => {
    const statePath = seed(dir);
    fenceStateMoveAside(statePath);

    const out = materializeProjectIfNeeded(dir, { trigger: 'unit' });
    assert.equal(out?.status, 'failed',
      'a project whose .one.json cannot be written is not "nothing needed"');
    assert.match(out?.context ?? '', /\.one\.json/, 'and the diagnostic names the exact refused path');
  }));
});

test('materializeProjectIfNeeded: unknown stack + not new-project + not onboarded → null', () => {
  withTempProject((dir) => {
    writeState(dir, { mode: 'existing-codebase', stack: 'not-a-stack' });
    const out = materializeProjectIfNeeded(dir, {});
    assert.equal(out, null);
  });
});

test('materializeProjectIfNeeded: a state-less monorepo sub-package is NOT minted its own .traffic-one', () => {
  withTempProject((root) => {
    // Un-onboarded workspace root + a sparse sub-package with no state of its own —
    // detectMode would call it 'new-project' and the old path wrote a stray shallow
    // .traffic-one/.one.json into it (the packages/ui incident).
    writePkg(root, { name: 'mono', private: true, workspaces: ['packages/*'] });
    const ui = path.join(root, 'packages', 'ui');
    fs.mkdirSync(ui, { recursive: true });

    const out = materializeProjectIfNeeded(ui, { trigger: 'unit' });
    assert.equal(out, null);
    assert.equal(fs.existsSync(path.join(ui, '.traffic-one')), false, 'no stray state minted into the sub-package');
  });
});

// ── the plan migration's return value, and who reads it ───────────────────────
//
// Both call sites here used to DISCARD it, while plan-migration.ts reasoned at
// length in a docblock about which paths `migrated` may name. Nothing read the
// answer, so the reasoning defended nothing. It reaches the agent now, through the
// `context` of whatever outcome convergence returns.

test('materializeProjectFromState: a fold is REPORTED in the outcome the agent reads', () => {
  // A REFUSED materialization, because the report must not depend on the run
  // having succeeded: an unverified plugin root is the cheapest complete-state
  // fixture, and the migration runs before the writer either way.
  withTempProject((dir) => {
    writeCompleteMaterializedFixture(dir);
    fs.writeFileSync(path.join(dir, 'architecture.md'), '# Legacy\n\nModule map from the old file.\n', 'utf8');

    const out = materializeProjectFromState(dir, { trigger: 'unit' });

    assert.match(out.context, /Legacy `architecture\.md` folded into `\.traffic-one\/plan\.md` and removed: `architecture\.md`\./);
    assert.equal(fs.existsSync(path.join(dir, 'architecture.md')), false);
    assert.ok(fs.readFileSync(path.join(dir, '.traffic-one', 'plan.md'), 'utf8').includes('Module map from the old file.'));
  });
});

test('materializeProjectFromState: a document deliberately LEFT ALONE is reported with its reason', () => {
  // The silence this replaces is the one KNOWN-ISSUES item 10 records: a document
  // that is not folded looks identical to one nobody tried to fold. A vendored file
  // carrying delegate markers is the case where the difference matters most.
  withTempProject((dir) => {
    writeCompleteMaterializedFixture(dir);
    const doc = path.join(dir, 'packages', 'vendor', 'architecture.md');
    fs.mkdirSync(path.dirname(doc), { recursive: true });
    fs.writeFileSync(doc, '# Vendor\n\n<!-- opencode-delegate:start -->\n- role: qa-engineer | files: ** | task: pass\n<!-- opencode-delegate:end -->\n', 'utf8');

    const out = materializeProjectFromState(dir, { trigger: 'unit' });

    assert.match(out.context, /Left exactly where it is, unfolded and not removed: `packages\/vendor\/architecture\.md` \(carries Traffic One runtime marker grammar/);
    assert.equal(fs.existsSync(doc), true);
  });
});

test('materializeProjectIfNeeded: the notice survives the paths that return an outcome of their own', () => {
  // `materializeProjectIfNeeded` has to migrate BEFORE its own branches — three of
  // them return `null` and the plan gate still needs the plan — so its notice is
  // threaded into the delegate rather than recomputed there. Recomputing would
  // report nothing: the second, idempotent migration finds the document gone.
  withTempProject((dir) => {
    writeState(dir, { mode: 'existing-codebase', stack: 'not-a-stack', onboardingComplete: true });
    fs.writeFileSync(path.join(dir, 'architecture.md'), '# Legacy\n\nCarried through the delegate.\n', 'utf8');

    const out = materializeProjectIfNeeded(dir, { trigger: 'unit' });

    assert.notEqual(out, null, 'an unknown stack with onboardingComplete delegates rather than going quiet');
    assert.match(out!.context, /folded into `\.traffic-one\/plan\.md` and removed: `architecture\.md`\./);
    assert.ok(fs.readFileSync(path.join(dir, '.traffic-one', 'plan.md'), 'utf8').includes('Carried through the delegate.'));
  });
});
