// src/runners/opencode-host/wrapper-source.ts
// The embedded ESM OpenCode plugin, emitted as ONE template literal (its
// spawnSync and payload normalizers live inside the generated string).

import * as os from 'os';
import * as path from 'path';
import { fileURLToPath } from 'url';
import {
  OPENCODE_HOOK_CHAT_MESSAGE,
  OPENCODE_HOOK_EVENT,
  OPENCODE_HOOK_SYSTEM_TRANSFORM,
  OPENCODE_HOOK_TOOL_AFTER,
  OPENCODE_HOOK_TOOL_BEFORE,
  OPENCODE_HOST_GLOBAL_PLUGIN_ID,
  OPENCODE_HOST_PACKAGE,
  OPENCODE_HOST_PROJECT_MARKER_REL,
  OPENCODE_HOST_TARGET_VERSION,
} from '../../config/opencode-host';
import {
  ONE_MCP_MANAGED_TOOLS,
  ONE_MCP_SERVER_NAME,
} from '../../config/one-mcp';
import { ONE_MCP_AGENT_TOOL_DENY_REASON } from '../../shared/one-mcp/agent-tools';
import {
  EMITTED_BOUNDED_READ_FN,
  emittedBoundedReadSource,
} from '../../shared/emitted-bounded-read';

import {
  ownerRecord,
} from './host-records';
import {
  jsString,
} from './jsonc-config';

export function wrapperSource(pluginRoot: string, installedAt = new Date().toISOString()): string {
  const owner = { ...ownerRecord(pluginRoot), installedAt };
  return `// GENERATED BY traffic-one — OpenCode host wrapper.
// OpenCode target: ${OPENCODE_HOST_PACKAGE}@${OPENCODE_HOST_TARGET_VERSION}
// Installed globally through ~/.config/opencode/opencode.jsonc's "plugin" array.
const TRAFFIC_ONE_WRAPPER_OWNER = ${JSON.stringify(owner)};

import { spawnSync } from 'node:child_process';
import { existsSync, appendFileSync } from 'node:fs';
import * as nodeFs from 'node:fs';
import { createRequire } from 'node:module';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __require = createRequire(import.meta.url);

// A read whose SHAPE somebody else chose, BOUNDED: this wrapper walks UPWARD from
// the host's cwd, so the files below live in a PROJECT — and a project's
// \`.traffic-one/.one.json\` arrives through a pull request, where git records a
// symlink as mode 120000. A plain readFileSync of a FIFO or of a link to
// /dev/zero never returns (DRIVEN: SIGKILL at 8 068 ms, control 30 ms), and a
// wrapper that never returns is a host plugin load that cannot report anything.
// O_NONBLOCK opens instead of waiting; the fstat is on the DESCRIPTOR, so what is
// classified is what was opened. Emitted verbatim from
// src/shared/emitted-bounded-read.ts — this file cannot import the leaf, because
// it runs before any plugin root is known.
${emittedBoundedReadSource('nodeFs')}

const TRAFFIC_ONE_PLUGIN_ROOT = ${jsString(pluginRoot)};
const TRAFFIC_ONE_RUNTIME = path.join(TRAFFIC_ONE_PLUGIN_ROOT, 'scripts', 'opencode-hook-runtime.cjs');
const TRAFFIC_ONE_ACTIVATION_REL = ${JSON.stringify(OPENCODE_HOST_PROJECT_MARKER_REL.split('/'))};
const TRAFFIC_ONE_MANAGED_MCP_TOOLS = new Set(${JSON.stringify(
  ONE_MCP_MANAGED_TOOLS.map((tool) => `${ONE_MCP_SERVER_NAME}_${tool}`),
)});

function asObject(value) {
  return value && typeof value === 'object' && !Array.isArray(value) ? value : {};
}

function firstString(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value;
  }
  return '';
}

function isManagedOneMcpTool(rawName) {
  return TRAFFIC_ONE_MANAGED_MCP_TOOLS.has(firstString(rawName));
}

function validTrafficOneRoot(dir) {
  const stateFile = path.join(dir, '.traffic-one', '.one.json');
  if (!existsSync(stateFile)) return false;
  try {
    const state = JSON.parse(${EMITTED_BOUNDED_READ_FN}(stateFile) ?? 'null');
    return Boolean(state && typeof state === 'object'
      && typeof state.mode === 'string'
      && state.mode.trim());
  } catch {
    return false;
  }
}

function validTrafficOneActivationRoot(dir) {
  const marker = readTrafficOneMarker(dir);
  return Boolean(marker && marker.enabled !== false);
}

function readTrafficOneMarker(dir) {
  const markerFile = path.join(dir, ...TRAFFIC_ONE_ACTIVATION_REL);
  if (!existsSync(markerFile)) return null;
  try {
    const marker = JSON.parse(${EMITTED_BOUNDED_READ_FN}(markerFile) ?? 'null');
    if (!marker || typeof marker !== 'object'
      || marker.owner !== 'traffic-one'
      || marker.version !== 1) return null;
    return marker;
  } catch {
    return null;
  }
}

function disabledTrafficOneRoot(dir) {
  const marker = readTrafficOneMarker(dir);
  return Boolean(marker && marker.enabled === false);
}

function findTrafficOneRoot(start) {
  let current = path.resolve(start || process.cwd());
  const home = firstString(process.env.HOME, process.env.USERPROFILE);
  const homeRoot = home ? path.resolve(home) : '';
  for (let i = 0; i < 40; i += 1) {
    if (homeRoot && current === homeRoot) return '';
    if (disabledTrafficOneRoot(current)) return '';
    if (validTrafficOneRoot(current) || validTrafficOneActivationRoot(current)) return current;
    const parent = path.dirname(current);
    if (!parent || parent === current) return '';
    current = parent;
  }
  return '';
}

function trafficOneDisabledFor(start) {
  let current = path.resolve(start || process.cwd());
  const home = firstString(process.env.HOME, process.env.USERPROFILE);
  const homeRoot = home ? path.resolve(home) : '';
  for (let i = 0; i < 40; i += 1) {
    if (homeRoot && current === homeRoot) return false;
    if (disabledTrafficOneRoot(current)) return true;
    if (validTrafficOneRoot(current) || validTrafficOneActivationRoot(current)) return false;
    const parent = path.dirname(current);
    if (!parent || parent === current) return false;
    current = parent;
  }
  return false;
}

function fallbackWorkspaceRoot(start) {
  const raw = firstString(start);
  if (!raw) return '';
  const current = path.resolve(raw);
  const home = firstString(process.env.HOME, process.env.USERPROFILE);
  const homeRoot = home ? path.resolve(home) : '';
  if (homeRoot && current === homeRoot) return '';
  return current;
}

function trafficOneRootFor(start) {
  if (trafficOneDisabledFor(start)) return '';
  return findTrafficOneRoot(start) || fallbackWorkspaceRoot(start);
}

function textFromParts(parts) {
  if (!Array.isArray(parts)) return '';
  return parts
    .map((part) => {
      const rec = asObject(part);
      if (rec.type === 'text') return firstString(rec.text);
      if (rec.type === 'subtask') return firstString(rec.prompt, rec.description);
      return '';
    })
    .filter(Boolean)
    .join('\\n');
}

function cwdFromPayload(pluginCtx, input) {
  const rec = asObject(input);
  const session = asObject(rec.session);
  const workspace = asObject(rec.workspace);
  const project = asObject(pluginCtx.project);
  return firstString(
    rec.cwd, rec.workdir, rec.workingDir,
    session.cwd, session.root,
    workspace.root, workspace.path,
    pluginCtx.directory, pluginCtx.worktree,
    project.directory, project.path,
  ) || process.cwd();
}

function normalizeToolPayload(event, input, output, pluginCtx) {
  const rec = asObject(input);
  const out = asObject(output);
  const tool = asObject(rec.tool);
  const args = asObject(out.args || rec.args || rec.arguments || rec.input || rec.tool_input || rec.toolInput || tool.args || tool.input);
  return {
    event,
    cwd: cwdFromPayload(pluginCtx, rec),
    workspaceRoot: firstString(pluginCtx.directory, pluginCtx.worktree),
    tool_name: firstString(rec.tool_name, rec.toolName, rec.name, rec.tool, tool.name, tool.id, tool.type),
    tool_input: args,
    input: rec,
    output: out,
    session_id: firstString(rec.sessionID, rec.sessionId, rec.session_id),
    call_id: firstString(rec.callID, rec.callId, rec.call_id),
  };
}

function normalizePromptPayload(event, input, output, pluginCtx) {
  const rec = asObject(input);
  const out = asObject(output);
  const message = asObject(out.message);
  const parts = Array.isArray(out.parts) ? out.parts : [];
  return {
    event,
    cwd: cwdFromPayload(pluginCtx, rec),
    workspaceRoot: firstString(pluginCtx.directory, pluginCtx.worktree),
    prompt: firstString(rec.prompt, rec.message, rec.text, message.text, message.prompt, textFromParts(parts)),
    // The session id of THIS message's session. For a spawned role subagent, this
    // is the child session — the run-team binder claims it to the role parsed from
    // the spawn prompt's [t1-role: senior-x] marker (OpenCode has no SubagentStart).
    session_id: firstString(rec.sessionID, rec.sessionId, rec.session_id, message.sessionID),
    input: rec,
    output: out,
  };
}

function trafficOneConfigDir() {
  try { return path.dirname(path.dirname(fileURLToPath(import.meta.url))); } catch { return ''; }
}

// Diagnostics are OFF unless a sentinel file exists next to this wrapper's config
// dir (touch ~/.config/opencode/.traffic-one-debug). When on, every hook invocation
// appends one JSON line to traffic-one-debug.log — the only way to see why a hook
// no-ops, since OpenCode 1.17+ logs nothing on plugin load and swallows hook errors.
function debugLog(event, data) {
  try {
    const dir = trafficOneConfigDir();
    if (!dir || !existsSync(path.join(dir, '.traffic-one-debug'))) return;
    appendFileSync(path.join(dir, 'traffic-one-debug.log'), JSON.stringify({ t: new Date().toISOString(), event, ...data }) + '\\n');
  } catch {}
}

function trafficOneHookEnv(projectRoot) {
  const base = {
    ...process.env,
    ELECTRON_RUN_AS_NODE: '1',
    TRAFFIC_ONE_PLUGIN_ROOT,
  };
  try {
    const mod = __require(path.join(TRAFFIC_ONE_PLUGIN_ROOT, 'scripts', 'shared', 'state', 'traffic-one-paths.js'));
    return {
      ...mod.resolveTrafficOneEnv(projectRoot, 'opencode', base),
      ELECTRON_RUN_AS_NODE: '1',
      TRAFFIC_ONE_PLUGIN_ROOT,
    };
  } catch (err) {
    debugLog('hook-env-fallback', { err: String(err && err.message || err) });
    return { ...base, HOME: os.homedir() };
  }
}

function runTrafficOne(subcommand, payload) {
  const projectRoot = trafficOneRootFor(payload.cwd || process.cwd());
  if (!projectRoot) { debugLog('skip-no-root', { subcommand, cwd: payload.cwd || null }); return { kind: 'noop' }; }
  const input = JSON.stringify({ ...payload, cwd: projectRoot, projectRoot, workspaceRoot: projectRoot });
  // ELECTRON_RUN_AS_NODE makes process.execPath behave as node when OpenCode runs
  // the plugin inside an Electron node-service (where execPath is the Electron
  // binary, not node); ignored by plain node/bun, so it is safe everywhere.
  const result = spawnSync(process.execPath, [TRAFFIC_ONE_RUNTIME, subcommand, '--host=opencode'], {
    input,
    encoding: 'utf8',
    timeout: 30000,
    env: trafficOneHookEnv(projectRoot),
  });
  if (result.error || result.status !== 0) {
    debugLog('spawn-fail', { subcommand, projectRoot, execPath: process.execPath, status: result.status, error: result.error ? String(result.error.message || result.error) : null, stderr: String(result.stderr || '').slice(0, 500) });
    return { kind: 'noop' };
  }
  try {
    const parsed = JSON.parse(String(result.stdout || '').trim() || '{"kind":"noop"}');
    debugLog('ok', { subcommand, projectRoot, kind: parsed && parsed.kind });
    return parsed;
  } catch {
    debugLog('parse-fail', { subcommand, projectRoot, stdout: String(result.stdout || '').slice(0, 500) });
    return { kind: 'noop' };
  }
}

function resultText(result) {
  if (!result || result.kind === 'noop') return;
  return firstString(result.context, result.systemMessage, result.reason);
}

function appendSystem(output, result) {
  const text = resultText(result);
  if (!text) return;
  const out = asObject(output);
  if (Array.isArray(out.system)) out.system.push(text);
}

function appendToolWarning(output, result) {
  const text = resultText(result);
  if (!text) return;
  const out = asObject(output);
  out.metadata = { ...asObject(out.metadata), trafficOneWarning: text };
  if (typeof out.output === 'string' && out.output.trim()) out.output = out.output + '\\n\\n[Traffic One]\\n' + text;
  else out.output = '[Traffic One]\\n' + text;
}

function appendPromptContext(output, result) {
  if (!result || result.kind === 'noop') return;
  // systemMessage is the USER-facing banner (it carries the clickable setup
  // link) and context is the agent-facing body. The old firstString(context,
  // systemMessage, …) let context SHADOW the banner, so the link the hook sent
  // was silently dropped — compose BOTH, banner first.
  const banner = firstString(result.systemMessage);
  const body = firstString(result.context, result.reason);
  const suffix = (banner ? '\\n\\n[Traffic One]\\n' + banner : '')
    + (body ? '\\n\\n[Traffic One context]\\n' + body : '');
  if (!suffix) return;
  const out = asObject(output);
  if (!Array.isArray(out.parts) || !out.parts.length) return;
  // OpenCode validates user-message parts against a strict schema (id/sessionID/
  // messageID required) BEFORE saving; a fresh partial part throws "invalid user
  // part before save" and kills the whole prompt. So append our context to an
  // existing text part, which already carries those ids, rather than push a new one.
  for (let i = out.parts.length - 1; i >= 0; i -= 1) {
    const part = out.parts[i];
    if (part && typeof part === 'object' && part.type === 'text' && typeof part.text === 'string') {
      part.text = part.text + suffix;
      return;
    }
  }
}

async function beforeTool(input, output, pluginCtx) {
  const payload = normalizeToolPayload(${jsString(OPENCODE_HOOK_TOOL_BEFORE)}, input, output, pluginCtx);
  // This guard intentionally runs before project-root lookup and before the
  // child runtime spawn. It therefore survives explicit project opt-out,
  // missing runtime files, parse failures, and OpenCode's legacy fail-open path.
  if (isManagedOneMcpTool(payload.tool_name)) {
    throw new Error(${JSON.stringify(ONE_MCP_AGENT_TOOL_DENY_REASON)});
  }
  const result = runTrafficOne('before-tool-use', payload);
  if (result && result.kind === 'deny') {
    throw new Error(firstString(result.reason, result.context) || 'Traffic One denied this OpenCode tool call.');
  }
}

async function afterTool(input, output, pluginCtx) {
  const result = runTrafficOne('after-tool-use', normalizeToolPayload(${jsString(OPENCODE_HOOK_TOOL_AFTER)}, input, output, pluginCtx));
  appendToolWarning(output, result);
}

async function systemTransform(input, output, pluginCtx) {
  const result = runTrafficOne('session-start', normalizePromptPayload(${jsString(OPENCODE_HOOK_SYSTEM_TRANSFORM)}, input, output, pluginCtx));
  if (result && result.kind === 'deny') throw new Error(firstString(result.reason, result.context) || 'Traffic One denied this OpenCode request.');
  appendSystem(output, result);
}

async function chatMessage(input, output, pluginCtx) {
  const result = runTrafficOne('user-prompt-submit', normalizePromptPayload(${jsString(OPENCODE_HOOK_CHAT_MESSAGE)}, input, output, pluginCtx));
  if (result && result.kind === 'deny') throw new Error(firstString(result.reason, result.context) || 'Traffic One denied this OpenCode message.');
  appendPromptContext(output, result);
}

function sessionIdleFromEvent(input) {
  const rec = asObject(input);
  const event = asObject(rec.event || rec);
  const type = firstString(event.type, rec.type);
  // VERIFY(session.idle): the bus event OpenCode emits when a session's turn
  // completes (1.15–1.17 vocabulary). Feature-detected end to end — a renamed
  // or absent event simply never fires this surface.
  if (type !== 'session.idle') return null;
  const props = asObject(event.properties);
  const info = asObject(props.info || event.info);
  return {
    sessionID: firstString(props.sessionID, event.sessionID, info.id, rec.sessionID),
    directory: firstString(info.directory, props.directory, event.directory),
  };
}

// Turn-end delivery: when a session goes idle with Traffic One setup still
// pending, the hook runtime answers with a one-line systemMessage carrying the
// setup link; surface it as a host toast. Deliberately NOT a session-prompt injection
// (that adds a model turn — loop risk). Feature-detected: an SDK without
// client.tui.showToast degrades to a logged no-op, never a crash.
async function sessionIdle(input, pluginCtx) {
  const idle = sessionIdleFromEvent(input);
  if (!idle) return;
  const result = runTrafficOne('session-idle', {
    event: 'session.idle',
    cwd: firstString(idle.directory, pluginCtx.directory, pluginCtx.worktree) || process.cwd(),
    workspaceRoot: firstString(pluginCtx.directory, pluginCtx.worktree),
    session_id: idle.sessionID,
  });
  const text = result && result.kind !== 'noop' ? firstString(result.systemMessage) : '';
  if (!text) return;
  const client = asObject(pluginCtx.client);
  const tui = asObject(client.tui);
  if (typeof tui.showToast === 'function') {
    try {
      await tui.showToast({ body: { message: text, variant: 'info' } });
    } catch (err) {
      debugLog('toast-fail', { err: String(err && err.message || err) });
    }
    return;
  }
  debugLog('stop-delivery-unavailable', { sessionID: idle.sessionID || null });
}

export const TrafficOne = async (ctx = {}) => {
  const pluginCtx = asObject(ctx);
  return {
    ${jsString(OPENCODE_HOOK_TOOL_BEFORE)}: (input, output) => beforeTool(input, output, pluginCtx),
    ${jsString(OPENCODE_HOOK_TOOL_AFTER)}: (input, output) => afterTool(input, output, pluginCtx),
    ${jsString(OPENCODE_HOOK_SYSTEM_TRANSFORM)}: (input, output) => systemTransform(input, output, pluginCtx),
    ${jsString(OPENCODE_HOOK_CHAT_MESSAGE)}: (input, output) => chatMessage(input, output, pluginCtx),
    ${jsString(OPENCODE_HOOK_EVENT)}: (input) => sessionIdle(input, pluginCtx),
  };
};

export default {
  id: ${jsString(OPENCODE_HOST_GLOBAL_PLUGIN_ID)},
  server: TrafficOne,
};
`;
}
