// src/shared/paths.ts
// The ONE path layer. pluginRoot resolves the authoring/install root (env
// override -> __dirname), and the same relative depth holds whether running from
// src/shared (tsx dev) or dist/scripts/shared (compiled). projectRoot is
// hint-aware: it prefers the directory of a tool's target file (PostToolUse
// materialisation derives the project from the edited path, not cwd).

import * as fs from 'fs';
import * as path from 'path';

import type { HookInput, Paths } from '../core/types';

const PLUGIN_ROOT_ENV = [
  'TRAFFIC_ONE_PLUGIN_ROOT',
  'CODEX_PLUGIN_ROOT',
  'CLAUDE_PLUGIN_ROOT',
  'CURSOR_PLUGIN_ROOT',
] as const;

export type PluginRootEnvVar = typeof PLUGIN_ROOT_ENV[number];

// Where the resolved root came from — the __default__ case is the same
// __dirname fallback pluginRoot() always had; the four env cases name exactly
// which of the four wins, because "which one won" is the whole diagnostic
// value when a stale exported root silently outlives the install it named.
export type PluginRootSource = PluginRootEnvVar | 'default';

// What the resolved root actually looks like on disk, decided from what only
// each layout ever contains (nothing else — every predicate here is checked
// against src/gen/index.ts's own sourceRepoRoot() markers and against the
// two artifacts src/build/build-runtime.ts always produces):
//   - 'installed': a real generated+built plugin distribution — it carries
//     BOTH the compiled runtime entry every host invokes as a FILE
//     (scripts/hook-runtime.cjs, the first SHIMS entry build-runtime.ts
//     always writes) AND at least one generated content dir gen always
//     writes WITH SOMETHING IN IT (rules/ or skills-catalog/, from
//     gen/index.ts's MANAGED_OUTPUT_DIRS). Neither half alone is enough, and
//     neither half may be satisfied by a mere directory entry: a `dist/`
//     mid-`npm run build` (content written, scripts/ not yet compiled), a
//     `dist/scripts` copied without its sibling content dirs, and a `dist/`
//     caught mid-`npm run gen` / mid-`rsync` (the content dirs exist but are
//     still EMPTY) are all partial trees, not trustworthy installs.
//   - 'source': the TypeScript authoring checkout — identified by the exact
//     pair sourceRepoRoot() itself trusts (src/gen/static/plugin-instructions.md
//     + package.json), so `pluginRoot()`'s own __dirname fallback under tsx
//     dev (which resolves here) classifies correctly instead of looking
//     broken. It is a legitimate root for PROSE lookups that know the source
//     layout (skill-filters' roleAgentDocCandidates, run-bootstrap-policy's
//     material candidates) and NOT a content root for materialization: the
//     shipped rules/skills tree is generated by gen, not relocated — see
//     materializeProjectAssets.
//   - 'unverified': neither — a nonexistent path, an empty directory, a file,
//     an unrelated directory, or a partial plugin tree (runtime without
//     content, content without runtime, either half still empty).
//     pluginRoot() still returns it (never throws); only a CONTENT CONSUMER
//     (materialization, prose lookup, a spawned executable) may refuse to
//     treat it as authoritative.
export type PluginRootLayout = 'installed' | 'source' | 'unverified';

export interface PluginRootInfo {
  readonly root: string;
  readonly layout: PluginRootLayout;
  readonly source: PluginRootSource;
}

// Every predicate below MUST NOT THROW, for any input — a nonexistent path, a
// file where a directory belongs, a directory where a file belongs, an
// unreadable directory, a symlink loop, an empty or whitespace-only string.
// That is load-bearing rather than defensive: under tsx (dev, `npm test`,
// `npm run gen`, `npm run golden:update`) the resolved root is this checkout,
// so a throwing accessor here does not degrade one diagnostic — it breaks the
// whole toolchain.

// Existence is deliberately NOT the predicate for the two `installed` halves.
// `fs.existsSync` is true for an empty directory and true for a plain FILE of
// the same name, so it called `scripts/hook-runtime.cjs` + an empty `rules/`
// (a `dist/` caught mid-gen, a half-extracted archive, an in-flight rsync) a
// complete install — which then resolved zero rules and zero skills and let
// materialization sweep the project's only copy of both. Content is proven by
// reading the directory, identity by stat'ing the file.

// At least one real entry inside `dir`. readdirSync throws ENOTDIR for a file
// and EACCES for an unreadable directory, both of which mean "not usable
// content" here, so the catch is the answer rather than a swallowed error.
// Dot entries do not count: a stray `.DS_Store` is not shipped content.
//
// This stops at "the directory has entries" on purpose — it stays O(one
// readdir) because pluginRootInfo() runs on every hook invocation. A tree that
// has entries but still cannot resolve the rules/skills a given project needs
// is NOT the classifier's job: materializeProjectAssets refuses when its
// resolved content set comes back empty, whatever this function decided.
function hasEntries(dir: string): boolean {
  try {
    return fs.readdirSync(dir).some((name) => !name.startsWith('.'));
  } catch {
    return false;
  }
}

// A real file at `candidate` — statSync (following symlinks, so an installed
// tree may symlink its runtime) and never a directory of the same name.
function isFileSafe(candidate: string): boolean {
  try {
    return fs.statSync(candidate).isFile();
  } catch {
    return false;
  }
}

export function classifyPluginRootLayout(root: string): PluginRootLayout {
  // Exported, so a caller other than pluginRootInfo() may pass a relative value
  // (or ''). Anchor it explicitly rather than letting each path.join below
  // resolve against the process cwd implicitly — same verdict, but the function
  // is then honest about which directory it judged.
  const base = path.resolve(root);
  const hasRuntime = isFileSafe(path.join(base, 'scripts', 'hook-runtime.cjs'));
  const hasContent = hasEntries(path.join(base, 'rules')) || hasEntries(path.join(base, 'skills-catalog'));
  if (hasRuntime && hasContent) return 'installed';
  const isSourceCheckout = isFileSafe(path.join(base, 'src', 'gen', 'static', 'plugin-instructions.md'))
    && isFileSafe(path.join(base, 'package.json'));
  if (isSourceCheckout) return 'source';
  return 'unverified';
}

// The richer accessor: which of the four env vars (if any) supplied the root,
// and what layout it classifies as. Never throws — see PluginRootLayout doc
// above for why that is load-bearing (tsx dev/test/gen/golden-update all
// resolve a root with no plugin.json and no rules/, and must keep working).
export function pluginRootInfo(): PluginRootInfo {
  for (const key of PLUGIN_ROOT_ENV) {
    // Trimmed and absolutized: this function's entire contract is being honest
    // about the root, and a bare RELATIVE value is not a root — it is a
    // fragment every consumer re-interprets against its own cwd.
    // `TRAFFIC_ONE_PLUGIN_ROOT=dist` (routine in a maintainer shell) therefore
    // let a hook running in a project directory join `dist/rules` under the
    // PROJECT, resolve nothing, and — before materializeProjectAssets refused —
    // take the project's materialized copies with it. Anchoring happens once,
    // here, against the hook process cwd, the only base a bare relative value
    // can mean; a value that anchors somewhere useless then classifies
    // 'unverified' below and every content consumer refuses it, instead of
    // quietly reading and deleting under the project. A whitespace-only value
    // is treated as unset (it otherwise classified 'unverified' and pinned
    // every consumer to a root literally named "   ") so the next env var, and
    // then the __dirname fallback, still gets its turn.
    const value = (process.env[key] ?? '').trim();
    if (!value) continue;
    const root = path.resolve(value);
    return { root, layout: classifyPluginRootLayout(root), source: key };
  }
  // src/shared/paths.ts -> ../../ = source root;
  // dist/scripts/shared/paths.js -> ../../ = generated plugin root.
  const root = path.resolve(__dirname, '..', '..');
  return { root, layout: classifyPluginRootLayout(root), source: 'default' };
}

// Ergonomic path-only accessor kept for the ~58 existing call sites that only
// ever wanted the path. Ctx.paths.pluginRoot() (src/core/types.ts) keeps this
// exact signature too — no handler reads the layout today, so widening the
// service interface would be a needless 58-site edit for a field nobody
// consumes through Ctx; a content consumer that needs the layout calls
// pluginRootInfo() directly instead.
export function pluginRoot(): string {
  return pluginRootInfo().root;
}

export function isManagedPluginCachePath(root: string): boolean {
  return [
    `${path.sep}.claude${path.sep}plugins${path.sep}cache${path.sep}`,
    `${path.sep}.codex${path.sep}plugins${path.sep}cache${path.sep}`,
  ].some((marker) => root.includes(marker));
}

export function isInPluginCache(): boolean {
  return isManagedPluginCachePath(pluginRoot());
}

const PROJECT_MARKERS = [
  path.join('.traffic-one', '.one.json'),
  '.traffic-one',
  'package.json',
  'go.mod',
  'pyproject.toml',
  'Cargo.toml',
  'deno.json',
  'deno.jsonc',
  'bun.lockb',
  'pnpm-lock.yaml',
  '.git',
];

function isInsideOrEqual(candidate: string, boundary: string): boolean {
  const rel = path.relative(boundary, candidate);
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

function existingDirectoryForHint(absPath: string): string {
  let current = absPath;
  try {
    if (!fs.existsSync(current) || !fs.lstatSync(current).isDirectory()) current = path.dirname(current);
  } catch {
    current = path.dirname(current);
  }
  return current;
}

function findUp(startDir: string, boundary?: string): string | null {
  let dir = startDir;
  for (;;) {
    if (boundary && !isInsideOrEqual(dir, boundary)) return null;
    for (const marker of PROJECT_MARKERS) {
      try {
        if (fs.existsSync(path.join(dir, marker))) return dir;
      } catch {
        // ignore and keep walking
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function safeRealpath(value: string): string {
  try {
    return fs.realpathSync(value);
  } catch {
    return path.resolve(value);
  }
}

function hostBoundary(cwd: string): string {
  return safeRealpath(path.resolve(cwd));
}

function candidateRootFromHint(cwd: string, hint: string, boundary: string, baseDir = cwd): string | null {
  const raw = String(hint || '').trim();
  if (!raw || raw.startsWith('-') || raw.includes('://') || raw.includes('$')) return null;
  const cleaned = raw.replace(/^["'`]+|["'`,;]+$/g, '').replace(/\\ /g, ' ');
  if (!cleaned || cleaned.startsWith('-') || cleaned.includes('://') || cleaned.includes('$')) return null;
  const abs = path.isAbsolute(cleaned) ? path.resolve(cleaned) : path.resolve(baseDir, cleaned);
  const resolved = safeRealpath(existingDirectoryForHint(abs));
  if (!isInsideOrEqual(resolved, boundary)) return null;
  return findUp(resolved, boundary);
}

function promptPathHints(prompt: unknown, cwd: string): string[] {
  const text = typeof prompt === 'string' ? prompt : '';
  if (!text) return [];
  const hints: string[] = [];
  const seen = new Set<string>();
  const add = (candidate: string): void => {
    const trimmed = candidate.trim();
    if (!trimmed || seen.has(trimmed)) return;
    const abs = path.resolve(cwd, trimmed);
    try {
      if (fs.existsSync(abs) && fs.lstatSync(abs).isDirectory()) {
        seen.add(trimmed);
        hints.push(trimmed);
      }
    } catch {
      // ignore bad prompt hints
    }
  };

  const quoted = /\b(?:in|inside|under|within|for)\s+["'`]([^"'`]+)["'`]/gi;
  for (const match of text.matchAll(quoted)) add(match[1] || '');

  const bare = /\b(?:in|inside|under|within|for)\s+((?:\.{1,2}\/)?[A-Za-z0-9_.@-]+(?:\/[A-Za-z0-9_.@-]+)*)(?=$|[\s,.;:!?])/gi;
  for (const match of text.matchAll(bare)) add(match[1] || '');
  return hints;
}

function projectWalkCeiling(input: HookInput, cwd: string): string {
  const ws = typeof input.workspaceRoot === 'string' ? input.workspaceRoot.trim() : '';
  if (ws && path.isAbsolute(ws)) return safeRealpath(ws);
  return hostBoundary(cwd);
}

export function projectRoot(input: HookInput): string {
  const cwd = path.resolve(input.cwd || process.cwd());
  const ceiling = projectWalkCeiling(input, cwd);
  const hintBoundary = ceiling;
  const workdirRoot = input.tool?.workdir
    ? candidateRootFromHint(cwd, input.tool.workdir, hintBoundary)
    : null;
  if (workdirRoot) return workdirRoot;

  const fileBase = input.tool?.workdir && !path.isAbsolute(input.tool.workdir)
    ? path.resolve(cwd, input.tool.workdir)
    : input.tool?.workdir || cwd;
  const fileRoot = input.tool?.filePath
    ? candidateRootFromHint(cwd, input.tool.filePath, hintBoundary, fileBase)
    : null;
  if (fileRoot) return fileRoot;

  for (const hint of promptPathHints(input.prompt, cwd)) {
    const promptRoot = candidateRootFromHint(cwd, hint, hintBoundary);
    if (promptRoot) return promptRoot;
  }

  const start = hostBoundary(cwd);
  return findUp(start, ceiling) ?? (isInsideOrEqual(start, ceiling) ? start : ceiling);
}

export function stateFile(root: string): string {
  return path.join(root, '.traffic-one', '.one.json');
}

export const paths: Paths = { pluginRoot, projectRoot, stateFile };
