// src/shared/paths.ts
// The ONE path layer. pluginRoot resolves the authoring/install root (env
// override -> __dirname), and the same relative depth holds whether running from
// src/shared (tsx dev) or dist/scripts/shared (compiled). projectRoot is
// hint-aware about the TOOL: it prefers the directory of a tool's target file
// (PostToolUse materialisation derives the project from the edited path, not
// cwd). It is deliberately NOT hint-aware about prompt TEXT — see
// promptSuggestedMember below for what replaced that branch and why.

import * as fs from 'fs';
import * as path from 'path';

import type { HookInput, Paths } from '../core/types';

const PLUGIN_ROOT_ENV = [
  'TRAFFIC_ONE_PLUGIN_ROOT',
  'CODEX_PLUGIN_ROOT',
  'CLAUDE_PLUGIN_ROOT',
  'CURSOR_PLUGIN_ROOT',
] as const;

export type PluginRootEnvVar = typeof PLUGIN_ROOT_ENV[number];

// Where the resolved root came from — the __default__ case is the same
// __dirname fallback pluginRoot() always had; the four env cases name exactly
// which of the four wins, because "which one won" is the whole diagnostic
// value when a stale exported root silently outlives the install it named.
export type PluginRootSource = PluginRootEnvVar | 'default';

// What the resolved root actually looks like on disk, decided from what only
// each layout ever contains (nothing else — every predicate here is checked
// against src/gen/index.ts's own sourceRepoRoot() markers and against the
// two artifacts src/build/build-runtime.ts always produces):
//   - 'installed': a real generated+built plugin distribution — it carries
//     BOTH the compiled runtime entry every host invokes as a FILE
//     (scripts/hook-runtime.cjs, the first SHIMS entry build-runtime.ts
//     always writes) AND at least one generated content dir gen always
//     writes WITH SOMETHING IN IT (rules/ or skills-catalog/, from
//     gen/index.ts's MANAGED_OUTPUT_DIRS). Neither half alone is enough, and
//     neither half may be satisfied by a mere directory entry: a `dist/`
//     mid-`npm run build` (content written, scripts/ not yet compiled), a
//     `dist/scripts` copied without its sibling content dirs, and a `dist/`
//     caught mid-`npm run gen` / mid-`rsync` (the content dirs exist but are
//     still EMPTY) are all partial trees, not trustworthy installs.
//   - 'source': the TypeScript authoring checkout — identified by the exact
//     pair sourceRepoRoot() itself trusts (src/gen/static/plugin-instructions.md
//     + package.json), so `pluginRoot()`'s own __dirname fallback under tsx
//     dev (which resolves here) classifies correctly instead of looking
//     broken. It is a legitimate root for PROSE lookups that know the source
//     layout (skill-filters' roleAgentDocCandidates, run-bootstrap-policy's
//     material candidates) and NOT a content root for materialization: the
//     shipped rules/skills tree is generated by gen, not relocated — see
//     materializeProjectAssets.
//   - 'unverified': neither — a nonexistent path, an empty directory, a file,
//     an unrelated directory, or a partial plugin tree (runtime without
//     content, content without runtime, either half still empty).
//     pluginRoot() still returns it (never throws); only a CONTENT CONSUMER
//     (materialization, prose lookup, a spawned executable) may refuse to
//     treat it as authoritative.
export type PluginRootLayout = 'installed' | 'source' | 'unverified';

export interface PluginRootInfo {
  readonly root: string;
  readonly layout: PluginRootLayout;
  readonly source: PluginRootSource;
}

// Every predicate below MUST NOT THROW, for any input — a nonexistent path, a
// file where a directory belongs, a directory where a file belongs, an
// unreadable directory, a symlink loop, an empty or whitespace-only string.
// That is load-bearing rather than defensive: under tsx (dev, `npm test`,
// `npm run gen`, `npm run golden:update`) the resolved root is this checkout,
// so a throwing accessor here does not degrade one diagnostic — it breaks the
// whole toolchain.

// Existence is deliberately NOT the predicate for the two `installed` halves.
// `fs.existsSync` is true for an empty directory and true for a plain FILE of
// the same name, so it called `scripts/hook-runtime.cjs` + an empty `rules/`
// (a `dist/` caught mid-gen, a half-extracted archive, an in-flight rsync) a
// complete install — which then resolved zero rules and zero skills and let
// materialization sweep the project's only copy of both. Content is proven by
// reading the directory, identity by stat'ing the file.

// At least one real entry inside `dir`. readdirSync throws ENOTDIR for a file
// and EACCES for an unreadable directory, both of which mean "not usable
// content" here, so the catch is the answer rather than a swallowed error.
// Dot entries do not count: a stray `.DS_Store` is not shipped content.
//
// This stops at "the directory has entries" on purpose — it stays O(one
// readdir) because pluginRootInfo() runs on every hook invocation. A tree that
// has entries but still cannot resolve the rules/skills a given project needs
// is NOT the classifier's job: materializeProjectAssets refuses when its
// resolved content set comes back empty, whatever this function decided.
function hasEntries(dir: string): boolean {
  try {
    return fs.readdirSync(dir).some((name) => !name.startsWith('.'));
  } catch {
    return false;
  }
}

// A real file at `candidate` — statSync (following symlinks, so an installed
// tree may symlink its runtime) and never a directory of the same name.
function isFileSafe(candidate: string): boolean {
  try {
    return fs.statSync(candidate).isFile();
  } catch {
    return false;
  }
}

export function classifyPluginRootLayout(root: string): PluginRootLayout {
  // Exported, so a caller other than pluginRootInfo() may pass a relative value
  // (or ''). Anchor it explicitly rather than letting each path.join below
  // resolve against the process cwd implicitly — same verdict, but the function
  // is then honest about which directory it judged.
  const base = path.resolve(root);
  const hasRuntime = isFileSafe(path.join(base, 'scripts', 'hook-runtime.cjs'));
  const hasContent = hasEntries(path.join(base, 'rules')) || hasEntries(path.join(base, 'skills-catalog'));
  if (hasRuntime && hasContent) return 'installed';
  const isSourceCheckout = isFileSafe(path.join(base, 'src', 'gen', 'static', 'plugin-instructions.md'))
    && isFileSafe(path.join(base, 'package.json'));
  if (isSourceCheckout) return 'source';
  return 'unverified';
}

// The richer accessor: which of the four env vars (if any) supplied the root,
// and what layout it classifies as. Never throws — see PluginRootLayout doc
// above for why that is load-bearing (tsx dev/test/gen/golden-update all
// resolve a root with no plugin.json and no rules/, and must keep working).
export function pluginRootInfo(): PluginRootInfo {
  for (const key of PLUGIN_ROOT_ENV) {
    // Trimmed and absolutized: this function's entire contract is being honest
    // about the root, and a bare RELATIVE value is not a root — it is a
    // fragment every consumer re-interprets against its own cwd.
    // `TRAFFIC_ONE_PLUGIN_ROOT=dist` (routine in a maintainer shell) therefore
    // let a hook running in a project directory join `dist/rules` under the
    // PROJECT, resolve nothing, and — before materializeProjectAssets refused —
    // take the project's materialized copies with it. Anchoring happens once,
    // here, against the hook process cwd, the only base a bare relative value
    // can mean; a value that anchors somewhere useless then classifies
    // 'unverified' below and every content consumer refuses it, instead of
    // quietly reading and deleting under the project. A whitespace-only value
    // is treated as unset (it otherwise classified 'unverified' and pinned
    // every consumer to a root literally named "   ") so the next env var, and
    // then the __dirname fallback, still gets its turn.
    const value = (process.env[key] ?? '').trim();
    if (!value) continue;
    const root = path.resolve(value);
    return { root, layout: classifyPluginRootLayout(root), source: key };
  }
  // src/shared/paths.ts -> ../../ = source root;
  // dist/scripts/shared/paths.js -> ../../ = generated plugin root.
  const root = path.resolve(__dirname, '..', '..');
  return { root, layout: classifyPluginRootLayout(root), source: 'default' };
}

// Ergonomic path-only accessor kept for the ~58 existing call sites that only
// ever wanted the path. Ctx.paths.pluginRoot() (src/core/types.ts) keeps this
// exact signature too — no handler reads the layout today, so widening the
// service interface would be a needless 58-site edit for a field nobody
// consumes through Ctx; a content consumer that needs the layout calls
// pluginRootInfo() directly instead.
export function pluginRoot(): string {
  return pluginRootInfo().root;
}

export function isManagedPluginCachePath(root: string): boolean {
  return [
    `${path.sep}.claude${path.sep}plugins${path.sep}cache${path.sep}`,
    `${path.sep}.codex${path.sep}plugins${path.sep}cache${path.sep}`,
  ].some((marker) => root.includes(marker));
}

export function isInPluginCache(): boolean {
  return isManagedPluginCachePath(pluginRoot());
}

const PROJECT_MARKERS = [
  path.join('.traffic-one', '.one.json'),
  '.traffic-one',
  'package.json',
  'go.mod',
  'pyproject.toml',
  'Cargo.toml',
  'deno.json',
  'deno.jsonc',
  'bun.lockb',
  'pnpm-lock.yaml',
  '.git',
];

function isInsideOrEqual(candidate: string, boundary: string): boolean {
  const rel = path.relative(boundary, candidate);
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

function existingDirectoryForHint(absPath: string): string {
  let current = absPath;
  try {
    if (!fs.existsSync(current) || !fs.lstatSync(current).isDirectory()) current = path.dirname(current);
  } catch {
    current = path.dirname(current);
  }
  return current;
}

function findUp(startDir: string, boundary?: string): string | null {
  let dir = startDir;
  for (;;) {
    if (boundary && !isInsideOrEqual(dir, boundary)) return null;
    for (const marker of PROJECT_MARKERS) {
      try {
        if (fs.existsSync(path.join(dir, marker))) return dir;
      } catch {
        // ignore and keep walking
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function safeRealpath(value: string): string {
  try {
    return fs.realpathSync(value);
  } catch {
    return path.resolve(value);
  }
}

function hostBoundary(cwd: string): string {
  return safeRealpath(path.resolve(cwd));
}

function candidateRootFromHint(cwd: string, hint: string, boundary: string, baseDir = cwd): string | null {
  const raw = String(hint || '').trim();
  if (!raw || raw.startsWith('-') || raw.includes('://') || raw.includes('$')) return null;
  const cleaned = raw.replace(/^["'`]+|["'`,;]+$/g, '').replace(/\\ /g, ' ');
  if (!cleaned || cleaned.startsWith('-') || cleaned.includes('://') || cleaned.includes('$')) return null;
  const abs = path.isAbsolute(cleaned) ? path.resolve(cleaned) : path.resolve(baseDir, cleaned);
  const resolved = safeRealpath(existingDirectoryForHint(abs));
  if (!isInsideOrEqual(resolved, boundary)) return null;
  return findUp(resolved, boundary);
}

// ── The directory a PROMPT mentions ─────────────────────────────────────────
//
// This used to be `promptPathHints`, a private third hint source inside
// projectRoot() below: any directory named after `in`/`inside`/`under`/
// `within`/`for` became a candidate root, first match wins. It is gone from
// resolution, and the reason is not that it was inaccurate — it is that
// NOTHING DOWNSTREAM RE-DECIDES IT ANY MORE.
//
// The two-stage shape is what made a wrong guess survivable. Stage one is this
// function's caller; stage two is hook/paths.ts resolveProjectRoot, which every
// write path re-runs on the answer (session/prompt-submit.ts,
// agent-model/choice-reply.ts). Stage two CORRECTS a bad guess only when it
// finds a committed non-workspace root above the guessed directory — measured:
// in an npm monorepo carrying `mode: 'new-project'`, `add tests for auth`
// resolved to `auth` at stage one and came back to the repo root at stage two.
// It RATIFIES the guess whenever the guessed directory is project-like and no
// committed ancestor overrules it, which is already true of a wrapper repo
// holding a mode-less `.one.json`, and is true BY DESIGN for a Traffic One
// workspace: nearestOnboardedRoot hands the walk back DOWN to a registered
// member, so `for auth` in a workspace that registered `auth` resolves to
// `auth` at both stages and the word "for" has picked the project.
//
// A registered member is a mode-bearing root that owns its own plan, run state
// and role claims. Which member a turn belongs to is therefore an ATTRIBUTION
// decision, and hook/workspace-members.ts is explicit that member identity is
// RECORDED rather than derived. An English preposition is not a record of
// anything, and `for` is an ordinary word in `add tests for auth`.
//
// So the mention survives as a SUGGESTION and nothing more. It is checked
// against the workspace's own registry — the only authority on who the members
// are — never against the filesystem, so a mention that happens to name a real
// directory nobody registered matches nothing. And an ambiguous prompt yields
// NO suggestion rather than the first match: "first match wins" is the specific
// behaviour that made the old branch a coin toss between two members.
//
// ONE SHAPE ANSWERS DIFFERENTLY NOW, AND THAT IS THE RULING RATHER THAN A COST.
// In a wrapper repo holding a mode-less `.one.json` with the app in a
// subdirectory, a bare first prompt naming that subdirectory used to anchor
// there and now anchors at the wrapper. Keep it that way. The wrapper's
// committed state is a fact the team wrote down; the subdirectory is a guess
// read off an English preposition, and when the guess is wrong it is wrong
// SILENTLY — there is no render, so the user cannot tell it happened. Anchoring
// on the written-down fact also agrees with everything hook/paths.ts has
// accumulated the hard way (a monorepo has ONE root; the packages/* leak rule),
// whereas this branch was a fossil of the superseded decision in ca4f85cd
// ("init on working folder instead of root/workspace folder"). Two subsystems
// disagreed and the regex won only because it ran first.
//
// The recovery path is intact and measured: `tool.workdir` and `tool.filePath`
// still reach the inner app for that shape, so only the first prompt before any
// tool call is affected. Do NOT re-pin the old answer with a prompt-based test —
// a tool-hint test is the honest way to hold that shape.
//
// DORMANT, like the registry readers it consumes: nothing calls it in
// production yet, and the adjacent product question is settled in the direction
// of NOT calling it — an empty workspace container refuses and directs the user
// at one member rather than guessing or self-registering. See the four
// `workspace-member-unresolved` renders in shared/tool-scope.ts, which already
// refuse-and-enumerate at the tool boundary. What is genuinely undecided is
// narrower: whether an AMBIGUOUS mention (two registered members named, so this
// helper answers null) is worth quoting back to the user, and where.

/** A registered member the prompt named, with the text that named it. */
export interface PromptMemberSuggestion {
  /** The registry's own relative spelling of the member. */
  readonly member: string;
  /** `member` joined onto the caller's container — spelling-preserving, never a realpath. */
  readonly root: string;
  /** The literal text the prompt used, for prose that quotes the user back. */
  readonly mention: string;
}

// The same two patterns the resolution branch used, kept deliberately: they are
// preposition-ANCHORED, and a bare scan for member names would match `web` in
// "a web app". The looseness that mattered was never the trigger set — it was
// that a match BOUND the root.
const QUOTED_MENTION = /\b(?:in|inside|under|within|for)\s+["'`]([^"'`]+)["'`]/gi;
const BARE_MENTION = /\b(?:in|inside|under|within|for)\s+((?:\.{1,2}\/)?[A-Za-z0-9_.@-]+(?:\/[A-Za-z0-9_.@-]+)*)(?=$|[\s,.;:!?])/gi;

function normalizeMention(raw: string): string {
  return raw.trim().replace(/\\/g, '/').replace(/^\.\//, '').replace(/\/+$/, '');
}

/** The last path segment — the name a human uses for `apps/web`. */
function lastSegment(memberPath: string): string {
  return memberPath.split('/').filter(Boolean).pop() || '';
}

/**
 * The ONE registered member this prompt names, or null.
 *
 * `members` is the registry's `members` array (validated, relative, opted-out
 * entries already excluded — see hook/workspace-members.ts). It is passed as a
 * VALUE rather than read here, so this file gains no import edge and no syscall:
 * every caller that could ask this question is already holding the registry
 * that `resolveProjectRootDetailed` handed it.
 *
 * Null on ambiguity, and that is the whole point rather than a guard. A prompt
 * naming two members, or naming a segment two members share (`apps/web` and
 * `services/web` are both "web"), has not identified anybody — the same reading
 * `resolveMemberIdentities` takes of a colliding id base, and the opposite of
 * the first-match-wins rule this replaces.
 */
export function promptSuggestedMember(
  prompt: unknown,
  container: string,
  members: readonly string[],
): PromptMemberSuggestion | null {
  const text = typeof prompt === 'string' ? prompt : '';
  if (!text || members.length === 0) return null;

  const mentions: string[] = [];
  for (const pattern of [QUOTED_MENTION, BARE_MENTION]) {
    pattern.lastIndex = 0;
    for (const match of text.matchAll(pattern)) {
      const normalized = normalizeMention(match[1] || '');
      if (normalized) mentions.push(normalized);
    }
  }
  if (mentions.length === 0) return null;

  let hit: PromptMemberSuggestion | null = null;
  for (const mention of mentions) {
    for (const member of members) {
      if (mention !== member && mention !== lastSegment(member)) continue;
      // A second, DIFFERENT member ends the search with no answer. A repeat of
      // the same member (`in web, under apps/web`) is not ambiguity.
      if (hit && hit.member !== member) return null;
      if (!hit) {
        hit = { member, root: path.join(container, ...member.split('/')), mention };
      }
    }
  }
  return hit;
}

function projectWalkCeiling(input: HookInput, cwd: string): string {
  const ws = typeof input.workspaceRoot === 'string' ? input.workspaceRoot.trim() : '';
  if (ws && path.isAbsolute(ws)) return safeRealpath(ws);
  return hostBoundary(cwd);
}

// CANONICALIZING resolver — the deliberate opposite of hook/paths.ts's
// resolveProjectRoot, and the two are NOT interchangeable:
//
//   projectRoot()        every exit is realpath'd (safeRealpath, which falls
//                        back to path.resolve for a path that cannot be
//                        stat'ed). `/tmp/proj` comes back `/private/tmp/proj`.
//   resolveProjectRoot() no realpath anywhere; the caller's own spelling is
//                        returned verbatim. `/tmp/proj` comes back `/tmp/proj`.
//
// Both contracts are load-bearing where they are used, so neither may be
// "aligned" with the other:
//   - This one feeds core/context.ts's ctx.projectRoot and hook/trace.ts, which
//     compare and record roots across processes that reach one project by
//     different spellings.
//   - The other one's result is compared BY STRING against its own input —
//     shared/retention.ts isLeakedNestedRoot deletes a nested `.traffic-one`
//     when `resolveProjectRoot(dir) !== dir`, so canonicalizing it would judge
//     every genuine project reached by a non-canonical cwd a leak and delete it.
//
// The cost of the divergence is bounded to in-process CACHE MISSES on
// string-keyed maps (authoringRootMemo here, heldLocks in
// state/project-state-lock.ts, the run-ledger fingerprint cache). It is NOT a
// mutual-exclusion defect: every lock in that family is a DIRECTORY, created by
// a non-recursive mkdirSync or by renameSync onto a directory path, so two
// spellings contend on one inode. A heldLocks re-entrancy miss WOULD be worse
// than a wasted lookup — the process would spin on a lock it already owns until
// the acquisition deadline and then throw — and that is unreachable by
// construction: neither resolver is in the import closure of any
// withProjectStateLock body, so no nested acquisition can be handed a second
// spelling. __tests__/path-spelling-contract.test.ts pins all of this.
export function projectRoot(input: HookInput): string {
  const cwd = path.resolve(input.cwd || process.cwd());
  const ceiling = projectWalkCeiling(input, cwd);
  const hintBoundary = ceiling;
  const workdirRoot = input.tool?.workdir
    ? candidateRootFromHint(cwd, input.tool.workdir, hintBoundary)
    : null;
  if (workdirRoot) return workdirRoot;

  const fileBase = input.tool?.workdir && !path.isAbsolute(input.tool.workdir)
    ? path.resolve(cwd, input.tool.workdir)
    : input.tool?.workdir || cwd;
  const fileRoot = input.tool?.filePath
    ? candidateRootFromHint(cwd, input.tool.filePath, hintBoundary, fileBase)
    : null;
  if (fileRoot) return fileRoot;

  // No third branch reading `input.prompt`. The tool hints above are STATEMENTS
  // of the path being operated on, made by the host; prompt text is not, and
  // the branch that treated it as one is retired above (promptSuggestedMember).
  // `input.prompt` is consequently no longer read by this function at all.
  const start = hostBoundary(cwd);
  return findUp(start, ceiling) ?? (isInsideOrEqual(start, ceiling) ? start : ceiling);
}

export function stateFile(root: string): string {
  return path.join(root, '.traffic-one', '.one.json');
}

export const paths: Paths = { pluginRoot, projectRoot, stateFile };
