// src/shared/runner-shims.ts
// Version-stable runner shims under ~/.traffic-one/bin (sibling of the managed
// toolchain root). Hosts persist user approvals against the LITERAL command
// path — on Codex that means ["node", ".../plugins/cache/.../2.9.135/scripts/
// lighthouse-runner.mjs"], which dies on every plugin bump (the cache dir is
// pruned) and then baits agents into the dead pre-approved path → 404 → manual
// rg/find discovery → a fresh approval cycle, per version per project. The
// shim path never changes: each shim resolves the LIVE plugin root at call
// time (env override first, then the newest version in the host plugin
// caches) and exec's the real runner, so one approval survives every bump on
// every host. Written idempotently from SessionStart and the toolchain
// installer; dependency-free (the shims run under bare node).

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { toolchainRoot } from './toolchain-paths';

// Stable bin dir: <state-home>/bin next to <state-home>/toolchains, honoring
// the same env/XDG overrides as the toolchain root.
export function stableBinDir(): string {
  return path.join(path.dirname(toolchainRoot()), 'bin');
}

// Every runner an agent is told to invoke from prose. Shims are .cjs so a bare
// `node <shim>` works regardless of the target's module flavor.
export const RUNNER_SHIMS: ReadonlyArray<{ shim: string; rel: string }> = [
  { shim: 'lighthouse-runner.cjs', rel: 'scripts/lighthouse-runner.mjs' },
  { shim: 'opencode-runner.cjs', rel: 'scripts/opencode-runner.cjs' },
  { shim: 'opencode-mcp.cjs', rel: 'scripts/opencode-mcp.cjs' },
  { shim: 'gitnexus-runner.cjs', rel: 'scripts/gitnexus-runner.cjs' },
  { shim: 'graphify-runner.cjs', rel: 'scripts/graphify-runner.cjs' },
  { shim: 'security-check-runner.cjs', rel: 'scripts/security-check-runner.cjs' },
  { shim: 'token-report.cjs', rel: 'scripts/token-report.cjs' },
  { shim: 'one-mcp-report.cjs', rel: 'scripts/one-mcp-report.cjs' },
  { shim: 'traffic-one-cleanup.cjs', rel: 'scripts/traffic-one-cleanup.cjs' },
  { shim: 'doctor.cjs', rel: 'scripts/doctor.cjs' },
  { shim: 'run-status.cjs', rel: 'scripts/run-status.cjs' },
  { shim: 'windsurf-hook-runtime.cjs', rel: 'scripts/windsurf-hook-runtime.cjs' },
];

function shimSource(rel: string): string {
  return `#!/usr/bin/env node
// GENERATED BY traffic-one — version-stable runner shim. This file's path
// never changes across plugin versions; it resolves the live plugin root at
// call time and runs the real runner there. Safe to re-run; do not edit.
'use strict';
const { spawnSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const REL = ${JSON.stringify(rel)};

function numericDesc(a, b) {
  return b.localeCompare(a, undefined, { numeric: true, sensitivity: 'base' });
}

function candidateRoots() {
  const roots = [];
  for (const key of ['TRAFFIC_ONE_PLUGIN_ROOT', 'CURSOR_PLUGIN_ROOT', 'CODEX_PLUGIN_ROOT', 'CLAUDE_PLUGIN_ROOT']) {
    const v = (process.env[key] || '').trim();
    if (v) roots.push(v);
  }
  const home = os.homedir();
  // Collect EVERY (host, marketplace, version) install first, then order by VERSION
  // across all hosts. Ordering by host first is what silently served stale code: with
  // .codex holding only 1.0.15 and .claude holding 1.0.17, the first-host-wins walk
  // returned 1.0.15 and never even considered 1.0.17 — observed live in cursor-15c,
  // where Cursor's MCP server ran 1.0.15 (90s OpenCode ceiling) while the hooks in the
  // SAME session ran 1.0.17 (600s). Version sorting used to apply only WITHIN one host.
  const versioned = [];
  for (const host of ['.codex', '.claude', '.cursor']) {
    const cache = path.join(home, host, 'plugins', 'cache');
    let marketplaces;
    try { marketplaces = fs.readdirSync(cache); } catch { continue; }
    for (const mk of marketplaces) {
      const pluginDir = path.join(cache, mk, 'traffic-one');
      let versions;
      try { versions = fs.readdirSync(pluginDir).filter((v) => /^\\d/.test(v)); } catch { continue; }
      for (const v of versions) versioned.push({ version: v, dir: path.join(pluginDir, v) });
    }
  }
  versioned.sort((a, b) => numericDesc(a.version, b.version));
  for (const entry of versioned) roots.push(entry.dir);
  // Local (unversioned) installs — Cursor's \`plugins/local/traffic-one\` has no
  // cache dir and the host sets no *_PLUGIN_ROOT for MCP-server processes, so this
  // is the only way the shim resolves the plugin when launched bare (CWD=\$HOME).
  for (const host of ['.codex', '.claude', '.cursor']) {
    const local = path.join(home, host, 'plugins', 'local', 'traffic-one');
    try { if (fs.statSync(local).isDirectory()) roots.push(local); } catch { /* no local install */ }
  }
  try {
    const windsurfStamp = fs.readFileSync(path.join(home, '.traffic-one', 'windsurf-plugin-root'), 'utf8').trim();
    if (windsurfStamp) roots.push(windsurfStamp);
  } catch { /* no windsurf stamp */ }
  return roots;
}

for (const root of candidateRoots()) {
  const target = path.join(root, REL);
  let exists = false;
  try { exists = fs.existsSync(target); } catch { exists = false; }
  if (!exists) continue;
  const r = spawnSync(process.execPath, [target, ...process.argv.slice(2)], { stdio: 'inherit' });
  process.exit(typeof r.status === 'number' ? r.status : 1);
}
console.error('traffic-one: no installed plugin provides ' + REL + ' (checked TRAFFIC_ONE_PLUGIN_ROOT/CURSOR_PLUGIN_ROOT/CODEX_PLUGIN_ROOT/CLAUDE_PLUGIN_ROOT and the .codex/.claude/.cursor plugin caches). Reinstall the traffic-one plugin.');
process.exit(1);
`;
}

// Write/refresh all shims. Idempotent and cheap (skips identical content);
// never throws — callers are SessionStart-grade best-effort sites.
export function ensureRunnerShims(): { dir: string; written: string[] } {
  const dir = stableBinDir();
  const written: string[] = [];
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return { dir, written };
  }
  for (const { shim, rel } of RUNNER_SHIMS) {
    const file = path.join(dir, shim);
    const next = shimSource(rel);
    try {
      const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
      if (current !== next) {
        fs.writeFileSync(file, next, { mode: 0o755 });
        written.push(shim);
      }
      // mkdir/write above succeed with the right mode on fresh files; chmod
      // separately so pre-existing files updated in place stay executable.
      fs.chmodSync(file, 0o755);
    } catch {
      // best-effort per shim; a read-only HOME must never break a session
    }
  }
  return { dir, written };
}
