// Unit coverage for the run-sim write primitive: the check-plan-write pipeline,
// crash-deny rejection, and the "denied writes leave nothing on disk" contract.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { assertion as triageAssertion } from '../../assertions/run-sim-maintenance-triage.assert';
import { assertion as negativeAssertion } from '../../assertions/run-sim-negative-gates.assert';
import type { AssertionContext, Case } from '../types';
import { expectDenyGap, PIPELINE_HANDLER_CRASHED } from './expect-deny';
import type { RunSimTranscript, WriteOutcome } from './types';
import {
  applyAll,
  applyScriptedWrite,
  checkPlanWriteHandlers,
  writeCtx,
} from './write';

function emptyTranscript(): RunSimTranscript {
  return {
    ok: true,
    caseId: 'write-test',
    runId: 'R',
    mode: 'new-project',
    durationMs: 0,
    phasesCompleted: [],
    writes: [],
    facts: {},
  };
}

function outcome(partial: Partial<WriteOutcome> & { path: string }): WriteOutcome {
  return {
    ordinal: 1,
    phase: 'negative',
    role: 'senior-reviewer',
    bytes: 1,
    denied: true,
    host: 'claude',
    ...partial,
  };
}

test('check-plan-write handlers match the host subcommand set', () => {
  assert.deepEqual(
    checkPlanWriteHandlers().map((handler) => handler.id).sort(),
    ['plan-guard.write', 'session.auth', 'session.authoring-guard', 'session.workspace-boundary'],
  );
});

test('writeCtx returns a real Ctx, not a force-cast shell', () => {
  const ctx = writeCtx('/nonexistent-sim-root', 'Write', 'file-write', {
    file_path: 'src/a.ts',
    content: 'export const a = 1;\n',
  });
  assert.equal(ctx.host, 'claude');
  assert.equal(ctx.input.tool?.filePath, 'src/a.ts');
  assert.equal(typeof ctx.now, 'function');
  assert.ok(ctx.fsjson);
  assert.ok(ctx.paths);
  assert.ok(ctx.skillBlock);
});

test('expectDenyGap rejects a crash deny and an unnamed handler', () => {
  assert.equal(expectDenyGap(outcome({
    path: 'src/a.ts',
    denied: true,
    denyId: 'runtime-assignments-owner-gate',
    gateId: 'plan-guard.write',
  })), null);

  assert.match(expectDenyGap(outcome({
    path: 'src/a.ts',
    denied: false,
  })) ?? '', /must deny allowed/);

  assert.match(expectDenyGap(outcome({
    path: 'src/a.ts',
    denied: true,
    denyId: PIPELINE_HANDLER_CRASHED,
    gateId: 'plan-guard.write',
  })) ?? '', /runtime crash/);

  assert.match(expectDenyGap(outcome({
    path: 'src/a.ts',
    denied: true,
    denyId: 'runtime-assignments-owner-gate',
  })) ?? '', /named no producing handler/);

  assert.match(expectDenyGap(outcome({
    path: 'src/a.ts',
    denied: true,
    denyId: 'runtime-assignments-owner-gate',
    gateId: 'session.auth',
    expectHandler: 'plan-guard.write',
  })) ?? '', /came from session\.auth/);
});

async function withWriteProject(fn: (cwd: string) => Promise<void>): Promise<void> {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 't1-run-sim-write-'));
  const env = process.env;
  const prevAuth = env.TRAFFIC_ONE_AUTH;
  const prevPrefs = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_AUTH = 'off';
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(cwd, 'prefs.json');
  const t1 = path.join(cwd, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(cwd, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(t1, 'plan.md'), 'plan', 'utf8');
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({
    mode: 'new-project',
    stack: 'default',
    frontend: 'react-vite',
    backend: 'supabase',
    mobile: { framework: 'none' },
    onboardingComplete: true,
    materializedStack: 'default|react-vite|supabase|none',
    currentRunId: 'R',
  }), 'utf8');
  try {
    await fn(cwd);
  } finally {
    if (prevAuth === undefined) delete env.TRAFFIC_ONE_AUTH;
    else env.TRAFFIC_ONE_AUTH = prevAuth;
    if (prevPrefs === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
    else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prevPrefs;
    fs.rmSync(cwd, { recursive: true, force: true });
  }
}

test('applyScriptedWrite records pipeline gateId/denyId and leaves a denied write off disk', async () => {
  await withWriteProject(async (cwd) => {
    const transcript = emptyTranscript();
    const target = '.traffic-one/runs/R/assignments.json';
    const result = await applyScriptedWrite(cwd, 'negative', 'senior-reviewer', {
      path: target,
      content: '{"schemaVersion":1,"assignments":[]}\n',
      expectDeny: true,
      denyMatch: 'generated atomically from CompiledArchitectureV1',
      expectHandler: 'plan-guard.write',
    }, transcript);

    assert.equal(result.denied, true);
    assert.equal(result.expected, true);
    assert.equal(result.gateId, 'plan-guard.write');
    assert.notEqual(result.denyId, PIPELINE_HANDLER_CRASHED);
    assert.equal(result.denyId, 'runtime-assignments-owner-gate');
    assert.match(result.reason ?? '', /generated atomically from CompiledArchitectureV1/);
    assert.equal(fs.existsSync(path.join(cwd, target)), false);
    assert.equal(expectDenyGap(result), null);
  });
});

test('applyAll treats a valid expectDeny as success and an unexpected deny as failure', async () => {
  await withWriteProject(async (cwd) => {
    const ok = emptyTranscript();
    const passed = await applyAll(cwd, 'negative', null, [{
      path: '.traffic-one/runs/R/assignments.json',
      content: '{"schemaVersion":1}\n',
      expectDeny: true,
      denyMatch: 'generated atomically from CompiledArchitectureV1',
      expectHandler: 'plan-guard.write',
    }], ok);
    assert.equal(passed, null);
    assert.equal(ok.writes[0]?.gateId, 'plan-guard.write');
    assert.notEqual(ok.writes[0]?.denyId, PIPELINE_HANDLER_CRASHED);

    const leaked = emptyTranscript();
    const unexpected = await applyAll(cwd, 'architect', null, [{
      path: '.traffic-one/runs/R/assignments.json',
      content: '{"schemaVersion":1}\n',
    }], leaked);
    assert.ok(unexpected);
    assert.equal(unexpected.denied, true);
    assert.equal(unexpected.gateId, 'plan-guard.write');
    assert.equal(fs.existsSync(path.join(cwd, '.traffic-one/runs/R/assignments.json')), false);
  });
});

const NEGATIVE_CASE: Case = {
  id: 'sim-write-assert',
  category: 'run-sim',
  layer: 'run-sim',
  fixture: 'empty-git',
  preSeed: { mode: 'new-project' },
  runSim: {
    brief: 'x',
    architecture: { schemaVersion: 1, routes: [], modules: [] },
    qa: { mode: 'stack' },
    negativeGates: true,
  },
  assertions: [{ id: 'run-sim-negative-gates' }],
};

function assertionContext(caseFolder: string): AssertionContext {
  return {
    cwd: caseFolder,
    caseFolder,
    env: {},
    members: [],
    host: 'pure-node',
    testCase: NEGATIVE_CASE,
    spec: { id: 'run-sim-negative-gates' },
    hostResult: { status: 'COMPLETED', exitCode: 0, durationMs: 1 },
  };
}

test('run-sim-negative-gates fails a crash deny and an unnamed handler', async () => {
  const caseFolder = fs.mkdtempSync(path.join(os.tmpdir(), 't1-neg-gates-'));
  try {
    const crashTranscript = {
      ok: true,
      writes: [{
        path: 'src/a.ts',
        denied: true,
        expected: true,
        denyMatch: 'STRUCT_COLLAPSED_LINE',
        denyId: PIPELINE_HANDLER_CRASHED,
        gateId: 'plan-guard.write',
        reason: 'Traffic One plan-guard.write gate failed; this tool call is blocked fail-closed.',
      }],
    };
    fs.writeFileSync(path.join(caseFolder, 'run-sim.json'), `${JSON.stringify(crashTranscript)}\n`, 'utf8');
    const crashed = await negativeAssertion.run(assertionContext(caseFolder));
    assert.equal(crashed.status, 'FAIL');
    assert.match(crashed.detail, /pipeline-handler-crashed/);
    assert.match(crashed.detail, /runtime crash/);

    const unnamedTranscript = {
      ok: true,
      writes: [{
        path: 'src/a.ts',
        denied: true,
        expected: true,
        denyMatch: 'STRUCT_COLLAPSED_LINE',
        denyId: 'implementer-collapse-gate',
        reason: 'STRUCT_COLLAPSED_LINE',
      }],
    };
    fs.writeFileSync(path.join(caseFolder, 'run-sim.json'), `${JSON.stringify(unnamedTranscript)}\n`, 'utf8');
    const unnamed = await negativeAssertion.run(assertionContext(caseFolder));
    assert.equal(unnamed.status, 'FAIL');
    assert.match(unnamed.detail, /producing handler/);
  } finally {
    fs.rmSync(caseFolder, { recursive: true, force: true });
  }
});

test('applyAll rejects an expectDeny produced by the wrong pipeline handler', async () => {
  await withWriteProject(async (cwd) => {
    process.env.TRAFFIC_ONE_AUTH = 'on';
    const transcript = emptyTranscript();
    const leaked = await applyAll(cwd, 'negative', null, [{
      path: '.traffic-one/runs/R/assignments.json',
      content: '{"schemaVersion":1}\n',
      expectDeny: true,
      denyMatch: 'generated atomically from CompiledArchitectureV1',
      expectHandler: 'plan-guard.write',
    }], transcript);
    assert.ok(leaked);
    assert.equal(leaked.denied, true);
    assert.ok(leaked.gateId);
    assert.notEqual(leaked.gateId, 'plan-guard.write');
    assert.notEqual(leaked.denyId, PIPELINE_HANDLER_CRASHED);
    assert.match(expectDenyGap(leaked) ?? '', /came from/);
    assert.equal(fs.existsSync(path.join(cwd, '.traffic-one/runs/R/assignments.json')), false);
  });
});

test('run-sim-negative-gates passes a named handler deny that matches its phrase', async () => {
  const caseFolder = fs.mkdtempSync(path.join(os.tmpdir(), 't1-neg-gates-ok-'));
  try {
    fs.writeFileSync(path.join(caseFolder, 'run-sim.json'), `${JSON.stringify({
      ok: true,
      writes: [{
        path: '.traffic-one/runs/R/assignments.json',
        denied: true,
        expected: true,
        denyMatch: 'generated atomically from CompiledArchitectureV1',
        expectHandler: 'plan-guard.write',
        denyId: 'runtime-assignments-owner-gate',
        gateId: 'plan-guard.write',
        reason: 'Runtime contract gate: generated atomically from CompiledArchitectureV1',
      }],
    })}\n`, 'utf8');
    const passed = await negativeAssertion.run(assertionContext(caseFolder));
    assert.equal(passed.status, 'PASS');
  } finally {
    fs.rmSync(caseFolder, { recursive: true, force: true });
  }
});

const TRIAGE_CASE: Case = {
  ...NEGATIVE_CASE,
  id: 'sim-write-triage-assert',
  runSim: {
    ...NEGATIVE_CASE.runSim!,
    maintenance: [{ kind: 'prompt', prompt: 'typo', expectRouting: 'triage', expectTier: 'trivial' }],
  },
};

function triageContext(caseFolder: string): AssertionContext {
  return { ...assertionContext(caseFolder), testCase: TRIAGE_CASE, spec: { id: 'run-sim-maintenance-triage' } };
}

test('run-sim-maintenance-triage fails a crash deny on a fail-closed probe', async () => {
  const caseFolder = fs.mkdtempSync(path.join(os.tmpdir(), 't1-triage-crash-'));
  try {
    fs.writeFileSync(path.join(caseFolder, 'run-sim.json'), `${JSON.stringify({
      ok: true,
      writes: [{
        phase: 'leg-1:parent-probe',
        path: 'src/a.ts',
        denied: true,
        expected: true,
        denyMatch: 'maintenance writes fail closed',
        denyId: PIPELINE_HANDLER_CRASHED,
        gateId: 'plan-guard.write',
        reason: 'Traffic One plan-guard.write gate failed',
      }],
      facts: {
        maintenanceLegs: [{
          ordinal: 1,
          kind: 'prompt',
          prompt: 'typo',
          expectedRouting: 'triage',
          routing: 'triage',
          expectedTier: 'trivial',
          tier: 'trivial',
          rotated: true,
          modelPolicyFrozen: true,
          runIdBefore: 'A',
          runIdAfter: 'B',
        }],
      },
    })}\n`, 'utf8');
    const crashed = await triageAssertion.run(triageContext(caseFolder));
    assert.equal(crashed.status, 'FAIL');
    assert.match(crashed.detail, /pipeline-handler-crashed/);
    assert.match(crashed.detail, /runtime crash/);
  } finally {
    fs.rmSync(caseFolder, { recursive: true, force: true });
  }
});
