'use strict';

const fs = require('fs');
const path = require('path');

const { pluginRoot } = require('./config.cjs');
const { stackSpecForState } = require('./stacks.cjs');
const { activeSkillsFor } = require('./skill-filters.cjs');

const GENERATED_MARKER = '<!-- GENERATED BY traffic-one: project-local active rules -->';

function toPosix(filePath) {
  return filePath.split(path.sep).join('/');
}

function readText(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
}

function writeTextIfChanged(filePath, content) {
  if (fs.existsSync(filePath) && readText(filePath) === content) {
    return false;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function isGenerated(filePath) {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(GENERATED_MARKER);
}

function removeGeneratedFile(filePath) {
  if (fs.existsSync(filePath) && isGenerated(filePath)) {
    fs.rmSync(filePath, { force: true });
    return true;
  }
  return false;
}

function removeGeneratedSkillDir(dirPath) {
  const skillPath = path.join(dirPath, 'SKILL.md');
  if (fs.existsSync(skillPath) && isGenerated(skillPath)) {
    fs.rmSync(dirPath, { recursive: true, force: true });
    return true;
  }
  return false;
}

function copySkillDir(srcDir, dstDir) {
  if (!fs.existsSync(srcDir)) return false;
  fs.mkdirSync(dstDir, { recursive: true });
  const entries = fs.readdirSync(srcDir, { withFileTypes: true });
  for (const entry of entries) {
    const src = path.join(srcDir, entry.name);
    const dst = path.join(dstDir, entry.name);
    if (entry.isDirectory()) {
      copySkillDir(src, dst);
    } else if (entry.isFile()) {
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      let content = fs.readFileSync(src, 'utf8');
      if (entry.name === 'SKILL.md' && !content.includes(GENERATED_MARKER)) {
        content = `${content.trimEnd()}\n\n${GENERATED_MARKER}\n`;
      }
      fs.writeFileSync(dst, content, 'utf8');
    }
  }
  return true;
}

function loadPreviousManifest(cwd) {
  const manifestPath = path.join(cwd, '.traffic-one', 'rules', 'manifest.json');
  try {
    return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  } catch {
    return {};
  }
}

function cleanupPrevious(cwd, previous, nextRulePaths, nextSkillNames) {
  let removed = 0;
  const activeRoot = path.join(cwd, '.traffic-one', 'rules', 'active');
  const skillsRoot = path.join(cwd, '.traffic-one', 'skills');

  for (const relPath of Array.isArray(previous.rules) ? previous.rules : []) {
    if (nextRulePaths.has(relPath)) continue;
    const dst = path.join(activeRoot, relPath);
    if (removeGeneratedFile(dst)) removed += 1;
  }

  for (const name of Array.isArray(previous.skills) ? previous.skills : []) {
    if (nextSkillNames.has(name)) continue;
    if (removeGeneratedSkillDir(path.join(skillsRoot, name))) removed += 1;
  }

  return removed;
}

function renderAgents(state, rules, skills) {
  const lines = [
    '# Traffic One Local Agent Context',
    '',
    GENERATED_MARKER,
    '',
    'Use the project-local active rule bundle below before falling back to plugin-root rules.',
    '',
    '## Active State',
    '',
    `- Stack: ${state.stack || 'minimal'}`,
    `- Frontend: ${state.frontend || 'none'}`,
    `- Backend: ${state.backend || 'none'}`,
    `- Mobile: ${(state.mobile && state.mobile.framework) || 'none'}`,
    '',
    '## Active Rules',
    '',
    ...rules.map((relPath) => `- .traffic-one/rules/active/${relPath}`),
    '',
    '## Active Skills',
    '',
    ...skills.map((name) => `- .traffic-one/skills/${name}/SKILL.md`),
    '',
  ];
  return `${lines.join('\n')}\n`;
}

function renderClaude(state, rules, skills) {
  const lines = [
    '# Traffic One Local Claude Context',
    '',
    GENERATED_MARKER,
    '',
    `Active stack: ${state.stack || 'minimal'}; frontend: ${state.frontend || 'none'}; backend: ${state.backend || 'none'}; mobile: ${(state.mobile && state.mobile.framework) || 'none'}.`,
    '',
    '## Active Rules',
    '',
    ...rules.map((relPath) => `@.traffic-one/rules/active/${relPath}`),
    '',
    '## Local Skills',
    '',
    ...skills.map((name) => `@.traffic-one/skills/${name}/SKILL.md`),
    '',
  ];
  return `${lines.join('\n')}\n`;
}

function writeRootAgents(cwd, localAgentsContent) {
  const rootAgents = path.join(cwd, 'AGENTS.md');
  const target = path.join('.traffic-one', 'rules', 'AGENTS.md');
  if (fs.existsSync(rootAgents) && !fs.lstatSync(rootAgents).isSymbolicLink() && !isGenerated(rootAgents)) {
    return false;
  }
  try {
    if (fs.existsSync(rootAgents)) {
      fs.rmSync(rootAgents, { force: true });
    }
    fs.symlinkSync(target, rootAgents);
    return true;
  } catch {
    return writeTextIfChanged(rootAgents, localAgentsContent);
  }
}

function writeRootClaude(cwd, localClaudeContent) {
  const rootClaude = path.join(cwd, 'CLAUDE.md');
  if (fs.existsSync(rootClaude) && !fs.lstatSync(rootClaude).isSymbolicLink() && !isGenerated(rootClaude)) {
    return false;
  }
  if (fs.existsSync(rootClaude)) {
    fs.rmSync(rootClaude, { force: true });
  }
  return writeTextIfChanged(rootClaude, localClaudeContent);
}

function unique(values) {
  const seen = new Set();
  const out = [];
  for (const value of values) {
    if (!value || seen.has(value)) continue;
    seen.add(value);
    out.push(value);
  }
  return out;
}

function modeRulesForState(root, state) {
  const mode = state && typeof state.mode === 'string' ? state.mode : '';
  if (!mode) return [];

  const relPath = `rules/modes/${mode}.md`;
  if (!fs.existsSync(path.join(root, relPath))) return [];

  return [relPath];
}

function materializeProjectAssets(cwd, state) {
  const root = pluginRoot();
  const spec = stackSpecForState(state);
  const rules = unique([
    ...spec.mandatory,
    ...modeRulesForState(root, state),
    ...spec.optional,
  ]).filter((relPath) => fs.existsSync(path.join(root, relPath)));
  const skills = [...activeSkillsFor(state)].filter((name) => fs.existsSync(path.join(root, 'skills', name, 'SKILL.md'))).sort();
  const nextRulePaths = new Set(rules);
  const nextSkillNames = new Set(skills);
  const previous = loadPreviousManifest(cwd);
  const removed = cleanupPrevious(cwd, previous, nextRulePaths, nextSkillNames);

  let written = 0;
  const activeRoot = path.join(cwd, '.traffic-one', 'rules', 'active');
  for (const relPath of rules) {
    const src = path.join(root, relPath);
    const dst = path.join(activeRoot, relPath);
    const source = fs.readFileSync(src, 'utf8').trimEnd();
    const content = `${GENERATED_MARKER}\n<!-- SOURCE: ${relPath} -->\n\n${source}\n`;
    if (writeTextIfChanged(dst, content)) written += 1;
  }

  const skillsRoot = path.join(cwd, '.traffic-one', 'skills');
  for (const name of skills) {
    if (copySkillDir(path.join(root, 'skills', name), path.join(skillsRoot, name))) {
      written += 1;
    }
  }

  const localAgents = renderAgents(state, rules, skills);
  const localClaude = renderClaude(state, rules, skills);
  if (writeTextIfChanged(path.join(cwd, '.traffic-one', 'rules', 'AGENTS.md'), localAgents)) written += 1;
  if (writeRootAgents(cwd, localAgents)) written += 1;
  if (writeRootClaude(cwd, localClaude)) written += 1;

  const manifest = {
    generatedBy: 'traffic-one',
    generatedAt: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
    stack: state.stack || 'minimal',
    frontend: state.frontend || 'none',
    backend: state.backend || 'none',
    mobile: (state.mobile && state.mobile.framework) || 'none',
    rules: rules.map(toPosix),
    skills,
  };
  writeTextIfChanged(
    path.join(cwd, '.traffic-one', 'rules', 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );

  return { rules: rules.length, skills: skills.length, written, removed };
}

module.exports = {
  GENERATED_MARKER,
  materializeProjectAssets,
};
