import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { runSessionStart, runSessionStartAuthed } from '../session-start';
import type { Ctx, HookInput } from '../../../core/types';
import { initializeToolchainState } from '../../../shared/state/toolchain';
import { writeGlobalCodeGraphProvider } from '../../../shared/state';
import { stackFingerprint } from '../../../shared/state/materialization';
import { retentionAdvisory, sweepTrafficOneRetention } from '../../../shared/retention';
import { currentLocalPreferenceTarget } from '../../../shared/onboarding/local-prefs';
import { HOST_IDS } from '../../../config/model-tiers';

// A retention SUSPENSION is indefinite and only the user can lift it, and the
// sweep's one scheduled caller is this SessionStart hook — which exits 0, so its
// stderr reaches nobody on the hosts we target. These tests pin the other half:
// the same text, verbatim, on the context every user-facing exit returns.
process.env.TRAFFIC_ONE_ASK_USE_PLUGIN = '0';

function ctx(cwd: string): Ctx {
  const input: HookInput = { event: 'SessionStart', host: 'claude', cwd, raw: {} };
  return { input, host: 'claude', cwd, now: () => 'x' } as unknown as Ctx;
}

function withProject(state: Record<string, unknown>, fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-retention-notice-'));
  const env = process.env;
  const prev = {
    prefs: env.TRAFFIC_ONE_PROJECT_PREFS_PATH,
    state: env.TRAFFIC_ONE_STATE_PATH,
    xdg: env.XDG_STATE_HOME,
    plan: env.TRAFFIC_ONE_USER_PLAN,
  };
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  env.TRAFFIC_ONE_STATE_PATH = path.join(dir, 'one.json');
  env.XDG_STATE_HOME = path.join(dir, 'state');
  env.TRAFFIC_ONE_USER_PLAN = 'pro';
  fs.mkdirSync(path.join(dir, '.traffic-one'), { recursive: true });
  fs.writeFileSync(path.join(dir, '.traffic-one', '.one.json'), JSON.stringify(state), 'utf8');
  writeLocalPrefs();
  try { fn(dir); } finally {
    if (prev.prefs === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev.prefs;
    if (prev.state === undefined) delete env.TRAFFIC_ONE_STATE_PATH; else env.TRAFFIC_ONE_STATE_PATH = prev.state;
    if (prev.xdg === undefined) delete env.XDG_STATE_HOME; else env.XDG_STATE_HOME = prev.xdg;
    if (prev.plan === undefined) delete env.TRAFFIC_ONE_USER_PLAN; else env.TRAFFIC_ONE_USER_PLAN = prev.plan;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeLocalPrefs(): void {
  const prefsPath = process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH!;
  fs.mkdirSync(path.dirname(prefsPath), { recursive: true });
  const hosts = Object.fromEntries(HOST_IDS.map((host) => [host, {
    performance: { level: 'low', source: 'prompted', target: currentLocalPreferenceTarget(host, process.env) },
    team: { mode: 'main-agent', source: 'prompted' },
  }]));
  fs.writeFileSync(prefsPath, JSON.stringify({
    openCode: { enabled: false, source: 'prompted', decidedAt: '2026-01-01T00:00:00Z' },
    hosts,
    toolchain: initializeToolchainState({}),
  }), 'utf8');
  writeGlobalCodeGraphProvider('graphify');
}

function existingState(extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    mode: 'existing-codebase',
    stack: 'minimal',
    frontend: 'none',
    backend: 'other',
    realtime: 'none',
    confirmed: true,
    onboardingComplete: true,
    confirmedAt: '2026-01-01T00:00:00Z',
    ...extra,
  };
}

function materializeFixture(cwd: string, stack = 'minimal'): void {
  const t1 = path.join(cwd, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({ generatedBy: 'traffic-one', stack, rules: ['rules/common/auth-gate.md'], skills: ['project-memory'] }), 'utf8');
  fs.writeFileSync(path.join(cwd, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(cwd, 'CLAUDE.md'), 'see agents', 'utf8');
}

// The policy file, not `.one.json`: it suspends every cap while leaving the
// state file legible, so the session takes its ordinary route to an ordinary
// exit and the notice has to ride that exit rather than a refusal.
function suspendRetention(cwd: string): void {
  fs.writeFileSync(path.join(cwd, '.traffic-one', 'retention.json'), '{ not json', 'utf8');
}

function contextText(result: { kind: string; context?: string }): string {
  assert.equal(result.kind, 'context', 'SessionStart must return a context to carry the notice');
  return result.context || '';
}

test('a suspended sweep puts its remedy on the SessionStart context a user reads', () => {
  withProject(existingState(), (cwd) => {
    suspendRetention(cwd);
    const text = contextText(runSessionStartAuthed(ctx(cwd)) as { kind: string; context?: string });
    assert.match(text, /SUSPENDED — /, 'the suspension reaches the user-visible context');
    assert.match(text, /every retention cap is off/);
    assert.match(text, /\.traffic-one keeps growing/);
  });
});

test('a clean sweep adds nothing to the context', () => {
  withProject(existingState(), (cwd) => {
    const text = contextText(runSessionStartAuthed(ctx(cwd)) as { kind: string; context?: string });
    assert.ok(!/SUSPENDED — /.test(text), 'a healthy project gets no retention prose at all');
    assert.ok(!/retention sweep/.test(text));
  });
});

test('the advisory on the context is byte-identical to what went to stderr', () => {
  withProject(existingState(), (cwd) => {
    suspendRetention(cwd);
    // The stderr dedupe is per-process and keyed on the whole message, which
    // embeds this temp path — so this sweep is the first and only announcement
    // of these two lines in this process.
    const written: string[] = [];
    const realWrite = process.stderr.write.bind(process.stderr);
    (process.stderr as unknown as { write: unknown }).write = (chunk: unknown): boolean => {
      written.push(String(chunk));
      return true;
    };
    let notices: readonly string[];
    try {
      notices = sweepTrafficOneRetention(cwd, { dryRun: true }).notices;
    } finally {
      (process.stderr as unknown as { write: unknown }).write = realWrite;
    }
    const advisory = retentionAdvisory(notices);
    assert.ok(advisory, 'a suspended sweep composes an advisory');
    assert.equal(advisory, written.join(''), 'one text, not two wordings of the same remedy');

    // And that exact block is the prefix of the session context.
    const text = contextText(runSessionStartAuthed(ctx(cwd)) as { kind: string; context?: string });
    assert.ok(text.startsWith(advisory!), 'the context leads with the verbatim advisory');
  });
});

test('the subagent exit stays clean — a user remedy is not a subagent instruction', () => {
  const base = existingState({ currentRunId: '1750000000000', activeAgentRole: 'senior-frontend' });
  const state = { ...base, materializedStack: stackFingerprint(base), materializedAt: new Date().toISOString() };
  withProject(state, (cwd) => {
    suspendRetention(cwd);
    materializeFixture(cwd);
    const result = runSessionStartAuthed(ctx(cwd)) as { kind: string; context?: string };
    const text = result.kind === 'context' ? (result.context || '') : '';
    assert.match(text, /senior-frontend/i, 'fixture guard: this is the subagent role context');
    assert.ok(!/SUSPENDED — /.test(text), 'the subagent is not the audience for a user remedy');
  });
});

test('the shipped subagent thread route never reaches the sweep', () => {
  withProject(existingState(), (cwd) => {
    suspendRetention(cwd);
    materializeFixture(cwd);
    const input: HookInput = {
      event: 'SessionStart',
      host: 'claude',
      cwd,
      raw: { parent_session_id: 'parent-abc', session_id: 'child-xyz' },
    };
    const result = runSessionStart({ input, host: 'claude', cwd, now: () => 'x' } as unknown as Ctx);
    const text = result.kind === 'context' ? (result.context || '') : '';
    assert.ok(!/SUSPENDED — /.test(text));
  });
});
