// src/shared/materialize/codex-agents.ts
// Project-local Codex role contracts.
//
// Codex has `typedSubagents: false`, so a spawned child gets `roleSource:
// 'plugin-injected-fallback'` and its role text through the session-start
// header. Until 9cc08b53 that header carried the FULL `agent.md` body via the
// per-run context pack; the pack was removed for cost and the header now carries
// only the ~7-bullet T1KERNEL excerpt. Kilo, Copilot and Windsurf are also
// fallback hosts and all three kept a materialized role file to read — Codex was
// the one left without a replacement, so every invariant living outside the
// kernel markers stopped reaching the role. Observed in 15co: `senior-frontend`
// wrote collapsed source repeatedly while the rule forbidding it sat ~186 lines
// outside its kernel.
//
// `.traffic-one/agents/` rather than a `.codex/` path: Codex has no project-level
// agent-file convention to honour, and the kernel already teaches the child to
// read `.traffic-one/rules/**` and `.traffic-one/skills/**` — this completes that
// sentence instead of inventing a directory.
//
// Only overwrites files bearing the generated marker — user-authored agents win.

import * as fs from 'fs';
import * as path from 'path';

import { TEAM_ROLES } from '../../config/onboarding';
import { eligibleRolesForProfile } from '../capabilities';
import { capabilityProfileForRun } from '../architecture-contract';
import { writeTextIfChanged } from '../fs-text';
import { readText } from '../fsjson';
import { roleAgentBody } from '../skill-filters';

type Rec = Record<string, unknown>;

export const CODEX_AGENTS_REL = path.join('.traffic-one', 'agents');
export const CODEX_AGENT_MARKER = '<!-- GENERATED BY traffic-one — Codex project agent -->';

/** The path a Codex child is told to read for role `role`, project-relative. */
export function codexAgentRelPath(role: string): string {
  return path.posix.join('.traffic-one', 'agents', `${role}.md`);
}

export function isGeneratedCodexAgent(filePath: string): boolean {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(CODEX_AGENT_MARKER);
}

function agentFile(role: string, label: string): string {
  const out = [
    CODEX_AGENT_MARKER,
    '',
    `# Traffic One — ${label} (\`${role}\`)`,
    '',
    'This is your FULL role contract. The kernel in your task header is a summary',
    'of it, not a replacement: every MUST and Hard rule below binds you.',
    '',
    'Write ONLY within the allowlist your work unit publishes; the run-team gate',
    'refuses out-of-scope writes and tells you to report them rather than relocate',
    'them. Do not spawn further subagents; report your result to the orchestrator.',
    '',
    '---',
    '',
  ];
  const contract = roleAgentBody(role);
  if (contract) out.push(contract, '');
  return out.join('\n');
}

function cleanupGeneratedAgents(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
      const role = entry.name.slice(0, -'.md'.length);
      const file = path.join(dir, entry.name);
      if (keep.has(role) || !isGeneratedCodexAgent(file)) continue;
      fs.rmSync(file, { force: true });
      removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  return removed;
}

export function writeCodexAgentFiles(cwd: string, state: Rec): number {
  const dir = path.join(cwd, CODEX_AGENTS_REL);
  const eligible = eligibleRolesForProfile(capabilityProfileForRun(cwd, state));
  const members = TEAM_ROLES.filter((member) => eligible.has(member.role));
  const keep = new Set(members.map((member) => member.role));
  let written = cleanupGeneratedAgents(dir, keep);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return written;
  }

  for (const member of members) {
    const target = path.join(dir, `${member.role}.md`);
    if (fs.existsSync(target) && !isGeneratedCodexAgent(target)) continue;
    try {
      if (writeTextIfChanged(target, agentFile(member.role, member.label))) written += 1;
    } catch {
      // best-effort per file
    }
  }
  return written;
}
