// src/shared/materialize/copilot-agents.ts
// Project-local Copilot agents: `.github/agents/<role>.agent.md` with tier-pinned models.
// Only overwrites files bearing the generated marker — user-authored agents win.

import * as fs from 'fs';
import * as path from 'path';

import { writeTextIfChanged } from '../fs-text';
import { readText } from '../fsjson';
import { detectHostPlan } from '../host-plan';
import { buildTeamLineup } from '../onboarding-server/flow';
import { roleAgentBody } from '../skill-filters';
import { modelForRoleHost, openCodeDelegationActive } from '../performance';

type Rec = Record<string, unknown>;

export const COPILOT_AGENTS_REL = path.join('.github', 'agents');
export const COPILOT_AGENT_MARKER = '<!-- GENERATED BY traffic-one — Copilot project agent -->';
const COPILOT_MODEL_FRONTMATTER_VALIDATED = false;

export function isGeneratedCopilotAgent(filePath: string): boolean {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(COPILOT_AGENT_MARKER);
}

function roleSpecificLines(role: string): string[] {
  if (role === 'senior-backend') {
    return [
      'Copilot backend baseline: when Supabase credentials are not configured yet,',
      'still create useful product-specific seed/demo fixtures and typed API fallbacks.',
      '',
    ];
  }
  if (role !== 'senior-frontend') return [];
  return [
    'Copilot frontend baseline: build credible product UI with demo fixtures and',
    'empty/loading/error states — not only "not configured" placeholders.',
    '',
  ];
}

function toolsForRole(role: string): string {
  return role === 'senior-reviewer'
    ? 'tools: ["view", "search", "bash"]'
    : 'tools: ["view", "search", "edit", "bash"]';
}

function agentFile(role: string, label: string, blurb: string, model: string): string {
  const out = [
    '---',
    `name: ${role}`,
    `description: ${(blurb || label).replace(/\n+/g, ' ').trim()}`,
    ...(COPILOT_MODEL_FRONTMATTER_VALIDATED && model ? [`model: ${model}`] : []),
    toolsForRole(role),
    '---',
    '',
    COPILOT_AGENT_MARKER,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt the orchestrator hands you and the project\'s `.traffic-one` rules',
    'and handoff-digest protocol (`.traffic-one/rules/common/agent-handoff-digests.md`).',
    ...(role === 'senior-architect'
      ? []
      : [
        'Write ONLY within the file scope assigned to your role in',
        '`.traffic-one/runs/<runId>/assignments.json` — the run-team gate blocks out-of-scope writes.',
      ]),
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
    ...roleSpecificLines(role),
  ];
  const contract = roleAgentBody(role);
  if (contract) {
    out.push(
      'Honor every MUST and Hard rule in the full role contract below before reporting completion.',
      '',
      '---',
      '',
      contract,
      '',
    );
  }
  return out.join('\n');
}

export function writeCopilotAgentFiles(cwd: string, state: Rec): number {
  const team = state.team && typeof state.team === 'object' ? (state.team as Rec) : null;
  const performance = state.performance && typeof state.performance === 'object' ? (state.performance as Rec) : null;
  const mode = team && typeof team.mode === 'string' ? team.mode : null;
  const level = performance && typeof performance.level === 'string' ? performance.level : null;
  if (mode !== 'subagents' || !level) return 0;

  const overrides = team && team.overrides && typeof team.overrides === 'object' ? (team.overrides as Rec) : null;
  const planCtx = { host: 'copilot', plan: detectHostPlan('copilot'), useOpenCode: openCodeDelegationActive(state, 'copilot') };
  let lineup;
  try {
    lineup = buildTeamLineup(level, 'copilot', overrides, planCtx);
  } catch {
    return 0;
  }
  if (!lineup || lineup.length === 0) return 0;

  const dir = path.join(cwd, COPILOT_AGENTS_REL);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return 0;
  }

  let written = 0;
  for (const m of lineup) {
    if (!m.role || !m.model) continue;
    const model = modelForRoleHost(level, m.role, 'copilot', overrides, planCtx) || m.model;
    const target = path.join(dir, `${m.role}.agent.md`);
    if (fs.existsSync(target) && !isGeneratedCopilotAgent(target)) continue;
    try {
      if (writeTextIfChanged(target, agentFile(m.role, m.label, m.blurb, model))) written += 1;
    } catch {
      // best-effort per file
    }
  }
  return written;
}
