// src/shared/materialize/copilot-agents.ts
// Project-local model-agnostic Copilot role contracts.
// Only overwrites files bearing the generated marker — user-authored agents win.

import * as fs from 'fs';
import * as path from 'path';

import { TEAM_ROLES } from '../../config/onboarding';
import { eligibleRolesForProfile } from '../capabilities';
import { capabilityProfileForRun } from '../architecture-contract';
import { writeTextIfChanged } from '../fs-text';
import { readText } from '../fsjson';
import { roleAgentBody } from '../skill-filters';

type Rec = Record<string, unknown>;

export const COPILOT_AGENTS_REL = path.join('.github', 'agents');
export const COPILOT_AGENT_MARKER = '<!-- GENERATED BY traffic-one — Copilot project agent -->';

export function isGeneratedCopilotAgent(filePath: string): boolean {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(COPILOT_AGENT_MARKER);
}

function roleSpecificLines(role: string): string[] {
  if (role === 'senior-backend') {
    return [
      'Copilot backend baseline: when Supabase credentials are not configured yet,',
      'still create useful product-specific seed/demo fixtures and typed API fallbacks.',
      '',
    ];
  }
  if (role !== 'senior-frontend') return [];
  return [
    'Copilot frontend baseline: build credible product UI with demo fixtures and',
    'empty/loading/error states — not only "not configured" placeholders.',
    '',
  ];
}

function toolsForRole(role: string): string {
  return role === 'senior-reviewer'
    ? 'tools: ["view", "search", "bash"]'
    : 'tools: ["view", "search", "edit", "bash"]';
}

function agentFile(role: string, label: string, blurb: string): string {
  const out = [
    '---',
    `name: ${role}`,
    `description: ${(blurb || label).replace(/\n+/g, ' ').trim()}`,
    toolsForRole(role),
    '---',
    '',
    COPILOT_AGENT_MARKER,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt the orchestrator hands you and the project\'s `.traffic-one` rules',
    'and handoff-digest protocol (`.traffic-one/rules/common/agent-handoff-digests.md`).',
    ...(role === 'senior-architect'
      ? []
      : [
        'Write ONLY within the file scope assigned to your role in',
        '`.traffic-one/runs/<runId>/assignments.json` — the run-team gate blocks out-of-scope writes.',
      ]),
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
    ...roleSpecificLines(role),
  ];
  const contract = roleAgentBody(role);
  if (contract) {
    out.push(
      'Honor every MUST and Hard rule in the full role contract below before reporting completion.',
      '',
      '---',
      '',
      contract,
      '',
    );
  }
  return out.join('\n');
}

function cleanupGeneratedAgents(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.agent.md')) continue;
      const role = entry.name.slice(0, -'.agent.md'.length);
      const file = path.join(dir, entry.name);
      if (keep.has(role) || !isGeneratedCopilotAgent(file)) continue;
      fs.rmSync(file, { force: true });
      removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  return removed;
}

export function writeCopilotAgentFiles(cwd: string, state: Rec): number {
  const dir = path.join(cwd, COPILOT_AGENTS_REL);
  const eligible = eligibleRolesForProfile(capabilityProfileForRun(cwd, state));
  const members = TEAM_ROLES.filter((member) => eligible.has(member.role));
  const keep = new Set(members.map((member) => member.role));
  let written = cleanupGeneratedAgents(dir, keep);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return written;
  }

  for (const member of members) {
    const target = path.join(dir, `${member.role}.agent.md`);
    if (fs.existsSync(target) && !isGeneratedCopilotAgent(target)) continue;
    try {
      if (writeTextIfChanged(target, agentFile(member.role, member.label, member.blurb))) written += 1;
    } catch {
      // best-effort per file
    }
  }
  return written;
}
