// src/shared/materialize/cursor-agents.ts
// Cursor-native per-role subagent definitions: ONE `.cursor/agents/<role>.md` per team role
// with the role's resolved performance-tier model in the `model:` frontmatter.
//
// IMPORTANT (corrected): despite cursor.com/docs/subagents claiming "Cursor honors the model
// field in your subagent frontmatter", live evidence showed it does NOT auto-apply it — when the
// orchestrator's `Task` spawn omits the `model` arg, the subagent INHERITS THE PARENT
// (orchestrator) model (captured: `subagent_model == parent model`; a balanced-override frontend
// pinned `gpt-5.5-medium` ran on the parent's Opus). So this file is the SOURCE the orchestrator
// reads to know which model to PASS in the Task `model` arg per role (and the value the spawn
// gate enforces) — it is NOT a substitute for passing the arg. The agent-model gate validates
// the PASSED `model` only; the orchestrator prose (resources/prompt-templates.md) tells it to
// read this `model:` and pass it. Claude/Codex set the per-role model via the spawn arg and need
// no agent files; the file body still gives the role its identity/scope on Cursor.

import * as fs from 'fs';
import * as path from 'path';

import { writeTextIfChanged } from '../fs-text';
import { detectHostPlan } from '../host-plan';
import { acceptableModelsFor } from '../model-tiers';
import { buildTeamLineup } from '../onboarding-server/flow';
import { openCodeDelegationActive } from '../performance';
import { CURSOR_AGENTS_REL } from './cursor-agent-model';
import { freshCursorModels, pickCursorSlug } from './cursor-models';

type Rec = Record<string, unknown>;

// Marker so humans (and a future cleanup pass) can tell these are regenerated, not
// hand-authored. Kept in the body — frontmatter must stay schema-clean for Cursor.
const GENERATED_NOTE =
  '<!-- GENERATED BY traffic-one — per-role Cursor subagent. `model` is pinned to this ' +
  "project's performance tier; do not hand-edit (regenerated on materialize). -->";

function roleSpecificLines(role: string): string[] {
  if (role !== 'senior-frontend') return [];
  return [
    'Cursor frontend baseline: for Supabase-backed or missing-env web/Ionic routes,',
    'render one shared setup banner/CTA at most, then still build the real product',
    'workflow with typed product-specific demo/seed fixtures plus empty, error,',
    'loading, and degraded states. Do not leave the first screen as only',
    '"not configured" UI, inactive controls, or blank panels.',
    '',
  ];
}

function agentFile(role: string, label: string, blurb: string, model: string): string {
  return [
    '---',
    `name: ${role}`,
    `description: ${(blurb || label).replace(/\n+/g, ' ').trim()}`,
    `model: ${model}`,
    '---',
    '',
    GENERATED_NOTE,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt you are handed and the project\'s `.traffic-one` rules and',
    'handoff-digest protocol (`.traffic-one/rules/common/agent-handoff-digests.md`). Write',
    'ONLY within the file scope assigned to your role in',
    '`.traffic-one/runs/<runId>/assignments.json` — the run-team gate blocks out-of-scope',
    'writes.',
    '',
    ...roleSpecificLines(role),
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
  ].join('\n');
}

// Materialize `.cursor/agents/<role>.md` for every subagent-team role, with the model
// resolved for THIS project's performance level + plan. Returns the count written.
// No-op unless team.mode==="subagents" with a known level and a non-empty lineup.
export function writeCursorAgentFiles(cwd: string, state: Rec): number {
  const team = state.team && typeof state.team === 'object' ? (state.team as Rec) : null;
  const performance = state.performance && typeof state.performance === 'object' ? (state.performance as Rec) : null;
  const mode = team && typeof team.mode === 'string' ? team.mode : null;
  const level = performance && typeof performance.level === 'string' ? performance.level : null;
  if (mode !== 'subagents' || !level) return 0;

  const overrides = team && team.overrides && typeof team.overrides === 'object' ? (team.overrides as Rec) : null;
  const planCtx = { host: 'cursor', plan: detectHostPlan('cursor'), useOpenCode: openCodeDelegationActive(state) };
  let lineup;
  try {
    lineup = buildTeamLineup(level, 'cursor', overrides, planCtx);
  } catch {
    return 0;
  }
  if (!lineup || lineup.length === 0) return 0;

  const dir = path.join(cwd, CURSOR_AGENTS_REL);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return 0;
  }
  // The lineup's `model` is now a bare FAMILY anchor (e.g. claude-opus-4-8). When this build's
  // actual Task-tool model list has been captured (.traffic-one/cursor-models.json), pin the
  // REAL build slug for the role's tier — the first captured model whose family matches the
  // tier family or a same-tier alternate — so the orchestrator can pass an exact model arg
  // instead of a guessed family. Without a captured list we write the bare family (refreshed on
  // capture via the PostToolUse re-materialize trigger). composer is the universal floor, so a
  // paid build always resolves SOMETHING.
  const captured = freshCursorModels(cwd, planCtx.plan);
  let written = 0;
  for (const m of lineup) {
    if (!m.role || !m.model) continue;
    const model = captured.length
      ? (pickCursorSlug(acceptableModelsFor(m.model, 'cursor'), captured) || m.model)
      : m.model;
    try {
      if (writeTextIfChanged(path.join(dir, `${m.role}.md`), agentFile(m.role, m.label, m.blurb, model))) written += 1;
    } catch {
      // best-effort per file
    }
  }
  return written;
}
