// src/shared/materialize/cursor-agents.ts
// Cursor-native per-role subagent definitions: one model-agnostic
// `.cursor/agents/<role>.md` contract per shipped team role. Runtime model routing
// comes from the active user's local host preferences, never from project files.
// Cursor loads `.cursor/agents/<role>.md` as the subagent definition, so this
// file inlines that SAME full role contract (via `roleAgentBody`), not just a short identity/scope
// stub: otherwise host-only gates that live in `agent.md` (e.g. the architect's "Required
// project-memory baseline" ls-verify) reach Claude/Codex but are invisible to Cursor's weaker
// composer model. A stub fallback is kept for the rare case the doc is unreadable so
// materialization never fails.

import * as fs from 'fs';
import * as path from 'path';

import { TEAM_ROLES } from '../../config/onboarding';
import { eligibleRolesForProfile } from '../capabilities';
import { capabilityProfileForRun } from '../architecture-contract';
import { readText } from '../fsjson';
import { roleAgentBody } from '../skill-filters';
import { CURSOR_AGENTS_REL } from './cursor-agent-model';
import { type RoleContractFile, type RoleContractOutcome, writeRoleContracts } from './role-contracts';

type Rec = Record<string, unknown>;

// Marker so humans (and a future cleanup pass) can tell these are regenerated, not
// hand-authored. Kept in the body — frontmatter must stay schema-clean for Cursor.
export const CURSOR_AGENT_MARKER = '<!-- GENERATED BY traffic-one — per-role Cursor subagent -->';

function isGeneratedCursorAgent(filePath: string): boolean {
  const text = readText(filePath);
  return typeof text === 'string' && (
    text.includes(CURSOR_AGENT_MARKER)
    || text.includes('<!-- GENERATED BY traffic-one — per-role Cursor subagent.')
  );
}

function roleSpecificLines(role: string): string[] {
  if (role === 'senior-backend') {
    return [
      'Cursor backend baseline: when Supabase credentials are not configured yet,',
      'still create useful product-specific seed/demo fixtures, local mock data,',
      'and typed API fallback helpers after the real schema/contracts are scaffolded.',
      'The generated app must have credible data to render before live credentials exist.',
      '',
    ];
  }
  if (role !== 'senior-frontend') return [];
  return [
    'Cursor frontend baseline: for Supabase-backed or missing-env web/Ionic routes,',
    'render one shared setup banner/CTA at most, then still build the real product',
    'workflow with typed product-specific demo/seed fixtures plus empty, error,',
    'loading, and degraded states. Do not leave the first screen as only',
    '"not configured" UI, inactive controls, or blank panels.',
    '',
  ];
}

function agentFile(role: string, label: string, blurb: string): string {
  const out = [
    '---',
    `name: ${role}`,
    `description: ${(blurb || label).replace(/\n+/g, ' ').trim()}`,
    '---',
    '',
    CURSOR_AGENT_MARKER,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt the orchestrator hands you and the project\'s `.traffic-one` rules',
    'and handoff-digest protocol (`.traffic-one/rules/common/agent-handoff-digests.md`).',
    // The implementer/reviewer/tester roles are confined to their assignments.json scope. The
    // architect is NOT — it creates the scaffold + memory baseline + assignments.json itself
    // (before that file exists) and must never list itself in it; its full contract below governs
    // its writes, so stating the scope rule here would contradict it for that one role.
    ...(role === 'senior-architect'
      ? []
      : [
        'Write ONLY within the file scope assigned to your role in',
        '`.traffic-one/runs/<runId>/assignments.json` — the run-team gate blocks out-of-scope writes.',
      ]),
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
    ...roleSpecificLines(role),
  ];
  // Inline the SAME full role contract Claude/Codex receive as the spawned subagent doc, so every
  // MUST / Hard-rule / ls-verify gate (e.g. the architect's project-memory baseline) binds Cursor
  // too — not just identity/scope. Fall back to the deferring stub only if the doc is unreadable.
  const contract = roleAgentBody(role);
  if (contract) {
    out.push(
      'The full role contract below is the SAME one the Claude/Codex subagent for this role runs',
      'under. Honor every MUST, Hard rule, and `ls`-verify-or-incomplete gate in it before you',
      'report completion — they are not optional on Cursor.',
      '',
      '---',
      '',
      contract,
      '',
    );
  } else {
    out.push(
      'Follow the project\'s `.traffic-one` rules and the role contract you are handed; complete',
      'every required artifact before reporting completion.',
      '',
    );
  }
  return out.join('\n');
}

function cleanupGeneratedAgents(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
      const role = entry.name.slice(0, -'.md'.length);
      const file = path.join(dir, entry.name);
      if (keep.has(role) || !isGeneratedCursorAgent(file)) continue;
      fs.rmSync(file, { force: true });
      removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  return removed;
}

// Materialize every capability-eligible role regardless of this user's
// team/performance choice. Runtime injects the active lineup/models per session.
export function writeCursorAgentFiles(cwd: string, state: Rec): RoleContractOutcome {
  const dir = path.join(cwd, CURSOR_AGENTS_REL);
  const eligible = eligibleRolesForProfile(capabilityProfileForRun(cwd, state));
  const members = TEAM_ROLES.filter((member) => eligible.has(member.role));
  const keep = new Set(members.map((member) => member.role));
  const removed = cleanupGeneratedAgents(dir, keep);
  const files: RoleContractFile[] = [];
  for (const member of members) {
    const target = path.join(dir, `${member.role}.md`);
    // A user-authored contract wins and is not a failure to write.
    if (fs.existsSync(target) && !isGeneratedCursorAgent(target)) continue;
    files.push({ path: target, content: agentFile(member.role, member.label, member.blurb) });
  }
  return writeRoleContracts(dir, removed, files);
}
