// src/shared/materialize/cursor-agents.ts
// Cursor-native per-role subagent definitions. Cursor honors the `model:` frontmatter
// of a `.cursor/agents/<name>.md` file (cursor.com/docs/subagents: "Cursor honors the
// model field in your subagent frontmatter" unless team-admin/Max-Mode/plan limits), so
// materializing ONE file per team role — with that role's resolved performance-tier model
// baked in — makes the orchestrator's Task spawn run on the CORRECT model from the first
// call. No inheriting the session model, no spawn-gate deny/retry ("New subagent —
// Couldn't start"). Cursor-only: Claude/Codex set the per-role model via the spawn tool's
// `model` parameter instead, so they need no agent files.
//
// The agent-model gate reads these back via cursorAgentModel() and validates the model
// Cursor will ACTUALLY use (the frontmatter), not the Task `model` arg Cursor ignores.

import * as fs from 'fs';
import * as path from 'path';

import { writeTextIfChanged } from '../fs-text';
import { detectHostPlan } from '../host-plan';
import { buildTeamLineup } from '../onboarding-server/flow';
import { openCodeDelegationActive } from '../performance';
import { CURSOR_AGENTS_REL } from './cursor-agent-model';

type Rec = Record<string, unknown>;

// Marker so humans (and a future cleanup pass) can tell these are regenerated, not
// hand-authored. Kept in the body — frontmatter must stay schema-clean for Cursor.
const GENERATED_NOTE =
  '<!-- GENERATED BY traffic-one — per-role Cursor subagent. `model` is pinned to this ' +
  "project's performance tier; do not hand-edit (regenerated on materialize). -->";

function agentFile(role: string, label: string, blurb: string, model: string): string {
  return [
    '---',
    `name: ${role}`,
    `description: ${(blurb || label).replace(/\n+/g, ' ').trim()}`,
    `model: ${model}`,
    '---',
    '',
    GENERATED_NOTE,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt you are handed and the project\'s `.traffic-one` rules and',
    'handoff-digest protocol (`.traffic-one/rules/common/agent-handoff-digests.md`). Write',
    'ONLY within the file scope assigned to your role in',
    '`.traffic-one/runs/<runId>/assignments.json` — the run-team gate blocks out-of-scope',
    'writes. Do not spawn further subagents; report your result to the orchestrator.',
    '',
  ].join('\n');
}

// Materialize `.cursor/agents/<role>.md` for every subagent-team role, with the model
// resolved for THIS project's performance level + plan. Returns the count written.
// No-op unless team.mode==="subagents" with a known level and a non-empty lineup.
export function writeCursorAgentFiles(cwd: string, state: Rec): number {
  const team = state.team && typeof state.team === 'object' ? (state.team as Rec) : null;
  const performance = state.performance && typeof state.performance === 'object' ? (state.performance as Rec) : null;
  const mode = team && typeof team.mode === 'string' ? team.mode : null;
  const level = performance && typeof performance.level === 'string' ? performance.level : null;
  if (mode !== 'subagents' || !level) return 0;

  const overrides = team && team.overrides && typeof team.overrides === 'object' ? (team.overrides as Rec) : null;
  const planCtx = { host: 'cursor', plan: detectHostPlan('cursor'), useOpenCode: openCodeDelegationActive(state) };
  let lineup;
  try {
    lineup = buildTeamLineup(level, 'cursor', overrides, planCtx);
  } catch {
    return 0;
  }
  if (!lineup || lineup.length === 0) return 0;

  const dir = path.join(cwd, CURSOR_AGENTS_REL);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return 0;
  }
  let written = 0;
  for (const m of lineup) {
    if (!m.role || !m.model) continue;
    try {
      if (writeTextIfChanged(path.join(dir, `${m.role}.md`), agentFile(m.role, m.label, m.blurb, m.model))) written += 1;
    } catch {
      // best-effort per file
    }
  }
  return written;
}
