// src/shared/materialize/generated.ts
// GENERATED-marker detection + cleanup of project-local generated assets, and
// the skill-dir copier. Ported 1:1 from scripts/hook-runtime/materialize/_helpers.cjs.

import * as fs from 'fs';
import * as path from 'path';

import { ensureDir, readText, removePath } from '../fsjson';
import { writeTextIfChanged } from '../fs-text';

export const GENERATED_MARKER = '<!-- GENERATED BY traffic-one: project-local active rules -->';

// ── Deleting is a write ──────────────────────────────────────────────────────
// Every remover below goes through fsjson.removePath rather than fs.rmSync. The
// product contract's pending half is byte-identity and its declined half is
// "left untouched", and a sweep that reclaims a project's materialized tree
// breaks both just as surely as writing to it would — irreversibly, which the
// writes are not. removePath is a pass-through for anything that is not under
// some project's `.traffic-one/`, so the host-native callers here (windsurf's
// `.windsurf/**` rule files and legacy skill dirs) are unaffected.
//
// Each remover keeps returning "did I remove it", so a refusal reads as `false`
// and the caller's `removed` count stays honest instead of over-reporting.

export function isGenerated(filePath: string): boolean {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(GENERATED_MARKER);
}

export function removeGeneratedFile(filePath: string): boolean {
  if (fs.existsSync(filePath) && isGenerated(filePath)) {
    return removePath(filePath);
  }
  return false;
}

function isGeneratedManifest(filePath: string): boolean {
  try {
    const json = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    return Boolean(json && json.generatedBy === 'traffic-one');
  } catch {
    return false;
  }
}

export function removeGeneratedManifest(filePath: string): boolean {
  if (fs.existsSync(filePath) && isGeneratedManifest(filePath)) {
    return removePath(filePath);
  }
  return false;
}

function isGeneratedTree(dirPath: string): boolean {
  if (!fs.existsSync(dirPath)) return false;
  const stat = fs.lstatSync(dirPath);
  if (stat.isFile()) return isGenerated(dirPath);
  if (!stat.isDirectory()) return false;
  return fs.readdirSync(dirPath, { withFileTypes: true }).every((entry) => isGeneratedTree(path.join(dirPath, entry.name)));
}

export function removeGeneratedTree(dirPath: string): boolean {
  if (fs.existsSync(dirPath) && isGeneratedTree(dirPath)) {
    return removePath(dirPath);
  }
  return false;
}

export function removeGeneratedSkillDir(dirPath: string): boolean {
  const skillPath = path.join(dirPath, 'SKILL.md');
  if (fs.existsSync(skillPath) && isGenerated(skillPath)) {
    return removePath(dirPath);
  }
  return false;
}

// Recursively copy a skill dir, stamping the GENERATED marker into SKILL.md.
// Write-if-different so a repeat materialization leaves mtimes (and watchers)
// alone; returns whether any file actually changed.
//
// The destination mkdir is fenced, and it is the one that mattered: this is the
// writer that left 51 empty `.traffic-one/skills/<name>/` directories on a
// project whose use-plugin question was unanswered — one per skill, created
// eagerly while every file write inside them was refused. A refusal means no
// file could land here anyway, so it reads as "nothing changed".
export function copySkillDir(srcDir: string, dstDir: string): boolean {
  if (!fs.existsSync(srcDir)) return false;
  if (!ensureDir(dstDir)) return false;
  let changed = false;
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const src = path.join(srcDir, entry.name);
    const dst = path.join(dstDir, entry.name);
    if (entry.isDirectory()) {
      if (copySkillDir(src, dst)) changed = true;
    } else if (entry.isFile()) {
      let content = fs.readFileSync(src, 'utf8');
      if (entry.name === 'SKILL.md' && !content.includes(GENERATED_MARKER)) {
        content = `${content.trimEnd()}\n\n${GENERATED_MARKER}\n`;
      }
      // No mkdir for the parent: it is `dstDir`, created above, and
      // writeTextIfChanged's fenced writer creates its own parent regardless.
      if (writeTextIfChanged(dst, content)) changed = true;
    }
  }
  return changed;
}
