// src/shared/materialize/kilo-agents.ts
// Kilo-native project role contracts: `.kilo/agents/<role>.md`.
//
// Kilo's Task API reliably exposes the built-in `general` worker, not arbitrary
// project-agent names. The orchestrator spawns `general` with the role marker and
// tells it to read the matching file here before working. We intentionally do not
// pin `model`: Kilo gives a session/manual model choice precedence over agent
// configuration, so omitting it preserves the user's live selection and avoids
// stale catalog ids.

import * as fs from 'fs';
import * as path from 'path';

import { KILO_HOST_AGENTS_REL } from '../../config/kilo-host';
import { TEAM_ROLES } from '../../config/onboarding';
import { writeTextIfChanged } from '../fs-text';
import { readText } from '../fsjson';
import { roleAgentBody } from '../skill-filters';
import { GENERATED_MARKER, isGenerated } from './generated';

type Rec = Record<string, unknown>;

export const KILO_AGENT_MARKER = '<!-- GENERATED BY traffic-one — per-role Kilo subagent -->';

function yamlString(value: string): string {
  return JSON.stringify(value.replace(/\n+/g, ' ').trim());
}

export function isGeneratedKiloAgent(filePath: string): boolean {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(KILO_AGENT_MARKER);
}

function cleanupGeneratedAgents(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
      const file = path.join(dir, entry.name);
      const role = entry.name.slice(0, -'.md'.length);
      if (keep.has(role) || !isGenerated(file)) continue;
      fs.rmSync(file, { force: true });
      removed += 1;
    }
    if (fs.existsSync(dir) && fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
  } catch {
    // best-effort cleanup
  }
  return removed;
}

function agentFile(role: string, label: string, blurb: string): string {
  const lines = [
    '---',
    `description: ${yamlString(blurb || label)}`,
    'mode: subagent',
    ...(role === 'senior-reviewer' ? ['permission:', '  edit: deny'] : []),
    '---',
    '',
    GENERATED_MARKER,
    KILO_AGENT_MARKER,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'This is the role contract for a Kilo `general` task subagent. Read and follow it before acting.',
    '',
    'Follow the task prompt the orchestrator hands you and the project root `AGENTS.md` rule entrypoint.',
    ...(role === 'senior-architect'
      ? []
      : [
        'Write ONLY within the file scope assigned to your role in',
        '`.traffic-one/runs/<runId>/assignments.json` — the run-team gate blocks out-of-scope writes.',
      ]),
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
  ];
  const contract = roleAgentBody(role);
  if (contract) {
    lines.push(
      'The full role contract below is the same Traffic One role contract used on the other hosts.',
      'Honor every MUST, hard rule, and completion gate before reporting completion.',
      '',
      '---',
      '',
      contract,
      '',
    );
  } else {
    lines.push('Follow the project rules and complete every requested artifact before reporting completion.', '');
  }
  return lines.join('\n');
}

export function writeKiloAgentFiles(cwd: string, _state: Rec): number {
  const dir = path.join(cwd, KILO_HOST_AGENTS_REL);
  const keep = new Set(TEAM_ROLES.map((member) => member.role));
  let written = cleanupGeneratedAgents(dir, keep);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return written;
  }
  for (const member of TEAM_ROLES) {
    const target = path.join(dir, `${member.role}.md`);
    if (fs.existsSync(target) && !isGeneratedKiloAgent(target)) continue;
    try {
      if (writeTextIfChanged(target, agentFile(member.role, member.label, member.blurb))) written += 1;
    } catch {
      // best-effort per role
    }
  }
  return written;
}
