// src/shared/materialize/opencode-assets.ts
// OpenCode-native model-pinned subagents live in the user's global config as
// `traffic-one-<projectHashPrefix>-<role>.md`. The project hash prevents two
// projects with different local performance choices from overwriting each other.
// Legacy generated `.opencode/agents/<role>.md` files are removed while
// user-authored project agents are preserved.
// Skills are NOT mirrored to `.opencode/skills` — that duplicated the canonical
// `.traffic-one/skills` (which the agent reads), and OpenCode builds its skill
// registry at startup so a mid-session copy is never loaded anyway. Root AGENTS.md
// remains the rule entrypoint.

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import {
  OPENCODE_HOST_AGENTS_DIR,
  OPENCODE_HOST_AGENTS_REL,
  OPENCODE_HOST_GLOBAL_CONFIG_DIR_REL,
  OPENCODE_HOST_SKILLS_REL,
} from '../../config/opencode-host';
import { eligibleRolesForProfile } from '../capabilities';
import { capabilityProfileForRun } from '../architecture-contract';
import { writeTextIfChanged } from '../fs-text';
import { detectHost } from '../host';
import { detectHostPlan } from '../host-plan';
import { buildTeamLineup } from '../onboarding-server/flow';
import { roleAgentBody } from '../skill-filters';
import { projectRootHash } from '../state/local-prefs';
import { GENERATED_MARKER, isGenerated, removeGeneratedFile, removeGeneratedSkillDir } from './generated';

type Rec = Record<string, unknown>;

const GENERATED_NOTE =
  '<!-- GENERATED BY traffic-one — per-role OpenCode subagent. `mode: subagent` is required; do not hand-edit (regenerated on materialize). -->';

export const OPENCODE_PROJECT_HASH_PREFIX_LENGTH = 12;

export function openCodeProjectAgentPrefix(cwd: string): string {
  return `traffic-one-${projectRootHash(cwd).slice(0, OPENCODE_PROJECT_HASH_PREFIX_LENGTH)}`;
}

export function openCodeGlobalAgentsDir(env: NodeJS.ProcessEnv = process.env): string {
  if (env.XDG_CONFIG_HOME) return path.join(env.XDG_CONFIG_HOME, 'opencode', OPENCODE_HOST_AGENTS_DIR);
  const home = env.HOME || env.USERPROFILE || os.homedir();
  return path.join(home, OPENCODE_HOST_GLOBAL_CONFIG_DIR_REL, OPENCODE_HOST_AGENTS_DIR);
}

export function openCodeGlobalAgentName(cwd: string, role: string): string {
  if (!/^[a-z0-9-]+$/.test(role)) throw new Error(`Invalid OpenCode role: ${role}`);
  return `${openCodeProjectAgentPrefix(cwd)}-${role}`;
}

export function openCodeGlobalAgentPath(cwd: string, role: string, env: NodeJS.ProcessEnv = process.env): string {
  return path.join(openCodeGlobalAgentsDir(env), `${openCodeGlobalAgentName(cwd, role)}.md`);
}

function removeEmptyDir(dir: string): void {
  try {
    if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
  } catch {
    // absent, non-empty, or not removable — leave it alone
  }
}

function cleanupLegacyProjectAgents(dir: string): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
      const file = path.join(dir, entry.name);
      if (!isGenerated(file)) continue;
      if (removeGeneratedFile(file)) removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  removeEmptyDir(dir);
  return removed;
}

function cleanupGlobalProjectAgents(cwd: string, keep: ReadonlySet<string>): number {
  const dir = openCodeGlobalAgentsDir();
  const prefix = `${openCodeProjectAgentPrefix(cwd)}-`;
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.startsWith(prefix) || !entry.name.endsWith('.md')) continue;
      const role = entry.name.slice(prefix.length, -'.md'.length);
      if (keep.has(role)) continue;
      if (removeGeneratedFile(path.join(dir, entry.name))) removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  removeEmptyDir(dir);
  return removed;
}

function cleanupGeneratedSkills(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory() || keep.has(entry.name)) continue;
      if (removeGeneratedSkillDir(path.join(dir, entry.name))) removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  return removed;
}

function agentFile(profileName: string, role: string, label: string, blurb: string, model: string): string {
  const lines = [
    '---',
    `name: ${profileName}`,
    `description: ${(blurb || label).replace(/\n+/g, ' ').trim()}`,
    'mode: subagent',
    ...(model ? [`model: ${model}`] : []),
    '---',
    '',
    GENERATED_MARKER,
    GENERATED_NOTE,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt the orchestrator hands you and the project root `AGENTS.md` rule entrypoint.',
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
  ];
  const contract = roleAgentBody(role);
  if (contract) {
    lines.push(
      'The full role contract below is the same Traffic One role contract used on the paid hosts.',
      'Honor every MUST, hard rule, and completion gate before reporting completion.',
      '',
      '---',
      '',
      contract,
      '',
    );
  } else {
    lines.push('Follow the project rules and complete every requested artifact before reporting completion.', '');
  }
  return lines.join('\n');
}

function writeOpenCodeGlobalAgentFiles(cwd: string, state: Rec): number {
  const team = state.team && typeof state.team === 'object' ? (state.team as Rec) : null;
  const performance = state.performance && typeof state.performance === 'object' ? (state.performance as Rec) : null;
  const mode = team && typeof team.mode === 'string' ? team.mode : null;
  const level = performance && typeof performance.level === 'string' ? performance.level : null;
  if (mode !== 'subagents' || !level) return cleanupGlobalProjectAgents(cwd, new Set());

  const overrides = team && team.overrides && typeof team.overrides === 'object' ? (team.overrides as Rec) : null;
  const modelSelections = team && team.modelSelections && typeof team.modelSelections === 'object'
    ? (team.modelSelections as Rec)
    : null;
  let lineup;
  try {
    const planCtx = { host: 'opencode', plan: detectHostPlan('opencode') };
    lineup = buildTeamLineup(level, 'opencode', overrides, planCtx, process.env, modelSelections);
  } catch {
    return cleanupGlobalProjectAgents(cwd, new Set());
  }
  if (!lineup || lineup.length === 0) return cleanupGlobalProjectAgents(cwd, new Set());
  const eligible = eligibleRolesForProfile(capabilityProfileForRun(cwd, state));
  lineup = lineup.filter((member) => eligible.has(member.role));
  if (lineup.length === 0) return cleanupGlobalProjectAgents(cwd, new Set());

  const keep = new Set(lineup.map((member) => member.role));
  let written = cleanupGlobalProjectAgents(cwd, keep);
  const dir = openCodeGlobalAgentsDir();
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return written;
  }
  for (const member of lineup) {
    const target = openCodeGlobalAgentPath(cwd, member.role);
    if (fs.existsSync(target) && !isGenerated(target)) continue;
    try {
      const profileName = openCodeGlobalAgentName(cwd, member.role);
      if (writeTextIfChanged(target, agentFile(profileName, member.role, member.label, member.blurb, member.model))) written += 1;
    } catch {
      // best-effort per role
    }
  }
  return written;
}

// Skills are intentionally NOT mirrored to `.opencode/skills` (see file header):
// it duplicated `.traffic-one/skills`, and OpenCode's skill registry is built at
// startup so a copy materialized mid-session is never loaded. Remove any
// previously-generated copy so existing projects get de-duplicated on materialize.
function removeOpenCodeSkills(cwd: string): number {
  const dir = path.join(cwd, OPENCODE_HOST_SKILLS_REL);
  const removed = cleanupGeneratedSkills(dir, new Set());
  try {
    if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
  } catch {
    // dir absent, or holds foreign (non-generated) content — leave it as-is
  }
  return removed;
}

// Project-local OpenCode files were emitted by older Traffic One releases. They
// are shared project artifacts, so every host must remove the generated copies
// during materialization. Marker checks preserve all user-authored files.
export function cleanupLegacyOpenCodeProjectAssets(cwd: string): number {
  return cleanupLegacyProjectAgents(path.join(cwd, OPENCODE_HOST_AGENTS_REL))
    + removeOpenCodeSkills(cwd);
}

// Global profiles are model-pinned, user-local state. Guard this helper itself so
// a caller on Claude/Codex/Cursor cannot create an OpenCode lineup accidentally.
export function refreshOpenCodeGlobalAgentFiles(cwd: string, state: Rec): number {
  return detectHost() === 'opencode' ? writeOpenCodeGlobalAgentFiles(cwd, state) : 0;
}

export function writeOpenCodeHostAssets(cwd: string, state: Rec, _skills: readonly string[]): number {
  return cleanupLegacyOpenCodeProjectAssets(cwd)
    + refreshOpenCodeGlobalAgentFiles(cwd, state);
}
