// src/shared/materialize/opencode-assets.ts
// OpenCode-native project assets: `.opencode/agents/<role>.md` subagent files.
// Skills are NOT mirrored to `.opencode/skills` — that duplicated the canonical
// `.traffic-one/skills` (which the agent reads), and OpenCode builds its skill
// registry at startup so a mid-session copy is never loaded anyway. Root AGENTS.md
// remains the rule entrypoint.

import * as fs from 'fs';
import * as path from 'path';

import { OPENCODE_HOST_AGENTS_REL, OPENCODE_HOST_SKILLS_REL } from '../../config/opencode-host';
import { writeTextIfChanged } from '../fs-text';
import { detectHostPlan } from '../host-plan';
import { buildTeamLineup } from '../onboarding-server/flow';
import { openCodeDelegationActive } from '../performance';
import { roleAgentBody } from '../skill-filters';
import { GENERATED_MARKER, isGenerated, removeGeneratedFile, removeGeneratedSkillDir } from './generated';

type Rec = Record<string, unknown>;

const GENERATED_NOTE =
  '<!-- GENERATED BY traffic-one — per-role OpenCode subagent. `mode: subagent` is required; do not hand-edit (regenerated on materialize). -->';

function cleanupGeneratedAgents(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
      const file = path.join(dir, entry.name);
      if (!isGenerated(file)) continue;
      const role = entry.name.slice(0, -'.md'.length);
      if (!keep.has(role) && removeGeneratedFile(file)) removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  return removed;
}

function cleanupGeneratedSkills(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory() || keep.has(entry.name)) continue;
      if (removeGeneratedSkillDir(path.join(dir, entry.name))) removed += 1;
    }
  } catch {
    // best-effort cleanup
  }
  return removed;
}

function agentFile(role: string, label: string, blurb: string, model: string): string {
  const lines = [
    '---',
    `name: ${role}`,
    `description: ${(blurb || label).replace(/\n+/g, ' ').trim()}`,
    'mode: subagent',
    ...(model ? [`model: ${model}`] : []),
    '---',
    '',
    GENERATED_MARKER,
    GENERATED_NOTE,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt the orchestrator hands you and the project root `AGENTS.md` rule entrypoint.',
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
  ];
  const contract = roleAgentBody(role);
  if (contract) {
    lines.push(
      'The full role contract below is the same Traffic One role contract used on the paid hosts.',
      'Honor every MUST, hard rule, and completion gate before reporting completion.',
      '',
      '---',
      '',
      contract,
      '',
    );
  } else {
    lines.push('Follow the project rules and complete every requested artifact before reporting completion.', '');
  }
  return lines.join('\n');
}

function writeOpenCodeAgentFiles(cwd: string, state: Rec): number {
  const team = state.team && typeof state.team === 'object' ? (state.team as Rec) : null;
  const performance = state.performance && typeof state.performance === 'object' ? (state.performance as Rec) : null;
  const mode = team && typeof team.mode === 'string' ? team.mode : null;
  const level = performance && typeof performance.level === 'string' ? performance.level : null;
  const dir = path.join(cwd, OPENCODE_HOST_AGENTS_REL);
  if (mode !== 'subagents' || !level) return cleanupGeneratedAgents(dir, new Set());

  const overrides = team && team.overrides && typeof team.overrides === 'object' ? (team.overrides as Rec) : null;
  let lineup;
  try {
    const planCtx = { host: 'opencode', plan: detectHostPlan('opencode'), useOpenCode: openCodeDelegationActive(state, 'opencode') };
    lineup = buildTeamLineup(level, 'opencode', overrides, planCtx);
  } catch {
    return 0;
  }
  if (!lineup || lineup.length === 0) return cleanupGeneratedAgents(dir, new Set());

  const keep = new Set(lineup.map((member) => member.role));
  let written = cleanupGeneratedAgents(dir, keep);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return written;
  }
  for (const member of lineup) {
    try {
      if (writeTextIfChanged(path.join(dir, `${member.role}.md`), agentFile(member.role, member.label, member.blurb, member.model))) written += 1;
    } catch {
      // best-effort per role
    }
  }
  return written;
}

// Skills are intentionally NOT mirrored to `.opencode/skills` (see file header):
// it duplicated `.traffic-one/skills`, and OpenCode's skill registry is built at
// startup so a copy materialized mid-session is never loaded. Remove any
// previously-generated copy so existing projects get de-duplicated on materialize.
function removeOpenCodeSkills(cwd: string): number {
  const dir = path.join(cwd, OPENCODE_HOST_SKILLS_REL);
  const removed = cleanupGeneratedSkills(dir, new Set());
  try {
    if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
  } catch {
    // dir absent, or holds foreign (non-generated) content — leave it as-is
  }
  return removed;
}

export function writeOpenCodeHostAssets(cwd: string, state: Rec, _skills: readonly string[]): number {
  return writeOpenCodeAgentFiles(cwd, state) + removeOpenCodeSkills(cwd);
}
