// src/shared/materialize/role-contract-uninstall.ts
// Marker check + file-by-file sweep of Traffic One–generated host Task/subagent
// contracts. Uninstall calls this BEFORE it deletes ~/.traffic-one, so the
// project-root sidecars can still name onboarded trees.
//
// Deletes files that carry `GENERATED BY traffic-one` AND a per-host
// role-contract needle. Leftover `.opencode/agents/*.md` also match the
// AGENTS.md rules marker (`isGenerated`) — materialize's leftover cleanup
// treats that marker as ownership there. The rules-marker-only match is NOT
// applied to `.cursor/agents` or AGENTS.md. User-authored files without a
// matching marker stay.
//
// Never `rm -rf` `.cursor/agents` or `~/.config/opencode/agents`. Empty role
// dirs and empty `agents` dirs are rmdir'd; `.cursor`, `.github`, and
// `.traffic-one` are left in place. Deletes use fs.rmSync after the marker
// check — not fsjson.removePath, whose consent fence can block
// `.traffic-one/agents`.

import * as fs from 'fs';
import * as path from 'path';

import { KILO_HOST_AGENTS_REL } from '../../config/kilo-host';
import { OPENCODE_HOST_AGENTS_REL } from '../../config/opencode-host';
import { readText } from '../fsjson';
import { isContainedProjectRoot, realResolve, resolvedHomeDir } from '../state/local-prefs/recorded-project-roots';
import { CODEX_AGENTS_REL } from './codex-agents';
import { COPILOT_AGENTS_REL } from './copilot-agents';
import { CURSOR_AGENTS_REL } from './cursor-agent-model';
import { isGenerated } from './generated';
import { openCodeGlobalAgentsDir } from './opencode-assets';
import { WINDSURF_AGENTS_REL } from './windsurf-agents';

export const ROLE_CONTRACT_MARKER_NEEDLES = [
  'per-role Cursor subagent',
  'Copilot project agent',
  'per-role Kilo subagent',
  'Codex project agent',
  'Devin Local project subagent',
  'per-role OpenCode subagent',
] as const;

const GENERATED_BY = 'GENERATED BY traffic-one';
const OPENCODE_ROLE_NEEDLE = 'per-role OpenCode subagent';
const OPENCODE_GLOBAL_AGENT_NAME = /^traffic-one-.+\.md$/;

export const PROJECT_ROLE_CONTRACT_RELS = [
  CURSOR_AGENTS_REL,
  COPILOT_AGENTS_REL,
  KILO_HOST_AGENTS_REL,
  CODEX_AGENTS_REL,
  WINDSURF_AGENTS_REL,
  OPENCODE_HOST_AGENTS_REL,
] as const;

export interface RoleContractSweepResult {
  removed: string[];
  kept: string[];
}

function isUnderRoot(resolved: string, root: string): boolean {
  return resolved !== root && resolved.startsWith(root + path.sep);
}

function segmentCountBelow(resolved: string, root: string): number {
  if (!isUnderRoot(resolved, root)) return 0;
  return resolved.slice(root.length + 1).split(path.sep).filter(Boolean).length;
}

// Files only: realpath under $HOME, not `/`, not $HOME itself.
function isContainedHomeFile(filePath: string, env: NodeJS.ProcessEnv): boolean {
  const home = resolvedHomeDir(env);
  const resolved = realResolve(filePath);
  if (resolved === path.parse(resolved).root) return false;
  return isUnderRoot(resolved, home);
}

// OpenCode global: same spirit as isRemovableResidueDir (under home, ≥3
// segments), or under XDG_CONFIG_HOME with the same floor. Realpath both
// sides so a `/var` → `/private/var` HOME still contains its files.
function isContainedOpenCodeFile(filePath: string, env: NodeJS.ProcessEnv): boolean {
  const resolved = realResolve(filePath);
  if (resolved === path.parse(resolved).root) return false;
  const home = resolvedHomeDir(env);
  if (isUnderRoot(resolved, home) && segmentCountBelow(resolved, home) >= 3) return true;
  if (env.XDG_CONFIG_HOME) {
    const xdg = realResolve(env.XDG_CONFIG_HOME);
    if (resolved !== xdg && isUnderRoot(resolved, xdg) && segmentCountBelow(resolved, xdg) >= 3) return true;
  }
  return false;
}

export function isGeneratedRoleContract(filePath: string): boolean {
  const text = readText(filePath);
  if (typeof text !== 'string') return false;
  if (!text.includes(GENERATED_BY)) return false;
  // Needles are the per-host Task/subagent phrases. The AGENTS.md rules marker
  // contains GENERATED_BY but none of these, so it does not match.
  return ROLE_CONTRACT_MARKER_NEEDLES.some((needle) => text.includes(needle));
}

function walkRoleContractFiles(dir: string, maxDepth: number, depth = 1): string[] {
  const files: string[] = [];
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return files;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (depth < maxDepth) files.push(...walkRoleContractFiles(full, maxDepth, depth + 1));
    } else if (entry.isFile()) {
      files.push(full);
    }
  }
  return files;
}

function rmdirEmptyRoleAndAgentsDirs(projectRoot: string, removedFiles: string[]): void {
  const dirs = new Set<string>();
  const root = path.resolve(projectRoot);
  for (const file of removedFiles) {
    let dir = path.dirname(path.resolve(file));
    while (isUnderRoot(dir, root)) {
      const rel = path.relative(root, dir);
      const parts = rel.split(path.sep).filter(Boolean);
      if (parts.length >= 2 && parts[parts.length - 1] === 'agents') {
        dirs.add(dir);
        break;
      }
      if (parts.length >= 3 && parts[parts.length - 2] === 'agents') {
        dirs.add(dir);
        dir = path.dirname(dir);
        continue;
      }
      break;
    }
  }
  for (const dir of [...dirs].sort((a, b) => b.length - a.length)) {
    try {
      if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
    } catch {
      // non-empty, gone, or not removable — leave it
    }
  }
}

function isOwnedProjectRoleContract(filePath: string, rel: string): boolean {
  if (isGeneratedRoleContract(filePath)) return true;
  // Leftover OpenCode project agents were stamped with the rules marker only.
  return rel === OPENCODE_HOST_AGENTS_REL && isGenerated(filePath);
}

function deleteIfOwned(
  filePath: string,
  env: NodeJS.ProcessEnv,
  dryRun: boolean,
  contained: (filePath: string, env: NodeJS.ProcessEnv) => boolean,
  owned: (filePath: string) => boolean,
): 'removed' | 'kept' {
  if (!contained(filePath, env) || !owned(filePath)) return 'kept';
  if (dryRun) return 'removed';
  try {
    fs.rmSync(filePath);
    return 'removed';
  } catch {
    return 'kept';
  }
}

export function sweepGeneratedRoleContractsInProject(
  projectRoot: string,
  env: NodeJS.ProcessEnv = process.env,
  dryRun = false,
): RoleContractSweepResult {
  const removed: string[] = [];
  const kept: string[] = [];
  if (!isContainedProjectRoot(projectRoot, env)) return { removed, kept };
  const root = path.resolve(projectRoot);
  const projectReal = realResolve(projectRoot);

  for (const rel of PROJECT_ROLE_CONTRACT_RELS) {
    const dir = path.join(root, rel);
    const resolvedDir = path.resolve(dir);
    if (!isUnderRoot(resolvedDir, root)) continue;
    const maxDepth = rel === WINDSURF_AGENTS_REL ? 2 : 1;
    for (const file of walkRoleContractFiles(dir, maxDepth)) {
      if (!isUnderRoot(realResolve(file), projectReal)) {
        kept.push(file);
        continue;
      }
      const verdict = deleteIfOwned(
        file,
        env,
        dryRun,
        isContainedHomeFile,
        (candidate) => isOwnedProjectRoleContract(candidate, rel),
      );
      if (verdict === 'removed') removed.push(file);
      else kept.push(file);
    }
  }
  if (!dryRun) rmdirEmptyRoleAndAgentsDirs(root, removed);
  return { removed, kept };
}

export function sweepOpenCodeGlobalGeneratedAgents(
  env: NodeJS.ProcessEnv = process.env,
  dryRun = false,
): RoleContractSweepResult {
  const removed: string[] = [];
  const kept: string[] = [];
  const dir = openCodeGlobalAgentsDir(env);
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return { removed, kept };
  }
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const file = path.join(dir, entry.name);
    if (!OPENCODE_GLOBAL_AGENT_NAME.test(entry.name)) {
      kept.push(file);
      continue;
    }
    const text = readText(file);
    const opencodeOwned = typeof text === 'string'
      && text.includes(GENERATED_BY)
      && text.includes(OPENCODE_ROLE_NEEDLE)
      && isGeneratedRoleContract(file);
    if (!opencodeOwned || !isContainedOpenCodeFile(file, env)) {
      kept.push(file);
      continue;
    }
    if (dryRun) {
      removed.push(file);
      continue;
    }
    try {
      fs.rmSync(file);
      removed.push(file);
    } catch {
      kept.push(file);
    }
  }
  return { removed, kept };
}

export function projectHasRoleContractRels(projectRoot: string): boolean {
  return PROJECT_ROLE_CONTRACT_RELS.some((rel) => {
    try {
      return fs.existsSync(path.join(projectRoot, rel));
    } catch {
      return false;
    }
  });
}
