// src/shared/materialize/windsurf-agents.ts
// Devin Local / Windsurf native custom subagents:
// `.devin/agents/<role>/AGENT.md` with a model pinned from the project's
// performance level and detected Windsurf plan.

import * as fs from 'fs';
import * as path from 'path';

import { writeTextIfChanged } from '../fs-text';
import { readText } from '../fsjson';
import { detectHostPlan } from '../host-plan';
import { buildTeamLineup } from '../onboarding-server/flow';
import { openCodeDelegationActive } from '../performance';
import { roleAgentBody } from '../skill-filters';

type Rec = Record<string, unknown>;

export const WINDSURF_AGENTS_REL = path.join('.devin', 'agents');
export const WINDSURF_AGENT_MARKER = '<!-- GENERATED BY traffic-one — Devin Local project subagent -->';

function yamlString(value: string): string {
  return JSON.stringify(value.replace(/\n+/g, ' ').trim());
}

export function isGeneratedWindsurfAgent(filePath: string): boolean {
  const text = readText(filePath);
  return typeof text === 'string' && text.includes(WINDSURF_AGENT_MARKER);
}

function cleanupGeneratedAgents(dir: string, keep: ReadonlySet<string>): number {
  let removed = 0;
  try {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const file = path.join(dir, entry.name, 'AGENT.md');
      if (keep.has(entry.name) || !isGeneratedWindsurfAgent(file)) continue;
      fs.rmSync(path.join(dir, entry.name), { recursive: true, force: true });
      removed += 1;
    }
    if (fs.existsSync(dir) && fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
  } catch {
    // best-effort cleanup
  }
  return removed;
}

function toolsForRole(role: string): string[] {
  return role === 'senior-reviewer'
    ? ['read', 'grep', 'glob', 'exec']
    : ['read', 'grep', 'glob', 'edit', 'write', 'exec'];
}

function roleSpecificLines(role: string): string[] {
  if (role === 'senior-backend') {
    return [
      'Devin Local backend baseline: when credentials are not configured yet,',
      'still create useful product-specific seed/demo fixtures and typed API fallbacks.',
      '',
    ];
  }
  if (role !== 'senior-frontend') return [];
  return [
    'Devin Local frontend baseline: build credible product UI with demo fixtures and',
    'empty/loading/error states; do not leave the first screen as only setup text.',
    '',
  ];
}

function agentFile(role: string, label: string, blurb: string, model: string): string {
  const lines = [
    '---',
    `name: ${yamlString(role)}`,
    `description: ${yamlString(blurb || label)}`,
    ...(model ? [`model: ${yamlString(model)}`] : []),
    'allowed-tools:',
    ...toolsForRole(role).map((tool) => `  - ${tool}`),
    ...(role === 'senior-reviewer'
      ? ['permissions:', '  deny:', '    - write', '    - edit']
      : []),
    '---',
    '',
    WINDSURF_AGENT_MARKER,
    '',
    `You are the Traffic One **${label}** (\`${role}\`) for this project.`,
    '',
    'Follow the task prompt the orchestrator hands you and the project root `AGENTS.md` rule entrypoint.',
    'Also follow the handoff-digest protocol in `.traffic-one/rules/common/agent-handoff-digests.md`.',
    ...(role === 'senior-architect'
      ? []
      : [
        'Write ONLY within the file scope assigned to your role in',
        '`.traffic-one/runs/<runId>/assignments.json` — the run-team gate blocks out-of-scope writes.',
      ]),
    'Do not spawn further subagents; report your result to the orchestrator.',
    '',
    ...roleSpecificLines(role),
  ];
  const contract = roleAgentBody(role);
  if (contract) {
    lines.push(
      'The full role contract below is the same Traffic One role contract used on the other hosts.',
      'Honor every MUST, hard rule, and completion gate before reporting completion.',
      '',
      '---',
      '',
      contract,
      '',
    );
  } else {
    lines.push('Follow the project rules and complete every requested artifact before reporting completion.', '');
  }
  return lines.join('\n');
}

export function writeWindsurfAgentFiles(cwd: string, state: Rec): number {
  const team = state.team && typeof state.team === 'object' ? (state.team as Rec) : null;
  const performance = state.performance && typeof state.performance === 'object' ? (state.performance as Rec) : null;
  const mode = team && typeof team.mode === 'string' ? team.mode : null;
  const level = performance && typeof performance.level === 'string' ? performance.level : null;
  const dir = path.join(cwd, WINDSURF_AGENTS_REL);
  if (mode !== 'subagents' || !level) return cleanupGeneratedAgents(dir, new Set());

  const overrides = team && team.overrides && typeof team.overrides === 'object' ? (team.overrides as Rec) : null;
  let lineup;
  try {
    const planCtx = { host: 'windsurf', plan: detectHostPlan('windsurf'), useOpenCode: openCodeDelegationActive(state, 'windsurf') };
    lineup = buildTeamLineup(level, 'windsurf', overrides, planCtx);
  } catch {
    return 0;
  }
  if (!lineup || lineup.length === 0) return cleanupGeneratedAgents(dir, new Set());

  const keep = new Set(lineup.map((member) => member.role));
  let written = cleanupGeneratedAgents(dir, keep);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    return written;
  }
  for (const member of lineup) {
    const roleDir = path.join(dir, member.role);
    const target = path.join(roleDir, 'AGENT.md');
    if (fs.existsSync(target) && !isGeneratedWindsurfAgent(target)) continue;
    try {
      fs.mkdirSync(roleDir, { recursive: true });
      if (writeTextIfChanged(target, agentFile(member.role, member.label, member.blurb, member.model))) written += 1;
    } catch {
      // best-effort per role
    }
  }
  return written;
}
