// src/shared/architecture-contract/scaffold-content.ts
// Canonical bodies for scaffold files whose CONTENT is runtime knowledge, not
// a design decision.
//
// The compiler only ever emitted scaffold PATHS; the required `.prettierignore`
// entries lived exclusively in rules prose, so a run shipped the file empty
// and the implementer burned four turns discovering `.traffic-one`,
// `pnpm-lock.yaml`, and `.turbo` serially through formatter failures
// (observed 8co). Same story for `.env.example`: the crawl-origin gate names
// `VITE_SITE_URL` but nothing ever wrote the variable anywhere an agent could
// legally source it from.
//
// Deterministic and idempotent: content is seeded ONLY when the file is
// missing or blank; a non-empty agent-authored file is never overwritten.

import * as fs from 'fs';
import * as path from 'path';

import { SKIP_DIRS, SKIP_OS_FILES } from '../../config/reporting';
import type { CapabilityProfileV1 } from '../capabilities';
import { seedI18nCatalogKeys } from '../i18n-seed';
import { profileUsesReactI18n } from './i18n';
import { moduleSkeleton, type ModuleSkeletonReferenceV1 } from './skeletons';
import type { CompiledArchitectureV1 } from './types';

// Mirror of the baseline scan-skip + lockfile knowledge in
// `architecture-contract/baseline.ts` (isScanSkippedPath / LOCKFILE): what the
// verifier refuses to scan, the formatter must not check either.
const PRETTIERIGNORE_BODY = [
  '# generated by traffic-one — formatter must skip what the verifier skips',
  'node_modules/',
  'dist/',
  'build/',
  'coverage/',
  'out/',
  '.next/',
  '.turbo/',
  '.vite/',
  '.traffic-one/',
  'pnpm-lock.yaml',
  'package-lock.json',
  'yarn.lock',
  'bun.lockb',
  'composer.lock',
  '*.min.*',
  '*.tsbuildinfo',
  '',
].join('\n');

const ENV_EXAMPLE_BODY = [
  '# generated by traffic-one — copy to .env and fill in real values',
  '# Public production origin. Crawl assets (sitemap.xml, robots.txt) and',
  '# canonical URLs MUST be generated from this value; generation must fail',
  '# when it is unset instead of inventing localhost or a placeholder domain.',
  'VITE_SITE_URL=',
  '',
].join('\n');

// ── The compiled AST lint layer ─────────────────────────────────────────────
// Which real community linter owns hardcoded-copy detection for this profile.
// Where a layer exists, the write-time lexical i18n findings demote to
// warnings (the AST rule sees copy in EVERY syntactic position — ternaries,
// `&&` branches, `.map()` callbacks — exactly where the lexical scanner
// provably missed a shipped bug in 13co). Profiles that return null KEEP the
// blocking lexical scanner: no mature AST equivalent exists for them
// (Svelte and Astro have no maintained no-raw-text plugin as of 2026-07).
export type UiAstLintLayer = 'react-i18next' | 'vue-i18n';

export function uiAstLintLayer(
  profile: CapabilityProfileV1 | undefined,
): UiAstLintLayer | null {
  if (!profile) return null;
  if (profileUsesReactI18n(profile)) return 'react-i18next';
  if (profile.profileId === 'vue' || profile.profileId === 'nuxt') return 'vue-i18n';
  return null;
}

// The project's own quality bar, expressed in its real toolchain instead of in
// hook heuristics. Every rule here previously existed as a regex structural gate
// that guessed from filenames and component names — and each one produced false
// blockers that had to be tuned run after run (a hardcoded page-name list, a
// statement counter that read string bodies as code, a `React.lazy` binding
// mistaken for a local declaration).
//
// Three things change by moving them here: the rules are readable and editable by
// the project owner, they run on the whole project rather than one touched file,
// and CI keeps enforcing them after the run ends.
//
// `max-lines` matches the retired STRUCT_MODULE_LOC budget. The boundary rules
// replace STRUCT_LAYER_MISMATCH / STRUCT_APP_INLINE_PAGE / STRUCT_MULTI_PAGE_MODULE
// with real import paths instead of name heuristics.
const ESLINT_BASE_RULES = [
  '      // A module that packs an entire feature into one file is unambiguous.',
  '      \'max-lines\': [\'error\', { max: 400, skipBlankLines: true, skipComments: true }],',
  '      \'max-lines-per-function\': [\'warn\', { max: 120, skipBlankLines: true, skipComments: true }],',
  '      complexity: [\'warn\', 15],',
  '      // Pages belong in the compiled page roots; the app shell only composes.',
  '      \'no-restricted-imports\': [\'error\', {',
  '        patterns: [{',
  '          group: [\'**/pages/*\', \'!**/pages/index*\'],',
  '          importNames: [\'default\'],',
  '          allowTypeImports: true,',
  '          message: \'Import route pages only from the router/app shell.\',',
  '        }],',
  '      }],',
];

// `supabase/functions/**` is Deno source: another runtime, another resolver,
// and never part of this project's lint/typecheck surface.
const ESLINT_IGNORES_LINE =
  '  { ignores: [\'dist/**\', \'build/**\', \'coverage/**\', \'.next/**\', \'.nuxt/**\', \'.output/**\', \'.svelte-kit/**\', \'supabase/functions/**\'] },';

// Dependency-free fallback for profiles WITHOUT an AST lint layer: a plain
// flat-config array needs only `eslint` itself, so a manifest that never
// declares a plugin still gets a working `npm run lint`.
const ESLINT_CONFIG_BODY = [
  '// generated by traffic-one — the project\'s quality bar. Edit freely; CI runs it.',
  '// Dependency-free by design: only `eslint` itself is required to run this.',
  '',
  'export default [',
  ESLINT_IGNORES_LINE,
  '  {',
  '    rules: {',
  ...ESLINT_BASE_RULES,
  '    },',
  '  },',
  '];',
  '',
].join('\n');

// React-family layer: real AST rules through the project's own toolchain. The
// killed class ("regex approximation of a parser misses an idiom", 13co): the
// lexical scanner cannot see JSX inside `{cond ? <p>{t('x')}</p> : null}`,
// `{cond && …}`, or a `.map()` callback — the parser sees every JSXText node
// regardless of position, and `mode: 'all'` also reads copy handed to
// `createElement()` calls, which have no JSX punctuation at all.
//
// Configured to allow technical strings — imports, identifiers, className
// values, non-UI attributes, single-token slugs/paths — because a false deny
// is worse than a missed detection. The matching devDependencies are seeded
// into the tooling manifest by `packageJsonBody` below; the implementer lint
// gate verifies the dependency and the `lint` script survive to IMPLEMENTED.
//
// One files-glob covers EVERY workspace package (13co digest: "ESLint has no
// TypeScript file configuration and ignores this package" — coverage must be
// structural, not per-package opt-in).
const ESLINT_CONFIG_REACT_I18NEXT_BODY = [
  '// generated by traffic-one — the project\'s quality bar. Edit freely; CI runs it.',
  '// AST rules on purpose: eslint-plugin-i18next sees hardcoded copy in every',
  '// syntactic position a regex scanner cannot (ternaries, &&, .map, createElement).',
  '',
  'import i18next from \'eslint-plugin-i18next\';',
  'import tseslint from \'typescript-eslint\';',
  '',
  'export default [',
  ESLINT_IGNORES_LINE,
  '  {',
  '    // One glob for every workspace package: no package is ever "ignored by',
  '    // configuration". typescript-eslint\'s parser reads plain JS too.',
  '    files: [\'**/*.{js,jsx,mjs,cjs,ts,tsx}\'],',
  '    languageOptions: {',
  '      parser: tseslint.parser,',
  '      parserOptions: { ecmaFeatures: { jsx: true } },',
  '    },',
  '    plugins: { i18next },',
  '    rules: {',
  ...ESLINT_BASE_RULES,
  '      // Hardcoded user-facing copy, in ALL syntactic positions. Technical',
  '      // strings are allowed: imports/identifiers are never validated, the',
  '      // attribute excludes cover styling/wiring props, the callee excludes',
  '      // cover i18n/DOM/router/test APIs, and single-token slug/path/url',
  '      // strings are excluded by pattern. Translatable attributes (alt,',
  '      // placeholder, title, aria-label, label) stay validated.',
  '      \'i18next/no-literal-string\': [\'error\', {',
  '        mode: \'all\',',
  '        \'jsx-attributes\': {',
  '          exclude: [',
  '            \'className\', \'class\', \'style\', \'styleName\', \'key\', \'id\', \'name\',',
  '            \'type\', \'href\', \'to\', \'src\', \'srcSet\', \'target\', \'rel\', \'role\',',
  '            \'htmlFor\', \'for\', \'value\', \'variant\', \'size\', \'width\', \'height\',',
  '            \'loading\', \'decoding\', \'method\', \'action\', \'autoComplete\', \'lang\',',
  '            \'dir\', \'content\', \'property\', \'sizes\', \'media\', \'as\', \'form\',',
  '            \'pattern\', \'inputMode\', \'data-testid\', \'testId\', \'viewBox\', \'fill\',',
  '            \'stroke\', \'d\', \'xmlns\', \'points\', \'transform\', \'x\', \'y\', \'cx\',',
  '            \'cy\', \'r\', \'x1\', \'x2\', \'y1\', \'y2\', \'offset\', \'gradientUnits\',',
  '          ],',
  '        },',
  '        callees: {',
  '          exclude: [',
  '            \'t\', \'i18n.t\', \'i18next.t\', \'useTranslation\', \'require\', \'fetch\',',
  '            \'Error\', \'TypeError\', \'RangeError\', \'URL\', \'URLSearchParams\',',
  '            \'classNames\', \'clsx\', \'cn\', \'cva\', \'tv\', \'twMerge\',',
  '            \'querySelector\', \'querySelectorAll\', \'closest\', \'matches\',',
  '            \'getElementById\', \'getItem\', \'setItem\', \'removeItem\',',
  '            \'addEventListener\', \'removeEventListener\', \'dispatchEvent\',',
  '            \'navigate\', \'redirect\', \'createContext\', \'matchMedia\',',
  '            \'describe\', \'it\', \'test\', \'expect\', \'includes\', \'startsWith\',',
  '            \'endsWith\', \'split\', \'join\', \'replace\', \'indexOf\', \'localeCompare\',',
  '            \'setAttribute\', \'getAttribute\', \'hasAttribute\', \'removeAttribute\',',
  '            \'format\', \'parse\', \'padStart\', \'padEnd\',',
  '          ],',
  '        },',
  '        // Single-token technical strings (slugs, paths, urls, css tokens,',
  '        // MIME types, storage keys) and SCREAMING_SNAKE constants. Real copy',
  '        // has spaces.',
  '        words: {',
  '          exclude: [',
  '            /^[\\w/.:#@%-]+$/.source,',
  '            /^[A-Z0-9_]+$/.source,',
  '            /^\\W+$/.source,',
  '          ],',
  '        },',
  '      }],',
  '    },',
  '  },',
  '];',
  '',
].join('\n');

// Vue/Nuxt layer: the same contract through @intlify/eslint-plugin-vue-i18n.
// `no-raw-text` is template-AST-based, so copy inside `v-if` branches and
// slot templates is seen the same as top-level text.
const ESLINT_CONFIG_VUE_I18N_BODY = [
  '// generated by traffic-one — the project\'s quality bar. Edit freely; CI runs it.',
  '// AST rules on purpose: @intlify/eslint-plugin-vue-i18n sees hardcoded copy',
  '// in every template position a regex scanner cannot.',
  '',
  'import vueI18n from \'@intlify/eslint-plugin-vue-i18n\';',
  'import tseslint from \'typescript-eslint\';',
  'import vueParser from \'vue-eslint-parser\';',
  '',
  'export default [',
  ESLINT_IGNORES_LINE,
  '  {',
  '    files: [\'**/*.{js,mjs,cjs,ts}\'],',
  '    languageOptions: { parser: tseslint.parser },',
  '    rules: {',
  ...ESLINT_BASE_RULES,
  '    },',
  '  },',
  '  {',
  '    files: [\'**/*.vue\'],',
  '    languageOptions: {',
  '      parser: vueParser,',
  '      parserOptions: { parser: tseslint.parser },',
  '    },',
  '    plugins: { \'@intlify/vue-i18n\': vueI18n },',
  '    rules: {',
  '      // Raw template copy must go through vue-i18n. Translatable attributes',
  '      // are validated on every element; technical attributes are not listed,',
  '      // so they are allowed.',
  '      \'@intlify/vue-i18n/no-raw-text\': [\'error\', {',
  '        attributes: {',
  '          \'/.+/\': [\'title\', \'label\', \'alt\', \'placeholder\', \'aria-label\'],',
  '        },',
  '      }],',
  '    },',
  '  },',
  '];',
  '',
].join('\n');

function eslintConfigBody(profile: CapabilityProfileV1 | undefined): string {
  const layer = uiAstLintLayer(profile);
  if (layer === 'react-i18next') return ESLINT_CONFIG_REACT_I18NEXT_BODY;
  if (layer === 'vue-i18n') return ESLINT_CONFIG_VUE_I18N_BODY;
  return ESLINT_CONFIG_BODY;
}

// CSS through the community parser. 13co: a 424-char single-line `@theme` block
// was invisible to every lexical gate; stylelint parses the sheet for real.
// Tailwind's at-rules are declared up front so the standard config never
// false-denies the styling system the stack itself selected.
const STYLELINTRC_BODY = `${JSON.stringify({
  extends: 'stylelint-config-standard',
  rules: {
    'at-rule-no-unknown': [true, {
      ignoreAtRules: [
        'tailwind', 'apply', 'layer', 'theme', 'config', 'plugin', 'utility',
        'variant', 'custom-variant', 'source', 'reference', 'screen',
      ],
    }],
    'import-notation': null,
  },
}, null, 2)}\n`;

// Seeded ONLY for the manifest at the eslint tooling root, and only when the
// file is missing or blank (agents own the manifest from the first real write;
// this seed is what makes the scaffolded eslint/stylelint configs loadable
// instead of naming tools nothing declared). The design changed deliberately:
// the config files above import real plugins now, so the matching
// devDependencies must be born alongside them or `npm run lint` is broken on
// arrival.
function packageJsonBody(profile: CapabilityProfileV1 | undefined): string {
  const layer = uiAstLintLayer(profile);
  const layerDependencies = layer === 'react-i18next'
    ? { 'eslint-plugin-i18next': '^6.1.1', 'typescript-eslint': '^8.35.0' }
    : layer === 'vue-i18n'
      ? {
          '@intlify/eslint-plugin-vue-i18n': '^4.0.0',
          'typescript-eslint': '^8.35.0',
          'vue-eslint-parser': '^10.1.0',
        }
      : {};
  const devDependencies = Object.fromEntries(Object.entries({
    eslint: '^9.30.0',
    prettier: '^3.6.0',
    stylelint: '^16.21.0',
    'stylelint-config-standard': '^38.0.0',
    ...layerDependencies,
  }).sort(([a], [b]) => a.localeCompare(b)));
  return `${JSON.stringify({
    private: true,
    scripts: {
      lint: 'eslint .',
      'lint:css': 'stylelint "**/*.css" --allow-empty-input',
      format: 'prettier --write .',
      'format:check': 'prettier --check .',
    },
    devDependencies,
  }, null, 2)}\n`;
}

const PRETTIERRC_BODY = `${JSON.stringify({
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 100,
}, null, 2)}\n`;

// The Vite entry document. Its SHAPE is runtime knowledge (Vite mounts
// `#root` and loads `/src/main.tsx` as the module entry), and its static
// `<title>`/`<noscript>` metadata is pre-boot content no framework
// localization primitive can ever reach — the i18n markup scanner carves out
// exactly that document metadata (see `i18n-enforcement.ts`,
// blankEntryHtmlDocumentMetadata). Observed 13co: this mandatory scaffold
// output, hand-written by the frontend, tripped STRUCT_HARDCODED_COPY on its
// `<title>` and blocked the role for multiple cycles. Only compiled for
// vite-react (the one profile whose scaffold demands an entry html); agents
// may freely rewrite the seeded body — non-empty files are never reseeded.
const INDEX_HTML_BODY = [
  '<!doctype html>',
  '<html lang="en">',
  '  <head>',
  '    <meta charset="UTF-8" />',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '    <title>App</title>',
  '  </head>',
  '  <body>',
  '    <div id="root"></div>',
  '    <noscript>This application requires JavaScript.</noscript>',
  '    <script type="module" src="/src/main.tsx"></script>',
  '  </body>',
  '</html>',
  '',
].join('\n');

// Collapsed source stops being detectable and starts being impossible: the
// formatter rewrites it. `printWidth` is the same bar the collapse scanner used.
const RUFF_TOML_BODY = [
  '# generated by traffic-one — Python quality bar. Edit freely; CI runs it.',
  'line-length = 100',
  '',
  '[lint]',
  'select = ["E", "F", "I", "UP", "B", "SIM", "PL"]',
  '',
  '[lint.pylint]',
  'max-statements = 60',
  '',
].join('\n');

const GOLANGCI_BODY = [
  '# generated by traffic-one — Go quality bar. Edit freely; CI runs it.',
  'version: "2"',
  'linters:',
  '  enable:',
  '    - govet',
  '    - errcheck',
  '    - staticcheck',
  '    - ineffassign',
  '    - unused',
  '    - funlen',
  'linters-settings:',
  '  funlen:',
  '    lines: 120',
  '    statements: 60',
  '',
].join('\n');

const PINT_BODY = `${JSON.stringify({ preset: 'laravel' }, null, 2)}\n`;

const RUSTFMT_BODY = [
  '# generated by traffic-one — Rust formatting. Edit freely; CI runs it.',
  'max_width = 100',
  'edition = "2021"',
  '',
].join('\n');

// Directories the verifier skips that git must nevertheless TRACK. Only the
// high-churn `.traffic-one` subdirectories are ignored, by the explicit lines
// below — the tree also holds `rules/`, `skills/`, `digests/`, `.one.json` and
// the project-memory notes, and the COMMITTED root `AGENTS.md` references them
// on 15 lines. Observed 10co: a bare `.traffic-one/` line shadowed those
// explicit rules (git never descends into an ignored directory), so they were
// dead, the "digests stay committed" intent below was unreachable, and a fresh
// clone got a kernel pointing at ~50 files that were not in the repo.
const GIT_TRACKED_SCAN_SKIPPED_DIRS = new Set<string>(['.traffic-one']);

// Seeded from the SAME skip authority the verifier uses, so what the scans ignore
// and what git ignores cannot drift. Two facts drove this: the prose telling agents
// which paths to gitignore was prose only — nothing wrote the entries, so
// `.traffic-one/runs/**` (including a 65 KB append-only debug log) got committed
// and 122 paths sat untracked — and that prose list was inverted: it omitted
// `runs/` (the real churn) and named `digests/` (the one thing worth keeping).
//
// The authority is shared but not verbatim: git semantics and verifier semantics
// genuinely differ on `.traffic-one` (above) and on lockfiles (`SKIP_LOCKFILES`
// is deliberately not expanded here — see `config/reporting.ts`).
const GITIGNORE_BODY = [
  '# generated by traffic-one — git must ignore what the verifier already skips',
  ...[...SKIP_DIRS]
    .filter((dir) => !GIT_TRACKED_SCAN_SKIPPED_DIRS.has(dir))
    .sort()
    .map((dir) => `${dir}/`),
  ...[...SKIP_OS_FILES].sort(),
  '',
  '# Traffic One run state: high-churn, reproducible, and never source.',
  '# `digests/` is deliberately NOT ignored — the handoff record is worth keeping.',
  '.traffic-one/runs/',
  '.traffic-one/reports/',
  '.traffic-one/backups/',
  '.traffic-one/one-mcp-report.json',
  '',
  '# Local environment',
  '.env',
  '.env.local',
  '.env.*.local',
  '!.env.example',
  '',
].join('\n');

export function scaffoldFileContent(
  relPath: string,
  profile?: CapabilityProfileV1,
): string | null {
  const base = relPath.replace(/\\/g, '/').split('/').pop() || '';
  if (base === '.gitignore') return GITIGNORE_BODY;
  if (base === '.prettierignore') return PRETTIERIGNORE_BODY;
  if (base === '.env.example') return ENV_EXAMPLE_BODY;
  if (base === '.prettierrc') return PRETTIERRC_BODY;
  if (base === 'index.html') return INDEX_HTML_BODY;
  if (base === 'eslint.config.js') return eslintConfigBody(profile);
  if (base === '.stylelintrc.json') return STYLELINTRC_BODY;
  if (base === 'ruff.toml') return RUFF_TOML_BODY;
  if (base === '.golangci.yml') return GOLANGCI_BODY;
  if (base === 'pint.json') return PINT_BODY;
  if (base === 'rustfmt.toml') return RUSTFMT_BODY;
  return null;
}

export interface ScaffoldContentOptions {
  /**
   * The full compiled contract. When present AND `newProject` is true, every
   * compiled UI module additionally receives a compliant skeleton at its
   * DEFAULT output path (same missing-or-blank rule — see skeletons.ts), and
   * each skeleton's TODO catalog keys are seeded into every declared locale.
   */
  compiled?: CompiledArchitectureV1;
  /**
   * Greenfield guard, mirroring the compiler's own `isNewProject` scaffold
   * condition: module skeletons are emitted only on `new-project` runs, never
   * into an existing codebase.
   */
  newProject?: boolean;
}

/**
 * Seed canonical content for scaffold outputs that exist as empty files or do
 * not exist at all. Returns the relative paths that were written. Non-empty
 * files are never touched — agents may extend them (e.g. append more env
 * vars) without the runtime fighting back.
 *
 * `package.json` is seeded for exactly ONE output: the manifest at the eslint
 * tooling root, whose devDependencies must match the plugins the compiled
 * `eslint.config.js` imports. Every other manifest stays agent-authored.
 */
export function ensureScaffoldContent(
  projectRoot: string,
  scaffoldOutputs: ReadonlyArray<{ path: string }>,
  profile?: CapabilityProfileV1,
  options?: ScaffoldContentOptions,
): string[] {
  const normalized = (value: string): string => value.replace(/\\/g, '/');
  const eslintConfig = scaffoldOutputs.find((output) => (
    normalized(output.path).split('/').pop() === 'eslint.config.js'
  ));
  const toolingRoot = eslintConfig ? path.posix.dirname(normalized(eslintConfig.path)) : null;
  const toolingManifest = toolingRoot === null
    ? null
    : toolingRoot === '.' ? 'package.json' : `${toolingRoot}/package.json`;
  const written: string[] = [];
  for (const output of scaffoldOutputs) {
    const body = normalized(output.path) === toolingManifest
      ? packageJsonBody(profile)
      : scaffoldFileContent(output.path, profile);
    if (!body) continue;
    if (seedIfBlank(projectRoot, output.path, body)) written.push(output.path);
  }
  if (options?.newProject && options.compiled) {
    written.push(...ensureModuleSkeletons(projectRoot, options.compiled));
  }
  return written;
}

// Write one file under the missing-or-blank rule shared with the scaffold loop
// above. Returns true when the body reached disk.
function seedIfBlank(projectRoot: string, rel: string, body: string): boolean {
  const absolute = path.join(projectRoot, rel);
  try {
    if (fs.existsSync(absolute)) {
      const current = fs.readFileSync(absolute, 'utf8');
      if (current.trim().length > 0) return false;
    } else {
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
    }
    fs.writeFileSync(absolute, body);
    return true;
  } catch {
    return false; // best effort — the completion gates still name the gap
  }
}

/**
 * Materialize the compliant skeleton of every compiled UI module (and the
 * typed empty export of every service/store) at its DEFAULT output path, then
 * seed each skeleton's catalog keys into every declared locale. Greenfield
 * only (the caller guards on mode), and strictly missing-or-blank: a non-empty
 * agent-authored module is never touched, and only skeletons that were
 * actually WRITTEN in this call contribute seed references — keys for content
 * an agent already replaced would be unreferenced catalog entries.
 */
function ensureModuleSkeletons(
  projectRoot: string,
  compiled: CompiledArchitectureV1,
): string[] {
  const written: string[] = [];
  const references: ModuleSkeletonReferenceV1[] = [];
  for (const module of compiled.modules) {
    const skeleton = moduleSkeleton(compiled, module);
    if (!skeleton) continue;
    if (seedIfBlank(projectRoot, module.output, skeleton.content)) {
      written.push(module.output);
      references.push(...skeleton.references);
    }
  }
  const i18n = compiled.i18n;
  if (i18n && references.length > 0) {
    // The seeding helper only writes into catalogs that exist and parse; on a
    // greenfield tree the declared JSON catalogs do not exist yet, so every
    // catalog a skeleton key lands in is born as an empty object first (the
    // catalogs are compiled scaffold outputs, and the same missing-or-blank
    // rule applies).
    for (const reference of references) {
      for (const locale of i18n.locales) {
        const catalog = i18n.catalogs.find((candidate) => (
          candidate.format === 'json'
          && candidate.locales.includes(locale)
          && candidate.namespaces.includes(reference.namespace)
        ));
        if (catalog && seedIfBlank(projectRoot, catalog.path, '{}\n')) {
          written.push(catalog.path);
        }
      }
    }
    seedI18nCatalogKeys(projectRoot, i18n, references);
  }
  return written;
}
