// src/shared/architecture-contract/scaffold-content.ts
// Canonical bodies for scaffold files whose CONTENT is runtime knowledge, not
// a design decision.
//
// The compiler only ever emitted scaffold PATHS; the required `.prettierignore`
// entries lived exclusively in rules prose, so a run shipped the file empty
// and the implementer burned four turns discovering `.traffic-one`,
// `pnpm-lock.yaml`, and `.turbo` serially through formatter failures
// (observed 8co). Same story for `.env.example`: the crawl-origin gate names
// `VITE_SITE_URL` but nothing ever wrote the variable anywhere an agent could
// legally source it from.
//
// Deterministic and idempotent: content is seeded ONLY when the file is
// missing or blank; a non-empty agent-authored file is never overwritten.

import * as fs from 'fs';
import * as path from 'path';

import { SKIP_DIRS, SKIP_OS_FILES } from '../../config/reporting';
import { readRegularFileResult } from '../bounded-read';
import { profileHasWebUi, type CapabilityProfileV1 } from '../capabilities';
import { O_NOFOLLOW, isSymlink, nofollowEnforcedByKernel, writeAll } from '../fs-nofollow';
import { greenfieldEvidence, hasCommittedHistory } from '../greenfield-evidence';
import { seedI18nCatalogKeys } from '../i18n-seed';
import {
  CONVENTION_SLOT_BY_BASENAME,
  slotAcceptsScaffold,
  type ConventionSlot,
} from './convention-evidence';
import { profileUsesReactI18n } from './i18n';
import { moduleSkeleton, type ModuleSkeletonReferenceV1 } from './skeletons';
import type { CompiledArchitectureV1 } from './types';
import { readRegularFileOrThrow } from '../bounded-read';

// Mirror of the baseline scan-skip + lockfile knowledge in
// `architecture-contract/baseline.ts` (isScanSkippedPath / LOCKFILE): what the
// verifier refuses to scan, the formatter must not check either.
//
// ONE authority, several encodings. `.prettierignore` takes newline-delimited
// paths; stylelint takes `ignoreFiles` globs. Stylelint was seeded without an
// equivalent while `lint:css` globs `**/*.css` across the whole repo, so the
// first build made it lint its own generated Tailwind output — 249 errors in
// 14co, 182 in 15co, in both cases repaired by hand inside the project. Deriving
// both from this list is what stops them drifting apart again.
const VERIFIER_SKIPPED_DIRS = [
  'node_modules',
  'dist',
  'build',
  'coverage',
  'out',
  '.next',
  '.turbo',
  '.vite',
  '.traffic-one',
] as const;

const PRETTIERIGNORE_BODY = [
  '# generated by traffic-one — formatter must skip what the verifier skips',
  ...VERIFIER_SKIPPED_DIRS.map((dir) => `${dir}/`),
  'pnpm-lock.yaml',
  'package-lock.json',
  'yarn.lock',
  'bun.lockb',
  'composer.lock',
  '*.min.*',
  '*.tsbuildinfo',
  '',
].join('\n');

/** The same skip list as `ignoreFiles` globs, resolved from the config's dir. */
const STYLELINT_IGNORE_FILES = [
  ...VERIFIER_SKIPPED_DIRS.map((dir) => `**/${dir}/**`),
  '**/*.min.css',
];

// `.env.example` goes to `senior-backend` whenever that role exists, so an
// UNCONDITIONAL Vite body seeded `VITE_SITE_URL=` into API-only projects that
// will never have a sitemap — observed in 15cl, where the Go backend replaced it
// by hand. The crawl-origin language is real compiled knowledge tied to
// sitemap/canonical generation; it belongs only on a profile that has that
// surface.
/**
 * The public site-url variable a given web framework actually reads.
 *
 * Shared with `run-bootstrap-policy/integration-requirements.ts`, which resolves
 * the same name from compiled output paths and puts it in the implementer's
 * integration requirements. Seeding a different variable than the requirement
 * names means the role is told to read `NEXT_PUBLIC_SITE_URL` from a file that
 * documents `VITE_SITE_URL` — the value is empty either way, so nothing fails
 * loudly; the role just cannot find the contract it was pointed at.
 */
export function siteUrlEnvVarForFramework(framework: string | undefined): string {
  switch ((framework || '').toLowerCase()) {
    case 'nextjs': return 'NEXT_PUBLIC_SITE_URL';
    case 'nuxt': return 'NUXT_PUBLIC_SITE_URL';
    case 'svelte':
    case 'sveltekit': return 'PUBLIC_SITE_URL';
    case 'laravel': return 'APP_URL';
    case 'angular': return 'SITE_URL';
    default: return 'VITE_SITE_URL';
  }
}

function envExampleWebBody(framework: string | undefined): string {
  return [
    '# generated by traffic-one — copy to .env and fill in real values',
    '# Public production origin. Crawl assets (sitemap.xml, robots.txt) and',
    '# canonical URLs MUST be generated from this value; generation must fail',
    '# when it is unset instead of inventing localhost or a placeholder domain.',
    `${siteUrlEnvVarForFramework(framework)}=`,
    '',
  ].join('\n');
}

const ENV_EXAMPLE_SERVICE_BODY = [
  '# generated by traffic-one — copy to .env and fill in real values',
  '# Every variable the service reads belongs here with an EMPTY value: the file',
  '# documents the contract, it never carries a working default or a secret.',
  'PORT=',
  'LOG_LEVEL=',
  '',
].join('\n');

// No profile means the caller could not say what it is building (the
// satisfiability sweep asks that way). Answer with the framework-neutral body
// rather than inventing a web surface.
function envExampleBody(profile?: CapabilityProfileV1): string {
  return profile && profileHasWebUi(profile)
    ? envExampleWebBody(profile.framework)
    : ENV_EXAMPLE_SERVICE_BODY;
}

// ── The compiled AST lint layer ─────────────────────────────────────────────
// Which real community linter owns hardcoded-copy detection for this profile.
// Where a layer exists, the write-time lexical i18n findings demote to
// warnings (the AST rule sees copy in EVERY syntactic position — ternaries,
// `&&` branches, `.map()` callbacks — exactly where the lexical scanner
// provably missed a shipped bug in 13co). Profiles that return null KEEP the
// blocking lexical scanner: no mature AST equivalent exists for them
// (Svelte and Astro have no maintained no-raw-text plugin as of 2026-07).
export type UiAstLintLayer = 'react-i18next' | 'vue-i18n';

export function uiAstLintLayer(
  profile: CapabilityProfileV1 | undefined,
): UiAstLintLayer | null {
  if (!profile) return null;
  if (profileUsesReactI18n(profile)) return 'react-i18next';
  if (profile.profileId === 'vue' || profile.profileId === 'nuxt') return 'vue-i18n';
  return null;
}

// The project's own quality bar, expressed in its real toolchain instead of in
// hook heuristics. Every rule here previously existed as a regex structural gate
// that guessed from filenames and component names — and each one produced false
// blockers that had to be tuned run after run (a hardcoded page-name list, a
// statement counter that read string bodies as code, a `React.lazy` binding
// mistaken for a local declaration).
//
// Three things change by moving them here: the rules are readable and editable by
// the project owner, they run on the whole project rather than one touched file,
// and CI keeps enforcing them after the run ends.
//
// `max-lines` matches the retired STRUCT_MODULE_LOC budget. The boundary rules
// replace STRUCT_LAYER_MISMATCH / STRUCT_APP_INLINE_PAGE / STRUCT_MULTI_PAGE_MODULE
// with real import paths instead of name heuristics.
const ESLINT_BASE_RULES = [
  '      // A module that packs an entire feature into one file is unambiguous.',
  '      \'max-lines\': [\'error\', { max: 400, skipBlankLines: true, skipComments: true }],',
  '      \'max-lines-per-function\': [\'warn\', { max: 120, skipBlankLines: true, skipComments: true }],',
  '      complexity: [\'warn\', 15],',
  '      // Pages belong in the compiled page roots; the app shell only composes.',
  '      \'no-restricted-imports\': [\'error\', {',
  '        patterns: [{',
  '          group: [\'**/pages/*\', \'!**/pages/index*\'],',
  '          importNames: [\'default\'],',
  '          allowTypeImports: true,',
  '          message: \'Import route pages only from the router/app shell.\',',
  '        }],',
  '      }],',
];

// `supabase/functions/**` is Deno source: another runtime, another resolver,
// and never part of this project's lint/typecheck surface.
const ESLINT_IGNORES_LINE =
  '  { ignores: [\'dist/**\', \'build/**\', \'coverage/**\', \'.next/**\', \'.nuxt/**\', \'.output/**\', \'.svelte-kit/**\', \'supabase/functions/**\'] },';

// Dependency-free fallback for profiles WITHOUT an AST lint layer: a plain
// flat-config array needs only `eslint` itself, so a manifest that never
// declares a plugin still gets a working `npm run lint`.
const ESLINT_CONFIG_BODY = [
  '// generated by traffic-one — the project\'s quality bar. Edit freely; CI runs it.',
  '// Dependency-free by design: only `eslint` itself is required to run this.',
  '',
  'export default [',
  ESLINT_IGNORES_LINE,
  '  {',
  '    rules: {',
  ...ESLINT_BASE_RULES,
  '    },',
  '  },',
  '];',
  '',
].join('\n');

// React-family layer: real AST rules through the project's own toolchain. The
// killed class ("regex approximation of a parser misses an idiom", 13co): the
// lexical scanner cannot see JSX inside `{cond ? <p>{t('x')}</p> : null}`,
// `{cond && …}`, or a `.map()` callback — the parser sees every JSXText node
// regardless of position, and `mode: 'all'` also reads copy handed to
// `createElement()` calls, which have no JSX punctuation at all.
//
// Configured to allow technical strings — imports, identifiers, className
// values, non-UI attributes, single-token slugs/paths — because a false deny
// is worse than a missed detection. The matching devDependencies are seeded
// into the tooling manifest by `packageJsonBody` below; the implementer lint
// gate verifies the dependency and the `lint` script survive to IMPLEMENTED.
//
// One files-glob covers EVERY workspace package (13co digest: "ESLint has no
// TypeScript file configuration and ignores this package" — coverage must be
// structural, not per-package opt-in).
const ESLINT_CONFIG_REACT_I18NEXT_BODY = [
  '// generated by traffic-one — the project\'s quality bar. Edit freely; CI runs it.',
  '// AST rules on purpose: eslint-plugin-i18next sees hardcoded copy in every',
  '// syntactic position a regex scanner cannot (ternaries, &&, .map, createElement).',
  '',
  'import i18next from \'eslint-plugin-i18next\';',
  'import tseslint from \'typescript-eslint\';',
  '',
  'export default [',
  ESLINT_IGNORES_LINE,
  '  {',
  '    // One glob for every workspace package: no package is ever "ignored by',
  '    // configuration". typescript-eslint\'s parser reads plain JS too.',
  '    files: [\'**/*.{js,jsx,mjs,cjs,ts,tsx}\'],',
  '    languageOptions: {',
  '      parser: tseslint.parser,',
  '      parserOptions: { ecmaFeatures: { jsx: true } },',
  '    },',
  '    plugins: { i18next },',
  '    rules: {',
  ...ESLINT_BASE_RULES,
  '      // Hardcoded user-facing copy, in ALL syntactic positions. Technical',
  '      // strings are allowed: imports/identifiers are never validated, the',
  '      // attribute excludes cover styling/wiring props, the callee excludes',
  '      // cover i18n/DOM/router/test APIs, and single-token slug/path/url',
  '      // strings are excluded by pattern. Translatable attributes (alt,',
  '      // placeholder, title, aria-label, label) stay validated.',
  '      \'i18next/no-literal-string\': [\'error\', {',
  '        mode: \'all\',',
  '        \'jsx-attributes\': {',
  '          exclude: [',
  '            \'className\', \'class\', \'style\', \'styleName\', \'key\', \'id\', \'name\',',
  '            \'type\', \'href\', \'to\', \'src\', \'srcSet\', \'target\', \'rel\', \'role\',',
  '            \'htmlFor\', \'for\', \'value\', \'variant\', \'size\', \'width\', \'height\',',
  '            \'loading\', \'decoding\', \'method\', \'action\', \'autoComplete\', \'lang\',',
  '            \'dir\', \'content\', \'property\', \'sizes\', \'media\', \'as\', \'form\',',
  '            \'pattern\', \'inputMode\', \'data-testid\', \'testId\', \'viewBox\', \'fill\',',
  '            \'stroke\', \'d\', \'xmlns\', \'points\', \'transform\', \'x\', \'y\', \'cx\',',
  '            \'cy\', \'r\', \'x1\', \'x2\', \'y1\', \'y2\', \'offset\', \'gradientUnits\',',
  '          ],',
  '        },',
  '        callees: {',
  '          exclude: [',
  '            \'t\', \'i18n.t\', \'i18next.t\', \'useTranslation\', \'require\', \'fetch\',',
  '            \'Error\', \'TypeError\', \'RangeError\', \'URL\', \'URLSearchParams\',',
  '            \'classNames\', \'clsx\', \'cn\', \'cva\', \'tv\', \'twMerge\',',
  '            \'querySelector\', \'querySelectorAll\', \'closest\', \'matches\',',
  '            \'getElementById\', \'getItem\', \'setItem\', \'removeItem\',',
  '            \'addEventListener\', \'removeEventListener\', \'dispatchEvent\',',
  '            \'navigate\', \'redirect\', \'createContext\', \'matchMedia\',',
  '            \'describe\', \'it\', \'test\', \'expect\', \'includes\', \'startsWith\',',
  '            \'endsWith\', \'split\', \'join\', \'replace\', \'indexOf\', \'localeCompare\',',
  '            \'setAttribute\', \'getAttribute\', \'hasAttribute\', \'removeAttribute\',',
  '            \'format\', \'parse\', \'padStart\', \'padEnd\',',
  '          ],',
  '        },',
  '        // Single-token technical strings (slugs, paths, urls, css tokens,',
  '        // MIME types, storage keys) and SCREAMING_SNAKE constants. Real copy',
  '        // has spaces.',
  '        words: {',
  '          exclude: [',
  '            /^[\\w/.:#@%-]+$/.source,',
  '            /^[A-Z0-9_]+$/.source,',
  '            /^\\W+$/.source,',
  '          ],',
  '        },',
  '      }],',
  '    },',
  '  },',
  '];',
  '',
].join('\n');

// Vue/Nuxt layer: the same contract through @intlify/eslint-plugin-vue-i18n.
// `no-raw-text` is template-AST-based, so copy inside `v-if` branches and
// slot templates is seen the same as top-level text.
const ESLINT_CONFIG_VUE_I18N_BODY = [
  '// generated by traffic-one — the project\'s quality bar. Edit freely; CI runs it.',
  '// AST rules on purpose: @intlify/eslint-plugin-vue-i18n sees hardcoded copy',
  '// in every template position a regex scanner cannot.',
  '',
  'import vueI18n from \'@intlify/eslint-plugin-vue-i18n\';',
  'import tseslint from \'typescript-eslint\';',
  'import vueParser from \'vue-eslint-parser\';',
  '',
  'export default [',
  ESLINT_IGNORES_LINE,
  '  {',
  '    files: [\'**/*.{js,mjs,cjs,ts}\'],',
  '    languageOptions: { parser: tseslint.parser },',
  '    rules: {',
  ...ESLINT_BASE_RULES,
  '    },',
  '  },',
  '  {',
  '    files: [\'**/*.vue\'],',
  '    languageOptions: {',
  '      parser: vueParser,',
  '      parserOptions: { parser: tseslint.parser },',
  '    },',
  '    plugins: { \'@intlify/vue-i18n\': vueI18n },',
  '    rules: {',
  '      // Raw template copy must go through vue-i18n. Translatable attributes',
  '      // are validated on every element; technical attributes are not listed,',
  '      // so they are allowed.',
  '      \'@intlify/vue-i18n/no-raw-text\': [\'error\', {',
  '        attributes: {',
  '          \'/.+/\': [\'title\', \'label\', \'alt\', \'placeholder\', \'aria-label\'],',
  '        },',
  '      }],',
  '    },',
  '  },',
  '];',
  '',
].join('\n');

function eslintConfigBody(profile: CapabilityProfileV1 | undefined): string {
  const layer = uiAstLintLayer(profile);
  if (layer === 'react-i18next') return ESLINT_CONFIG_REACT_I18NEXT_BODY;
  if (layer === 'vue-i18n') return ESLINT_CONFIG_VUE_I18N_BODY;
  return ESLINT_CONFIG_BODY;
}

// CSS through the community parser. 13co: a 424-char single-line `@theme` block
// was invisible to every lexical gate; stylelint parses the sheet for real.
// Tailwind's at-rules are declared up front so the standard config never
// false-denies the styling system the stack itself selected.
const STYLELINTRC_BODY = `${JSON.stringify({
  extends: 'stylelint-config-standard',
  ignoreFiles: STYLELINT_IGNORE_FILES,
  rules: {
    'at-rule-no-unknown': [true, {
      ignoreAtRules: [
        'tailwind', 'apply', 'layer', 'theme', 'config', 'plugin', 'utility',
        'variant', 'custom-variant', 'source', 'reference', 'screen',
      ],
    }],
    'import-notation': null,
  },
}, null, 2)}\n`;

// Seeded ONLY for the manifest at the eslint tooling root, and only when the
// file is missing or blank (agents own the manifest from the first real write;
// this seed is what makes the scaffolded eslint/stylelint configs loadable
// instead of naming tools nothing declared). The design changed deliberately:
// the config files above import real plugins now, so the matching
// devDependencies must be born alongside them or `npm run lint` is broken on
// arrival.
function packageJsonBody(profile: CapabilityProfileV1 | undefined): string {
  const layer = uiAstLintLayer(profile);
  const layerDependencies = layer === 'react-i18next'
    ? { 'eslint-plugin-i18next': '^6.1.1', 'typescript-eslint': '^8.35.0' }
    : layer === 'vue-i18n'
      ? {
          '@intlify/eslint-plugin-vue-i18n': '^4.0.0',
          'typescript-eslint': '^8.35.0',
          'vue-eslint-parser': '^10.1.0',
        }
      : {};
  const devDependencies = Object.fromEntries(Object.entries({
    eslint: '^9.30.0',
    prettier: '^3.6.0',
    stylelint: '^16.21.0',
    'stylelint-config-standard': '^38.0.0',
    ...layerDependencies,
  }).sort(([a], [b]) => a.localeCompare(b)));
  return `${JSON.stringify({
    private: true,
    scripts: {
      lint: 'eslint .',
      'lint:css': 'stylelint "**/*.css" --allow-empty-input',
      format: 'prettier --write .',
      'format:check': 'prettier --check .',
    },
    devDependencies,
  }, null, 2)}\n`;
}

// `printWidth` must stay UNDER the collapse detector's bars, or the two fight:
// prettier formats to its width, the strict detector (140 code chars, 80 on a
// JSX line — shared/collapsed-source.ts) still flags the result, the completion
// repair loop cannot fix what it just formatted, and the role can never emit
// `IMPLEMENTED`. 80 is prettier's own default and sits comfortably below both.
const PRETTIERRC_BODY = `${JSON.stringify({
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 80,
}, null, 2)}\n`;

// The Vite entry document. Its SHAPE is runtime knowledge (Vite mounts
// `#root` and loads `/src/main.tsx` as the module entry), and its static
// `<title>`/`<noscript>` metadata is pre-boot content no framework
// localization primitive can ever reach — the i18n markup scanner carves out
// exactly that document metadata (see `i18n-enforcement.ts`,
// blankEntryHtmlDocumentMetadata). Observed 13co: this mandatory scaffold
// output, hand-written by the frontend, tripped STRUCT_HARDCODED_COPY on its
// `<title>` and blocked the role for multiple cycles. Only compiled for
// vite-react (the one profile whose scaffold demands an entry html); agents
// may freely rewrite the seeded body — non-empty files are never reseeded.
const INDEX_HTML_BODY = [
  '<!doctype html>',
  '<html lang="en">',
  '  <head>',
  '    <meta charset="UTF-8" />',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '    <title>App</title>',
  '  </head>',
  '  <body>',
  '    <div id="root"></div>',
  '    <noscript>This application requires JavaScript.</noscript>',
  '    <script type="module" src="/src/main.tsx"></script>',
  '  </body>',
  '</html>',
  '',
].join('\n');

// Collapsed source stops being detectable and starts being impossible: the
// formatter rewrites it. `printWidth` is the same bar the collapse scanner used.
const RUFF_TOML_BODY = [
  '# generated by traffic-one — Python quality bar. Edit freely; CI runs it.',
  'line-length = 100',
  '',
  '[lint]',
  'select = ["E", "F", "I", "UP", "B", "SIM", "PL"]',
  '',
  '[lint.pylint]',
  'max-statements = 60',
  '',
].join('\n');

// Schema v2 moved linter settings under `linters.settings`. The v1 top-level
// `linters-settings` key is not merely ignored — v2 validates the config against
// a JSON schema with `additionalProperties: false` and REFUSES TO RUN:
//   jsonschema: "" does not validate with "/additionalProperties":
//   additional properties 'linters-settings' not allowed
//   The command is terminated due to an error: the configuration contains invalid elements
// (reproduced against golangci-lint 2.12.2). So the seeded file did not soften
// the quality bar, it disabled the linter outright for every Go project.
const GOLANGCI_BODY = [
  '# generated by traffic-one — Go quality bar. Edit freely; CI runs it.',
  'version: "2"',
  'linters:',
  '  enable:',
  '    - govet',
  '    - errcheck',
  '    - staticcheck',
  '    - ineffassign',
  '    - unused',
  '    - funlen',
  '  settings:',
  '    funlen:',
  '      lines: 120',
  '      statements: 60',
  '',
].join('\n');

const PINT_BODY = `${JSON.stringify({ preset: 'laravel' }, null, 2)}\n`;

const RUSTFMT_BODY = [
  '# generated by traffic-one — Rust formatting. Edit freely; CI runs it.',
  'max_width = 100',
  'chain_width = 100',
  'edition = "2021"',
  '',
].join('\n');

// Directories the verifier skips that git must nevertheless TRACK. Only the
// high-churn `.traffic-one` subdirectories are ignored, by the explicit lines
// below — the tree also holds `rules/`, `skills/`, `digests/`, `.one.json` and
// the project-memory notes, and the COMMITTED root `AGENTS.md` references them
// on 15 lines. Observed 10co: a bare `.traffic-one/` line shadowed those
// explicit rules (git never descends into an ignored directory), so they were
// dead, the "digests stay committed" intent below was unreachable, and a fresh
// clone got a kernel pointing at ~50 files that were not in the repo.
const GIT_TRACKED_SCAN_SKIPPED_DIRS = new Set<string>(['.traffic-one']);

// Traffic One's own high-churn state under `.traffic-one/`: run artefacts,
// per-run and project-level debug logs (see `collectActions` in
// `shared/retention.ts` — `.traffic-one/debug/*` and `.traffic-one/runs/<id>/debug/*`
// are exactly what it sweeps; the latter is already covered transitively by
// the `runs/` entry below, since a directory pattern hides everything under it),
// and the one-mcp status file. `digests/` is deliberately absent — the handoff
// record is worth keeping.
//
// Emitted as `**/.traffic-one/${entry}` so a polyglot workspace member's own
// `.traffic-one/` (e.g. `web/.traffic-one/runs/`) matches. A leading `**` is
// the gitignore form that is not anchored to the directory containing
// `.gitignore`. `.onboarding-main-sessions.json` is the Cursor pre-onboarding
// main-session store (onboarding-server/onboarding-session.ts) — committable
// without this line, and a future-stamped copy of it would silence consent.
const TRAFFIC_ONE_RUN_STATE_ENTRIES = [
  'runs/', 'reports/', 'backups/', 'debug/', 'one-mcp-report.json',
  '.onboarding-main-sessions.json',
] as const;

// The GREENFIELD seed only — and "greenfield" is decided by EVIDENCE on disk
// (`greenfieldEvidence`, further below), never by a caller's mode flag. It
// reaches a project through the compiler's scaffold path
// (`ensureScaffoldContent` + `seedIfBlank`, still below) or through
// `ensureProjectGitignore` for any managed region whose recorded scope is
// `full`. Seeded from the SAME skip
// authority the verifier uses, so what the scans ignore and what git ignores
// cannot drift. Two facts drove this: the prose telling agents which paths to
// gitignore was prose only — nothing wrote the entries, so
// `.traffic-one/runs/**` (including a 65 KB append-only debug log) got committed
// and 122 paths sat untracked — and that prose list was inverted: it omitted
// `runs/` (the real churn) and named `digests/` (the one thing worth keeping).
//
// This is deliberately NOT what an EXISTING project's `.gitignore` gets — see
// TRAFFIC_ONE_BLOCK_BODY below for why deciding `vendor/`/`dist/`/`target/`
// etc. for a repo Traffic One did not create is out of scope.
//
// The authority is shared but not verbatim: git semantics and verifier semantics
// genuinely differ on `.traffic-one` (above) and on lockfiles (`SKIP_LOCKFILES`
// is deliberately not expanded here — see `config/reporting.ts`).
const GITIGNORE_BODY = [
  '# generated by traffic-one — git must ignore what the verifier already skips',
  ...[...SKIP_DIRS]
    .filter((dir) => !GIT_TRACKED_SCAN_SKIPPED_DIRS.has(dir))
    .sort()
    .map((dir) => `${dir}/`),
  ...[...SKIP_OS_FILES].sort(),
  '',
  '# Traffic One run state: high-churn, reproducible, and never source.',
  '# `digests/` is deliberately NOT ignored — the handoff record is worth keeping.',
  ...TRAFFIC_ONE_RUN_STATE_ENTRIES.map((entry) => `**/.traffic-one/${entry}`),
  '',
  '# Local environment',
  '.env',
  '.env.local',
  '.env.*.local',
  '!.env.example',
  '',
].join('\n');

// The ONLY lines `ensureProjectGitignore` (below) ever imposes on a project it
// did not scaffold. Everything else in GITIGNORE_BODY above — the
// SKIP_DIRS/SKIP_OS_FILES-derived opinions, `.env*` — reaches a project only
// where the disk itself proves greenfield (`greenfieldEvidence`: no
// `.gitignore` content and no commit in the repository that owns the project
// root), through either writer: deciding that an EXISTING repo's
// `vendor/`, `dist/`, `target/`, `generated/`, etc. are safe to gitignore is
// not ours to make. Go projects routinely commit `vendor/` (`go mod vendor`),
// published libraries routinely commit `dist/`/`build/`, and git's ignore
// rules never untrack what is already committed — so getting this wrong fails
// silently: the next NEW file under one of those directories goes untracked
// on the next clone, with no error anywhere near Traffic One.
// Exported so the tests can assert the EXACT bytes of a converged file while
// spelling the block's own format out independently (the greenfield body is
// already reachable as `scaffoldFileContent('.gitignore')`). A format change
// then has to be a deliberate edit in two places rather than something a test
// silently ratifies.
export const TRAFFIC_ONE_BLOCK_BODY = [
  '# generated by traffic-one — Traffic One\'s own run state: high-churn, reproducible, never source.',
  '# `digests/` is deliberately NOT ignored — the handoff record is worth keeping.',
  ...TRAFFIC_ONE_RUN_STATE_ENTRIES.map((entry) => `**/.traffic-one/${entry}`),
].join('\n');

// Delimited block markers, same convention as the Windsurf global-rules block
// (`OWNER_START`/`OWNER_END` in `runners/windsurf-host/index.ts`) and the
// gitnexus AGENTS.md block (`gitnexus:start`/`gitnexus:end` in
// `materialize/render-agents.ts`): a re-run can find and update exactly its
// own region without touching a single byte the project owner wrote.
export const GITIGNORE_BLOCK_START = '# traffic-one:gitignore:start';
export const GITIGNORE_BLOCK_END = '# traffic-one:gitignore:end';

/**
 * Which of the two bodies a managed region carries.
 *
 * RECORDED IN THE REGION ITSELF (`scope=<id>` on the start marker) instead of
 * being re-derived from the caller on every call. The caller's `newProject`
 * flag is a guess about a project's history, and a provably unstable one:
 * `materializeProjectAssets` derives it from `state.mode`, and
 * `onboarding/repair.ts` re-derives a LOST mode with `detectMode(cwd)`, which
 * counts source files — so a greenfield project that has since been populated
 * comes back as `existing-codebase` and the same project's next call arrives
 * with `newProject: false`. The file on disk is the only authority on what
 * Traffic One already promised this project.
 *
 * Without the record, that flip narrowed an established full block down to
 * `TRAFFIC_ONE_BLOCK_BODY` and DELETED `node_modules/ dist/ build/ vendor/
 * target/ .env` from a real project's ignore list (measured: 866 → 924 → 356
 * bytes over three calls). Nothing fails loudly when it happens — git never
 * untracks what is already committed — so the damage surfaces later, as the
 * user's next `git add .` committing a `.env` that stopped being ignored.
 *
 * The same unstable flag pointed the OTHER way is why the record alone is not
 * enough: a region that starts life `full` because the flag said so is a
 * permanent decision made on a guess, and `createdBlockScope` (below) is what
 * stops the guess from making it.
 */
export type GitignoreScope = 'full' | 'traffic-one';

const GITIGNORE_SCOPE_PREFIX = `${GITIGNORE_BLOCK_START} scope=`;

function gitignoreScopeBody(scope: GitignoreScope): string {
  return scope === 'full' ? GITIGNORE_BODY : TRAFFIC_ONE_BLOCK_BODY;
}

function gitignoreBlock(scope: GitignoreScope): string {
  return [
    `${GITIGNORE_SCOPE_PREFIX}${scope}`,
    gitignoreScopeBody(scope).trimEnd(),
    GITIGNORE_BLOCK_END,
    '',
  ].join('\n');
}

// Splits keeping each line's own terminator attached (including a `\r` before
// a `\n`, if present), so slicing a contiguous run back out of the ORIGINAL
// text reproduces every owner byte around it exactly — full-file `===`
// equality (the previous check) missed the instant an owner added, reordered,
// or trailing-newline-diffed a single line, and then silently doubled the
// whole rule set below an unmarked copy on every call forever (never healed,
// because the doubled state is itself stable under the same broken check).
function linesKeepingTerminators(text: string): string[] {
  return text.split(/(?<=\n)/);
}

function lineContent(line: string): string {
  return line.replace(/\r?\n$/, '').replace(/[ \t]+$/, '');
}

// The greenfield seed's own content, landmark-matched line-by-line so CRLF and
// trailing-whitespace differences (an editor's line-ending conversion, a
// trailing-space autofix) can't defeat detection the way whole-file equality
// did. `GITIGNORE_BODY` opens with a distinctive generated-header comment and
// its shape is otherwise unique to this seed, so a contiguous match is
// unambiguous — this is not fuzzy matching, it is the same content tolerant of
// line-ending/whitespace noise only.
const GITIGNORE_BODY_LINES = linesKeepingTerminators(GITIGNORE_BODY).map(lineContent);

// The lines that exist ONLY in the full body. Any single one of them inside a
// managed region proves the region carries `GITIGNORE_BODY`, which is how a
// region written by an earlier release — marked, but with no `scope=` recorded
// yet — gets classified without consulting the caller's flag.
//
// Deliberately the whole set of exclusive lines rather than just the header
// comment: an owner who reworded or deleted our header must not thereby cause
// every build-output opinion to be silently narrowed away, and a future release
// that rewords the header must not quietly reintroduce the narrowing this
// classification exists to prevent. Losing the distinction would require
// deleting every opinion in the region — at which point there is nothing left
// to destroy.
const TRAFFIC_ONE_BLOCK_BODY_LINES = new Set(
  linesKeepingTerminators(TRAFFIC_ONE_BLOCK_BODY).map(lineContent),
);
const GITIGNORE_FULL_ONLY_LINES = GITIGNORE_BODY_LINES.filter(
  (line) => line !== '' && !TRAFFIC_ONE_BLOCK_BODY_LINES.has(line),
);

// Finds the legacy seed as a contiguous run of lines anywhere in `existing` —
// above, below, or surrounded by owner content — and returns the raw
// (unnormalized) text on each side, unsliced, so the caller can wrap just the
// landmark region and hand every other byte back untouched.
function findLegacyBodySpan(existing: string): { before: string; after: string } | null {
  const rawLines = linesKeepingTerminators(existing);
  const normalized = rawLines.map(lineContent);
  const body = GITIGNORE_BODY_LINES;
  for (let i = 0; i + body.length <= normalized.length; i += 1) {
    let matches = true;
    for (let j = 0; j < body.length; j += 1) {
      if (normalized[i + j] !== body[j]) { matches = false; break; }
    }
    if (matches) {
      return { before: rawLines.slice(0, i).join(''), after: rawLines.slice(i + body.length).join('') };
    }
  }
  return null;
}

// Reads the scope off a start-marker line, or null when the line is not a start
// marker at all.
//
// WHOLE-LINE and ANCHORED. The previous `indexOf` substring match treated an
// owner's own PROSE ABOUT the markers as the marker itself: a line reading
// `# note: # traffic-one:gitignore:start is how the block opens` opened "our"
// region mid-line, and the next rewrite dropped that line's tail plus every
// owner line between it and the real block (measured 87 → 444 → 378 bytes, two
// owner lines destroyed). The mirror case — prose naming the END marker — was
// worse: it made `end` precede `start` and the file grew by a full rule set on
// every single call, unbounded (72 → 429 → 786 → 1143).
//
// Trailing whitespace is tolerated (an editor's trailing-space autofix must not
// orphan a region); leading whitespace is deliberately NOT — an indented marker
// is a quoted example in someone's notes, not our delimiter.
function startMarkerScope(content: string): GitignoreScope | 'unknown' | null {
  // Untagged: every block written before the scope was recorded. Classified
  // from the region's own content below, then rewritten WITH the tag.
  if (content === GITIGNORE_BLOCK_START) return 'unknown';
  if (!content.startsWith(GITIGNORE_SCOPE_PREFIX)) return null;
  const scope = content.slice(GITIGNORE_SCOPE_PREFIX.length);
  return scope === 'full' || scope === 'traffic-one' ? scope : 'unknown';
}

type ManagedRegionScan =
  | { kind: 'absent' }
  | { kind: 'malformed' }
  | { kind: 'present'; start: number; end: number; scope: GitignoreScope | 'unknown' };

// Structural validation BEFORE any rewrite: exactly one start, exactly one end,
// start above end. Anything else is a file a human hand-edited inside our own
// region, and every possible repair has to guess which bytes are ours and which
// are theirs — the guess is what deleted owner lines on five of the reviewer's
// shapes. So the malformed verdict is not repaired, it is REFUSED (see
// `nextGitignoreContent`).
function scanManagedRegion(rawLines: readonly string[]): ManagedRegionScan {
  let starts = 0;
  let ends = 0;
  let start = -1;
  let end = -1;
  let scope: GitignoreScope | 'unknown' = 'unknown';
  let index = -1;
  for (const raw of rawLines) {
    index += 1;
    const content = lineContent(raw);
    const marker = startMarkerScope(content);
    if (marker !== null) {
      starts += 1;
      start = index;
      scope = marker;
    } else if (content === GITIGNORE_BLOCK_END) {
      ends += 1;
      end = index;
    }
  }
  if (starts === 0 && ends === 0) return { kind: 'absent' };
  // Zero-with-one (a hand-deleted marker), duplicated, nested, and two whole
  // blocks all land here, as does a reversed pair below.
  if (starts !== 1 || ends !== 1) return { kind: 'malformed' };
  if (start > end) return { kind: 'malformed' };
  return { kind: 'present', start, end, scope };
}

// An untagged region's scope, read from what the region actually holds.
function regionScope(regionLines: readonly string[]): GitignoreScope {
  const content = new Set(regionLines.map(lineContent));
  return GITIGNORE_FULL_ONLY_LINES.some((line) => content.has(line)) ? 'full' : 'traffic-one';
}

// Mirrors the Windsurf block replace, with one fix: that implementation
// unconditionally inserts a blank-line separator before the block, so a file
// whose entire content IS the block (the steady state right after this same
// function created it) gets two spurious leading blank lines on every later
// call. Only inserting the separator when a real preamble exists keeps a
// no-op run byte-identical.
//
// The tail collapses BLANK LINES ONLY — never `/^\s+/`, which also ate the
// INDENTATION of the first owner line below the end marker. Leading whitespace
// is significant in a gitignore pattern (only TRAILING spaces are ignored, and
// only when unquoted), so `  build/` names a directory literally called
// `  build` and matches nothing real. Stripping the two spaces turns that inert
// line into a live rule that hides the project's actual `build/` — a silent
// widening of the ignore set, in bytes the block promises never to touch.
function spliceGitignoreBlock(before: string, scope: GitignoreScope, after: string): string {
  const preamble = before.trimEnd();
  const tail = after.replace(/^(?:[ \t]*\r?\n)+/, '');
  return `${preamble ? `${preamble}\n\n` : ''}${gitignoreBlock(scope)}${tail}`;
}

/**
 * The file's next content, or `null` for REFUSE — leave every byte alone.
 *
 * `createdScope` is consulted for exactly one decision: which body a region
 * being CREATED starts life with, and it is resolved lazily because answering
 * it costs a walk up the filesystem (see `greenfieldEvidence`) that a refresh
 * must not pay for. Refreshing an existing region always reads the scope out of
 * the file (recorded tag first, region content second), so no caller can narrow
 * a block the project already has.
 *
 * Refusing is the answer to a malformed marker pair because it is the only
 * option that is provably non-destructive AND provably non-growing: nothing is
 * written at all, so no owner line can be deleted, no rule can be duplicated,
 * and the file is byte-identical after any number of calls. The cost is that a
 * hand-mangled region stops receiving updates until a human repairs the pair —
 * correct for a file whose delimiters someone has already edited by hand.
 */
function nextGitignoreContent(existing: string, createdScope: () => GitignoreScope): string | null {
  const rawLines = linesKeepingTerminators(existing);
  const scan = scanManagedRegion(rawLines);
  if (scan.kind === 'malformed') return null;
  if (scan.kind === 'present') {
    const scope = scan.scope === 'unknown'
      ? regionScope(rawLines.slice(scan.start, scan.end + 1))
      : scan.scope;
    return spliceGitignoreBlock(
      rawLines.slice(0, scan.start).join(''),
      scope,
      rawLines.slice(scan.end + 1).join(''),
    );
  }
  // The greenfield scaffold path already seeded this EXACT body, unmarked,
  // before this block existed (`scaffoldFileContent('.gitignore')` still
  // returns it, and `.gitignore` is in REPOSITORY_SCAFFOLD_OUTPUTS, so this is
  // the live shape of every greenfield project, not a legacy population).
  // Recognized by landmark, not by the caller's flag or whole-file equality
  // (see findLegacyBodySpan): owner lines before and/or after the seed survive
  // byte-for-byte, and the seed is re-wrapped WHOLE as `full` — the caller
  // cannot narrow it — with that scope now recorded in the marker, so the
  // classification never has to be re-derived on a later call.
  const legacy = findLegacyBodySpan(existing);
  if (legacy) return spliceGitignoreBlock(legacy.before, 'full', legacy.after);
  const block = gitignoreBlock(createdScope());
  return existing.trim() ? `${existing.trimEnd()}\n\n${block}` : block;
}

// `readFileSync`/`writeFileSync` both follow symlinks, so a `.gitignore` that is
// a symlink pointing outside `projectRoot` would get written THROUGH the link
// into whatever it targets. An `lstatSync` guard ahead of the write only NARROWS
// that window — the path can become a symlink in between — so the refusal lives
// in the open flags instead, where the kernel enforces it atomically.
//
// O_NOFOLLOW is undefined on Windows and degrades to 0 there, hence the retained
// pre-open `lstat` for that case: no platform ends up with LESS protection than
// the check alone gave it. Both live in shared/fs-nofollow.ts now — this file
// solved the problem first and fsjson.ts's write fence needed the same
// primitives, and two copies of a platform-degradation detail is exactly the
// drift that turns one of them back into a hole.

/** A regular-file fd opened for in-place update, or why we will not write. */
function openGitignoreForUpdate(absolute: string): number | 'absent' | 'refused' {
  if (!nofollowEnforcedByKernel && isSymlink(absolute)) return 'refused';
  try {
    // O_RDWR also refuses a DIRECTORY outright (EISDIR), and reading and
    // writing through one fd guarantees the bytes we rewrite are the bytes we
    // read — the path cannot be swapped underneath us between the two.
    //
    // O_NONBLOCK IS THE ONE FLAG THAT WAS MISSING, and the round that added it
    // also had to correct the reason the census carried for this line. That row
    // said the open "blocks BEFORE the fstat guard, so the fd rule does not
    // reach it", and that is FALSE on this pair of flags: DRIVEN, `O_RDWR` opens
    // a FIFO in 0 ms on Darwin (the round-3 peer measured 76 ms end to end) and
    // O_NOFOLLOW ELOOPs the symlink, so neither shape could block here. The
    // reason was over-cautious in the safe direction, which still costs — a
    // wrong reason sends the next round at a non-defect. What O_NONBLOCK buys is
    // not a fix for a live hang but the PROOF: the census decides boundedness
    // from the flags, and the flags now say it. POSIX leaves O_RDWR on a FIFO
    // undefined and this tree ships on three platforms; a proof that depends on
    // a platform's undefined behaviour is not one.
    return fs.openSync(absolute, fs.constants.O_RDWR | O_NOFOLLOW | (fs.constants.O_NONBLOCK || 0));
  } catch (error) {
    // ELOOP (a symlink, refused by O_NOFOLLOW), EISDIR, EACCES, … all mean
    // "not ours to rewrite". Only a genuinely absent path may be created.
    return (error as NodeJS.ErrnoException).code === 'ENOENT' ? 'absent' : 'refused';
  }
}

function createGitignore(absolute: string, content: string): boolean {
  try {
    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    // O_EXCL: if ANYTHING materialized at this path since the open above —
    // including a symlink planted deliberately — creation fails rather than
    // writing through it, and the next call converges the real file.
    const fd = fs.openSync(
      absolute,
      fs.constants.O_WRONLY | fs.constants.O_CREAT | fs.constants.O_EXCL | O_NOFOLLOW,
    );
    try {
      writeAll(fd, Buffer.from(content, 'utf8'));
    } finally {
      fs.closeSync(fd);
    }
    return true;
  } catch {
    return false; // best effort — never blocks the caller
  }
}

// ── greenfield: EVIDENCE on disk, never a caller's guess ────────────────────
//
// `greenfieldEvidence` and `hasCommittedHistory` moved to
// shared/greenfield-evidence.ts once a second consumer needed the same veto (the
// same reason the symlink primitives moved to shared/fs-nofollow.ts). Their
// semantics — walks UP to the owning repo, fails toward "has history", no
// subprocess, veto only — are documented there and are what the two arms below
// depend on.

/**
 * The `.gitignore` bytes the PROJECT wrote: everything outside Traffic One's own
 * managed region, with a legacy unmarked seed treated as ours too.
 *
 * Exists because `greenfieldEvidence`'s first arm is self-poisoning for any
 * consumer that runs after materialization. Materialization converges
 * `.gitignore` on every SessionStart, long before a build delegates or compiles,
 * so by then EVERY project — including a genuinely greenfield one — has
 * `.gitignore` content, and the raw file would answer "not greenfield" for all
 * of them. What the predicate actually wants to know is whether the project
 * itself ever stated anything about git; Traffic One's own block is not the
 * project stating anything.
 *
 * BOUNDED (shared/bounded-read.ts), and `null` IS THE POINT OF THE THIRD ARM
 * rather than tidiness about types. The bare `fs.readFileSync` this replaces
 * hung on a committed `.gitignore -> /dev/zero`: SIGKILL at 12 070 ms (round-1
 * peer) and at 12 090 ms re-driven here against a byte-verified copy carrying
 * the bare read, versus `null` in 161 ms after (load 3.34 → 3.52 of 10 cpus)
 * — and the obvious repair, folding a shape we cannot read into the `''` the
 * `catch` already returns, would have been WORSE than the hang it removes.
 * `greenfieldEvidence` answers TRUE on empty bytes, so `''` means "the project
 * has stated nothing about git", and the one production consumer spends that
 * answer on `ensureInitialCommit({ initIfNeeded: true })` — `git init`, `add -A`
 * and a commit authored as Traffic One over a working tree whose `.gitignore` we
 * could not see, which is precisely the misclassification that caller's own
 * comment says it added the disk veto to prevent.
 *
 * So the three outcomes the bounded reader distinguishes are kept distinct here:
 *   absent      `''` — no `.gitignore` is a project that genuinely stated
 *                      nothing, and this is the greenfield case the predicate
 *                      exists to recognise.
 *   text        the owner bytes, exactly as before.
 *   unreadable  `null` — something IS there and we cannot see it, so the project
 *                      may well have spoken. Every caller must fail toward NOT
 *                      greenfield.
 *
 * That last arm is what makes `greenfieldEvidence`'s own docblock TRUE. It has
 * claimed since it was written that "both [arms] fail toward not greenfield when
 * they cannot be read", and for this arm that was FALSE: a directory or a
 * mode-000 `.gitignore` reached the `catch` and came back as `''`, i.e. as
 * greenfield. The recorded claim is left where it is and this note says what the
 * behaviour under it used to be.
 */
export function projectOwnedGitignore(projectRoot: string): string | null {
  const read = readRegularFileResult(path.join(projectRoot, '.gitignore'));
  if (read.kind === 'absent') return '';
  if (read.kind === 'unreadable') return null;
  const existing = read.text;
  const rawLines = linesKeepingTerminators(existing);
  const scan = scanManagedRegion(rawLines);
  // A malformed pair means a human edited our delimiters: every byte is theirs
  // to account for, which is the conservative answer here as it is for the
  // writer (`nextGitignoreContent` refuses).
  if (scan.kind === 'present') {
    return rawLines.slice(0, scan.start).join('') + rawLines.slice(scan.end + 1).join('');
  }
  const legacy = scan.kind === 'absent' ? findLegacyBodySpan(existing) : null;
  return legacy ? legacy.before + legacy.after : existing;
}

/**
 * The scope a block being CREATED starts life with.
 *
 * `newProject` is NECESSARY and no longer SUFFICIENT: it can only ever narrow.
 * The caller's flag is a guess about history — `materializeProjectAssets`
 * derives it from `state.mode`, which `detectMode` fills by counting source
 * files — and a guess must not be able to hand an existing repository Traffic
 * One's build-output opinions. So `full` requires the flag AND positive
 * evidence, and the evidence acts purely as a veto: it never widens a block the
 * caller did not ask to widen, which is what keeps an established
 * `scope=traffic-one` project from acquiring opinions it was never given.
 */
function createdBlockScope(
  projectRoot: string,
  existing: string,
  newProject: boolean | undefined,
): GitignoreScope {
  return newProject && greenfieldEvidence(projectRoot, existing) ? 'full' : 'traffic-one';
}

/**
 * Idempotently converge `<projectRoot>/.gitignore` on the Traffic One block.
 *
 * Two bodies exist. A greenfield project — one Traffic One is scaffolding, with
 * no history and no opinion of its own yet — carries the full
 * SKIP_DIRS-derived `GITIGNORE_BODY`. Every existing repository gets ONLY
 * `TRAFFIC_ONE_BLOCK_BODY`, because deciding that someone else's `vendor/`,
 * `dist/` or `target/` is safe to ignore is not ours to make.
 *
 * A block being CREATED gets the full body only when `newProject` asks for it
 * AND the project's own disk state proves greenfield (`createdBlockScope` /
 * `greenfieldEvidence`); `newProject` alone cannot, because it is a guess about
 * history that reads `new-project` for any repository with five or fewer files
 * in `SOURCE_EXTS`. Refreshing a block that already exists reads its scope out
 * of the FILE (see `GitignoreScope`), so no later call — including one whose
 * `state.mode` was re-derived by `onboarding/repair.ts` into
 * `existing-codebase` — can narrow an established full block and delete ignore
 * rules the project has been relying on.
 *
 * Owner content outside the marker pair is never reordered, deduped, or
 * rewritten, a malformed marker pair is refused rather than repaired, and a
 * symlinked or non-regular path is never written at all. Returns true iff the
 * file changed.
 *
 * The one production trigger is `materializeProjectAssets` (runs for every
 * mode, guarded on Traffic One consent there) — this function itself performs
 * no consent check, so any future caller must gate the same way.
 */
export function ensureProjectGitignore(projectRoot: string, opts: { newProject?: boolean } = {}): boolean {
  const absolute = path.join(projectRoot, '.gitignore');
  const opened = openGitignoreForUpdate(absolute);
  if (opened === 'refused') return false;
  if (opened === 'absent') {
    return createGitignore(absolute, gitignoreBlock(createdBlockScope(projectRoot, '', opts.newProject)));
  }
  try {
    // A directory already failed the open; this additionally refuses a fifo or
    // device node, which must never be truncated and rewritten.
    if (!fs.fstatSync(opened).isFile()) return false;
    const existing = fs.readFileSync(opened, 'utf8');
    // Lazily: a refresh reads its scope off the file and must not pay for the
    // walk up the filesystem the evidence check performs.
    const next = nextGitignoreContent(
      existing,
      () => createdBlockScope(projectRoot, existing, opts.newProject),
    );
    if (next === null || next === existing) return false;
    const payload = Buffer.from(next, 'utf8');
    fs.ftruncateSync(opened, 0);
    writeAll(opened, payload);
    return true;
  } catch {
    return false; // best effort — never blocks the caller
  } finally {
    try { fs.closeSync(opened); } catch { /* the fd is going away regardless */ }
  }
}

export function scaffoldFileContent(
  relPath: string,
  profile?: CapabilityProfileV1,
): string | null {
  const base = relPath.replace(/\\/g, '/').split('/').pop() || '';
  if (base === '.gitignore') return GITIGNORE_BODY;
  if (base === '.prettierignore') return PRETTIERIGNORE_BODY;
  if (base === '.env.example') return envExampleBody(profile);
  if (base === '.prettierrc') return PRETTIERRC_BODY;
  if (base === 'index.html') return INDEX_HTML_BODY;
  if (base === 'eslint.config.js') return eslintConfigBody(profile);
  if (base === '.stylelintrc.json') return STYLELINTRC_BODY;
  if (base === 'ruff.toml') return RUFF_TOML_BODY;
  if (base === '.golangci.yml') return GOLANGCI_BODY;
  if (base === 'pint.json') return PINT_BODY;
  if (base === 'rustfmt.toml') return RUSTFMT_BODY;
  return null;
}

/**
 * The scaffold bodies that are an opinion about someone else's REPOSITORY rather
 * than about the toolchain this run compiles — every one of them a file its tool
 * DISCOVERS automatically, so its mere presence changes how the project's own
 * lint/format commands behave:
 *
 *   - `eslint.config.js` — ESLint 9 prefers flat config over `.eslintrc*`, so
 *     this file does not extend a repo's lint setup, it REPLACES it, and hands it
 *     a `max-lines: 400` error cap it never agreed to.
 *   - `.prettierrc` (singleQuote, printWidth 80) and `.prettierignore` — the next
 *     `prettier --write .`, which the seeded `package.json` adds as `format`,
 *     reformats every file in the repository to those opinions.
 *   - `ruff.toml` / `.golangci.yml` / `pint.json` / `rustfmt.toml` /
 *     `.stylelintrc.json` — same shape per toolchain, and `ruff.toml` in
 *     particular OUTRANKS a project's `pyproject.toml [tool.ruff]` section.
 *
 * They reach a project only under compile.ts's `isNewProject`, which is
 * `state.mode === 'new-project'` — the guess. Which of them a given project may
 * receive is decided per toolchain SLOT by convention-evidence.ts, from facts on
 * disk; `.gitignore` is not one of them, because its own two-armed authority
 * lives in greenfield-evidence.ts.
 */
const CONVENTION_BASENAMES = new Set<string>(Object.keys(CONVENTION_SLOT_BY_BASENAME));

/**
 * The node tooling cluster and the manifest that makes it run. All of them come
 * out of one `nodeToolingScaffoldOutputs` call rooted at that manifest, and the
 * manifest is the only place their devDependencies and `lint`/`format` scripts
 * live — so the two sides seed together or not at all. Seeding the manifest alone
 * installs a toolchain for a config that is not there; seeding a config alone
 * leaves an `eslint.config.js` importing plugins nobody installed, and
 * rules/common/quality-tooling.md says it plainly: "a config with no installed
 * tool and no script is inert".
 *
 * This cluster ALSO keeps the committed-history arm, where the toolchain-quality
 * configs below have given it up. Not an oversight — the hazard here is the one
 * intrinsic evidence cannot see. `packageJsonBody` adds `format: prettier --write
 * .`, and prettier has a parser for `.md`, `.yml`, `.json`, `.html` and `.css`,
 * so the first `npm run format` rewrites files in EVERY language, including a
 * repository that holds not one line of JavaScript. A per-slot source arm is
 * language-scoped by construction and reads the `main.tf`-plus-a-commit shape
 * that greenfield-evidence.ts was written for — a Terraform stack, a dbt project,
 * a docs site — as empty. `ruff check .` cannot rewrite a file and cannot see a
 * language it does not parse, which is what makes the intrinsic arms sufficient
 * there and insufficient here.
 */
const NODE_TOOLING_SLOTS = new Set<ConventionSlot>(['js-lint', 'js-format', 'css-lint']);

function conventionSlotOf(rel: string): ConventionSlot | null {
  return CONVENTION_SLOT_BY_BASENAME[rel.split('/').pop() || ''] ?? null;
}

// `seedIfBlank`'s own precondition, asked WITHOUT writing: a file that is absent
// or blank is one this function may fill.
function blankOrMissing(projectRoot: string, rel: string): boolean {
  try {
    return readRegularFileOrThrow(path.join(projectRoot, rel)).trim().length === 0;
  } catch {
    return true;
  }
}

export interface ScaffoldContentOptions {
  /**
   * The full compiled contract. When present AND `newProject` is true, every
   * compiled UI module additionally receives a compliant skeleton at its
   * DEFAULT output path (same missing-or-blank rule — see skeletons.ts), and
   * each skeleton's TODO catalog keys are seeded into every declared locale.
   */
  compiled?: CompiledArchitectureV1;
  /**
   * Greenfield guard, mirroring the compiler's own `isNewProject` scaffold
   * condition: module skeletons are emitted only on `new-project` runs, never
   * into an existing codebase.
   */
  newProject?: boolean;
}

/**
 * Seed canonical content for scaffold outputs that exist as empty files or do
 * not exist at all. Returns the relative paths that were written. Non-empty
 * files are never touched — agents may extend them (e.g. append more env
 * vars) without the runtime fighting back.
 *
 * `package.json` is seeded for exactly ONE output: the manifest at the eslint
 * tooling root, whose devDependencies must match the plugins the compiled
 * `eslint.config.js` imports. Every other manifest stays agent-authored.
 */
export function ensureScaffoldContent(
  projectRoot: string,
  scaffoldOutputs: ReadonlyArray<{ path: string }>,
  profile?: CapabilityProfileV1,
  options?: ScaffoldContentOptions,
): string[] {
  const normalized = (value: string): string => value.replace(/\\/g, '/');
  const eslintConfig = scaffoldOutputs.find((output) => (
    normalized(output.path).split('/').pop() === 'eslint.config.js'
  ));
  const toolingRoot = eslintConfig ? path.posix.dirname(normalized(eslintConfig.path)) : null;
  const toolingManifest = toolingRoot === null
    ? null
    : toolingRoot === '.' ? 'package.json' : `${toolingRoot}/package.json`;
  const written: string[] = [];
  // `.gitignore` keeps this arm because `greenfieldEvidence`'s two arms are
  // exactly `seedIfBlank` (no project-owned content) plus this one — git never
  // untracks what is already committed, so a commit is the thing an ignore rule
  // can silently shadow. The node tooling cluster keeps it for the repo-wide
  // formatter reason in NODE_TOOLING_SLOTS.
  let history: boolean | null = null;
  const projectAlreadyHasHistory = (): boolean => {
    if (history === null) history = hasCommittedHistory(projectRoot);
    return history;
  };
  // No node slot's verdict can change the outcome once the cluster is out (its
  // gate below starts with this same question), and each one costs a source-tree
  // walk of the whole project — the dominant cost of this function on a large
  // repository, and this runs inside the PLAN_READY transaction. On a 3,001-file
  // non-JS repository with history the skip is ~16x on the median and ~24x on
  // the minimums, where scheduler noise is lowest.
  //
  // Skipping them leaves the outputs byte-identical: `nodeSlotsAccept` folds an
  // empty list to `true` and is ANDed with this flag anyway, and the loop's own
  // lookup misses, reads `false`, and withholds exactly what the cluster gate
  // would have. Verified as tree hashes over every covered project shape, not
  // just as an argument.
  const nodeClusterPossible = !projectAlreadyHasHistory();
  // EVERY verdict is resolved BEFORE the first write, and that ordering is the
  // correctness of this function, not a convenience — arm A of the slot rule
  // reads the filesystem, and the filesystem is what this loop is about to
  // change.
  //
  // The load-bearing case is the CLUSTER GATE below, and it is a starvation
  // rather than a poisoning: `nodeSlotsAccept` folds over every node slot's
  // verdict to decide the tooling manifest, and that manifest is scaffold output
  // 0 while the configs it folds are outputs 50 (`.prettierrc`), 51
  // (`.prettierignore`), 53 (`eslint.config.js`) and 54 (`.stylelintrc.json`).
  // Resolve at the point of use instead and the fold runs over an empty map,
  // `every` is vacuously true, and the manifest is seeded for a cluster the loop
  // then withholds one config at a time. Measured on a react compile over a tree
  // that already holds `.js` source: 9 files written eagerly, 11 lazily — a
  // `package.json` installing eslint and prettier plus a `.stylelintrc.json`
  // beside it, for configs that never arrive.
  //
  // A second route is closed in convention-evidence.ts, and this guard
  // deliberately does not depend on that staying so: `packageJsonBody` seeds
  // `prettier`, `stylelint` and `eslint` as devDependencies, so any manifest
  // pattern loose enough to match a NESTED key reads our own output 0 back as
  // the project declaring three slots. `topLevelManifestKey` anchors on the
  // indent so it does not; against the pattern that preceded it, lazy resolution
  // also dropped `.prettierrc`, `.prettierignore` and `.stylelintrc.json` from a
  // clean greenfield compile (14 written, 11).
  //
  // NOT a route, though it reads like one: a slot-mate. `.prettierrc` and
  // `.prettierignore` are both js-format, but this memo is keyed by (slot,
  // directory), so the second reuses the first's verdict whether resolution is
  // eager or lazy. Only the two routes above turn on the ordering.
  //
  // All of it fails silently — the seed is never written, or it is written
  // without the toolchain that makes it run.
  const slotVerdicts = new Map<string, boolean>();
  for (const output of scaffoldOutputs) {
    const rel = normalized(output.path);
    const slot = conventionSlotOf(rel);
    if (!slot) continue;
    if (NODE_TOOLING_SLOTS.has(slot) && !nodeClusterPossible) continue;
    const dir = path.posix.dirname(rel);
    const key = `${slot}\n${dir}`;
    if (!slotVerdicts.has(key)) {
      slotVerdicts.set(
        key,
        slotAcceptsScaffold(projectRoot, path.resolve(projectRoot, dir), slot),
      );
    }
  }
  // The coupling, in both directions (see NODE_TOOLING_SLOTS): the cluster lands
  // only when its manifest can be filled too, and the manifest lands only when
  // every config it installs a tool for is landing with it. A compiled cluster
  // always has a manifest; when there is none in the outputs at all there is no
  // toolchain to be out of step with, so the coupling has nothing to say.
  const nodeSlotsAccept = nodeClusterPossible
    && [...slotVerdicts]
      .filter(([key]) => NODE_TOOLING_SLOTS.has(key.split('\n')[0] as ConventionSlot))
      .every(([, accepts]) => accepts);
  const nodeClusterSeeds = nodeSlotsAccept
    && (toolingManifest === null || blankOrMissing(projectRoot, toolingManifest));
  for (const output of scaffoldOutputs) {
    const rel = normalized(output.path);
    const isToolingManifest = rel === toolingManifest;
    const body = isToolingManifest
      ? packageJsonBody(profile)
      : scaffoldFileContent(output.path, profile);
    if (!body) continue;
    if (rel.split('/').pop() === '.gitignore') {
      if (projectAlreadyHasHistory()) continue;
    } else if (isToolingManifest) {
      if (!nodeSlotsAccept) continue;
    } else if (CONVENTION_BASENAMES.has(rel.split('/').pop() || '')) {
      const slot = conventionSlotOf(rel) as ConventionSlot;
      const accepts = slotVerdicts.get(`${slot}\n${path.posix.dirname(rel)}`) === true;
      if (!accepts) continue;
      if (NODE_TOOLING_SLOTS.has(slot) && !nodeClusterSeeds) continue;
    }
    if (seedIfBlank(projectRoot, output.path, body)) written.push(output.path);
  }
  if (options?.newProject && options.compiled) {
    written.push(...ensureModuleSkeletons(projectRoot, options.compiled));
  }
  return written;
}

// Write one file under the missing-or-blank rule shared with the scaffold loop
// above. Returns true when the body reached disk.
function seedIfBlank(projectRoot: string, rel: string, body: string): boolean {
  const absolute = path.join(projectRoot, rel);
  try {
    if (fs.existsSync(absolute)) {
      const current = readRegularFileOrThrow(absolute);
      if (current.trim().length > 0) return false;
    } else {
      fs.mkdirSync(path.dirname(absolute), { recursive: true });
    }
    fs.writeFileSync(absolute, body);
    return true;
  } catch {
    return false; // best effort — the completion gates still name the gap
  }
}

/**
 * Materialize the compliant skeleton of every compiled UI module (and the
 * typed empty export of every service/store) at its DEFAULT output path, then
 * seed each skeleton's catalog keys into every declared locale. Greenfield
 * only (the caller guards on mode), and strictly missing-or-blank: a non-empty
 * agent-authored module is never touched, and only skeletons that were
 * actually WRITTEN in this call contribute seed references — keys for content
 * an agent already replaced would be unreferenced catalog entries.
 */
function ensureModuleSkeletons(
  projectRoot: string,
  compiled: CompiledArchitectureV1,
): string[] {
  const written: string[] = [];
  const references: ModuleSkeletonReferenceV1[] = [];
  for (const module of compiled.modules) {
    const skeleton = moduleSkeleton(compiled, module);
    if (!skeleton) continue;
    if (seedIfBlank(projectRoot, module.output, skeleton.content)) {
      written.push(module.output);
      references.push(...skeleton.references);
    }
  }
  const i18n = compiled.i18n;
  if (i18n && references.length > 0) {
    // The seeding helper only writes into catalogs that exist and parse; on a
    // greenfield tree the declared JSON catalogs do not exist yet, so every
    // catalog a skeleton key lands in is born as an empty object first (the
    // catalogs are compiled scaffold outputs, and the same missing-or-blank
    // rule applies).
    for (const reference of references) {
      for (const locale of i18n.locales) {
        const catalog = i18n.catalogs.find((candidate) => (
          candidate.format === 'json'
          && candidate.locales.includes(locale)
          && candidate.namespaces.includes(reference.namespace)
        ));
        if (catalog && seedIfBlank(projectRoot, catalog.path, '{}\n')) {
          written.push(catalog.path);
        }
      }
    }
    seedI18nCatalogKeys(projectRoot, i18n, references);
  }
  return written;
}
