// src/shared/architecture-contract/scaffold-content.ts
// Canonical bodies for scaffold files whose CONTENT is runtime knowledge, not
// a design decision.
//
// The compiler only ever emitted scaffold PATHS; the required `.prettierignore`
// entries lived exclusively in rules prose, so a run shipped the file empty
// and the implementer burned four turns discovering `.traffic-one`,
// `pnpm-lock.yaml`, and `.turbo` serially through formatter failures
// (observed 8co). Same story for `.env.example`: the crawl-origin gate names
// `VITE_SITE_URL` but nothing ever wrote the variable anywhere an agent could
// legally source it from.
//
// Deterministic and idempotent: content is seeded ONLY when the file is
// missing or blank; a non-empty agent-authored file is never overwritten.

import * as fs from 'fs';
import * as path from 'path';

// Mirror of the baseline scan-skip + lockfile knowledge in
// `architecture-contract/baseline.ts` (isScanSkippedPath / LOCKFILE): what the
// verifier refuses to scan, the formatter must not check either.
const PRETTIERIGNORE_BODY = [
  '# generated by traffic-one — formatter must skip what the verifier skips',
  'node_modules/',
  'dist/',
  'build/',
  'coverage/',
  'out/',
  '.next/',
  '.turbo/',
  '.vite/',
  '.traffic-one/',
  'pnpm-lock.yaml',
  'package-lock.json',
  'yarn.lock',
  'bun.lockb',
  'composer.lock',
  '*.min.*',
  '*.tsbuildinfo',
  '',
].join('\n');

const ENV_EXAMPLE_BODY = [
  '# generated by traffic-one — copy to .env and fill in real values',
  '# Public production origin. Crawl assets (sitemap.xml, robots.txt) and',
  '# canonical URLs MUST be generated from this value; generation must fail',
  '# when it is unset instead of inventing localhost or a placeholder domain.',
  'VITE_SITE_URL=',
  '',
].join('\n');

export function scaffoldFileContent(relPath: string): string | null {
  const base = relPath.replace(/\\/g, '/').split('/').pop() || '';
  if (base === '.prettierignore') return PRETTIERIGNORE_BODY;
  if (base === '.env.example') return ENV_EXAMPLE_BODY;
  return null;
}

/**
 * Seed canonical content for scaffold outputs that exist as empty files or do
 * not exist at all. Returns the relative paths that were written. Non-empty
 * files are never touched — agents may extend them (e.g. append more env
 * vars) without the runtime fighting back.
 */
export function ensureScaffoldContent(
  projectRoot: string,
  scaffoldOutputs: ReadonlyArray<{ path: string }>,
): string[] {
  const written: string[] = [];
  for (const output of scaffoldOutputs) {
    const body = scaffoldFileContent(output.path);
    if (!body) continue;
    const absolute = path.join(projectRoot, output.path);
    try {
      if (fs.existsSync(absolute)) {
        const current = fs.readFileSync(absolute, 'utf8');
        if (current.trim().length > 0) continue;
      } else {
        fs.mkdirSync(path.dirname(absolute), { recursive: true });
      }
      fs.writeFileSync(absolute, body);
      written.push(output.path);
    } catch {
      // Best effort — the format-coverage gate still names the missing entries.
    }
  }
  return written;
}
