// tests/replay-corpus/cases/plan-guard.cases.ts
// plan-guard module: plan-write (20), scaffold-gate (22, Windsurf/Devin only),
// supabase-local (24), deploy (25) and library-allowlist (30). The static half
// of plan-write has its own file (plan-static.cases.ts).
//
// All of these run AFTER onboarding-gate (priority 10), so every case here uses
// a preseeded, MATERIALIZED fixture — never freshProject/undecidedProject.
// Materialized matters as much as onboarded: onboarding-gate's own inline
// convergence denies `repaired-materialization` for any mutating call on an
// unmaterialized project, which is precisely how all ten original cases in this
// file ended up characterizing onboarding-gate instead of plan-guard.

import type { CaseSpec } from '../run-case';
import {
  deployStamped,
  existingCodebase,
  greenfieldNoPlan,
  greenfieldMainAgent,
  resetRecordedMainAgent,
  scaffoldedGreenfield,
  scaffoldedMainAgent,
} from '../fixtures';

export const PLAN_GUARD_CASES: CaseSpec[] = [
  {
    id: 'plan-guard.reset-record-erased-by-shell',
    notes: 'rm -f on the project\'s reset record -> reset-record-owner-gate. The record prices the next reset and carries the per-successor terminal-role obligation, so erasing it rolls the ladder back to free and admits a spawn whose model is exhausted; it has ONE writer and it is the runner, never an agent. The fixture must have really reset (the fence returns early unless the record exists), which is why this is the only case on resetRecordedMainAgent. Paired with the read below deliberately: this gate is the one shell scan in plan-write whose polarity is INVERTED — it refuses every verb that is not a known read — so a corpus row proving the refusal is worth little without one proving reads still work',
    host: 'claude',
    event: 'PreToolUse',
    project: resetRecordedMainAgent,
    expectGate: 'plan-guard.write',
    tool: { class: 'shell', rawName: 'Bash', command: 'rm -f .traffic-one/runs/.resets.json' },
  },
  {
    id: 'plan-guard.reset-record-read-allowed',
    notes: 'Control case, and the one that makes the fail-closed polarity above affordable: an agent may LOOK at the record. Same fixture, same path, a read verb -> allow. If a future narrowing of the read allowlist starts refusing plain `cat`, this row reds instead of the cost landing on a user who only wanted to see why their reset was priced',
    host: 'claude',
    event: 'PreToolUse',
    project: resetRecordedMainAgent,
    expectGate: null,
    tool: { class: 'shell', rawName: 'Bash', command: 'cat .traffic-one/runs/.resets.json' },
  },
  {
    id: 'plan-guard.library-allowlist-forbidden-next',
    notes: 'npm add next flips what the framework detector reports about this project, while the run\'s compiled architecture and verification contracts stay frozen against react-vite -> library-allowlist-forbidden. This row moved off `npm add mobx`: the table split into a BLOCKING half (installs that make the frozen contracts false) and an ADVISORY half (installs that merely diverge from the prescribed stack), and mobx is now the second — see the -mobx row below, which pins the advice. Only the blocking half can characterize a deny id, so this is the row that keeps library-allowlist-forbidden reachable',
    host: 'claude',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: 'plan-guard.library',
    tool: { class: 'shell', rawName: 'Bash', command: 'npm add next' },
  },
  {
    id: 'plan-guard.library-allowlist-advised-mobx',
    notes: 'The advisory half, and the reason the row above had to move. `npm add mobx` conflicts with the seeded web stack but breaks nothing the run compiled, so the install PROCEEDS and the advice rides along on the same command -> `allow`, no deny id (a PreToolUse gate that only attaches context is an allow decision here; the context itself is pinned by plan-guard.test.ts). Seeded: mark the mobx row `blocking` in forbidden.ts and this row becomes deny plan-guard.library/library-allowlist-forbidden',
    host: 'claude',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: null,
    tool: { class: 'shell', rawName: 'Bash', command: 'npm add mobx' },
  },
  {
    id: 'plan-guard.library-allowlist-allowed-redux',
    notes: 'Control case: installing an on-allowlist state library is not denied',
    host: 'claude',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: null,
    tool: { class: 'shell', rawName: 'Bash', command: 'npm add @reduxjs/toolkit' },
  },
  {
    id: 'plan-guard.feature-source-write-before-plan',
    notes: 'Writing feature source before .traffic-one/plan.md exists -> plan-write missing-plan violation. Path is apps/web/src/... (the monorepo layout stack=default requires), not root src/...: a root-level Vite path ALSO trips the separate monorepo-root-vite violation, which would obscure which one this case means to characterize',
    host: 'claude',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: 'plan-guard.write',
    tool: { class: 'file-write', rawName: 'Write', filePath: 'apps/web/src/components/Widget.tsx', content: 'export default function Widget() { return null; }\n' },
  },
  {
    id: 'plan-guard.readme-write-allowed-without-plan',
    notes: 'Control case: README is explicitly exempted from the plan-missing gate even before plan.md exists',
    host: 'claude',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: null,
    tool: { class: 'file-write', rawName: 'Write', filePath: 'README.md', content: '# Fixture project\n' },
  },
  {
    id: 'plan-guard.apply-patch-invalid-payload',
    notes: 'A structurally invalid apply_patch body is denied before any readiness/static check runs',
    host: 'codex',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: 'session.workspace-boundary',
    tool: { class: 'file-edit', rawName: 'apply_patch', patchText: 'not a real *** Begin Patch envelope' },
  },
  {
    id: 'plan-guard.scaffold-stack-gate-windsurf-nextjs',
    notes: 'Windsurf/Devin only: create-next-app conflicts with the seeded react-vite frontend -> scaffold-stack-gate',
    host: 'windsurf',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: 'plan-guard.scaffold',
    tool: { class: 'shell', rawName: 'run_command', command: 'npx create-next-app@latest my-app' },
  },
  {
    id: 'plan-guard.scaffold-plan-gate-windsurf-subagents',
    notes: 'Windsurf/Devin, on-stack scaffolder, subagents team mode, no plan.md yet -> scaffold-plan-gate',
    host: 'windsurf',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: 'plan-guard.scaffold',
    tool: { class: 'shell', rawName: 'run_command', command: 'npx create-remix@latest my-app' },
  },
  {
    id: 'plan-guard.scaffold-main-agent-plan-gate-windsurf',
    notes: 'Same scaffolder, but the fixture is seeded with team.mode=main-agent -> scaffold-main-agent-plan-gate',
    host: 'windsurf',
    event: 'PreToolUse',
    project: greenfieldMainAgent,
    expectGate: 'plan-guard.scaffold',
    tool: { class: 'shell', rawName: 'run_command', command: 'npx create-remix@latest my-app' },
  },
  {
    id: 'plan-guard.scaffold-gate-noop-other-hosts',
    notes: 'Control case: the scaffold-gate is Windsurf/Devin-only; the identical command is a noop on Claude',
    host: 'claude',
    event: 'PreToolUse',
    project: greenfieldNoPlan,
    expectGate: null,
    tool: { class: 'shell', rawName: 'Bash', command: 'npx create-next-app@latest my-app' },
  },
  {
    id: 'plan-guard.scaffolded-greenfield-edit-allowed',
    notes: 'Control case: once plan.md + src assets exist, an ordinary in-stack edit is not denied by plan-guard. Path is apps/web/src/App.tsx (the monorepo layout stack=default requires — see scaffoldedGreenfield); old_string/new_string (not just `content`) is required too: plan-write reconstructs the post-edit file from Claude\'s real Edit shape and denies plan-write-struct-scan-incomplete without it — old_string here matches the fixture\'s literal App.tsx content, one exact occurrence',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedGreenfield,
    expectGate: null,
    tool: { class: 'file-edit', rawName: 'Edit', filePath: 'apps/web/src/App.tsx' },
    raw: { tool_input: { file_path: 'apps/web/src/App.tsx', old_string: 'return null;', new_string: 'return <div />;' } },
  },
  {
    id: 'plan-guard.struct-scan-incomplete',
    notes: 'The other half of the case above: an Edit on a web-profile source file with NO reconstructable old_string/new_string pair cannot be judged, so plan-write refuses rather than scanning a file it cannot rebuild -> plan-write-struct-scan-incomplete',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: 'plan-guard.write',
    tool: { class: 'file-edit', rawName: 'Edit', filePath: 'apps/web/src/App.tsx' },
  },
  {
    id: 'plan-guard.monorepo-root-vite',
    notes: 'stack=default in new-project mode is the Turborepo layout, so a root-level src/** Vite file is denied unconditionally (monorepo-root-vite) — the readiness violation every path in plan-static.cases.ts is deliberately shaped to avoid',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: 'plan-guard.write',
    tool: { class: 'file-write', rawName: 'Write', filePath: 'src/main.tsx', content: 'export const main = () => null;\n' },
  },
  {
    id: 'plan-guard.state-mode-downgrade',
    notes: 'Rewriting a CONFIRMED new-project state file to an existing-* mode would disarm every stack/layout/library gate in one write -> state-mode-downgrade. onboarding-gate releases writes to the canonical state file (the model is allowed to repair it), so plan-write is the gate that owns this',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: 'plan-guard.write',
    tool: {
      class: 'file-write',
      rawName: 'Write',
      filePath: '.traffic-one/.one.json',
      content: '{"version":1,"mode":"existing-codebase","confirmed":true,"onboardingComplete":true}',
    },
  },
  {
    id: 'plan-guard.registry-probe-gate',
    notes: 'Querying the npm registry to pick versions during new-project setup -> registry-probe-gate (versions come from the active stack contract; installs resolve inside the pinned ranges and stay allowed)',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: 'plan-guard.write',
    tool: { class: 'shell', rawName: 'Bash', command: 'npm view typescript versions' },
  },
  {
    id: 'plan-guard.supabase-local-stack-gate',
    notes: 'The onboarded backend is Supabase and Traffic One\'s Supabase flow is platform-connected, so booting the LOCAL stack is denied -> supabase-local-stack-gate. Uses the existing-codebase fixture because that is the seeded backend:supabase project; the gate is scoped to exactly that state and leaves other projects\' tooling alone',
    host: 'claude',
    event: 'PreToolUse',
    project: existingCodebase,
    expectGate: 'plan-guard.supabase-local',
    tool: { class: 'shell', rawName: 'Bash', command: 'supabase start' },
  },
  {
    id: 'plan-guard.supabase-local-non-supabase-backend-allowed',
    notes: 'Control case: the identical command on a project whose backend is not Supabase is not this gate\'s business',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: null,
    tool: { class: 'shell', rawName: 'Bash', command: 'supabase start' },
  },
  {
    id: 'plan-guard.deploy-shipper-approval-required',
    notes: 'A production publish with no fresh senior-shipper approval stamp -> deploy-gate-shipper-approval-required (the stamp grants a 10-minute window)',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: 'plan-guard.deploy',
    tool: { class: 'shell', rawName: 'Bash', command: 'vercel deploy --prod' },
  },
  {
    id: 'plan-guard.deploy-security-check-stale',
    notes: 'Second rung of the deploy ladder: shipper approval is fresh, but no security check has PASSED in the last 10 minutes -> deploy-gate-security-check-stale',
    host: 'claude',
    event: 'PreToolUse',
    project: (host) => deployStamped(host, 'approved'),
    expectGate: 'plan-guard.deploy',
    tool: { class: 'shell', rawName: 'Bash', command: 'vercel deploy --prod' },
  },
  {
    id: 'plan-guard.deploy-fingerprint-mismatch',
    notes: 'Third rung: approval fresh, security check fresh and passing, but its recorded fingerprint does not match the current worktree -> deploy-gate-fingerprint-mismatch. The fingerprint the gate computes is a sha256 of the tree, so the fixture stores a literal that cannot equal it — deterministic without depending on the fixture\'s actual hash',
    host: 'claude',
    event: 'PreToolUse',
    project: (host) => deployStamped(host, 'security-passed'),
    expectGate: 'plan-guard.deploy',
    tool: { class: 'shell', rawName: 'Bash', command: 'npm publish' },
  },
  {
    id: 'plan-guard.deploy-non-publishing-command-allowed',
    notes: 'Control case: DEPLOY_RE matches publishing commands only — a local build/preview of the same tool is untouched',
    host: 'claude',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: null,
    tool: { class: 'shell', rawName: 'Bash', command: 'vercel build' },
  },
  {
    id: 'plan-guard.run-id-mismatch-write',
    notes: 'A digest written under a fabricated ISO run id while currentRunId is a real minted id -> run-id-mismatch. The WRITE-side twin of agent-model.spawn-run-id-mismatch (same cause, different surface and id), and the pair is what keeps a retiering from collapsing them: the spawn deny self-heals a prompt, this one redirects a path. Two path choices are load-bearing: a DIGEST rather than `runs/<id>/assignments.json` (a runtime-owned artifact is refused by its owner gate first — see the case below), and content that does NOT claim PLAN_READY (that phrase turns the same write into the architect memory-baseline gate). Both of those run before the run-id check and only the FIRST violation of a call is reported',
    host: 'claude',
    event: 'PreToolUse',
    project: (host) => scaffoldedMainAgent(host, { currentRunId: 'replay-fixture-run' }),
    expectGate: 'plan-guard.write',
    tool: {
      class: 'file-write',
      rawName: 'Write',
      filePath: '.traffic-one/digests/2026-06-17T12-09-40Z/architect.md',
      content: '# Architect notes\n\nStill drafting the plan.\n',
    },
  },
  {
    id: 'plan-guard.runtime-assignments-owner-gate',
    notes: 'The same fabricated-id write aimed at a RUNTIME-owned artifact (`runs/<id>/assignments.json`) -> runtime-assignments-owner-gate. Kept next to the case above because the pair pins the ORDER of the two checks: ownership is decided before the run id, so a run-id fix can never be the remedy an agent is handed for a runtime-owned path',
    host: 'claude',
    event: 'PreToolUse',
    project: (host) => scaffoldedMainAgent(host, { currentRunId: 'replay-fixture-run' }),
    expectGate: 'plan-guard.write',
    tool: {
      class: 'file-write',
      rawName: 'Write',
      filePath: '.traffic-one/runs/2026-06-17T12-09-40Z/assignments.json',
      content: '{}\n',
    },
  },
  {
    id: 'plan-guard.opencode-external-temp-shell',
    notes: 'OpenCode/Kilo only: a model command writing scratch output under /tmp -> opencode-external-temp-shell. Host-gated on opencodeSelfHosted because the cause is those hosts\' external-directory permission prompt, which stalls the run',
    host: 'opencode',
    event: 'PreToolUse',
    project: scaffoldedMainAgent,
    expectGate: 'plan-guard.write',
    tool: { class: 'shell', rawName: 'bash', command: 'npm run build > /tmp/build.log 2>&1' },
  },
  {
    id: 'plan-guard.apply-patch-reconstruction-failed',
    notes: 'A Codex apply_patch whose envelope parses but whose context does not match the file on disk -> apply-patch-reconstruction-failed. Deliberately distinct from apply-patch-payload-invalid (characterized in session-guards): same tool, same gate, two ids, because the remedies differ — re-read the file and rebuild the hunks vs. fix the patch syntax',
    host: 'codex',
    event: 'PreToolUse',
    project: existingCodebase,
    expectGate: 'plan-guard.write',
    tool: {
      class: 'file-edit',
      rawName: 'apply_patch',
      patchText: '*** Begin Patch\n*** Update File: src/index.ts\n@@\n-export const nothing = false;\n+export const already = true;\n*** End Patch\n',
    },
  },
];
