// src/modules/plan-guard/__tests__/deny-target-offender.test.ts
// The plan-write aggregator's `denyTarget` must name a target that actually
// OFFENDED. It used to be `filePath` — the direct target, else
// `gateTargets[0]`, the patch's FIRST operation — so on a multi-file
// apply_patch the refusal's machine-readable subject was whichever file the
// agent happened to write first, which had usually violated nothing.
//
// Two readers depend on that subject and neither can recover it from anywhere
// else:
//   * `runs/<id>/debug/decisions.jsonl`, stamped by core/pipeline.ts, where
//     `denyTarget` is the only field naming WHICH file was refused; and
//   * the deny-repeat counter, which signs a refusal as `denyTarget` plus the
//     whole rendered reason (shared/state/deny-repeat.ts), so the subject
//     decides how refusals PARTITION into escalation buckets.
//
// Measured on the fixture below before the fix: a 3-operation patch whose first
// operation stayed constant while the agent cleared the offending files one at
// a time produced three refusals with an identical, path-free reason and an
// identical first operation. All three collapsed into ONE bucket and the third
// escalated — DENY_REPEAT_ESCALATE_AT is 3 — telling an agent that had just
// removed two of three violations to STOP RETRYING, about a file it had already
// fixed. That is the exact false positive deny-repeat.ts's header calls "worse
// than never firing it at all".

import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { planWriteGate } from '../plan-write';
import { runPipeline } from '../../../core/pipeline';
import { buildContext } from '../../../core/context';
import type { Ctx, Handler, HookInput, HostId, ToolClass } from '../../../core/types';
import { DENY_REPEAT_ESCALATE_AT } from '../../../shared/state/deny-repeat';
import { hostScopedPerformancePrefs } from '../../../test-support/host-prefs';

const TMP_PREFIX = 't1-denytarget-';
const RUN_ID = 'R';

// Attributed by PREFIX on teardown, not by a global temp count: other suites run
// concurrently, so only dirs this file created can be judged.
const dirs: string[] = [];
const savedEnv = {
  prefs: process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH,
  state: process.env.XDG_STATE_HOME,
  plan: process.env.TRAFFIC_ONE_USER_PLAN,
};

after(() => {
  if (savedEnv.prefs === undefined) delete process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  else process.env.TRAFFIC_ONE_PROJECT_PREFS_PATH = savedEnv.prefs;
  if (savedEnv.state === undefined) delete process.env.XDG_STATE_HOME;
  else process.env.XDG_STATE_HOME = savedEnv.state;
  if (savedEnv.plan === undefined) delete process.env.TRAFFIC_ONE_USER_PLAN;
  else process.env.TRAFFIC_ONE_USER_PLAN = savedEnv.plan;
  for (const dir of dirs) fs.rmSync(dir, { recursive: true, force: true });
  const leaked = fs.readdirSync(os.tmpdir()).filter((name) => name.startsWith(TMP_PREFIX));
  assert.deepEqual(leaked, [], `this file leaked temp dirs: ${leaked.join(', ')}`);
});

// A materialized new-project (stack=default) main-agent project: the shape
// `stateRequiresNewProjectMonorepo` recognises, which is what arms the
// path-keyed readiness rules used as the instrument below.
function project(
  stateExtra: Record<string, unknown> = {},
  team?: Record<string, unknown>,
): string {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), TMP_PREFIX)));
  dirs.push(dir);
  const env = process.env;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  env.XDG_STATE_HOME = path.join(dir, 'machine-state');
  env.TRAFFIC_ONE_USER_PLAN = 'pro';
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
  fs.writeFileSync(path.join(t1, 'plan.md'), 'plan', 'utf8');
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({
    mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
    onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none', ...stateExtra,
  }), 'utf8');
  // The team/performance pair lives in host-scoped PREFS, not in `.one.json` —
  // the same split materializedFixture in plan-write.test.ts makes.
  if (team) {
    fs.writeFileSync(env.TRAFFIC_ONE_PROJECT_PREFS_PATH, JSON.stringify(hostScopedPerformancePrefs(
      { level: team.mode === 'subagents' ? 'high' : 'low', source: 'prompted' }, team, 'pro',
    )), 'utf8');
  }
  return dir;
}

type File = readonly [path: string, body: string];

// A file that violates nothing: a named-export component outside every
// root-level path rule.
const clean = (name: string): File => [
  `apps/web/src/components/${name}.tsx`,
  `export const ${name} = () => null;`,
];
// A file that violates ONE readiness rule whose prose never names a path
// (`monorepo-root-flat-scaffold`, plan-readiness/index.ts). Path-free prose is
// what makes `denyTarget` the only discriminator: with several of these in one
// patch, `appendUnique` renders exactly one line however many files trip it.
const flatConfig = (name: string): File => [name, '{}'];
// A file that violates ONE static rule (`default-export`, plan-static.ts).
const defaultExport = (name: string): File => [
  `apps/web/src/components/${name}.tsx`,
  `export default function ${name}() { return null; }`,
];

function addPatch(files: readonly File[]): string {
  const lines = ['*** Begin Patch'];
  for (const [file, body] of files) {
    lines.push(`*** Add File: ${file}`);
    lines.push(`+${body}`);
  }
  lines.push('*** End Patch');
  return lines.join('\n');
}

function patchCtx(cwd: string, patchText: string, host: HostId = 'claude'): Ctx {
  const input: HookInput = {
    event: 'PreToolUse', host, cwd,
    raw: { tool_name: 'apply_patch', tool_input: { patchText } },
    tool: { class: 'file-edit' as ToolClass, rawName: 'apply_patch', patchText },
  };
  return { input, host, cwd, now: () => 'x' } as unknown as Ctx;
}

interface Verdict { denyTarget: string; reason: string; lines: string[] }

function refuse(cwd: string, files: readonly File[]): Verdict {
  const result = planWriteGate(patchCtx(cwd, addPatch(files)));
  assert.equal(result.kind, 'deny', `expected a deny for ${files.map(([f]) => f).join(', ')}`);
  if (result.kind !== 'deny') throw new Error('unreachable');
  return {
    denyTarget: String(result.denyTarget),
    reason: result.reason,
    lines: result.reason.split('\n').filter((line) => line.startsWith('  - ')),
  };
}

// ── the fix ──────────────────────────────────────────────────────────────────

test('a multi-file patch names the OFFENDING file, not the first operation', () => {
  const cwd = project();

  // The positive baseline first, because every claim below is a NEGATIVE ("the
  // subject is not the clean file") and a negative passes vacuously against an
  // input that never denied or never carried the clean file at all. So: this
  // patch really does contain three operations, the first two really are clean,
  // and it really is refused, for exactly one rule.
  const files = [clean('Alpha'), clean('Beta'), flatConfig('tsconfig.node.json')] as const;
  const verdict = refuse(cwd, files);
  assert.equal(files.length, 3, 'three operations are being judged');
  assert.equal(verdict.lines.length, 1, `one rule tripped, one line: ${verdict.lines.join(' | ')}`);
  assert.match(verdict.reason, /New-project monorepo gate: root-level TypeScript/,
    'and it is the flat-scaffold rule — the instrument this file measures with');
  for (const [file] of [files[0], files[1]]) {
    assert.equal(planWriteGate(patchCtx(cwd, addPatch([clean(path.basename(file, '.tsx'))]))).kind, 'noop',
      `${file} must violate nothing on its own, or the negative below proves nothing`);
  }

  assert.equal(verdict.denyTarget, 'tsconfig.node.json',
    'the refusal names the third operation, the only one that offended');
});

test('a single-file write is unmoved: its own path is the subject, before and after', () => {
  const cwd = project();
  // K=1 is the overwhelming majority of real traffic, and the only candidate a
  // one-target write has IS the first operation — so this row must read exactly
  // as it did before the change, through both the direct Write channel and a
  // one-operation apply_patch.
  assert.equal(refuse(cwd, [flatConfig('tsconfig.json')]).denyTarget, 'tsconfig.json');

  const direct = planWriteGate({
    input: {
      event: 'PreToolUse', host: 'claude' as HostId, cwd,
      raw: { tool_name: 'Write', tool_input: { file_path: 'tsconfig.app.json', content: '{}' } },
      tool: { class: 'file-write' as ToolClass, rawName: 'Write', filePath: 'tsconfig.app.json', content: '{}' },
    },
    host: 'claude', cwd, now: () => 'x',
  } as unknown as Ctx);
  assert.equal(direct.kind, 'deny');
  if (direct.kind === 'deny') assert.equal(direct.denyTarget, 'tsconfig.app.json');
});

test('the subject follows the patch\'s operation order, not the order the gates ran in', () => {
  const cwd = project();
  // Readiness runs before the static family in the dispatcher, so an
  // implementation that recorded the first target to FIRE would answer with the
  // flat-config file below. Operation order is what the agent wrote and what the
  // reason lists, so the first operation that offends is the answer.
  const verdict = refuse(cwd, [defaultExport('Alpha'), flatConfig('tsconfig.node.json')]);
  assert.equal(verdict.lines.length, 2, `both rules tripped: ${verdict.lines.join(' | ')}`);
  assert.equal(verdict.denyTarget, 'apps/web/src/components/Alpha.tsx',
    'the earlier OPERATION is the subject even though the later one tripped the earlier GATE');
});

test('the state-mode downgrade guard names the state file, not the operation beside it', () => {
  const cwd = project({ confirmed: true });
  // The third per-target rule that lives in the dispatcher rather than in a
  // per-target helper: it walks the gate targets itself and breaks on the first
  // `.traffic-one/.one.json` write that would downgrade the mode. It has an
  // obvious subject and must offer it like the other two.
  // An UPDATE of the state file, rebuilt from what is on disk so the patch
  // reconstructs — the guard reads the pre-tool state and compares it with the
  // proposed one, so an unreconstructable payload would never reach it.
  const [alphaPath, alphaBody] = clean('Alpha');
  const stateRel = '.traffic-one/.one.json';
  const onDisk = fs.readFileSync(path.join(cwd, stateRel), 'utf8');
  const downgraded = JSON.stringify({ ...JSON.parse(onDisk), mode: 'existing-codebase' });
  const patchText = [
    '*** Begin Patch',
    `*** Add File: ${alphaPath}`,
    `+${alphaBody}`,
    `*** Update File: ${stateRel}`,
    '@@',
    `-${onDisk}`,
    `+${downgraded}`,
    '*** End Patch',
  ].join('\n');
  const result = planWriteGate(patchCtx(cwd, patchText));
  assert.equal(result.kind, 'deny');
  if (result.kind !== 'deny') return;
  const verdict = { denyTarget: String(result.denyTarget), reason: result.reason };
  assert.match(verdict.reason, /State mode gate/,
    'the positive baseline: this really is the downgrade guard');
  assert.equal(verdict.denyTarget, '.traffic-one/.one.json',
    'the state file is the subject, not the clean component written alongside it');
});

test('a cause with no target of its own keeps naming the write itself', () => {
  const cwd = project({}, { mode: 'subagents', source: 'prompted', approved: true });
  // Run-team enforcement judges the write as a whole — it is handed the target
  // LIST, not one target per iteration — so there is no offending target to
  // name and the subject must stay what it has always been: the first
  // operation. Anything else would be inventing an attribution the gate never
  // made.
  const files = [
    ['packages/ui/tsconfig.json', '{"extends":"../../tsconfig.base.json"}'],
    ['packages/api-client/tsconfig.json', '{"extends":"../../tsconfig.base.json"}'],
  ] as const satisfies readonly File[];
  const verdict = refuse(cwd, files);
  assert.match(verdict.reason, /Run-team enforcement gate/,
    'the positive baseline: this really is the non-per-target cause');
  assert.equal(verdict.lines.length, 1,
    `and the only one — a per-target rule firing too would decide this row instead: ${verdict.lines.join(' | ')}`);
  assert.equal(verdict.denyTarget, 'packages/ui/tsconfig.json',
    'no per-target rule offended, so the first operation stands as the subject');
});

// ── bucket space ─────────────────────────────────────────────────────────────
// `denyTarget` is half the deny-repeat signature, so changing it MOVES the
// escalation partition for this whole gate. Both halves of the contract are
// asserted here, on the same instrument, because a change that fixed one by
// breaking the other would be a worse gate than the one it replaced.

const HANDLER: Handler = { id: 'plan-guard.write', event: 'PreToolUse', priority: 20, run: planWriteGate };

async function driveOnce(cwd: string, files: readonly File[]): Promise<{ escalated: boolean; target: string }> {
  const patchText = addPatch(files);
  const result = await runPipeline([HANDLER], buildContext({
    event: 'PreToolUse', host: 'claude', cwd,
    raw: { tool_name: 'apply_patch', tool_input: { patchText } },
    tool: { class: 'file-edit', rawName: 'apply_patch', patchText },
  }));
  assert.equal(result.kind, 'deny');
  if (result.kind !== 'deny') throw new Error('unreachable');
  return { escalated: /STOP RETRYING/.test(result.reason), target: String(result.denyTarget) };
}

function counts(cwd: string): number[] {
  const file = path.join(cwd, '.traffic-one', 'runs', RUN_ID, 'debug', 'deny-repeats.json');
  return Object.values(JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, number>);
}

test('an agent clearing one rule file by file is never escalated as looping', async () => {
  const cwd = project({ currentRunId: RUN_ID });
  // The realistic multi-file fix session: a stable first operation the agent
  // re-emits every turn (a barrel, a config, an entry — anything it keeps
  // rewriting) followed by the offenders, which it relocates one at a time.
  // Every refusal renders the IDENTICAL path-free line, so `denyTarget` is the
  // only thing that can tell these three refusals apart.
  const barrel = clean('Barrel');
  const attempts: readonly File[][] = [
    [barrel, flatConfig('tsconfig.json'), flatConfig('tsconfig.app.json'), flatConfig('tsconfig.node.json')],
    [barrel, flatConfig('tsconfig.app.json'), flatConfig('tsconfig.node.json')],
    [barrel, flatConfig('tsconfig.node.json')],
  ];
  assert.equal(attempts.length, DENY_REPEAT_ESCALATE_AT,
    'exactly enough turns to reach the threshold, so "not escalated" is a real result');

  const seen: string[] = [];
  for (const [index, files] of attempts.entries()) {
    const result = await driveOnce(cwd, files);
    seen.push(result.target);
    assert.equal(result.escalated, false,
      `turn ${index + 1} told a converging agent to STOP RETRYING`);
  }
  assert.deepEqual(seen, ['tsconfig.json', 'tsconfig.app.json', 'tsconfig.node.json'],
    'each turn names the offender it is actually about, so each is its own refusal');
  assert.deepEqual(counts(cwd), [1, 1, 1],
    `three steps of real progress, counted once each: ${JSON.stringify(counts(cwd))}`);
});

test('an agent genuinely looping on one file still escalates at the threshold', async () => {
  const cwd = project({ currentRunId: RUN_ID });
  // The other half, and the one that must not be traded away: the same patch,
  // unchanged, three times. Splitting buckets by offender must not make a real
  // loop unreachable.
  const files = [clean('Barrel'), flatConfig('tsconfig.json')] as const;
  const escalations: boolean[] = [];
  for (let attempt = 0; attempt < DENY_REPEAT_ESCALATE_AT; attempt += 1) {
    const result = await driveOnce(cwd, files);
    escalations.push(result.escalated);
    assert.equal(result.target, 'tsconfig.json', `attempt ${attempt + 1} names the offender`);
  }
  assert.deepEqual(escalations, [false, false, true],
    'the third identical refusal escalates, exactly as it did before the subject moved');
  assert.deepEqual(counts(cwd), [DENY_REPEAT_ESCALATE_AT],
    'one loop, one bucket');

  const last = await driveOnce(cwd, files);
  assert.match(
    (await runPipeline([HANDLER], buildContext({
      event: 'PreToolUse', host: 'claude', cwd,
      raw: { tool_name: 'apply_patch', tool_input: { patchText: addPatch(files) } },
      tool: { class: 'file-edit', rawName: 'apply_patch', patchText: addPatch(files) },
    })) as { reason: string }).reason,
    /refused `tsconfig\.json`/,
    'and the escalation prose names the offending file, not the barrel it was rendered beside',
  );
  assert.equal(last.escalated, true, 'escalation persists once reached');
});
