// Two properties that only exist once a write goes through the REAL
// `planWriteGate`, and that no unit test of `runTeamEnforcementViolation` can
// reach on its own:
//
//   1. THE DISPLACEMENT MUST NOT LAND ON A DENIED WRITE. `planWriteGate` calls
//      `runTeamEnforcementViolation` unconditionally (plan-write/index.ts) —
//      after the reservation check, before the static checks — so the gate's
//      scope attribution ran, and staked its claim, for writes the gate went on
//      to refuse for a completely unrelated reason. A stray session could
//      therefore retire a working role agent with a write that never happened.
//
//   2. THE MEMBER FENCE MUST ENGAGE FOR A REAL MEMBER. Every existing member
//      fixture in this tree is a directory with NO state of its own, and that
//      is the one shape `nearestOnboardedRoot`'s container redirect already
//      handled: the walk climbs past the member to the container and is handed
//      back down, carrying the registry with it. An ONBOARDED member stops the
//      walk at its own committed state one level below the container, so the
//      registry was dropped, `scope.workspace.kind` was `'none'`, the fence
//      could not refuse a call spanning two members, and `workspaceMember` was
//      `''` in the claim-debug row — empty precisely in the cross-member case
//      it exists to record. The fixture here is the missing one.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { planWriteGate } from '../plan-write';
import { runTeamEnforcementViolation } from '../plan-runteam';
import type { Ctx, HookInput, ToolClass } from '../../../core/types';
import { resetAuthoringRootCache } from '../../../shared/authoring-root';
import { resolveToolScope, workspaceMemberRefusal } from '../../../shared/tool-scope';
import { claimThreadRole, readEffectiveState } from '../../../shared/state';
import { recordMainOnboardingSession } from '../../../shared/onboarding-server/onboarding-session';
import { hostScopedPerformancePrefs } from '../../../test-support/host-prefs';

const RUN = 'run-1';
const SUBAGENT_TEAM = { mode: 'subagents', source: 'prompted', approved: true };
// FE owns src/app + src/components except the api carve-out; BE owns the rest.
const FE_BE_MANIFEST = [
  { role: 'senior-frontend', agentKey: 'senior-frontend', scope: { include: ['src/app/', 'src/components/'], exclude: ['src/app/api/'] } },
  { role: 'senior-backend', agentKey: 'senior-backend', scope: { include: ['src/app/api/', 'src/server/'] } },
];
// A collapsed one-liner: a plan-static violation that has nothing to do with
// role ownership, so a write carrying it is doomed on its own terms.
const COLLAPSED = 'export function App(){const a=1;return <main><section><h1>Home</h1><p>Text</p></section><footer><span>Foot</span></footer></main>;}\n';

function write(file: string, body: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body, 'utf8');
}

/** A materialized subagents-mode project: committed state, manifest, run assignments. */
function project(dir: string): string {
  const t1 = path.join(dir, '.traffic-one');
  write(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r');
  write(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's');
  write(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }));
  write(path.join(t1, 'plan.md'), 'plan');
  write(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n');
  write(path.join(dir, 'package.json'), JSON.stringify({ name: path.basename(dir) }));
  write(path.join(t1, '.one.json'), JSON.stringify({
    mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
    onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none', currentRunId: RUN,
  }));
  write(path.join(t1, 'runs', RUN, 'assignments.json'),
    JSON.stringify({ version: 1, runId: RUN, assignments: FE_BE_MANIFEST }));
  return dir;
}

function withEnv(body: (root: string) => void): void {
  const created = fs.mkdtempSync(path.join(os.tmpdir(), 't1-member-claim-'));
  const env = process.env;
  const prevPrefs = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  const prevPlan = env.TRAFFIC_ONE_USER_PLAN;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(created, 'prefs.json');
  env.TRAFFIC_ONE_USER_PLAN = 'pro';
  // The team mode lives in the per-project preference bucket, not in committed
  // state — `readEffectiveState` merges it, and without it the run-team gate
  // stands down and every row here passes vacuously.
  fs.writeFileSync(env.TRAFFIC_ONE_PROJECT_PREFS_PATH, JSON.stringify(
    hostScopedPerformancePrefs({ level: 'high', source: 'prompted' }, SUBAGENT_TEAM, 'pro'),
  ), 'utf8');
  try {
    resetAuthoringRootCache();
    body(fs.realpathSync(created));
  } finally {
    resetAuthoringRootCache();
    if (prevPrefs === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prevPrefs;
    if (prevPlan === undefined) delete env.TRAFFIC_ONE_USER_PLAN; else env.TRAFFIC_ONE_USER_PLAN = prevPlan;
    fs.rmSync(created, { recursive: true, force: true });
  }
}

function ctx(cwd: string, toolInput: Record<string, unknown>, canonical: Partial<NonNullable<HookInput['tool']>> = {}, raw: Record<string, unknown> = {}): Ctx {
  const cls: ToolClass = 'file-write';
  const input: HookInput = {
    event: 'PreToolUse', host: 'claude', cwd,
    raw: { ...raw, tool_name: 'Write', tool_input: toolInput },
    tool: { class: cls, rawName: 'Write', ...canonical },
  };
  return { input, host: 'claude', cwd, now: () => 'x' } as unknown as Ctx;
}

function writeCtx(cwd: string, target: string, sessionId: string, content: string): Ctx {
  return ctx(cwd, { file_path: target, content }, { filePath: target, content }, { session_id: sessionId });
}

function claimRecord(dir: string, sessionId: string): Record<string, unknown> {
  return JSON.parse(fs.readFileSync(path.join(dir, '.traffic-one', 'runs', RUN, `${sessionId}.json`), 'utf8'));
}

function claimDebugRows(dir: string): Record<string, unknown>[] {
  const file = path.join(dir, '.traffic-one', 'runs', RUN, 'debug', 'claim-capture.jsonl');
  if (!fs.existsSync(file)) return [];
  return fs.readFileSync(file, 'utf8').split('\n').filter(Boolean)
    .map((line) => JSON.parse(line) as Record<string, unknown>);
}

// ── 1. the denied write ──────────────────────────────────────────────────────

test('a DENIED write through the real gate stakes nothing and retires nobody', () => {
  withEnv((root) => {
    const dir = project(path.join(root, 'app'));
    recordMainOnboardingSession(dir, 'orchestrator');
    const target = path.join(dir, 'src', 'app', 'page.tsx');
    assert.ok(claimThreadRole(dir, { currentRunId: RUN, materializedStack: 'default|react-vite|supabase|none' },
      'fe-child', 'senior-frontend', { parentSessionId: 'orchestrator' }),
    'fixture: a live senior-frontend must hold the role');

    const denied = planWriteGate(writeCtx(dir, target, 'stray-session', COLLAPSED));
    assert.equal(denied.kind, 'deny', JSON.stringify(denied));
    // The write was doomed for a reason that has nothing to do with role
    // ownership — which is the whole point: the attribution ran anyway.
    assert.match((denied as { reason: string }).reason, /STRUCT_COLLAPSED_LINE/,
      'fixture: the write must fail a check unrelated to the run team, or this row measures the run-team deny');

    assert.equal(fs.existsSync(path.join(dir, '.traffic-one', 'runs', RUN, 'stray-session.json')), false,
      'a refused write must leave no claim behind for the session that attempted it');
    const held = claimRecord(dir, 'fe-child');
    assert.equal(held.status, 'claimed');
    assert.equal(held.releasedReason, undefined,
      'a write that never happened must not retire the agent that owns the path');

    // And the holder is not merely un-retired — its own in-scope write still
    // passes run-team ownership. Asserted as the ABSENCE of the run-team deny
    // rather than as a clean allow: this fixture is a bare project, so a write
    // here still meets the monorepo-layout and materialization gates, and those
    // have nothing to do with who owns the path.
    const holderWrite = planWriteGate(writeCtx(dir, target, 'fe-child',
      'export function App() {\n  return <main>Home</main>;\n}\n'));
    assert.doesNotMatch(
      holderWrite.kind === 'deny' ? holderWrite.reason : '',
      /Run-team enforcement gate/,
      'the holder was locked out of its own scope by a write the gate refused',
    );
  });
});

// ── 1b. the denied write, with a POST-ATTRIBUTION cause ──────────────────────
//
// The row above measures less than it reads. `planWriteGate` concatenates every
// violation into one reason, and the causes that actually clear
// `recordFallbackClaims` there are the monorepo-layout and materialization
// gates — both of which run BEFORE the attribution point, and both of which the
// bare `project()` fixture trips on every write. So the assertion on
// STRUCT_COLLAPSED_LINE is true of the reason without being the thing that
// cleared the flag, and a build that staked the claim after the static rules
// would still pass it. (STRUCT_COLLAPSED_LINE is itself a READINESS finding, so
// it can never be the post-attribution cause this row needs.)
//
// This fixture removes every earlier cause: a materialized monorepo — the root
// workspace declaration plus the `AGENTS.md`/`CLAUDE.md` pair the materialization
// gate reads — where the SOLE violation is one of plan-static's fourteen rules,
// which are judged AFTER the run-team gate stakes its claim. The write is
// aimed at a path outside every assignment, because the dynamic first-write
// claim is the branch that writes, and the clean control below proves that
// branch is reachable in this exact fixture rather than assumed to be.
//
// THE ORDERING MUTATION this row exists to kill: compute `recordFallbackClaims`
// as `violations.length === 0` at its old position (before the static rules are
// judged) and the deny below stakes
// `runs/run-1/claims/packages_ui_src_lib_format.ts.json` for a write that never
// happened — locking that path to `fe-child` for the rest of the run.
const MONOREPO_ONLY_ANY = 'export const format = (value: any): string => String(value);\n';
const MONOREPO_CLEAN = 'export const format = (value: string): string => value;\n';

/** `project()` plus the two things every earlier gate in the dispatcher wants. */
function materializedMonorepo(dir: string): string {
  project(dir);
  // The materialization gate reads BOTH generated context files; `project()`
  // writes only AGENTS.md, which is why every other row here carries a
  // materialization violation it does not assert on.
  write(path.join(dir, 'CLAUDE.md'), 'see agents');
  write(path.join(dir, 'package.json'), JSON.stringify({
    name: path.basename(dir), private: true, packageManager: 'pnpm@10.0.0', workspaces: ['apps/*', 'packages/*'],
  }));
  write(path.join(dir, 'pnpm-workspace.yaml'), "packages:\n  - 'apps/*'\n  - 'packages/*'\n");
  write(path.join(dir, 'apps', 'web', 'package.json'), JSON.stringify({ name: 'web' }));
  write(path.join(dir, 'packages', 'ui', 'package.json'), JSON.stringify({ name: 'ui' }));
  return dir;
}

test('a write refused by a check that runs AFTER attribution stakes no claim either', () => {
  withEnv((root) => {
    const dir = materializedMonorepo(path.join(root, 'app'));
    recordMainOnboardingSession(dir, 'orchestrator');
    assert.ok(claimThreadRole(dir, { currentRunId: RUN, materializedStack: 'default|react-vite|supabase|none' },
      'fe-child', 'senior-frontend', { parentSessionId: 'orchestrator' }),
    'fixture: a live senior-frontend must hold the role, or no agent context reaches the claim branch');

    // Outside both assigned scopes, so ownership routes to the dynamic
    // first-write claim rather than to a scope-conflict deny.
    const target = path.join(dir, 'packages', 'ui', 'src', 'lib', 'format.ts');
    const claimFile = path.join(dir, '.traffic-one', 'runs', RUN, 'claims', 'packages_ui_src_lib_format.ts.json');

    const denied = planWriteGate(writeCtx(dir, target, 'fe-child', MONOREPO_ONLY_ANY));
    assert.equal(denied.kind, 'deny', JSON.stringify(denied));
    const bullets = (denied as { reason: string }).reason
      .split('\n').filter((line) => line.startsWith('  - '));
    assert.equal(bullets.length, 1,
      `FIXTURE the sole violation must be the post-attribution one, got:\n${bullets.join('\n')}`);
    assert.match(bullets[0]!, /Avoid `any`/,
      'FIXTURE and it must come from plan-static, which is judged after the run-team gate');

    assert.equal(fs.existsSync(claimFile), false,
      'a write the static rules refused staked a first-write claim on the path anyway,'
      + ' locking it to this session for the rest of the run');

    // NON-VACUITY, and it is the whole reason the control is the SAME session,
    // the SAME path and the SAME fixture: the branch that stakes is reachable
    // here, and it stakes the moment the write is actually allowed.
    const allowed = planWriteGate(writeCtx(dir, target, 'fe-child', MONOREPO_CLEAN));
    assert.equal(allowed.kind, 'noop',
      allowed.kind === 'deny' ? allowed.reason : 'the clean control must be allowed');
    assert.equal(fs.existsSync(claimFile), true,
      'FIXTURE an allowed write must still stake its claim, or this row would pass with claims switched off');
  });
});

// ── 1c. the ROLE claim, on a FREE role ───────────────────────────────────────
//
// Row 1 asserts that a denied write "stakes nothing and retires nobody" and
// measures only half of it: its fixture PRE-CLAIMS the role, so the occupied-role
// refusal inside `attributeForeignWriteBySpawnScope` is what stops the mint, not
// the gate's verdict. Remove the incumbent and the headline stopped being true —
// the scope attribution minted a live role claim for a stray session whose write
// was refused, and that claim then denies the next legitimate respawn for as long
// as it stays live (bounded at SUBAGENT_STALE_MS, 30 minutes). That price was
// argued for a SUCCESSFUL write.
//
// The fixture is the materialized monorepo again, for the same reason row 1b
// needs it: the sole violation must be one the dispatcher judges AFTER the
// attribution point, or the row passes on a build that mints anyway.
const FREE_ROLE_ONLY_ANY = 'export const shape = (value: any): string => String(value);\n';
const FREE_ROLE_CLEAN = 'export const shape = (value: string): string => value;\n';

/**
 * Re-point the run's assignments at MONOREPO-shaped scopes.
 *
 * `FE_BE_MANIFEST` assigns root `src/` directories, and in the materialized
 * monorepo a root Vite app is itself a violation (`monorepo-root-vite`) — which
 * fires BEFORE the attribution point and so disqualifies every root-`src/`
 * target from being the post-attribution sole cause these two rows need.
 */
function monorepoAssignments(dir: string): void {
  write(path.join(dir, '.traffic-one', 'runs', RUN, 'assignments.json'), JSON.stringify({
    version: 1,
    runId: RUN,
    assignments: [
      { role: 'senior-frontend', agentKey: 'senior-frontend', scope: { include: ['apps/web/'] } },
      { role: 'senior-backend', agentKey: 'senior-backend', scope: { include: ['packages/ui/'] } },
    ],
  }));
}

test('a DENIED write mints no ROLE claim when the role is held by nobody', () => {
  withEnv((root) => {
    const dir = materializedMonorepo(path.join(root, 'app'));
    monorepoAssignments(dir);
    recordMainOnboardingSession(dir, 'orchestrator');
    // NO incumbent: this is the whole difference from row 1. `stray-session`
    // carries no parent, transcript or agent linkage, so scope attribution is
    // the only path that can resolve it — and `senior-frontend` is free.
    const roleClaim = path.join(dir, '.traffic-one', 'runs', RUN, 'stray-session.json');
    // Inside senior-frontend's assigned scope, so exactly ONE role owns it and
    // the attribution is unambiguous.
    const target = path.join(dir, 'apps', 'web', 'shape.ts');

    const denied = planWriteGate(writeCtx(dir, target, 'stray-session', FREE_ROLE_ONLY_ANY));
    assert.equal(denied.kind, 'deny', JSON.stringify(denied));
    const bullets = (denied as { reason: string }).reason
      .split('\n').filter((line) => line.startsWith('  - '));
    assert.equal(bullets.length, 1,
      `FIXTURE the sole violation must be the post-attribution one, got:\n${bullets.join('\n')}`);
    assert.match(bullets[0]!, /Avoid `any`/, 'FIXTURE and it must come from plan-static');

    assert.equal(fs.existsSync(roleClaim), false,
      'a refused write made its author the incumbent for senior-frontend — a stray whose write never'
      + ' landed now denies the next legitimate rescue for up to 30 minutes');

    // NON-VACUITY: the mint is reachable in this exact fixture, and it happens
    // the moment the write is actually allowed.
    const allowed = planWriteGate(writeCtx(dir, target, 'stray-session', FREE_ROLE_CLEAN));
    assert.equal(allowed.kind, 'noop',
      allowed.kind === 'deny' ? allowed.reason : 'the clean control must be allowed');
    assert.equal(fs.existsSync(roleClaim), true,
      'FIXTURE an allowed write must still bind the role, or this row would pass with attribution switched off');
    assert.equal(claimRecord(dir, 'stray-session').role, 'senior-frontend');
  });
});

// ── 1d. the ownership conflict a doomed write must still be TOLD about ───────
//
// `recordFallbackClaims` used to gate the whole fallback-claim call, and that
// function both RECORDS a claim and CHECKS whether somebody else holds one. So a
// write that was going to be refused for an unrelated reason was also refused the
// conflict: the author fixed the static rule, retried, and only then learned the
// path belongs to another role. The clean control is the same fixture with clean
// content, which reports the conflict in both builds — so the conflict is real
// and was withheld precisely when another violation coexisted.
test('a doomed write still reports the ownership conflict alongside the static rule', () => {
  withEnv((root) => {
    const dir = materializedMonorepo(path.join(root, 'app'));
    recordMainOnboardingSession(dir, 'orchestrator');
    for (const [session, role] of [['fe-child', 'senior-frontend'], ['be-child', 'senior-backend']] as const) {
      assert.ok(claimThreadRole(dir, { currentRunId: RUN, materializedStack: 'default|react-vite|supabase|none' },
        session, role, { parentSessionId: 'orchestrator' }), `fixture: ${role} must be live`);
    }
    // Outside every assignment, so ownership routes to the dynamic first-write
    // claim — and `be-child` gets there first.
    const target = path.join(dir, 'packages', 'ui', 'src', 'lib', 'held.ts');
    assert.equal(planWriteGate(writeCtx(dir, target, 'be-child', MONOREPO_CLEAN)).kind, 'noop',
      'fixture: the first writer must take the path');

    const conflictOnly = planWriteGate(writeCtx(dir, target, 'fe-child', MONOREPO_CLEAN));
    assert.equal(conflictOnly.kind, 'deny');
    assert.match((conflictOnly as { reason: string }).reason, /already being written by/,
      'fixture: a clean write into a held path reports the conflict');

    const both = planWriteGate(writeCtx(dir, target, 'fe-child', MONOREPO_ONLY_ANY));
    assert.equal(both.kind, 'deny');
    const reason = (both as { reason: string }).reason;
    assert.match(reason, /Avoid `any`/, 'the static rule is reported');
    assert.match(reason, /already being written by/,
      'and so is the ownership conflict — suppressing the RECORD on a doomed write must not suppress the CHECK,'
      + ' or the author fixes the static rule, retries, and only then learns the path belongs to somebody else');
  });
});

// ── 1e. the multi-target loop the peer could not reach through the gate ──────
//
// Read from the code and settled here at the unit, because the real gate's
// multi-target shapes all route through `featureTargetPaths` and the peer could
// not build one that reached the per-target ownership loop with two targets of
// different kinds. `runTeamEnforcementViolation` takes that list directly, so the
// loop is reachable exactly as production reaches it — with the dispatcher's own
// argument shape — and needs no fixture the gate cannot produce.
test('a multi-target write stakes NOTHING when a later target draws a scope conflict', () => {
  withEnv((root) => {
    const dir = materializedMonorepo(path.join(root, 'app'));
    recordMainOnboardingSession(dir, 'orchestrator');
    assert.ok(claimThreadRole(dir, { currentRunId: RUN, materializedStack: 'default|react-vite|supabase|none' },
      'fe-child', 'senior-frontend', { parentSessionId: 'orchestrator' }), 'fixture');

    // A is outside every assignment (the branch that stakes); B is in
    // senior-backend's scope (the branch that denies). A comes FIRST, so the
    // single-pass form took A's lease and then refused the write for B.
    const a = 'packages/ui/src/lib/multi.ts';
    const b = 'src/app/api/route.ts';
    const claimFile = path.join(dir, '.traffic-one', 'runs', RUN, 'claims', 'packages_ui_src_lib_multi.ts.json');
    const args = {
      projectRoot: dir,
      filePath: a,
      state: readEffectiveState(dir),
      rawData: { session_id: 'fe-child' },
      writeTargetPaths: [a, b],
      featureTargetPaths: [a, b],
      writingFeatureSource: true,
      writingFeatureSourceViaCommand: false,
      block: (_name: string, fallback: string) => fallback,
    };

    const denied = runTeamEnforcementViolation(args);
    assert.ok(denied, 'the write must be refused for the second target');
    assert.match(denied!, /senior-backend/, 'and refused for the scope conflict it draws');
    assert.equal(fs.existsSync(claimFile), false,
      "the first target's first-write claim survived a write refused because of the second — locking a path"
      + ' this session never wrote for the rest of the run');

    // NON-VACUITY: drop the conflicting target and the same first target stakes.
    assert.equal(runTeamEnforcementViolation({ ...args, writeTargetPaths: [a], featureTargetPaths: [a] }), null);
    assert.equal(fs.existsSync(claimFile), true,
      'FIXTURE an allowed write must still stake, or this row would pass with claims switched off');
  });
});

// ── 1f. WHICH cause names the deny ───────────────────────────────────────────
//
// The static family is JUDGED before the run-team gate and REGISTERED after it,
// and only the second half is observable: collapse the separate accumulator and
// delete the re-registration, and every deny where a static rule and the run-team
// gate BOTH fire is re-labelled from the run-team identity to the static one.
// That mutant survived the whole lane suite plus the checked-in replay-corpus
// snapshot, because no row made a static rule co-fire with a run-team deny.
test('a co-firing static rule does not steal the run-team gate\'s deny identity', () => {
  withEnv((root) => {
    const dir = materializedMonorepo(path.join(root, 'app'));
    monorepoAssignments(dir);
    recordMainOnboardingSession(dir, 'orchestrator');
    assert.ok(claimThreadRole(dir, { currentRunId: RUN, materializedStack: 'default|react-vite|supabase|none' },
      'fe-child', 'senior-frontend', { parentSessionId: 'orchestrator' }), 'fixture');

    // senior-backend's scope, written by the frontend child, with an `any` in
    // the content: the run-team scope conflict and a plan-static rule both fire.
    const denied = planWriteGate(writeCtx(dir, path.join(dir, 'packages', 'ui', 'handler.ts'),
      'fe-child', MONOREPO_ONLY_ANY));
    assert.equal(denied.kind, 'deny', JSON.stringify(denied));
    const reason = (denied as { reason: string }).reason;
    assert.match(reason, /Run-team enforcement gate/, 'FIXTURE both causes must fire');
    assert.match(reason, /Avoid `any`/, 'FIXTURE both causes must fire');
    assert.equal((denied as { denyId?: string }).denyId, 'run-team-scope-conflict',
      'the deny is identified by the first cause in REGISTRATION order, and the static family is registered'
      + ' at the position it used to fire in — judging it early must not also report it early');
  });
});

// ── 2. a REAL member ─────────────────────────────────────────────────────────

/** A container registering two members, both onboarded projects in their own right. */
function workspace(root: string): { container: string; api: string; web: string } {
  const container = path.join(root, 'ws');
  write(path.join(container, '.traffic-one', '.one.json'), JSON.stringify({
    mode: 'workspace', onboardingComplete: true, workspaceMembers: [{ path: 'api' }, { path: 'web' }],
  }));
  return { container, api: project(path.join(container, 'api')), web: project(path.join(container, 'web')) };
}

test('an ONBOARDED member resolves as a member, and a call spanning two of them is refused', () => {
  withEnv((root) => {
    const { container, api, web } = workspace(root);
    for (const member of [api, web]) {
      assert.ok(fs.existsSync(path.join(member, '.traffic-one', '.one.json')),
        'FIXTURE the member must hold state of its OWN — a stateless member is the case already covered');
    }

    const scope = resolveToolScope(writeCtx(container, path.join(api, 'src', 'app', 'page.tsx'), 'any', 'x'));
    assert.equal(scope.projectRoot, api, 'the root was always right');
    assert.equal(scope.workspace.kind, 'member',
      'and the workspace facts must survive the member\'s own committed state, or the fence never engages');
    assert.equal(scope.workspace.kind === 'member' ? scope.workspace.container : '', container);
    assert.equal(workspaceMemberRefusal(scope), null, 'a single-member call is not refused');

    // The fence's reason for existing: two members are two projects, with two
    // plans, two runs and two sets of role claims.
    const split = resolveToolScope(ctx(container, {
      paths: [path.join(api, 'src', 'app', 'page.tsx'), path.join(web, 'src', 'app', 'page.tsx')],
    }));
    const refusal = workspaceMemberRefusal(split);
    assert.ok(refusal, 'a call spanning two onboarded members must be refused, not silently judged against one');
    assert.equal(refusal!.denyId, 'workspace-member-unresolved');
    assert.match(refusal!.reason, /spans 2 members/);
    assert.equal(planWriteGate(ctx(container, {
      paths: [path.join(api, 'src', 'app', 'page.tsx'), path.join(web, 'src', 'app', 'page.tsx')],
    })).kind, 'deny', 'and the refusal reaches the real write gate');
  });
});

// ── 3. the member that is a package-manager monorepo in its own right ────────
//
// The motivating shape for the whole feature, and the one an earlier revision
// still missed: a polyglot workspace registering `frontend` (a pnpm/npm
// monorepo) beside `backend` (a Go module). `frontend` used to leave the
// resolver at the `dirDeclaresWorkspace` exit, one branch ABOVE the acceptance
// clause, and came back with no container at all — so the fence engaged for
// `backend` and not for `frontend`, and the SAME spanning call then flipped on
// TARGET ORDER alone (measured: refused with `backend` last, allowed with
// `frontend` last, because the resolver anchors to the last target). Both orders
// are asserted here for exactly that reason; one of them passes without the fix.
function polyglotWorkspace(root: string): { container: string; frontend: string; backend: string } {
  const container = path.join(root, 'ws');
  write(path.join(container, '.traffic-one', '.one.json'), JSON.stringify({
    mode: 'workspace', onboardingComplete: true, workspaceMembers: [{ path: 'frontend' }, { path: 'backend' }],
  }));
  const frontend = project(path.join(container, 'frontend'));
  // What makes this member different from every other member fixture in the
  // tree: it declares package-manager workspaces of its OWN.
  write(path.join(frontend, 'package.json'), JSON.stringify({ name: 'frontend', workspaces: ['apps/*'] }));
  write(path.join(frontend, 'apps', 'site', 'package.json'), JSON.stringify({ name: 'site' }));
  return { container, frontend, backend: project(path.join(container, 'backend')) };
}

test('a member that DECLARES package-manager workspaces is still a member, in either target order', () => {
  withEnv((root) => {
    const { container, frontend, backend } = polyglotWorkspace(root);

    const scope = resolveToolScope(writeCtx(container, path.join(frontend, 'src', 'app', 'page.tsx'), 'any', 'x'));
    assert.equal(scope.projectRoot, frontend, 'the root was always right for this member too');
    assert.equal(scope.workspace.kind, 'member',
      'a member does not stop being a member by declaring workspaces inside itself');
    assert.equal(scope.workspace.kind === 'member' ? scope.workspace.container : '', container);
    assert.equal(workspaceMemberRefusal(scope), null);

    // A target inside the member's OWN package-manager workspace still anchors
    // to the member, not to the sub-package: the member is the project.
    const deep = resolveToolScope(writeCtx(container, path.join(frontend, 'apps', 'site', 'index.ts'), 'any', 'x'));
    assert.equal(deep.projectRoot, frontend);
    assert.equal(deep.workspace.kind, 'member');

    const fePath = path.join(frontend, 'src', 'app', 'page.tsx');
    const bePath = path.join(backend, 'src', 'app', 'page.tsx');
    for (const [label, paths] of [
      ['backend last', [fePath, bePath]],
      ['frontend last', [bePath, fePath]],
    ] as const) {
      const refusal = workspaceMemberRefusal(resolveToolScope(ctx(container, { paths: [...paths] })));
      assert.ok(refusal, `the spanning call was allowed with ${label} — the fence must not depend on target order`);
      assert.match(refusal!.reason, /spans 2 members/, label);
      assert.equal(planWriteGate(ctx(container, { paths: [...paths] })).kind, 'deny', `${label}: through the real gate`);
    }
  });
});

test('the claim-debug row names a declaring member too', () => {
  withEnv((root) => {
    const { frontend, backend } = polyglotWorkspace(root);
    recordMainOnboardingSession(frontend, 'orchestrator-fe');

    const denied = planWriteGate(writeCtx(backend, path.join(frontend, 'src', 'app', 'page.tsx'), 'backend-session', COLLAPSED));
    assert.equal(denied.kind, 'deny');

    const rows = claimDebugRows(frontend).filter((row) => row.label === 'runteam-write');
    assert.ok(rows.length > 0, 'the write must be recorded in the member it anchored to');
    assert.equal(rows[rows.length - 1]!.workspaceMember, frontend,
      'the field this item exists to record was omitted for every write anchored to a declaring member');
  });
});

test('the claim-debug row names the member a cross-member write anchored to', () => {
  withEnv((root) => {
    const { api, web } = workspace(root);
    // `web` is a project in its own right, with its own orchestrator and its own
    // frontend agent holding the role.
    recordMainOnboardingSession(web, 'orchestrator-web');
    assert.ok(claimThreadRole(web, { currentRunId: RUN, materializedStack: 'default|react-vite|supabase|none' },
      'web-fe', 'senior-frontend', { parentSessionId: 'orchestrator-web' }),
    'fixture: web\'s own frontend agent must hold the role');

    // A session running in member `api` writes into member `web`.
    const denied = planWriteGate(writeCtx(api, path.join(web, 'src', 'app', 'page.tsx'), 'api-session', COLLAPSED));
    assert.equal(denied.kind, 'deny');

    const rows = claimDebugRows(web).filter((row) => row.label === 'runteam-write');
    assert.ok(rows.length > 0, 'the write must be recorded in the member it anchored to');
    assert.equal(rows[rows.length - 1]!.workspaceMember, web,
      'the one question a multi-member run has to answer afterwards — WHICH member did this resolve in —'
      + ' was unanswerable, because the field was omitted exactly in the cross-member case');
    assert.deepEqual(claimDebugRows(api), [],
      'and nothing was recorded in the member the session merely came from');

    // The claim itself is untouched: this is the cross-member half of the
    // displacement, reached through the whole gate rather than through the unit.
    const held = claimRecord(web, 'web-fe');
    assert.equal(held.status, 'claimed');
    assert.equal(held.releasedReason, undefined);
  });
});
