import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { planReadinessViolations } from '../plan-readiness';

const names = (name: string): string => name;

function withProject(fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-readiness-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeStateFile(dir: string, state: Record<string, unknown>): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(t1, { recursive: true });
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify(state), 'utf8');
}

function writePlan(dir: string): void {
  fs.mkdirSync(path.join(dir, '.traffic-one'), { recursive: true });
  fs.writeFileSync(path.join(dir, '.traffic-one', 'plan.md'), 'plan', 'utf8');
}

function writeMaterialized(dir: string): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
}

function writeRequiredScaffold(dir: string): void {
  fs.writeFileSync(path.join(dir, 'pnpm-workspace.yaml'), 'packages:\n  - "apps/*"\n  - "packages/*"\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'turbo.json'), '{"tasks":{}}', 'utf8');
  fs.writeFileSync(path.join(dir, 'tsconfig.base.json'), '{"compilerOptions":{}}', 'utf8');
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    private: true,
    packageManager: 'pnpm@10.12.1',
    workspaces: ['apps/*', 'packages/*'],
  }), 'utf8');
  for (const rel of [
    'apps/web',
    'packages/ui/src',
    'packages/tailwind-config',
    'packages/i18n/src',
  ]) {
    fs.mkdirSync(path.join(dir, rel), { recursive: true });
  }
  fs.writeFileSync(path.join(dir, 'apps/web/package.json'), '{"name":"web","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/ui/package.json'), '{"name":"@app/ui","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/ui/src/index.ts'), '', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/tailwind-config/package.json'), '{"name":"@app/tailwind-config","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/tailwind-config/tailwind.config.ts'), 'export default {};', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/i18n/package.json'), '{"name":"@app/i18n","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/i18n/src/index.ts'), '', 'utf8');
}

const DEFAULT_STATE = {
  mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
};

test('monorepo-package-json: a non-workspace root package.json on a monorepo stack is blocked', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: 'package.json', content: '{"name":"x"}', projectRoot: dir,
      state: { ...DEFAULT_STATE }, writingFeatureSource: false, block: names,
    });
    assert.deepEqual(v, ['monorepo-package-json']);
  });
});

test('monorepo-package-json: pnpm-workspace.yaml satisfies workspace declaration for root package.json', () => {
  withProject((dir) => {
    fs.writeFileSync(path.join(dir, 'pnpm-workspace.yaml'), 'packages:\n  - "apps/*"\n  - "packages/*"\n', 'utf8');
    const v = planReadinessViolations({
      filePath: 'package.json',
      content: JSON.stringify({
        name: 'devlearn',
        private: true,
        packageManager: 'pnpm@10.23.0',
        engines: { node: '>=22' },
      }),
      projectRoot: dir,
      state: { ...DEFAULT_STATE },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('monorepo-root-vite: a root src/ Vite file on a monorepo stack is blocked', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: 'src/main.tsx', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE }, writingFeatureSource: false, block: names,
    });
    assert.ok(v.includes('monorepo-root-vite'));
  });
});

test('state-gate: feature write with a missing/incomplete state file on a new project', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { mode: 'new-project' }, writingFeatureSource: true, block: names,
    });
    assert.ok(v.includes('state-gate'));
  });
});

test('materialization-gate: onboarded + valid stack but assets not on disk yet', () => {
  withProject((dir) => {
    writeStateFile(dir, { ...DEFAULT_STATE, onboardingComplete: true });
    writePlan(dir); // present so the plan-gate does not also fire
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true }, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, ['materialization-gate']);
  });
});

test('plan-gate: new project, no plan.md, writing feature source', () => {
  withProject((dir) => {
    // onboardingComplete:false makes featureContextMaterialized true → only the plan-gate fires.
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: false }, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, ['plan-gate']);
  });
});

test('plan-gate: legacy architecture.md does not satisfy readiness', () => {
  withProject((dir) => {
    fs.writeFileSync(path.join(dir, 'architecture.md'), '# Legacy architecture', 'utf8');
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: false }, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, ['plan-gate']);
  });
});

test('architect completion gate: PLAN_READY requires the baseline monorepo scaffold', () => {
  withProject((dir) => {
    const state = { ...DEFAULT_STATE, onboardingComplete: true };
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['architect-scaffold-gate']);

    const nonTerminal = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'still planning\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(nonTerminal, []);
  });
});

test('architect completion gate: PLAN_READY is allowed once scaffold files exist', () => {
  withProject((dir) => {
    writeRequiredScaffold(dir);
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('architect completion gate: PLAN_READY accepts pnpm-workspace.yaml plus root package without workspaces', () => {
  withProject((dir) => {
    writeRequiredScaffold(dir);
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
      name: 'devlearn',
      private: true,
      packageManager: 'pnpm@10.23.0',
      engines: { node: '>=22' },
    }), 'utf8');
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('a fully materialized project with a plan emits no readiness violations', () => {
  withProject((dir) => {
    writeMaterialized(dir);
    writePlan(dir);
    const state = { ...DEFAULT_STATE, onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none' };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: 'apps/web/src/components/Button.tsx', content: 'export const Button = () => null;',
      projectRoot: dir, state, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, []);
  });
});
