import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { planWriteGate } from '../plan-write';
import type { Ctx, HookInput, ToolClass } from '../../../core/types';
import { writeAuthChoice } from '../../session/auth-choice';

function withMaterialized(stateExtra: Record<string, unknown>, fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-planwrite-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  const prevChoice = env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH = path.join(dir, 'auth-choice.json');
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
  fs.writeFileSync(path.join(t1, 'plan.md'), 'plan', 'utf8');
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({
    mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
    onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none', ...stateExtra,
  }), 'utf8');
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    if (prevChoice === undefined) delete env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH; else env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH = prevChoice;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeCtx(cwd: string, rawName: string, cls: ToolClass, toolInput: Record<string, unknown>): Ctx {
  const input: HookInput = {
    event: 'PreToolUse', host: 'claude', cwd,
    raw: { tool_name: rawName, tool_input: toolInput },
    tool: { class: cls, rawName },
  };
  return { input, host: 'claude', cwd, now: () => 'x' } as unknown as Ctx;
}

test('clean write in a materialized main-agent project → noop', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/components/Button.tsx', content: 'export const Button = () => null;',
    }));
    assert.equal(r.kind, 'noop');
  });
});

test('subagents project: a feature write outside any role session is denied (run-team)', () => {
  withMaterialized({ team: { mode: 'subagents', source: 'prompted', approved: true } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/featureThing.ts', content: 'export const x = 1;',
    }));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') {
      assert.ok(r.reason.includes('Run-team enforcement gate'));
      assert.ok(r.reason.includes('team.mode'));
    }
  });
});

test('static layout violation is denied even in a clean main-agent project', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'packages/ui/src/components/Btn.tsx', content: 'export default function Btn() { return null; }',
    }));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') assert.ok(r.reason.includes('plan gate violation'));
  });
});

test('non-file, non-feature shell command in a clean project → noop', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Bash', 'shell', { command: 'ls -la' }));
    assert.equal(r.kind, 'noop');
  });
});

test('continue-without-Traffic-One choice bypasses the plan gate', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    fs.rmSync(path.join(cwd, '.traffic-one', 'plan.md'), { force: true });
    writeAuthChoice('continue-without-traffic-one', cwd);
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/x.ts', content: 'export const x = 1;',
    }));
    assert.equal(r.kind, 'noop');
  });
});
