import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { planWriteGate } from '../plan-write';
import type { Ctx, HookInput, ToolClass, HostId } from '../../../core/types';
import { writeAuthChoice } from '../../session/auth-choice';
import { writeModelChoice } from '../../agent-model/model-choice';
import { claimThreadRole, ensureRunAgentClaim } from '../../../shared/state/run-agent';

function withMaterialized(stateExtra: Record<string, unknown>, fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-planwrite-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  const prevChoice = env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH = path.join(dir, 'auth-choice.json');
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
  fs.writeFileSync(path.join(t1, 'plan.md'), 'plan', 'utf8');
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({
    mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
    onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none', ...stateExtra,
  }), 'utf8');
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    if (prevChoice === undefined) delete env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH; else env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH = prevChoice;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeCtx(
  cwd: string,
  rawName: string,
  cls: ToolClass,
  toolInput: Record<string, unknown>,
  rawExtra: Record<string, unknown> = {},
  host: HostId = 'claude',
): Ctx {
  const input: HookInput = {
    event: 'PreToolUse', host, cwd,
    raw: { ...rawExtra, tool_name: rawName, tool_input: toolInput },
    tool: { class: cls, rawName },
  };
  return { input, host, cwd, now: () => 'x' } as unknown as Ctx;
}

test('clean write in a materialized main-agent project → noop', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/components/Button.tsx', content: 'export const Button = () => null;',
    }));
    assert.equal(r.kind, 'noop');
  });
});

test('OpenCode write (camelCase filePath) of a root Vite file is gated — was blind on opencode', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    // OpenCode's write tool sends `filePath` (camelCase); the snake_case-only read
    // missed it, so the monorepo-root-vite / plan / feature-source gates all went
    // blind on the opencode host (the orchestrator scaffolded a root Vite app + ran
    // npm install before the architect/plan). Reading the canonical/camelCase field
    // restores the gate.
    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'vite.config.ts', content: 'export default {};',
    }, {}, 'opencode'));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') assert.ok(/root Vite app files are not allowed|monorepo/i.test(r.reason));
  });
});

test('Kilo write of root tsconfig.json is gated on monorepo stacks', () => {
  withMaterialized({ team: { mode: 'subagents', source: 'prompted', approved: true } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'tsconfig.json', content: '{"files":[]}',
    }, {}, 'kilo'));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') assert.ok(/tsconfig|monorepo|plan gate/i.test(r.reason));
  });
});

test('Kilo write of root tsconfig.base.json is allowed as monorepo baseline', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'tsconfig.base.json', content: '{"compilerOptions":{}}',
    }, {}, 'kilo'));
    assert.equal(r.kind, 'noop');
  });
});

test('Kilo rootless macOS absolute assignments path is normalized to the project manifest', () => {
  withMaterialized({}, (cwd) => {
    const target = path.join(cwd, '.traffic-one', 'runs', 'run-1', 'assignments.json').slice(1);
    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: target,
      content: JSON.stringify({
        version: 1,
        runId: 'run-1',
        assignments: [
          { role: 'senior-frontend', scope: { include: ['apps/web/**'], exclude: [] } },
          { role: 'senior-backend', scope: { include: ['supabase/**'], exclude: [] } },
        ],
      }),
    }, { session_id: 'kilo-architect' }, 'kilo'));
    assert.equal(r.kind, 'noop');
  });
});

test('subagents project: a feature write outside any role session is denied (run-team)', () => {
  withMaterialized({ team: { mode: 'subagents', source: 'prompted', approved: true } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/featureThing.ts', content: 'export const x = 1;',
    }));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') {
      assert.ok(r.reason.includes('Run-team enforcement gate'));
      assert.ok(r.reason.includes('team.mode'));
    }
  });
});

test('subagents project: parent build-artifact write is denied even outside src', () => {
  withMaterialized({ team: { mode: 'subagents', source: 'prompted', approved: true } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'packages/api-client/tsconfig.json',
      content: '{"extends":"../../tsconfig.base.json"}',
    }, {}, 'opencode'));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') {
      assert.ok(r.reason.includes('Run-team enforcement gate'));
      assert.ok(r.reason.includes('team.mode'));
      assert.ok(r.reason.includes('assigned build-artifact') || r.reason.includes('implementation artifacts'));
    }
  });
});

test('subagents project: claimed role can write its package build artifact', () => {
  withMaterialized({
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    assert.ok(claimThreadRole(cwd, state, 'frontend-child', 'senior-frontend', { parentSessionId: 'orchestrator' }));

    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'packages/i18n/package.json',
      content: '{"name":"@app/i18n","type":"module"}',
    }, { session_id: 'frontend-child' }, 'opencode'));
    assert.equal(r.kind, 'noop');
  });
});

test('Windsurf native foreground architect can write package.json from its sole pending claim', () => {
  withMaterialized({
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    assert.ok(ensureRunAgentClaim(cwd, state, 'senior-architect', {}, {
      toolName: 'run_subagent',
      agentType: 'subagent_general',
    }));

    const result = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      file_path: path.join(cwd, 'package.json'),
      content: '{"private":true,"packageManager":"pnpm@10.0.0","workspaces":["apps/*","packages/*"]}',
    }, { hook_event_name: 'PreToolUse' }, 'windsurf'));
    assert.equal(result.kind, 'noop', result.kind === 'deny' ? result.reason : undefined);
  });
});

test('Windsurf architect may create baseline package directories with mkdir before plan.md', () => {
  withMaterialized({
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const result = planWriteGate(writeCtx(cwd, 'exec', 'shell', {
      command: 'mkdir -p packages/ui/src',
    }, { hook_event_name: 'PreToolUse' }, 'windsurf'));
    assert.equal(result.kind, 'noop', result.kind === 'deny' ? result.reason : undefined);
  });
});

test('OpenCode shell write to external /tmp is denied before host permission prompt', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'bash', 'shell', {
      command: 'npx tsc -p packages/i18n/tsconfig.json > /tmp/i18n_build.log',
    }, {}, 'opencode'));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') {
      assert.ok(r.reason.includes('/tmp'));
      assert.ok(/external-directory|permission|stall/i.test(r.reason));
    }
  });
});

test('subagents project: denied readiness write does not leave a fallback path claim', () => {
  withMaterialized({
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    assert.ok(claimThreadRole(cwd, state, 'architect-child', 'senior-architect', { parentSessionId: 'orchestrator' }));

    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'packages/unknown/src/theme.ts',
      content: 'export const theme = {};\n',
    }, { session_id: 'architect-child' }, 'kilo'));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') assert.ok(r.reason.includes('Architect scope gate'));
    assert.equal(fs.existsSync(path.join(cwd, '.traffic-one', 'runs', 'run-1', 'claims')), false);
  });
});

test('subagents project: claimed senior-architect can write Tailwind globals baseline before PLAN_READY', () => {
  withMaterialized({
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    assert.ok(claimThreadRole(cwd, state, 'architect-child', 'senior-architect', { parentSessionId: 'orchestrator' }));

    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'packages/tailwind-config/src/globals.css',
      content: '@import "tailwindcss";\n:root { color-scheme: light; }\n',
    }, { session_id: 'architect-child' }, 'kilo'));
    assert.equal(r.kind, 'noop');
    assert.equal(fs.existsSync(path.join(cwd, '.traffic-one', 'runs', 'run-1', 'claims')), false);
  });
});

test('Cursor pending model choice blocks direct scaffold writes until the user replies', () => {
  const prevPlan = process.env.TRAFFIC_ONE_USER_PLAN;
  process.env.TRAFFIC_ONE_USER_PLAN = 'pro';
  try {
    const runId = '1780000000000';
    withMaterialized({
      currentRunId: runId,
      performance: { level: 'high', source: 'prompted' },
      team: { mode: 'subagents', source: 'prompted', approved: true, overrides: { 'senior-architect': 'balanced' } },
    }, (cwd) => {
      fs.writeFileSync(path.join(cwd, '.traffic-one', 'cursor-models.json'), JSON.stringify({
        models: ['claude-opus-4-8-thinking-high', 'gpt-5.5-medium', 'composer-2.5-fast'],
      }), 'utf8');

      const blocked = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
        file_path: 'README.md',
        content: '# Project\n',
      }, {}, 'cursor'));
      assert.equal(blocked.kind, 'deny');
      if (blocked.kind === 'deny') {
        assert.ok(/model choice required/i.test(blocked.reason));
        assert.ok(/scaffold directly|edit project files/i.test(blocked.reason));
      }

      writeModelChoice(cwd, runId, 'use-fallback');
      const allowed = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
        file_path: 'README.md',
        content: '# Project\n',
      }, {}, 'cursor'));
      assert.equal(allowed.kind, 'noop');
    });
  } finally {
    if (prevPlan === undefined) delete process.env.TRAFFIC_ONE_USER_PLAN;
    else process.env.TRAFFIC_ONE_USER_PLAN = prevPlan;
  }
});

test('subagents project: claimed senior-frontend can write flat root Next UI source', () => {
  withMaterialized({
    mode: 'existing-codebase',
    frontend: 'nextjs',
    backend: 'none',
    materializedStack: 'default|nextjs|none|none',
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    const threadId = '019e7390-ca45-7e03-84d3-284bda1ba905';
    const transcript = path.join(cwd, `rollout-2026-05-29T14-48-49-${threadId}.jsonl`);
    assert.ok(claimThreadRole(cwd, state, threadId, 'senior-frontend', { parentSessionId: 'orchestrator' }));

    const route = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/app/(public)/news/page.tsx',
      content: 'export default function NewsPage() { return null; }',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(route.kind, 'noop');

    const feature = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/features/news/news-page.tsx',
      content: 'export function NewsPage() { return null; }',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(feature.kind, 'noop');
  });
});

test('subagents project: assignment manifest routes writes by scope end-to-end', () => {
  withMaterialized({
    mode: 'existing-codebase',
    frontend: 'nextjs',
    backend: 'none',
    materializedStack: 'default|nextjs|none|none',
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    const threadId = '019e7390-ca45-7e03-84d3-284bda1ba905';
    const transcript = path.join(cwd, `rollout-2026-05-29T14-48-49-${threadId}.jsonl`);
    assert.ok(claimThreadRole(cwd, state, threadId, 'senior-frontend', { parentSessionId: 'orchestrator' }));

    const manifest = path.join(cwd, '.traffic-one', 'runs', 'run-1', 'assignments.json');
    fs.mkdirSync(path.dirname(manifest), { recursive: true });
    fs.writeFileSync(manifest, JSON.stringify({
      version: 1, runId: 'run-1', assignments: [
        { role: 'senior-frontend', agentKey: 'senior-frontend', scope: { include: ['src/app/'], exclude: ['src/app/api/'] } },
        { role: 'senior-backend', agentKey: 'senior-backend', scope: { include: ['src/app/api/'] } },
      ],
    }), 'utf8');

    const mine = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/app/(public)/news/page.tsx', content: 'export default function P() { return null; }',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(mine.kind, 'noop');

    const theirs = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/app/api/news/route.ts', content: 'export function GET() {}',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(theirs.kind, 'deny');
    if (theirs.kind === 'deny') assert.ok(theirs.reason.includes('assigned scope'));
  });
});

test('static layout violation is denied even in a clean main-agent project', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'packages/ui/src/components/Btn.tsx', content: 'export default function Btn() { return null; }',
    }));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') assert.ok(r.reason.includes('plan gate violation'));
  });
});

test('static asset gate denies SVG text written to a .png path', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'write', 'file-write', {
      filePath: 'apps/web/public/og-default.png',
      content: '<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    }, {}, 'opencode'));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') {
      assert.ok(/SVG\/XML|bitmap|extension/i.test(r.reason));
    }
  });
});

test('non-file, non-feature shell command in a clean project → noop', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Bash', 'shell', { command: 'ls -la' }));
    assert.equal(r.kind, 'noop');
  });
});

test('continue-without-Traffic-One choice bypasses the plan gate', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    fs.rmSync(path.join(cwd, '.traffic-one', 'plan.md'), { force: true });
    writeAuthChoice('continue-without-traffic-one', cwd);
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/x.ts', content: 'export const x = 1;',
    }));
    assert.equal(r.kind, 'noop');
  });
});
