import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { planReadinessViolations } from '../plan-readiness';

const names = (name: string): string => name;

function withProject(fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-readiness-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeStateFile(dir: string, state: Record<string, unknown>): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(t1, { recursive: true });
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify(state), 'utf8');
}

function writePlan(dir: string): void {
  fs.mkdirSync(path.join(dir, '.traffic-one'), { recursive: true });
  fs.writeFileSync(path.join(dir, '.traffic-one', 'plan.md'), 'plan', 'utf8');
}

function writeMaterialized(dir: string): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
}

function writeRequiredScaffold(dir: string): void {
  fs.writeFileSync(path.join(dir, 'pnpm-workspace.yaml'), 'packages:\n  - "apps/*"\n  - "packages/*"\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'turbo.json'), '{"tasks":{}}', 'utf8');
  fs.writeFileSync(path.join(dir, 'tsconfig.base.json'), '{"compilerOptions":{}}', 'utf8');
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    private: true,
    packageManager: 'pnpm@10.12.1',
    workspaces: ['apps/*', 'packages/*'],
  }), 'utf8');
  for (const rel of [
    'apps/web',
    'packages/ui/src',
    'packages/tailwind-config',
    'packages/i18n/src',
  ]) {
    fs.mkdirSync(path.join(dir, rel), { recursive: true });
  }
  fs.writeFileSync(path.join(dir, 'apps/web/package.json'), '{"name":"web","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/ui/package.json'), '{"name":"@app/ui","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/ui/src/index.ts'), '', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/tailwind-config/package.json'), '{"name":"@app/tailwind-config","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/tailwind-config/tailwind.config.ts'), 'export default {};', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/i18n/package.json'), '{"name":"@app/i18n","private":true}', 'utf8');
  fs.writeFileSync(path.join(dir, 'packages/i18n/src/index.ts'), '', 'utf8');
}

function writeRequiredMemory(dir: string, state: Record<string, unknown> = DEFAULT_STATE): void {
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'decisions'), { recursive: true });
  for (const [rel, content] of Object.entries({
    'product.md': '# Product\nBuild an education platform MVP.',
    'stack.md': '# Stack\nReact/Vite frontend with the selected backend.',
    'coding.md': '# Coding\nUse TypeScript and the Traffic One conventions.',
    'security.md': '# Security\nValidate inputs and keep secrets out of source.',
    'known-issues.md': '# Known issues\nNone known yet.',
    'deployment.md': '# Deployment\nDeploy from the built production artifact.',
    'environment-setup.md': '# Environment setup\nInstall dependencies and configure environment variables.',
    'agent-log.md': '# Agent log\nArchitect initialized project memory.',
    '.agentignore': 'node_modules\n',
  })) {
    fs.writeFileSync(path.join(t1, rel), content, 'utf8');
  }
  const backend = typeof state.backend === 'string' ? state.backend : 'supabase';
  const noOwnedBackend = backend === 'none' || backend === 'external-api';
  fs.writeFileSync(path.join(t1, 'api.md'), noOwnedBackend
    ? 'Not applicable because this project has no owned backend API.'
    : '# API\nOwned backend API contracts will be tracked here.', 'utf8');
  fs.writeFileSync(path.join(t1, 'database.md'), noOwnedBackend
    ? 'Not applicable because this project has no owned database.'
    : '# Database\nDatabase tables and persistence contracts will be tracked here.', 'utf8');
  fs.writeFileSync(path.join(t1, 'schema.sql'), noOwnedBackend
    ? '-- Not applicable because this project has no owned database schema.'
    : '-- schema snapshot\ncreate table if not exists healthcheck (id uuid primary key);', 'utf8');
  if (state.stack !== 'default' || state.frontend !== 'react-vite' || state.backend !== 'supabase') {
    fs.writeFileSync(path.join(t1, 'decisions', '0001-stack.md'), '# Stack decision\nUse the requested non-default stack.', 'utf8');
  }
}

const DEFAULT_STATE = {
  mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
};

test('monorepo-package-json: a non-workspace root package.json on a monorepo stack is blocked', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: 'package.json', content: '{"name":"x"}', projectRoot: dir,
      state: { ...DEFAULT_STATE }, writingFeatureSource: false, block: names,
    });
    assert.deepEqual(v, ['monorepo-package-json']);
  });
});

test('monorepo-package-json: pnpm-workspace.yaml satisfies workspace declaration for root package.json', () => {
  withProject((dir) => {
    fs.writeFileSync(path.join(dir, 'pnpm-workspace.yaml'), 'packages:\n  - "apps/*"\n  - "packages/*"\n', 'utf8');
    const v = planReadinessViolations({
      filePath: 'package.json',
      content: JSON.stringify({
        name: 'devlearn',
        private: true,
        packageManager: 'pnpm@10.23.0',
        engines: { node: '>=22' },
      }),
      projectRoot: dir,
      state: { ...DEFAULT_STATE },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('monorepo-root-vite: a root src/ Vite file on a monorepo stack is blocked', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: 'src/main.tsx', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE }, writingFeatureSource: false, block: names,
    });
    assert.ok(v.includes('monorepo-root-vite'));
  });
});

test('state-gate: feature write with a missing/incomplete state file on a new project', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { mode: 'new-project' }, writingFeatureSource: true, block: names,
    });
    assert.ok(v.includes('state-gate'));
  });
});

test('materialization-gate: onboarded + valid stack but assets not on disk yet', () => {
  withProject((dir) => {
    writeStateFile(dir, { ...DEFAULT_STATE, onboardingComplete: true });
    writePlan(dir); // present so the plan-gate does not also fire
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true }, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, ['materialization-gate']);
  });
});

test('plan-gate: new project, no plan.md, writing feature source', () => {
  withProject((dir) => {
    // onboardingComplete:false makes featureContextMaterialized true → only the plan-gate fires.
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: false }, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, ['plan-gate']);
  });
});

test('plan-gate: legacy architecture.md does not satisfy readiness', () => {
  withProject((dir) => {
    fs.writeFileSync(path.join(dir, 'architecture.md'), '# Legacy architecture', 'utf8');
    const v = planReadinessViolations({
      filePath: 'apps/web/src/x.ts', content: '', projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: false }, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, ['plan-gate']);
  });
});

test('architect completion gate: PLAN_READY requires the baseline monorepo scaffold', () => {
  withProject((dir) => {
    const state = { ...DEFAULT_STATE, onboardingComplete: true };
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.ok(v.includes('architect-scaffold-gate'));
    assert.ok(v.includes('architect-memory-baseline-gate'));

    const nonTerminal = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'still planning\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(nonTerminal, []);
  });
});

test('architect completion gate: PLAN_READY is allowed once scaffold files exist', () => {
  withProject((dir) => {
    writeRequiredScaffold(dir);
    writeRequiredMemory(dir);
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('architect completion gate: PLAN_READY accepts pnpm-workspace.yaml plus root package without workspaces', () => {
  withProject((dir) => {
    writeRequiredScaffold(dir);
    writeRequiredMemory(dir);
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
      name: 'devlearn',
      private: true,
      packageManager: 'pnpm@10.23.0',
      engines: { node: '>=22' },
    }), 'utf8');
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('architect memory baseline gate: PLAN_READY requires project memory for every new project', () => {
  withProject((dir) => {
    writeRequiredScaffold(dir);
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['architect-memory-baseline-gate']);
  });
});

test('architect memory baseline gate: no-backend projects require N/A reasons for backend docs', () => {
  withProject((dir) => {
    const state = { ...DEFAULT_STATE, stack: 'custom-backend', backend: 'none', onboardingComplete: true };
    writeRequiredScaffold(dir);
    writeRequiredMemory(dir, state);
    fs.writeFileSync(path.join(dir, '.traffic-one', 'api.md'), '# API\n', 'utf8');
    const v = planReadinessViolations({
      filePath: '.traffic-one/digests/R/architect.md',
      content: 'verdict: PLAN_READY\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['architect-memory-baseline-gate']);
  });
});

test('a fully materialized project with a plan emits no readiness violations', () => {
  withProject((dir) => {
    writeMaterialized(dir);
    writePlan(dir);
    const state = { ...DEFAULT_STATE, onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none' };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: 'apps/web/src/components/Button.tsx', content: 'export const Button = () => null;',
      projectRoot: dir, state, writingFeatureSource: true, block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('plan-opencode-queue-gate: OpenCode-enabled new projects require machine-readable delegate block in plan.md', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: '.traffic-one/plan.md',
      content: '## OpenCode Delegation Queue\n1. i18n catalog\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['plan-opencode-queue-gate']);
  });
});

test('plan-opencode-queue-gate: Windsurf nudges ONCE then falls back to paid (best-effort, no deadlock)', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const args = {
      filePath: '.traffic-one/plan.md',
      content: '## Prose plan, no delegate block\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      host: 'windsurf',
      block: names,
    };
    // First write missing the queue → nudge fires.
    assert.deepEqual(planReadinessViolations(args), ['plan-opencode-queue-gate']);
    // Second write still missing the queue → allowed (fall back to paid, no stuck loop).
    assert.deepEqual(planReadinessViolations(args), []);
  });
});

test('plan-opencode-queue-gate: other hosts still HARD-block every time (no behavior change)', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const args = {
      filePath: '.traffic-one/plan.md',
      content: '## Prose plan, no delegate block\n',
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      host: 'claude',
      block: names,
    };
    // Non-Windsurf hosts keep the original hard block on repeated writes.
    assert.deepEqual(planReadinessViolations(args), ['plan-opencode-queue-gate']);
    assert.deepEqual(planReadinessViolations(args), ['plan-opencode-queue-gate']);
  });
});

test('plan-opencode-queue-gate: passes when opencode-delegate block has units', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: '.traffic-one/plan.md',
      content: [
        '# Plan',
        '<!-- opencode-delegate:start -->',
        '- id: i18n | role: frontend | files: packages/i18n/src/locales/en/common.json | task: seed strings',
        '- id: seed | role: backend | files: supabase/seed.sql | task: seed demo rows',
        '- id: smoke | role: tester | files: apps/web/e2e/smoke.spec.ts | task: scaffold smoke coverage',
        '<!-- opencode-delegate:end -->',
      ].join('\n'),
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('plan-opencode-queue-gate: OpenCode host rejects self-delegation queue blocks', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: '.traffic-one/plan.md',
      content: [
        '# Plan',
        '<!-- opencode-delegate:start -->',
        '- id: i18n | role: frontend | files: packages/i18n/src/locales/en/common.json | task: seed strings',
        '- id: seed | role: backend | files: supabase/seed.sql | task: seed demo rows',
        '- id: smoke | role: tester | files: apps/web/e2e/smoke.spec.ts | task: scaffold smoke coverage',
        '<!-- opencode-delegate:end -->',
      ].join('\n'),
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      host: 'opencode',
      block: names,
    });
    assert.deepEqual(v, ['plan-opencode-self-delegation-gate']);
  });
});

test('plan-opencode-queue-gate: ignores incomplete delegate rows the runner cannot execute', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: '.traffic-one/plan.md',
      content: [
        '# Plan',
        '<!-- opencode-delegate:start -->',
        '- role: frontend | files: packages/i18n/src/locales/en/common.json',
        '- role: backend | task: seed demo rows',
        '- role: tester | files: apps/web/e2e/smoke.spec.ts',
        '<!-- opencode-delegate:end -->',
      ].join('\n'),
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['plan-opencode-queue-gate']);
  });
});

test('plan-opencode-queue-policy-gate: rejects overlapping OpenCode units without depends edge', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: ['.traffic', '-one/plan.md'].join(''),
      content: [
        '# Plan',
        '<!-- opencode-delegate:start -->',
        '- id: all-ui | role: frontend | files: apps/web/src/** | task: prep UI fixtures',
        '- id: card | role: frontend | files: apps/web/src/components/Card.tsx | task: build card stub',
        '- id: smoke | role: tester | files: apps/web/e2e/smoke.spec.ts | task: scaffold smoke coverage',
        '<!-- opencode-delegate:end -->',
      ].join('\n'),
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['plan-opencode-queue-policy-gate']);
  });
});

test('plan-opencode-queue-policy-gate: allows overlapping OpenCode units with explicit depends edge', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: ['.traffic', '-one/plan.md'].join(''),
      content: [
        '# Plan',
        '<!-- opencode-delegate:start -->',
        '- id: all-ui | role: frontend | files: apps/web/src/** | task: prep UI fixtures',
        '- id: card | role: frontend | files: apps/web/src/components/Card.tsx | depends: all-ui | task: build card stub',
        '- id: smoke | role: tester | files: apps/web/e2e/smoke.spec.ts | task: scaffold smoke coverage',
        '<!-- opencode-delegate:end -->',
      ].join('\n'),
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, []);
  });
});

test('plan-opencode-queue-policy-gate: rejects testable unit without exact test/config allowlist', () => {
  withProject((dir) => {
    const state = {
      ...DEFAULT_STATE,
      onboardingComplete: true,
      openCode: { enabled: true },
      toolchain: { opencode: { installedVersion: '1.0.0' } },
    };
    writeStateFile(dir, state);
    const v = planReadinessViolations({
      filePath: '.traffic-one/plan.md',
      content: [
        '# Plan',
        '<!-- opencode-delegate:start -->',
        '- id: i18n | role: frontend | files: packages/i18n/src/locales/en/common.json | task: seed strings',
        '- id: seed | role: backend | files: supabase/seed.sql | task: seed demo rows',
        '- id: markdown | role: frontend | files: apps/web/src/lib/markdown.ts | task: pure markdown helper, unit-testable',
        '<!-- opencode-delegate:end -->',
      ].join('\n'),
      projectRoot: dir,
      state,
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['plan-opencode-queue-policy-gate']);
  });
});

test('assignments-shape-gate: rejects non-canonical roles-object assignments.json', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: '.traffic-one/runs/R/assignments.json',
      content: JSON.stringify({ roles: { 'senior-frontend': { ownedPaths: ['apps/web/**'] } } }),
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['assignments-shape-gate']);
  });
});

test('assignments-roles-gate: assignments manifest is limited to implementer roles', () => {
  withProject((dir) => {
    const v = planReadinessViolations({
      filePath: '.traffic-one/runs/R/assignments.json',
      content: JSON.stringify({
        version: 1,
        runId: 'R',
        assignments: [
          { role: 'senior-frontend', scope: { include: ['apps/web/**'] } },
          { role: 'senior-tester', scope: { include: ['tests/**'] } },
        ],
      }),
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['assignments-roles-gate']);
  });
});

test('assignments-owner-gate: tester cannot rewrite assignments after PLAN_READY', () => {
  withProject((dir) => {
    fs.mkdirSync(path.join(dir, '.traffic-one', 'digests', 'R'), { recursive: true });
    fs.writeFileSync(path.join(dir, '.traffic-one', 'digests', 'R', 'architect.md'), 'verdict: PLAN_READY\n', 'utf8');
    const v = planReadinessViolations({
      filePath: '.traffic-one/runs/R/assignments.json',
      content: JSON.stringify({
        version: 1,
        runId: 'R',
        assignments: [
          { role: 'senior-frontend', scope: { include: ['apps/web/**'] } },
          { role: 'senior-backend', scope: { include: ['supabase/**'] } },
        ],
      }),
      projectRoot: dir,
      state: { ...DEFAULT_STATE, onboardingComplete: true, currentRunId: 'R', activeAgentRole: 'senior-tester' },
      writingFeatureSource: false,
      block: names,
    });
    assert.deepEqual(v, ['assignments-owner-gate']);
  });
});
