// src/modules/plan-guard/__tests__/plan-write-deny-id.test.ts
// The plan-write aggregator deny reports ONE identity mined from whichever
// registered violation fired first (see makeViolationBlock in
// plan-write/index.ts), because ~50 distinct causes across
// plan-static/plan-readiness/plan-runteam/plan-runid all funnel into that one
// deny() call. This file pins the property that makes the identity meaningful:
// it must be a function of THIS write, not of what the process denied earlier.
//
// The regression it exists for: the accumulator was module scope, latched by a
// `!firstFired` guard, and nothing ever reset it — so the FIRST plan-write deny
// in a process labelled every later one. A one-shot hook process (one tool call
// per OS process) hid it completely; every multi-hook process did not: the
// replay corpus runs its whole corpus in one process, so its verdict baseline
// became a function of case ORDERING, and test:env / doctor's run
// reconstruction mislabelled every deny after the first. Under the planned
// allow-at-N budget keyed on `denyId`, one bucket spent on an unrelated
// violation would then have unblocked all ~50 causes at once.
//
// Two DIFFERENT violations, one process, each must report its own id.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { planWriteGate } from '../plan-write';
import type { Ctx, HookInput, HostId, ToolClass } from '../../../core/types';

function withMaterialized(fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-planwrite-denyid-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
  fs.writeFileSync(path.join(t1, 'plan.md'), 'plan', 'utf8');
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({
    mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
    onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none',
  }), 'utf8');
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeCtx(cwd: string, filePath: string, content: string, host: HostId = 'claude'): Ctx {
  const rawName = 'Write';
  const input: HookInput = {
    event: 'PreToolUse',
    host,
    cwd,
    raw: { tool_name: rawName, tool_input: { file_path: filePath, content } },
    tool: { class: 'file-write' as ToolClass, rawName },
  };
  return { input, host, cwd, now: () => 'x' } as unknown as Ctx;
}

interface Verdict { denyId: string; denyTarget: string; reason: string; }

function denyFor(cwd: string, filePath: string, content: string): Verdict {
  const result = planWriteGate(writeCtx(cwd, filePath, content));
  assert.equal(result.kind, 'deny', `expected a deny for ${filePath}, got ${result.kind}`);
  if (result.kind !== 'deny') throw new Error('unreachable');
  return {
    denyId: String(result.denyId),
    denyTarget: String(result.denyTarget),
    reason: result.reason,
  };
}

test('two different plan-write violations in ONE process each report their own denyId', () => {
  withMaterialized((cwd) => {
    // A reusable component with a default export → `default-export`.
    const first = denyFor(
      cwd,
      'apps/web/src/components/Button.tsx',
      'export default function Button() { return null; }\n',
    );
    // A service file typed with `any` → `no-any`. A DIFFERENT cause, a
    // different remedy, and the second call in this same process.
    const second = denyFor(
      cwd,
      'apps/web/src/services/courses.ts',
      'export const load = (x: any) => x;\n',
    );

    assert.equal(first.denyId, 'default-export');
    assert.equal(second.denyId, 'no-any');
    // The pairing is the actual contract: the reported id must match the
    // violation the deny TEXT describes. Before the fix, the second call still
    // rendered the no-any prose while reporting `default-export`.
    assert.match(first.reason, /named exports only/);
    assert.match(second.reason, /Avoid the any type|Avoid `any`/);
    // …and the target discriminator follows the write, not the first one seen.
    assert.equal(first.denyTarget, 'apps/web/src/components/Button.tsx');
    assert.equal(second.denyTarget, 'apps/web/src/services/courses.ts');
  });
});

// Order independence, stated directly: the same write must produce the same
// identity whether or not another violation was denied before it. This is what
// the replay corpus (whole corpus in one process, sorted by case id) needs to
// be a baseline of BEHAVIOUR rather than of case ordering.
test('a plan-write denyId does not depend on what the process denied earlier', () => {
  const idFor = (order: 'alone' | 'after-another'): string => {
    let observed = '';
    withMaterialized((cwd) => {
      if (order === 'after-another') {
        denyFor(cwd, 'apps/web/src/components/Button.tsx', 'export default function Button() { return null; }\n');
      }
      observed = denyFor(cwd, 'apps/web/src/services/courses.ts', 'export const load = (x: any) => x;\n').denyId;
    });
    return observed;
  };
  assert.equal(idFor('alone'), 'no-any');
  assert.equal(idFor('after-another'), idFor('alone'));
});

// Repeating the SAME violation must stay stable too — the accumulator being
// per-invocation must not make an id depend on the retry count either (the
// deny-repeat escalation appends prose, never a new identity).
test('an identical repeated violation keeps reporting the same denyId', () => {
  withMaterialized((cwd) => {
    const content = 'export default function Button() { return null; }\n';
    const ids = [1, 2, 3].map(() => denyFor(cwd, 'apps/web/src/components/Button.tsx', content).denyId);
    assert.deepEqual(ids, ['default-export', 'default-export', 'default-export']);
  });
});
