import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';

import { planWriteGate } from '../plan-write';
import type { Ctx, HookInput, ToolClass } from '../../../core/types';
import { writeAuthChoice } from '../../session/auth-choice';
import { claimThreadRole } from '../../../shared/state/run-agent';

function withMaterialized(stateExtra: Record<string, unknown>, fn: (cwd: string) => void): void {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 't1-planwrite-'));
  const env = process.env;
  const prev = env.TRAFFIC_ONE_PROJECT_PREFS_PATH;
  const prevChoice = env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH;
  env.TRAFFIC_ONE_PROJECT_PREFS_PATH = path.join(dir, 'prefs.json');
  env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH = path.join(dir, 'auth-choice.json');
  const t1 = path.join(dir, '.traffic-one');
  fs.mkdirSync(path.join(t1, 'rules', 'common'), { recursive: true });
  fs.mkdirSync(path.join(t1, 'skills', 'project-memory'), { recursive: true });
  fs.writeFileSync(path.join(t1, 'rules', 'common', 'auth-gate.md'), 'r', 'utf8');
  fs.writeFileSync(path.join(t1, 'skills', 'project-memory', 'SKILL.md'), 's', 'utf8');
  fs.writeFileSync(path.join(t1, 'manifest.json'), JSON.stringify({
    generatedBy: 'traffic-one', stack: 'default', rules: ['rules/common/auth-gate.md'], skills: ['project-memory'],
  }), 'utf8');
  fs.writeFileSync(path.join(dir, 'AGENTS.md'), 'x\n<!-- GENERATED BY traffic-one: project-local active rules -->\n', 'utf8');
  fs.writeFileSync(path.join(dir, 'CLAUDE.md'), 'see agents', 'utf8');
  fs.writeFileSync(path.join(t1, 'plan.md'), 'plan', 'utf8');
  fs.writeFileSync(path.join(t1, '.one.json'), JSON.stringify({
    mode: 'new-project', stack: 'default', frontend: 'react-vite', backend: 'supabase', mobile: { framework: 'none' },
    onboardingComplete: true, materializedStack: 'default|react-vite|supabase|none', ...stateExtra,
  }), 'utf8');
  try {
    fn(dir);
  } finally {
    if (prev === undefined) delete env.TRAFFIC_ONE_PROJECT_PREFS_PATH; else env.TRAFFIC_ONE_PROJECT_PREFS_PATH = prev;
    if (prevChoice === undefined) delete env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH; else env.TRAFFIC_ONE_AUTH_CHOICE_STATE_PATH = prevChoice;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeCtx(
  cwd: string,
  rawName: string,
  cls: ToolClass,
  toolInput: Record<string, unknown>,
  rawExtra: Record<string, unknown> = {},
): Ctx {
  const input: HookInput = {
    event: 'PreToolUse', host: 'claude', cwd,
    raw: { ...rawExtra, tool_name: rawName, tool_input: toolInput },
    tool: { class: cls, rawName },
  };
  return { input, host: 'claude', cwd, now: () => 'x' } as unknown as Ctx;
}

test('clean write in a materialized main-agent project → noop', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/components/Button.tsx', content: 'export const Button = () => null;',
    }));
    assert.equal(r.kind, 'noop');
  });
});

test('subagents project: a feature write outside any role session is denied (run-team)', () => {
  withMaterialized({ team: { mode: 'subagents', source: 'prompted', approved: true } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/featureThing.ts', content: 'export const x = 1;',
    }));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') {
      assert.ok(r.reason.includes('Run-team enforcement gate'));
      assert.ok(r.reason.includes('team.mode'));
    }
  });
});

test('subagents project: claimed senior-frontend can write flat root Next UI source', () => {
  withMaterialized({
    mode: 'existing-codebase',
    frontend: 'nextjs',
    backend: 'none',
    materializedStack: 'default|nextjs|none|none',
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    const threadId = '019e7390-ca45-7e03-84d3-284bda1ba905';
    const transcript = path.join(cwd, `rollout-2026-05-29T14-48-49-${threadId}.jsonl`);
    assert.ok(claimThreadRole(cwd, state, threadId, 'senior-frontend', { parentSessionId: 'orchestrator' }));

    const route = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/app/(public)/news/page.tsx',
      content: 'export default function NewsPage() { return null; }',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(route.kind, 'noop');

    const feature = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/features/news/news-page.tsx',
      content: 'export function NewsPage() { return null; }',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(feature.kind, 'noop');
  });
});

test('subagents project: assignment manifest routes writes by scope end-to-end', () => {
  withMaterialized({
    mode: 'existing-codebase',
    frontend: 'nextjs',
    backend: 'none',
    materializedStack: 'default|nextjs|none|none',
    currentRunId: 'run-1',
    team: { mode: 'subagents', source: 'prompted', approved: true },
  }, (cwd) => {
    const state = JSON.parse(fs.readFileSync(path.join(cwd, '.traffic-one', '.one.json'), 'utf8'));
    const threadId = '019e7390-ca45-7e03-84d3-284bda1ba905';
    const transcript = path.join(cwd, `rollout-2026-05-29T14-48-49-${threadId}.jsonl`);
    assert.ok(claimThreadRole(cwd, state, threadId, 'senior-frontend', { parentSessionId: 'orchestrator' }));

    const manifest = path.join(cwd, '.traffic-one', 'runs', 'run-1', 'assignments.json');
    fs.mkdirSync(path.dirname(manifest), { recursive: true });
    fs.writeFileSync(manifest, JSON.stringify({
      version: 1, runId: 'run-1', assignments: [
        { role: 'senior-frontend', agentKey: 'senior-frontend', scope: { include: ['src/app/'], exclude: ['src/app/api/'] } },
        { role: 'senior-backend', agentKey: 'senior-backend', scope: { include: ['src/app/api/'] } },
      ],
    }), 'utf8');

    const mine = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/app/(public)/news/page.tsx', content: 'export default function P() { return null; }',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(mine.kind, 'noop');

    const theirs = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'src/app/api/news/route.ts', content: 'export function GET() {}',
    }, { session_id: 'orchestrator', transcript_path: transcript }));
    assert.equal(theirs.kind, 'deny');
    if (theirs.kind === 'deny') assert.ok(theirs.reason.includes('assigned scope'));
  });
});

test('static layout violation is denied even in a clean main-agent project', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'packages/ui/src/components/Btn.tsx', content: 'export default function Btn() { return null; }',
    }));
    assert.equal(r.kind, 'deny');
    if (r.kind === 'deny') assert.ok(r.reason.includes('plan gate violation'));
  });
});

test('non-file, non-feature shell command in a clean project → noop', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    const r = planWriteGate(writeCtx(cwd, 'Bash', 'shell', { command: 'ls -la' }));
    assert.equal(r.kind, 'noop');
  });
});

test('continue-without-Traffic-One choice bypasses the plan gate', () => {
  withMaterialized({ team: { mode: 'main-agent', source: 'prompted' } }, (cwd) => {
    fs.rmSync(path.join(cwd, '.traffic-one', 'plan.md'), { force: true });
    writeAuthChoice('continue-without-traffic-one', cwd);
    const r = planWriteGate(writeCtx(cwd, 'Write', 'file-write', {
      file_path: 'apps/web/src/x.ts', content: 'export const x = 1;',
    }));
    assert.equal(r.kind, 'noop');
  });
});
