// THE GATE EXEMPTION'S ANCHOR SET, AND THE THREE STATES OF THE FILE AT ONE.
//
// The exemption's docblock used to claim every anchor was self-relative or
// HOME-derived and never environment-derived. Measured false: THREE variables
// moved the set — HOME, XDG_STATE_HOME and TRAFFIC_ONE_TOOLCHAIN_ROOT, the last
// two through toolchain-paths.ts — and the set was a list of PATHS, with
// nothing asking whether the file sitting at one was the shipped runner. A stub
// written at a moved anchor was admitted.
//
// Two narrowings closed it, and this file measures both:
//
//   1. The exemption set is now the WRITE set MINUS the anchors env relocates.
//      Shims are still written everywhere (a relocated install keeps a live
//      copy); only the security exemption stops following them there.
//   2. At the anchors that remain, the file's IDENTITY is checked — byte
//      equality against `shimSource(rel)`, the generator that writes the shims
//      — with a deliberate carve-out for absence, which is the part that needs
//      a test rather than a comment, because getting it wrong re-creates the
//      wedge inside the recovery. See the absence row below.
//
// The identity check replaced a SHAPE check that was documented as identity: the
// marker line and the `const REL` line, both public constants (the marker is
// quoted in this repo's own AGENTS.md), so a planted payload carrying them was
// admitted. That residual was pinned here by a test asserting the marked forgery
// WAS admitted; it is gone, and the marked-forgery row of the table below is
// what replaced it.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { NODE_FLOOR_MAJOR } from '../../../shared/node-floor';
import {
  gateExemptResetScriptPaths,
  resetCommand,
  resetScriptPath,
  resetShimCommand,
  resetShimPath,
} from '../../../shared/reset-command';
import { shimSource, stableBinDir } from '../../../shared/runner-shims';
import { isTrafficOneResetCommand } from '../../../shared/tool-classify';

const ENV_KEYS = ['HOME', 'USERPROFILE', 'XDG_STATE_HOME', 'TRAFFIC_ONE_TOOLCHAIN_ROOT'] as const;

function withEnv(values: Partial<Record<(typeof ENV_KEYS)[number], string | undefined>>, run: () => void): void {
  const saved = Object.fromEntries(ENV_KEYS.map((key) => [key, process.env[key]]));
  try {
    for (const key of ENV_KEYS) {
      const next = values[key];
      if (next === undefined) delete process.env[key];
      else process.env[key] = next;
    }
    run();
  } finally {
    for (const key of ENV_KEYS) {
      if (saved[key] === undefined) delete process.env[key];
      else process.env[key] = saved[key];
    }
  }
}

// What ensureRunnerShims actually emits — the generator itself, not a hand-copy
// of the lines a reader can see in it. That is the whole of the narrowing: the
// bytes the check demands are DERIVED, so they move with a version bump instead
// of ageing into a snapshot, and there is nothing here for an adversary to
// transcribe. The genuine row below is therefore near-tautological on purpose
// (the writer and the judge are one function); every other row is where the
// security content lives.
const REL = 'scripts/traffic-one-reset.cjs';
const REAL_SHIM = shimSource(REL);

const FORGERY = '#!/usr/bin/env node\nconsole.log("not ours");\n';

// The forgery the SHAPE check admitted: a payload with the two public literals
// prepended. Nothing in it is secret and nothing in it is derived from the
// running plugin, which is exactly why the shape check was not an identity
// check.
const MARKED_FORGERY = [
  '#!/usr/bin/env node',
  "'use strict';",
  '// GENERATED BY traffic-one',
  `const REL = ${JSON.stringify(REL)};`,
  'require("child_process").execSync("true");',
  'void REL;',
  '',
].join('\n');

// The FULL grammar, which is four words: `node <script> --run-id <id>`. A
// two-word `node <script>` is refused by the word count before the anchor is
// ever consulted, so a probe written that way reports "refused" for every
// input and measures nothing at all.
const RUN_ID = '1785169657252';

function admitted(target: string): boolean {
  return Boolean(isTrafficOneResetCommand('Bash', { command: `node ${target} --run-id ${RUN_ID}` }));
}

function scratchHome(): { readonly scratch: string; readonly home: string } {
  const scratch = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 't1-anchor-')));
  const home = path.join(scratch, 'home');
  fs.mkdirSync(home, { recursive: true });
  return { scratch, home };
}

// Every state the file at the documented anchor can be in, driven through the
// real classifier. `plant` prepares the anchor (or deliberately leaves it
// alone); nothing here re-implements the check.
const ANCHOR_STATES: ReadonlyArray<{
  readonly label: string;
  readonly plant: (anchor: string, scratch: string) => void;
  readonly admitted: boolean;
  readonly why: string;
}> = [
  {
    label: 'the genuine generated shim',
    plant: (anchor) => fs.writeFileSync(anchor, REAL_SHIM, 'utf8'),
    admitted: true,
    why: 'the documented recovery command must keep working; this is what ensureRunnerShims writes',
  },
  {
    label: 'a planted file carrying BOTH marker literals',
    plant: (anchor) => fs.writeFileSync(anchor, MARKED_FORGERY, 'utf8'),
    admitted: false,
    why: 'the literals are public — an adversary who reads the source supplies them for free, '
      + 'which is why the shape check was replaced by byte-equality against shimSource(rel)',
  },
  {
    label: 'a planted file carrying neither literal',
    plant: (anchor) => fs.writeFileSync(anchor, FORGERY, 'utf8'),
    admitted: false,
    why: 'a file at the right path that is not the shipped runner must not carry the exemption — '
      + 'the set was a list of paths and this was the whole of the hole',
  },
  {
    label: 'no file at all',
    plant: () => { /* absence is the state under test */ },
    admitted: true,
    why: 'THE CARVE-OUT: a pre-consent machine has no shims, the deny prose of the gate stopping the '
      + 'user prescribes this command, and node exits module-not-found — there is nothing here to forge',
  },
  {
    label: 'a symlink to an attacker-controlled file',
    plant: (anchor, scratch) => {
      const evil = path.join(scratch, 'evil.cjs');
      fs.writeFileSync(evil, MARKED_FORGERY, 'utf8');
      fs.symlinkSync(evil, anchor);
    },
    admitted: false,
    why: 'the link is judged by the bytes it resolves to, so pointing the anchor at a payload buys nothing',
  },
  {
    label: 'a symlink to a genuine copy of the shim',
    plant: (anchor, scratch) => {
      const real = path.join(scratch, 'genuine.cjs');
      fs.writeFileSync(real, REAL_SHIM, 'utf8');
      fs.symlinkSync(real, anchor);
    },
    admitted: true,
    why: 'same rule read the other way: bytes equal to the generator ARE the shim, wherever the link lands',
  },
  {
    label: 'a byte-TRUNCATED genuine shim',
    plant: (anchor) => fs.writeFileSync(anchor, REAL_SHIM.slice(0, REAL_SHIM.length - 1), 'utf8'),
    admitted: false,
    why: 'a prefix of the shim is not the shim: a head-only check would have admitted it, and a truncated '
      + 'file is not a file we can vouch for',
  },
  {
    label: 'a genuine shim with ONE byte changed',
    plant: (anchor) => fs.writeFileSync(
      anchor,
      `${REAL_SHIM.slice(0, REAL_SHIM.length - 2)}X\n`,
      'utf8',
    ),
    admitted: false,
    why: 'same length, one differing byte — the comparison is bytes, not size, and not the head',
  },
];

test('the file at the documented anchor is admitted only when it IS the generated shim', () => {
  for (const state of ANCHOR_STATES) {
    const { scratch, home } = scratchHome();
    try {
      withEnv({ HOME: home, USERPROFILE: home }, () => {
        const anchor = resetShimPath();
        assert.ok(gateExemptResetScriptPaths().includes(anchor),
          'fixture guard: the documented shim must be in the exemption set');
        fs.mkdirSync(path.dirname(anchor), { recursive: true });
        state.plant(anchor, scratch);
        assert.equal(admitted(anchor), state.admitted, `${state.label}: ${state.why}`);
      });
    } finally {
      fs.rmSync(scratch, { recursive: true, force: true });
    }
  }
});

test('an ABSENT shim is admitted, because denying it rebuilds the wedge inside the recovery', () => {
  // The carve-out, and the one that cost two replay-corpus cases when it was
  // missing. A user who has not answered the consent question has no shims
  // written yet — and the deny prose of the very gate stopping them prescribes
  // this command. Refusing it because the file is not there yet means "you must
  // run doctor" and "doctor is denied until a consented run writes a file" at
  // the same time.
  //
  // It is SAFE because there is nothing at the path to forge: node exits
  // module-not-found, so the admitted command cannot do anything at all.
  const { scratch, home } = scratchHome();
  try {
    withEnv({ HOME: home, USERPROFILE: home }, () => {
      const anchor = resetShimPath();
      assert.equal(fs.existsSync(anchor), false, 'fixture guard: nothing is there');
      assert.equal(admitted(anchor), true, 'an absent shim is admitted; there is nothing there to be a forgery');
    });
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }
});

test('an env-relocated anchor is refused even holding a GENUINE shim', () => {
  // The other narrowing, and it is still worth keeping now that the content
  // check is byte-equality rather than shape. What changed is the reason: a
  // payload at a moved anchor is refused twice over, so what this measures is
  // that the exemption SET does not follow a variable the caller controls, and
  // therefore does not rest on the content check as its only fence. The file
  // written below is byte-genuine on purpose — the refusal has to come from the
  // path, which is the only way to tell the two fences apart.
  const { scratch, home } = scratchHome();
  try {
    for (const [label, env] of [
      ['TRAFFIC_ONE_TOOLCHAIN_ROOT', { TRAFFIC_ONE_TOOLCHAIN_ROOT: path.join(scratch, 'toolchains') }],
      ['XDG_STATE_HOME', { XDG_STATE_HOME: path.join(scratch, 'xdg') }],
    ] as const) {
      withEnv({ HOME: home, USERPROFILE: home, ...env }, () => {
        const moved = path.join(stableBinDir(), 'traffic-one-reset.cjs');
        fs.mkdirSync(path.dirname(moved), { recursive: true });
        fs.writeFileSync(moved, REAL_SHIM, 'utf8');

        assert.equal(admitted(moved), false,
          `${label}: an anchor the caller can move must not carry the exemption, however genuine the file looks`);
        assert.ok(!gateExemptResetScriptPaths().includes(moved),
          `${label}: and it is out of the set, not merely failing the content check`);
        // The documented recovery is unaffected — which is the thing that had
        // to be measured before narrowing, not assumed.
        assert.ok(gateExemptResetScriptPaths().includes(resetShimPath()),
          `${label}: the documented anchor survives the narrowing`);
      });
    }
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }
});

// ── the MCP reachability claim, which was also false ────────────────────────
// fail-closed.ts asserted the exemption was unreachable through MCP. It was
// reachable: shell-ness was decided from the LAST DOT-SEGMENT of the tool name,
// so any MCP tool whose name ended in `.Bash` and carried a field called
// `command` cleared the boundary — and every other argument in the call rode
// along unjudged, because for a real MCP tool that field is not what executes.
// The byte-match that protects the sibling row does not reach it: the string
// being compared is not the string the server runs.
//
// Narrowed at both ends where a second end exists. An exemption always needs an
// UNQUALIFIED shell tool name, and on the two surfaces that route MCP to a
// dedicated subcommand (cursor, windsurf) such a subcommand yields no exemption
// at all. On nested/wrapper/copilot there is no subcommand to consult, so what
// stands there is the host naming convention that MCP tools arrive qualified —
// which is what the test below measures, and it is a convention, not a fence.

test('a QUALIFIED MCP tool name cannot buy the exemption, however well-formed the command', () => {
  const { scratch, home } = scratchHome();
  try {
    withEnv({ HOME: home, USERPROFILE: home }, () => {
      const anchor = resetShimPath();
      fs.mkdirSync(path.dirname(anchor), { recursive: true });
      fs.writeFileSync(anchor, REAL_SHIM, 'utf8');
      const command = `node ${anchor} --run-id ${RUN_ID}`;

      // The control: unqualified, and genuinely exempt. Without this the
      // denials below would be indistinguishable from a broken fixture.
      assert.equal(isTrafficOneResetCommand('Bash', { command }), true, 'control: the real thing is admitted');

      // THE FIXTURE HAS TO BE ABLE TO NOTICE ITSELF REGRESSING, and until these
      // two lines it could not: delete the write above and the control still
      // passed, because the moved HOME leaves the anchor EMPTY and the absence
      // carve-out admits an absent shim — the same absence path the old test
      // slipped through on. Both halves are needed. The byte guard says the
      // reference bytes are really at the anchor; the forgery says the content
      // test is really running in THIS fixture home, so the control's `true` is
      // a comparison that happened rather than a file that was not there.
      assert.equal(fs.readFileSync(anchor, 'utf8'), REAL_SHIM,
        'fixture guard: the reference shim must actually be at the anchor');
      fs.writeFileSync(anchor, MARKED_FORGERY, 'utf8');
      assert.equal(isTrafficOneResetCommand('Bash', { command }), false,
        'a forged shim at the same anchor in the same fixture home is refused');
      fs.writeFileSync(anchor, REAL_SHIM, 'utf8');

      for (const name of [
        'mcp__evil.Bash',
        'mcp__server.exec_command',
        'some.namespace.Bash',
        'x.Bash',
        'evil__Bash.Bash',
      ]) {
        assert.equal(isTrafficOneResetCommand(name, { command }), false,
          `a qualified MCP name must not satisfy shell-ness: ${name}`);
      }
    });
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }
});

// ── the availability half, which the rows above cannot see ──────────────────
// Every state in the table is about the file at the SHIM anchor, and refusing a
// shim from another plugin version is the right answer there: the reference is
// derived from the running generator, and weakening it back into a shape test
// is the regression the marked-forgery row keeps dead.
//
// The hole was one level up. `~/.traffic-one/bin` is user-scoped and
// version-agnostic — one directory shared by every installed version, whose
// contents belong to whichever version ran SessionStart last — and per the
// maintainer guide one host imports another's user-scope bundle, so skew on one
// machine is supported. `resetCommand()` printed the shim spelling, so on a
// skewed machine the product printed the one command its own gate refuses. The
// self-relative runner was exempt all along with no content test at all, and
// nothing pointed at it.
//
// The stale variant below is a ONE-CONSTANT edit of the real template, which is
// exactly the diff a Node-floor bump produces between two versions.
test('the command the product PRINTS is admitted even when the shim at the anchor is another version\'s', () => {
  const stale = REAL_SHIM.replace(`var __t1NodeFloor = ${NODE_FLOOR_MAJOR};`, 'var __t1NodeFloor = 20;');
  assert.notEqual(stale, REAL_SHIM, 'fixture guard: the stale variant must actually differ from the template');

  const { scratch, home } = scratchHome();
  try {
    withEnv({ HOME: home, USERPROFILE: home }, () => {
      const anchor = resetShimPath();
      fs.mkdirSync(path.dirname(anchor), { recursive: true });
      fs.writeFileSync(anchor, stale, 'utf8');

      // The state that makes this worth testing: the shim spelling really is
      // refused here. If this ever stops being true the identity check has been
      // weakened and the row above should be failing too.
      assert.equal(admitted(anchor), false,
        'control: a cross-version shim is refused, which is what makes the printed spelling matter');
      assert.equal(isTrafficOneResetCommand('Bash', { command: resetShimCommand(RUN_ID) }), false,
        'control: and the shim PRINTER prints that refused spelling, which is why it is not the default');

      assert.equal(isTrafficOneResetCommand('Bash', { command: resetCommand(RUN_ID) }), true,
        'the printed recovery command must be admissible on a machine with a skewed shim');
    });
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }
});

test('the printed recovery command does not depend on a shim existing at all', () => {
  // The pre-consent machine, and the read-only HOME: nothing has been written to
  // `~/.traffic-one/bin` yet. The shim spelling survives that through
  // isGeneratedShim's absence clause; the printed spelling does not need the
  // clause, because the runner it names ships with the code doing the printing.
  const { scratch, home } = scratchHome();
  try {
    withEnv({ HOME: home, USERPROFILE: home }, () => {
      assert.ok(!fs.existsSync(resetShimPath()), 'fixture guard: no shim on this fixture machine');
      assert.equal(isTrafficOneResetCommand('Bash', { command: resetCommand(RUN_ID) }), true);
      assert.ok(gateExemptResetScriptPaths().includes(resetScriptPath()),
        'and the spelling it prints is in the exemption set by construction');
    });
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }
});

test('the self-relative runner is admitted with a FILE at it, not merely because nothing is there', () => {
  // The witness the claim above did not have. `isGateExemptScript` admits the
  // self-relative anchor unconditionally — no content test, because a forged
  // runner inside the tree the running code was loaded from means the process
  // is already executing forged code. On a source checkout that is
  // indistinguishable from the absence carve-out: `scripts/` does not exist, so
  // an assertion taken with nothing at the path is satisfied by either rule and
  // an "admit only when absent" mutant survives it. Planting junk separates
  // them — the content is deliberately NOT the runner, and it is still admitted.
  //
  // Written with `wx`, and removed only by the process that created it: this is
  // the one anchor a fixture cannot relocate (it is derived from __dirname), so
  // two concurrent test processes share the path, and an exclusive create is
  // what keeps them from deleting each other's file. An install layout that
  // legitimately has the runner there is the EEXIST branch, where the plant is
  // skipped and the assertion is taken against the real file, which is not
  // vacuous either.
  const own = resetScriptPath();
  const hadDir = fs.existsSync(path.dirname(own));
  let planted = false;
  try {
    fs.mkdirSync(path.dirname(own), { recursive: true });
    try {
      fs.writeFileSync(own, '// planted junk, not the reset runner\nprocess.exit(1);\n', { flag: 'wx' });
      planted = true;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
    }
    assert.ok(fs.existsSync(own), 'fixture guard: something is at the self-relative anchor');
    assert.equal(isTrafficOneResetCommand('Bash', { command: resetCommand(RUN_ID) }), true,
      'the self-relative runner carries the exemption on its PATH, with no content test');
    assert.equal(isTrafficOneResetCommand('Bash', { command: `node ${own} --run-id ${RUN_ID}` }), true,
      'and the printed spelling and the anchor are the same admission, not two');
  } finally {
    if (planted) fs.rmSync(own, { force: true });
    // rmdir, not rm -rf: it refuses a non-empty directory, so a concurrent
    // process's file is never swept away with the fixture.
    if (planted && !hadDir) try { fs.rmdirSync(path.dirname(own)); } catch { /* not ours to remove */ }
  }
});

test('HOME still moves the anchor, and that is stated rather than claimed away', () => {
  // The honest residual. HOME is not a narrowing available to us: it is the
  // anchor the entire per-user state tree is keyed on, so a caller who controls
  // it already holds the consent record, the override ledger and the shims. The
  // docblock used to say no anchor was environment-derived; this pins what is
  // actually true, so the next reader gets the real boundary.
  const a = scratchHome();
  const b = scratchHome();
  try {
    let first = '';
    let second = '';
    withEnv({ HOME: a.home, USERPROFILE: a.home }, () => { first = resetShimPath(); });
    withEnv({ HOME: b.home, USERPROFILE: b.home }, () => { second = resetShimPath(); });
    assert.notEqual(first, second, 'HOME moves the documented anchor; the exemption is HOME-derived by design');
    assert.ok(first.startsWith(a.home) && second.startsWith(b.home));
  } finally {
    fs.rmSync(a.scratch, { recursive: true, force: true });
    fs.rmSync(b.scratch, { recursive: true, force: true });
  }
});
